#!/bin/sh /etc/rc.common

START=99
STOP=1
USE_PROCD=1

start_service() {
	local EXE_NAME=unifi-anywhere
	local APP=/usr/sbin/$EXE_NAME
	local CFG=/tmp/$EXE_NAME.json
	local SHARE_DIR=/usr/share/$EXE_NAME
	local BLECONN_SHARE_DIR=/usr/share/bleconn
	local STOP_TIMEOUT=11

	# Don't run app on devices which are not supported by bleconnd
	$BLECONN_SHARE_DIR/bleconn-check-sys-support.sh $BLECONN_SHARE_DIR || return 0

	$SHARE_DIR/check-sys-support.sh $SHARE_DIR || return 0

	# Generate config
	$SHARE_DIR/$EXE_NAME-cfg-maker.sh $CFG $SHARE_DIR $BLECONN_SHARE_DIR || return 1

	procd_open_instance
	procd_set_param command $APP --syslog $CFG
	procd_set_param respawn
	procd_set_param term_timeout $STOP_TIMEOUT
	procd_close_instance
}
