#!/bin/sh
# Copyright (C) 2009 OpenWrt.org

echo "ACTION=${ACTION}"  >/dev/console
echo "DEVICENAME=${DEVICENAME}" >/dev/console


[ change = "$ACTION" -a regulatory.0 = "$DEVICENAME" ] && {
	/sbin/crda &
}
