#!/bin/sh

if [ "$(config get radio_number)" = "0x3" ]; then
	is_dual_band=1
	mainifname_2G="wl0"
	mainifname_5GL="wl1"
	mainifname_5GH="wl2"
	main_ifname_list="wl0 wl1"
	guestifname_2G="wl0.1"
	guestifname_5GL="wl1.1"
	guestifname_5GH="wl1.1"
	GUEST_BANDS="wla wlg"
	board_band_info="dual-band"
	wifi1_band_mode="all"
	if [ "$(config get ssid_number_per_radio)" = "0x7" ]; then
		is_single_ssid=1
		guest2G_ifname_list="wl0.1 wl0.2"
		guest5G_ifname_list="wl1.1 wl1.2"
		guest_ifname_list="wl0.1 wl0.2 wl1.1 wl1.2"
		ifname_list="wl0 wl0.1 wl0.2 wl1 wl1.1 wl1.2"
		wireless1_ifname="wl0 wl1"
		wireless2_ifname="wl0.1 wl1.1"
		wireless3_ifname="wl0.2 wl1.2"
	else
		is_single_ssid=0
		guest2G_ifname_list="wl0.1"
		guest5G_ifname_list="wl1.1"
		guest_ifname_list="wl0.1 wl1.1"
		ifname_list="wl0 wl0.1 wl1 wl1.1"
	fi
elif [ "$(config get radio_number)" = "0x7" ]; then
	is_dual_band=0
	mainifname_2G="wl1"
	mainifname_5GL="wl2"
	mainifname_5GH="wl0"
	main_ifname_list="wl0 wl1 wl2"
	guest_ifname_list="wl0.1 wl1.1 wl2.1"
	GUEST_BANDS="wla wlg wla_2nd"
	ifname_list="wl1 wl1.1 wl2 wl2.1 wl0 wl0.1"
	guestifname_2G="wl1.1"
	guestifname_5GL="wl2.1"
	guestifname_5GH="wl0.1"
	board_band_info="triad-band"
	wifi1_band_mode="low"
	wifi2_band_mode="high"
	guest2G_ifname_list="wl1.1"
	guest5G_ifname_list="wl2.1"
fi

