#!/bin/sh /etc/rc.common

START=19
STOP=91

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
        

        setup_switch() { return 0; }
        . /lib/switch/switch.sh
        setup_switch

        . /lib/switch/core.sh
        setup_vlan
		unsetup_ports
}

restart() {
        stop
        start
        env -i ACTION=RESTART /sbin/hotplug-call switch
}

shutdown() {
        echo "do nothing"
}

stop() {
        echo "do nothing"
}

reload() {
        start
}
