#!/bin/sh /etc/rc.common

START=99
STOP=80
mtd_name=`cat /proc/mtd | grep "ART" | grep -o "mtd."`

start() {
	[ -c /dev/dk0 ] || mknod /dev/dk0 c 63 0
	[ -c /dev/dk1 ] || mknod /dev/dk1 c 63 1
	[ -L /dev/caldata ] || ln -s /dev/${mtd_name} /dev/caldata
    
	if [ "$(/sbin/is_cal)" = "true" ]; then
		/sbin/wifi sta
	else
		# the art procedure has been moved advance for 32M DDR product.
		# because art needs more memory than it own when finish initialization.
		#cd /usr/sbin/
		#/etc/init.d/art start
		#cd /
		echo "wireless_sta do nothing"
	fi
	return 0
}

stop() {
	return 0
}

reload() {
	return 0
}
