#!/bin/sh /etc/rc.common

START=99
STOP=80

start() {    
	if [ "$(/sbin/is_cal)" = "true" ]; then
		/sbin/wifi check
	else
		echo "wireless_check do nothing"
	fi
	return 0
}

stop() {
	return 0
}

reload() {
	return 0
}
