#!/bin/sh

rtoa() {
	local section_line
	
	nvrammanager -r /tmp/user-config -p user-config
	nvrammanager -w /tmp/user-config -p router-config
	nvrammanager -r /tmp/ap-config -p ap-config
	if [ -s "/tmp/ap-config" ];then
		echo "-----------------ap-config is not null--------------" >/dev/console
	else
		echo "-----------------ap-config is null--------------" >/dev/console
		nvrammanager -r /tmp/apdef-config -p apdef-config
		nvrammanager -w /tmp/apdef-config -p ap-config
	fi
	echo "-------------sync start----------" >/dev/console
	sync_mode_file rtoa
	echo "-------------sync end----------" >/dev/console
	rm -f /tmp/user-config /tmp/ap-config /tmp/apdef-config 
	reboot
}

ator() {
	nvrammanager -r /tmp/user-config -p user-config
	nvrammanager -w /tmp/user-config -p ap-config
	nvrammanager -r /tmp/router-config -p router-config
	if [ -s "/tmp/router-config" ]; then
		echo "-----------------router-config is not null--------------" >/dev/console
	else
		echo "-----------------router-config is null--------------" >/dev/console
		nvrammanager -r /tmp/router-config -p default-config
		nvrammanager -w /tmp/router-config -p router-config
	fi
	echo "-------------sync start----------" >/dev/console
	sync_mode_file ator
	echo "-------------sync end----------" >/dev/console
	rm -f /tmp/user-config /tmp/router-config
	reboot
}

act=$1
case "$act" in
	rtoa)	    rtoa ;;
	ator)	    ator ;;
	*)	    ;;
esac
