#!/bin/sh
#	$Id: MAKEDEV,v 1.8 2003/04/01 19:43:06 awarner Exp $

#Make Node for DB25 parallel port by stanley
mknod -m 755 lp0 c 6 0; chown 0.0 lp0
mknod -m 755 lp1 c 6 1; chown 0.0 lp1

#Make cdrom device node
mknod -m 660 scd0 b 11 0 ; chown 0.0 scd0
mknod -m 660 scd1 b 11 1 ; chown 0.0 scd1
mknod -m 660 scd2 b 11 2 ; chown 0.0 scd2
mknod -m 660 scd3 b 11 3 ; chown 0.0 scd3
mknod -m 660 scd4 b 11 4 ; chown 0.0 scd4
mknod -m 660 scd5 b 11 5 ; chown 0.0 scd5
mknod -m 660 scd6 b 11 6 ; chown 0.0 scd6
mknod -m 660 scd7 b 11 7 ; chown 0.0 scd7
mknod -m 660 scd8 b 11 8 ; chown 0.0 scd8
mknod -m 660 scd9 b 11 9 ; chown 0.0 scd9
mknod -m 660 scd10 b 11 10 ; chown 0.0 scd10
mknod -m 660 scd11 b 11 11 ; chown 0.0 scd11
mknod -m 660 scd12 b 11 12 ; chown 0.0 scd12
mknod -m 660 scd13 b 11 13 ; chown 0.0 scd13
mknod -m 660 scd14 b 11 14 ; chown 0.0 scd14
mknod -m 660 scd15 b 11 15 ; chown 0.0 scd15

mknod -m 660 ttyACM0 c 166 0
mknod -m 660 ttyACM1 c 166 1
mknod -m 660 ttyACM2 c 166 2
mknod -m 660 ttyACM3 c 166 3
mknod -m 660 ttyACM4 c 166 4
mknod -m 660 ttyACM5 c 166 5
mknod -m 660 ttyACM6 c 166 6
mknod -m 660 ttyACM7 c 166 7
mknod noz0 c 241 0; mknod noz1 c 241 1
mknod noz2 c 241 2; mknod noz3 c 241 3

mknod -m 660 ttyHS0 c 252 0
mknod -m 660 ttyHS1 c 252 1
mknod -m 660 ttyHS2 c 252 2
mknod -m 660 ttyHS3 c 252 3
mknod -m 660 ttyHS4 c 252 4
mknod -m 660 ttyHS5 c 252 5
mknod -m 660 ttyHS6 c 252 6
mknod -m 660 ttyHS7 c 252 7
mknod -m 660 scd0 b 11 0

#Make Node for usbserial device
mknod -m 660 ttyUSB0 c 188 0; chown root.uucp ttyUSB0
mknod -m 660 ttyUSB1 c 188 1; chown root.uucp ttyUSB1
mknod -m 660 ttyUSB2 c 188 2; chown root.uucp ttyUSB2
mknod -m 660 ttyUSB3 c 188 3; chown root.uucp ttyUSB3
mknod -m 660 ttyUSB4 c 188 4; chown root.uucp ttyUSB4
mknod -m 660 ttyUSB5 c 188 5; chown root.uucp ttyUSB5
mknod -m 660 ttyUSB6 c 188 6; chown root.uucp ttyUSB6
mknod -m 660 ttyUSB7 c 188 7; chown root.uucp ttyUSB7
mknod -m 660 ttyUSB8 c 188 8; chown root.uucp ttyUSB8
mknod -m 660 ttyUSB9 c 188 9; chown root.uucp ttyUSB9
mknod -m 660 ttyUSB10 c 188 10; chown root.uucp ttyUSB10
mknod -m 660 ttyUSB11 c 188 11; chown root.uucp ttyUSB11
mknod -m 660 ttyUSB12 c 188 12; chown root.uucp ttyUSB12
mknod -m 660 ttyUSB13 c 188 13; chown root.uucp ttyUSB13
mknod -m 660 ttyUSB14 c 188 14; chown root.uucp ttyUSB14
mknod -m 660 ttyUSB15 c 188 15; chown root.uucp ttyUSB15

mknod -m 660 VIAUSBModem0 c 167 0; chown root.uucp VIAUSBModem0

mknod -m 660 ttyIPWp0 c 250 0; chown 0.0 ttyIPWp0
mknod -m 660 ttyIPWp8 c 250 8; chown 0.0 ttyIPWp8

mknod -m 660 hda b 3 0 ; chown 0.0 hda
mknod -m 660 hda1 b 3 1 ; chown 0.0 hda1
mknod -m 660 hda2 b 3 2 ; chown 0.0 hda2
mknod -m 660 hda3 b 3 3 ; chown 0.0 hda3
mknod -m 660 hda4 b 3 4 ; chown 0.0 hda4
mknod -m 660 hda5 b 3 5 ; chown 0.0 hda5
mknod -m 660 hda6 b 3 6 ; chown 0.0 hda6
mknod -m 660 hda7 b 3 7 ; chown 0.0 hda7
mknod -m 660 hda8 b 3 8 ; chown 0.0 hda8
mknod -m 660 hdb b 3 64	; chown 0.0 hdb
mknod -m 660 hdb1 b 3 65 ; chown 0.0 hdb1
mknod -m 660 hdb2 b 3 66 ; chown 0.0 hdb2
mknod -m 660 hdb3 b 3 67 ; chown 0.0 hdb3
mknod -m 660 hdb4 b 3 68 ; chown 0.0 hdb4
mknod -m 660 hdb5 b 3 69 ; chown 0.0 hdb5
mknod -m 660 hdb6 b 3 70 ; chown 0.0 hdb6
mknod -m 660 hdb7 b 3 71 ; chown 0.0 hdb7
mknod -m 660 hdb8 b 3 72 ; chown 0.0 hdb8
mknod -m 660 hdc b 22 0 ; chown 0.0 hdc
mknod -m 660 hdc1 b 22 1 ; chown 0.0 hdc1
mknod -m 660 hdc2 b 22 2 ; chown 0.0 hdc2
mknod -m 660 hdc3 b 22 3 ; chown 0.0 hdc3
mknod -m 660 hdc4 b 22 4 ; chown 0.0 hdc4
mknod -m 660 hdc5 b 22 5 ; chown 0.0 hdc5
mknod -m 660 hdc6 b 22 6 ; chown 0.0 hdc6
mknod -m 660 hdc7 b 22 7 ; chown 0.0 hdc7
mknod -m 660 hdc8 b 22 8 ; chown 0.0 hdc8
mknod -m 660 hdd b 22 64 ; chown 0.0 hdd
mknod -m 660 hdd1 b 22 65 ; chown 0.0 hdd1
mknod -m 660 hdd2 b 22 66 ; chown 0.0 hdd2
mknod -m 660 hdd3 b 22 67 ; chown 0.0 hdd3
mknod -m 660 hdd4 b 22 68 ; chown 0.0 hdd4
mknod -m 660 hdd5 b 22 69 ; chown 0.0 hdd5
mknod -m 660 hdd6 b 22 70 ; chown 0.0 hdd6
mknod -m 660 hdd7 b 22 71 ; chown 0.0 hdd7
mknod -m 660 hdd8 b 22 72 ; chown 0.0 hdd8

#Make Node for IDE Hard Disk by Laroche
#mknod -m 660 hde b 33 0 ; chown 0.0 hde
#mknod -m 660 hde1 b 33 1 ; chown 0.0 hde1
#mknod -m 660 hde2 b 33 2 ; chown 0.0 hde2
#mknod -m 660 hde3 b 33 3 ; chown 0.0 hde3
#mknod -m 660 hde4 b 33 4 ; chown 0.0 hde4
#mknod -m 660 hde5 b 33 5 ; chown 0.0 hde5
#mknod -m 660 hde6 b 33 6 ; chown 0.0 hde6
#mknod -m 660 hdf b 33 64 ; chown 0.0 hdf
#mknod -m 660 hdf1 b 33 65 ; chown 0.0 hdf1
#mknod -m 660 hdf2 b 33 66 ; chown 0.0 hdf2
#mknod -m 660 hdf3 b 33 67 ; chown 0.0 hdf3
#mknod -m 660 hdf4 b 33 68 ; chown 0.0 hdf4
#mknod -m 660 hdf5 b 33 69 ; chown 0.0 hdf5
#mknod -m 660 hdf6 b 33 70 ; chown 0.0 hdf6

#Make Node for USB Printer by Laroche
mknod -m 755 usblp0 c 180  0; chown 0.0 usblp0
mknod -m 755 usblp1 c 180  1; chown 0.0 usblp1
mknod -m 755 usblp2 c 180  2; chown 0.0 usblp2
mknod -m 755 usblp3 c 180  3; chown 0.0 usblp3

#   Make Node for USB Device by Laroche
mknod -m 755 sda b 8 0 ; chown 0.0 sda
mknod -m 755 sda1 b 8 1 ;chown 0.0 sda1
mknod -m 755 sda2 b 8 2 ;chown 0.0 sda2
mknod -m 755 sda3 b 8 3 ;chown 0.0 sda3
mknod -m 755 sda4 b 8 4 ;chown 0.0 sda4
mknod -m 755 sda5 b 8 5 ;chown 0.0 sda5
mknod -m 755 sda6 b 8 6 ;chown 0.0 sda6
mknod -m 755 sda7 b 8 7 ;chown 0.0 sda7
mknod -m 755 sda8 b 8 8 ;chown 0.0 sda8
mknod -m 755 sda9 b 8 9 ;chown 0.0 sda9
mknod -m 755 sda10 b 8 10 ;chown 0.0 sda10
mknod -m 755 sda11 b 8 11 ;chown 0.0 sda11
mknod -m 755 sda12 b 8 12 ;chown 0.0 sda12
mknod -m 755 sda13 b 8 13 ;chown 0.0 sda13
mknod -m 755 sda14 b 8 14 ;chown 0.0 sda14
mknod -m 755 sda15 b 8 15 ;chown 0.0 sda15
mknod -m 755 sdb b 8 16 ; chown 0.0 sdb
mknod -m 755 sdb1 b 8 17 ;chown 0.0 sdb1
mknod -m 755 sdb2 b 8 18 ;chown 0.0 sdb2
mknod -m 755 sdb3 b 8 19 ;chown 0.0 sdb3
mknod -m 755 sdb4 b 8 20 ;chown 0.0 sdb4
mknod -m 755 sdb5 b 8 21 ;chown 0.0 sdb5
mknod -m 755 sdb6 b 8 22 ;chown 0.0 sdb6
mknod -m 755 sdb7 b 8 23 ;chown 0.0 sdb7
mknod -m 755 sdb8 b 8 24 ;chown 0.0 sdb8
mknod -m 755 sdb9 b 8 25 ;chown 0.0 sdb9
mknod -m 755 sdb10 b 8 26 ;chown 0.0 sdb10
mknod -m 755 sdb11 b 8 27 ;chown 0.0 sdb11
mknod -m 755 sdb12 b 8 28 ;chown 0.0 sdb12
mknod -m 755 sdb13 b 8 29 ;chown 0.0 sdb13
mknod -m 755 sdb14 b 8 30 ;chown 0.0 sdb14
mknod -m 755 sdb15 b 8 31 ;chown 0.0 sdb15
mknod -m 755 sdc b 8 32 ; chown 0.0 sdc
mknod -m 755 sdc1 b 8 33 ;chown 0.0 sdc1
mknod -m 755 sdc2 b 8 34 ;chown 0.0 sdc2
mknod -m 755 sdc3 b 8 35 ;chown 0.0 sdc3
mknod -m 755 sdc4 b 8 36 ;chown 0.0 sdc4
mknod -m 755 sdc5 b 8 37 ;chown 0.0 sdc5
mknod -m 755 sdc6 b 8 38 ;chown 0.0 sdc6
mknod -m 755 sdc7 b 8 39 ;chown 0.0 sdc7
mknod -m 755 sdc8 b 8 40 ;chown 0.0 sdc8
mknod -m 755 sdc9 b 8 41 ;chown 0.0 sdc9
mknod -m 755 sdc10 b 8 42 ;chown 0.0 sdc10
mknod -m 755 sdc11 b 8 43 ;chown 0.0 sdc11
mknod -m 755 sdc12 b 8 44 ;chown 0.0 sdc12
mknod -m 755 sdc13 b 8 45 ;chown 0.0 sdc13
mknod -m 755 sdc14 b 8 46 ;chown 0.0 sdc14
mknod -m 755 sdc15 b 8 47 ;chown 0.0 sdc15
mknod -m 755 sdd b 8 48 ; chown 0.0 sdd
mknod -m 755 sdd1 b 8 49 ;chown 0.0 sdd1
mknod -m 755 sdd2 b 8 50 ;chown 0.0 sdd2
mknod -m 755 sdd3 b 8 51 ;chown 0.0 sdd3
mknod -m 755 sdd4 b 8 52 ;chown 0.0 sdd4
mknod -m 755 sdd5 b 8 53 ;chown 0.0 sdd5
mknod -m 755 sdd6 b 8 54 ;chown 0.0 sdd6
mknod -m 755 sdd7 b 8 55 ;chown 0.0 sdd7
mknod -m 755 sdd8 b 8 56 ;chown 0.0 sdd8
mknod -m 755 sdd9 b 8 57 ;chown 0.0 sdd9
mknod -m 755 sdd10 b 8 58 ;chown 0.0 sdd10
mknod -m 755 sdd11 b 8 59 ;chown 0.0 sdd11
mknod -m 755 sdd12 b 8 60 ;chown 0.0 sdd12
mknod -m 755 sdd13 b 8 61 ;chown 0.0 sdd13
mknod -m 755 sdd14 b 8 62 ;chown 0.0 sdd14
mknod -m 755 sdd15 b 8 63 ;chown 0.0 sdd15
mknod -m 755 sde b 8 64 ; chown 0.0 sde
mknod -m 755 sde1 b 8 65 ;chown 0.0 sde1
mknod -m 755 sde2 b 8 66 ;chown 0.0 sde2
mknod -m 755 sde3 b 8 67 ;chown 0.0 sde3
mknod -m 755 sde4 b 8 68 ;chown 0.0 sde4
mknod -m 755 sde5 b 8 69 ;chown 0.0 sde5
mknod -m 755 sde6 b 8 70 ;chown 0.0 sde6
mknod -m 755 sde7 b 8 71 ;chown 0.0 sde7
mknod -m 755 sde8 b 8 72 ;chown 0.0 sde8
mknod -m 755 sde9 b 8 73 ;chown 0.0 sde9
mknod -m 755 sde10 b 8 74 ;chown 0.0 sde10
mknod -m 755 sde11 b 8 75 ;chown 0.0 sde11
mknod -m 755 sde12 b 8 76 ;chown 0.0 sde12
mknod -m 755 sde13 b 8 77 ;chown 0.0 sde13
mknod -m 755 sde14 b 8 78 ;chown 0.0 sde14
mknod -m 755 sde15 b 8 79 ;chown 0.0 sde15
mknod -m 755 sdf b 8 80 ; chown 0.0 sdf
mknod -m 755 sdf1 b 8 81 ;chown 0.0 sdf1
mknod -m 755 sdf2 b 8 82 ;chown 0.0 sdf2
mknod -m 755 sdf3 b 8 83 ;chown 0.0 sdf3
mknod -m 755 sdf4 b 8 84 ;chown 0.0 sdf4
mknod -m 755 sdf5 b 8 85 ;chown 0.0 sdf5
mknod -m 755 sdf6 b 8 86 ;chown 0.0 sdf6
mknod -m 755 sdf7 b 8 87 ;chown 0.0 sdf7
mknod -m 755 sdf8 b 8 88 ;chown 0.0 sdf8
mknod -m 755 sdf9 b 8 89 ;chown 0.0 sdf9
mknod -m 755 sdf10 b 8 90 ;chown 0.0 sdf10
mknod -m 755 sdf11 b 8 91 ;chown 0.0 sdf11
mknod -m 755 sdf12 b 8 92 ;chown 0.0 sdf12
mknod -m 755 sdf13 b 8 93 ;chown 0.0 sdf13
mknod -m 755 sdf14 b 8 94 ;chown 0.0 sdf14
mknod -m 755 sdf15 b 8 95 ;chown 0.0 sdf15
mknod -m 755 sdg b 8 96 ; chown 0.0 sdg
mknod -m 755 sdg1 b 8 97 ;chown 0.0 sdg1
mknod -m 755 sdg2 b 8 98 ;chown 0.0 sdg2
mknod -m 755 sdg3 b 8 99 ;chown 0.0 sdg3
mknod -m 755 sdg4 b 8 100 ;chown 0.0 sdg4
mknod -m 755 sdg5 b 8 101 ;chown 0.0 sdg5
mknod -m 755 sdg6 b 8 102 ;chown 0.0 sdg6
mknod -m 755 sdg7 b 8 103 ;chown 0.0 sdg7
mknod -m 755 sdg8 b 8 104 ;chown 0.0 sdg8
mknod -m 755 sdg9 b 8 105 ;chown 0.0 sdg9
mknod -m 755 sdg10 b 8 106 ;chown 0.0 sdg10
mknod -m 755 sdg11 b 8 107 ;chown 0.0 sdg11
mknod -m 755 sdg12 b 8 108 ;chown 0.0 sdg12
mknod -m 755 sdg13 b 8 109 ;chown 0.0 sdg13
mknod -m 755 sdg14 b 8 110 ;chown 0.0 sdg14
mknod -m 755 sdg15 b 8 111 ;chown 0.0 sdg15
mknod -m 755 sdh b 8 112 ; chown 0.0 sdh
mknod -m 755 sdh1 b 8 113 ;chown 0.0 sdh1
mknod -m 755 sdh2 b 8 114 ;chown 0.0 sdh2
mknod -m 755 sdh3 b 8 115 ;chown 0.0 sdh3
mknod -m 755 sdh4 b 8 116 ;chown 0.0 sdh4
mknod -m 755 sdh5 b 8 117 ;chown 0.0 sdh5
mknod -m 755 sdh6 b 8 118 ;chown 0.0 sdh6
mknod -m 755 sdh7 b 8 119 ;chown 0.0 sdh7
mknod -m 755 sdh8 b 8 120 ;chown 0.0 sdh8
mknod -m 755 sdh9 b 8 121 ;chown 0.0 sdh9
mknod -m 755 sdh10 b 8 122 ;chown 0.0 sdh10
mknod -m 755 sdh11 b 8 123 ;chown 0.0 sdh11
mknod -m 755 sdh12 b 8 124 ;chown 0.0 sdh12
mknod -m 755 sdh13 b 8 125 ;chown 0.0 sdh13
mknod -m 755 sdh14 b 8 126 ;chown 0.0 sdh14
mknod -m 755 sdh15 b 8 127 ;chown 0.0 sdh15
mknod -m 755 sdi b 8 128 ; chown 0.0 sdi
mknod -m 755 sdi1 b 8 129 ;chown 0.0 sdi1
mknod -m 755 sdi2 b 8 130 ;chown 0.0 sdi2
mknod -m 755 sdi3 b 8 131 ;chown 0.0 sdi3
mknod -m 755 sdi4 b 8 132 ;chown 0.0 sdi4
mknod -m 755 sdi5 b 8 133 ;chown 0.0 sdi5
mknod -m 755 sdi6 b 8 134 ;chown 0.0 sdi6
mknod -m 755 sdi7 b 8 135 ;chown 0.0 sdi7
mknod -m 755 sdi8 b 8 136 ;chown 0.0 sdi8
mknod -m 755 sdi9 b 8 137 ;chown 0.0 sdi9
mknod -m 755 sdi10 b 8 138 ;chown 0.0 sdi10
mknod -m 755 sdi11 b 8 139 ;chown 0.0 sdi11
mknod -m 755 sdi12 b 8 140 ;chown 0.0 sdi12
mknod -m 755 sdi13 b 8 141 ;chown 0.0 sdi13
mknod -m 755 sdi14 b 8 142 ;chown 0.0 sdi14
mknod -m 755 sdi15 b 8 143 ;chown 0.0 sdi15
mknod -m 755 sdj b 8 144 ; chown 0.0 sdj
mknod -m 755 sdj1 b 8 145 ;chown 0.0 sdj1
mknod -m 755 sdj2 b 8 146 ;chown 0.0 sdj2
mknod -m 755 sdj3 b 8 147 ;chown 0.0 sdj3
mknod -m 755 sdj4 b 8 148 ;chown 0.0 sdj4
mknod -m 755 sdj5 b 8 149 ;chown 0.0 sdj5
mknod -m 755 sdj6 b 8 150 ;chown 0.0 sdj6
mknod -m 755 sdj7 b 8 151 ;chown 0.0 sdj7
mknod -m 755 sdj8 b 8 152 ;chown 0.0 sdj8
mknod -m 755 sdj9 b 8 153 ;chown 0.0 sdj9
mknod -m 755 sdj10 b 8 154 ;chown 0.0 sdj10
mknod -m 755 sdj11 b 8 155 ;chown 0.0 sdj11
mknod -m 755 sdj12 b 8 156 ;chown 0.0 sdj12
mknod -m 755 sdj13 b 8 157 ;chown 0.0 sdj13
mknod -m 755 sdj14 b 8 158 ;chown 0.0 sdj14
mknod -m 755 sdj15 b 8 159 ;chown 0.0 sdj15
mknod -m 755 sdk b 8 160 ; chown 0.0 sdk
mknod -m 755 sdk1 b 8 161 ;chown 0.0 sdk1
mknod -m 755 sdk2 b 8 162 ;chown 0.0 sdk2
mknod -m 755 sdk3 b 8 163 ;chown 0.0 sdk3
mknod -m 755 sdk4 b 8 164 ;chown 0.0 sdk4
mknod -m 755 sdk5 b 8 165 ;chown 0.0 sdk5
mknod -m 755 sdk6 b 8 166 ;chown 0.0 sdk6
mknod -m 755 sdk7 b 8 167 ;chown 0.0 sdk7
mknod -m 755 sdk8 b 8 168 ;chown 0.0 sdk8
mknod -m 755 sdk9 b 8 169 ;chown 0.0 sdk9
mknod -m 755 sdk10 b 8 170 ;chown 0.0 sdk10
mknod -m 755 sdk11 b 8 171 ;chown 0.0 sdk11
mknod -m 755 sdk12 b 8 172 ;chown 0.0 sdk12
mknod -m 755 sdk13 b 8 173 ;chown 0.0 sdk13
mknod -m 755 sdk14 b 8 174 ;chown 0.0 sdk14
mknod -m 755 sdk15 b 8 175 ;chown 0.0 sdk15
mknod -m 755 sdl b 8 176 ; chown 0.0 sdl
mknod -m 755 sdl1 b 8 177 ;chown 0.0 sdl1
mknod -m 755 sdl2 b 8 178 ;chown 0.0 sdl2
mknod -m 755 sdl3 b 8 179 ;chown 0.0 sdl3
mknod -m 755 sdl4 b 8 180 ;chown 0.0 sdl4
mknod -m 755 sdl5 b 8 181 ;chown 0.0 sdl5
mknod -m 755 sdl6 b 8 182 ;chown 0.0 sdl6
mknod -m 755 sdl7 b 8 183 ;chown 0.0 sdl7
mknod -m 755 sdl8 b 8 184 ;chown 0.0 sdl8
mknod -m 755 sdl9 b 8 185 ;chown 0.0 sdl9
mknod -m 755 sdl10 b 8 186 ;chown 0.0 sdl10
mknod -m 755 sdl11 b 8 187 ;chown 0.0 sdl11
mknod -m 755 sdl12 b 8 188 ;chown 0.0 sdl12
mknod -m 755 sdl13 b 8 189 ;chown 0.0 sdl13
mknod -m 755 sdl14 b 8 190 ;chown 0.0 sdl14
mknod -m 755 sdl15 b 8 191 ;chown 0.0 sdl15
mknod -m 755 sdm b 8 192 ; chown 0.0 sdm
mknod -m 755 sdm1 b 8 193 ;chown 0.0 sdm1
mknod -m 755 sdm2 b 8 194 ;chown 0.0 sdm2
mknod -m 755 sdm3 b 8 195 ;chown 0.0 sdm3
mknod -m 755 sdm4 b 8 196 ;chown 0.0 sdm4
mknod -m 755 sdm5 b 8 197 ;chown 0.0 sdm5
mknod -m 755 sdm6 b 8 198 ;chown 0.0 sdm6
mknod -m 755 sdm7 b 8 199 ;chown 0.0 sdm7
mknod -m 755 sdm8 b 8 200 ;chown 0.0 sdm8
mknod -m 755 sdm9 b 8 201 ;chown 0.0 sdm9
mknod -m 755 sdm10 b 8 202 ;chown 0.0 sdm10
mknod -m 755 sdm11 b 8 203 ;chown 0.0 sdm11
mknod -m 755 sdm12 b 8 204 ;chown 0.0 sdm12
mknod -m 755 sdm13 b 8 205 ;chown 0.0 sdm13
mknod -m 755 sdm14 b 8 206 ;chown 0.0 sdm14
mknod -m 755 sdm15 b 8 207 ;chown 0.0 sdm15
mknod -m 755 sdn b 8 208 ; chown 0.0 sdn
mknod -m 755 sdn1 b 8 209 ;chown 0.0 sdn1
mknod -m 755 sdn2 b 8 210 ;chown 0.0 sdn2
mknod -m 755 sdn3 b 8 211 ;chown 0.0 sdn3
mknod -m 755 sdn4 b 8 212 ;chown 0.0 sdn4
mknod -m 755 sdn5 b 8 213 ;chown 0.0 sdn5
mknod -m 755 sdn6 b 8 214 ;chown 0.0 sdn6
mknod -m 755 sdn7 b 8 215 ;chown 0.0 sdn7
mknod -m 755 sdn8 b 8 216 ;chown 0.0 sdn8
mknod -m 755 sdn9 b 8 217 ;chown 0.0 sdn9
mknod -m 755 sdn10 b 8 218 ;chown 0.0 sdn10
mknod -m 755 sdn11 b 8 219 ;chown 0.0 sdn11
mknod -m 755 sdn12 b 8 220 ;chown 0.0 sdn12
mknod -m 755 sdn13 b 8 221 ;chown 0.0 sdn13
mknod -m 755 sdn14 b 8 222 ;chown 0.0 sdn14
mknod -m 755 sdn15 b 8 223 ;chown 0.0 sdn15
mknod -m 755 sdo b 8 224 ; chown 0.0 sdo
mknod -m 755 sdo1 b 8 225 ;chown 0.0 sdo1
mknod -m 755 sdo2 b 8 226 ;chown 0.0 sdo2
mknod -m 755 sdo3 b 8 227 ;chown 0.0 sdo3
mknod -m 755 sdo4 b 8 228 ;chown 0.0 sdo4
mknod -m 755 sdo5 b 8 229 ;chown 0.0 sdo5
mknod -m 755 sdo6 b 8 230 ;chown 0.0 sdo6
mknod -m 755 sdo7 b 8 231 ;chown 0.0 sdo7
mknod -m 755 sdo8 b 8 232 ;chown 0.0 sdo8
mknod -m 755 sdo9 b 8 233 ;chown 0.0 sdo9
mknod -m 755 sdo10 b 8 234 ;chown 0.0 sdo10
mknod -m 755 sdo11 b 8 235 ;chown 0.0 sdo11
mknod -m 755 sdo12 b 8 236 ;chown 0.0 sdo12
mknod -m 755 sdo13 b 8 237 ;chown 0.0 sdo13
mknod -m 755 sdo14 b 8 238 ;chown 0.0 sdo14
mknod -m 755 sdo15 b 8 239 ;chown 0.0 sdo15
mknod -m 755 sdp b 8 240 ; chown 0.0 sdp
mknod -m 755 sdp1 b 8 241 ;chown 0.0 sdp1
mknod -m 755 sdp2 b 8 242 ;chown 0.0 sdp2
mknod -m 755 sdp3 b 8 243 ;chown 0.0 sdp3
mknod -m 755 sdp4 b 8 244 ;chown 0.0 sdp4
mknod -m 755 sdp5 b 8 245 ;chown 0.0 sdp5
mknod -m 755 sdp6 b 8 246 ;chown 0.0 sdp6
mknod -m 755 sdp7 b 8 247 ;chown 0.0 sdp7
mknod -m 755 sdp8 b 8 248 ;chown 0.0 sdp8
mknod -m 755 sdp9 b 8 249 ;chown 0.0 sdp9
mknod -m 755 sdp10 b 8 250 ;chown 0.0 sdp10
mknod -m 755 sdp11 b 8 251 ;chown 0.0 sdp11
mknod -m 755 sdp12 b 8 252 ;chown 0.0 sdp12
mknod -m 755 sdp13 b 8 253 ;chown 0.0 sdp13
mknod -m 755 sdp14 b 8 254 ;chown 0.0 sdp14
mknod -m 755 sdp15 b 8 255 ;chown 0.0 sdp15
mknod -m 755 sdq b 65 0 ; chown 0.0 sdq
mknod -m 755 sdq1 b 65 1 ;chown 0.0 sdq1
mknod -m 755 sdq2 b 65 2 ;chown 0.0 sdq2
mknod -m 755 sdq3 b 65 3 ;chown 0.0 sdq3
mknod -m 755 sdq4 b 65 4 ;chown 0.0 sdq4
mknod -m 755 sdq5 b 65 5 ;chown 0.0 sdq5
mknod -m 755 sdq6 b 65 6 ;chown 0.0 sdq6
mknod -m 755 sdq7 b 65 7 ;chown 0.0 sdq7
mknod -m 755 sdq8 b 65 8 ;chown 0.0 sdq8
mknod -m 755 sdq9 b 65 9 ;chown 0.0 sdq9
mknod -m 755 sdq10 b 65 10 ;chown 0.0 sdq10
mknod -m 755 sdq11 b 65 11 ;chown 0.0 sdq11
mknod -m 755 sdq12 b 65 12 ;chown 0.0 sdq12
mknod -m 755 sdq13 b 65 13 ;chown 0.0 sdq13
mknod -m 755 sdq14 b 65 14 ;chown 0.0 sdq14
mknod -m 755 sdq15 b 65 15 ;chown 0.0 sdq15
mknod -m 755 sdr b 65 16 ; chown 0.0 sdr
mknod -m 755 sdr1 b 65 17 ;chown 0.0 sdr1
mknod -m 755 sdr2 b 65 18 ;chown 0.0 sdr2
mknod -m 755 sdr3 b 65 19 ;chown 0.0 sdr3
mknod -m 755 sdr4 b 65 20 ;chown 0.0 sdr4
mknod -m 755 sdr5 b 65 21 ;chown 0.0 sdr5
mknod -m 755 sdr6 b 65 22 ;chown 0.0 sdr6
mknod -m 755 sdr7 b 65 23 ;chown 0.0 sdr7
mknod -m 755 sdr8 b 65 24 ;chown 0.0 sdr8
mknod -m 755 sdr9 b 65 25 ;chown 0.0 sdr9
mknod -m 755 sdr10 b 65 26 ;chown 0.0 sdr10
mknod -m 755 sdr11 b 65 27 ;chown 0.0 sdr11
mknod -m 755 sdr12 b 65 28 ;chown 0.0 sdr12
mknod -m 755 sdr13 b 65 29 ;chown 0.0 sdr13
mknod -m 755 sdr14 b 65 30 ;chown 0.0 sdr14
mknod -m 755 sdr15 b 65 31 ;chown 0.0 sdr15
mknod -m 755 sds b 65 32 ; chown 0.0 sds
mknod -m 755 sds1 b 65 33 ;chown 0.0 sds1
mknod -m 755 sds2 b 65 34 ;chown 0.0 sds2
mknod -m 755 sds3 b 65 35 ;chown 0.0 sds3
mknod -m 755 sds4 b 65 36 ;chown 0.0 sds4
mknod -m 755 sds5 b 65 37 ;chown 0.0 sds5
mknod -m 755 sds6 b 65 38 ;chown 0.0 sds6
mknod -m 755 sds7 b 65 39 ;chown 0.0 sds7
mknod -m 755 sds8 b 65 40 ;chown 0.0 sds8
mknod -m 755 sds9 b 65 41 ;chown 0.0 sds9
mknod -m 755 sds10 b 65 42 ;chown 0.0 sds10
mknod -m 755 sds11 b 65 43 ;chown 0.0 sds11
mknod -m 755 sds12 b 65 44 ;chown 0.0 sds12
mknod -m 755 sds13 b 65 45 ;chown 0.0 sds13
mknod -m 755 sds14 b 65 46 ;chown 0.0 sds14
mknod -m 755 sds15 b 65 47 ;chown 0.0 sds15
mknod -m 755 sdt b 65 48 ; chown 0.0 sdt
mknod -m 755 sdt1 b 65 49 ;chown 0.0 sdt1
mknod -m 755 sdt2 b 65 50 ;chown 0.0 sdt2
mknod -m 755 sdt3 b 65 51 ;chown 0.0 sdt3
mknod -m 755 sdt4 b 65 52 ;chown 0.0 sdt4
mknod -m 755 sdt5 b 65 53 ;chown 0.0 sdt5
mknod -m 755 sdt6 b 65 54 ;chown 0.0 sdt6
mknod -m 755 sdt7 b 65 55 ;chown 0.0 sdt7
mknod -m 755 sdt8 b 65 56 ;chown 0.0 sdt8
mknod -m 755 sdt9 b 65 57 ;chown 0.0 sdt9
mknod -m 755 sdt10 b 65 58 ;chown 0.0 sdt10
mknod -m 755 sdt11 b 65 59 ;chown 0.0 sdt11
mknod -m 755 sdt12 b 65 60 ;chown 0.0 sdt12
mknod -m 755 sdt13 b 65 61 ;chown 0.0 sdt13
mknod -m 755 sdt14 b 65 62 ;chown 0.0 sdt14
mknod -m 755 sdt15 b 65 63 ;chown 0.0 sdt15
mknod -m 755 sdu b 65 64 ; chown 0.0 sdu
mknod -m 755 sdu1 b 65 65 ;chown 0.0 sdu1
mknod -m 755 sdu2 b 65 66 ;chown 0.0 sdu2
mknod -m 755 sdu3 b 65 67 ;chown 0.0 sdu3
mknod -m 755 sdu4 b 65 68 ;chown 0.0 sdu4
mknod -m 755 sdu5 b 65 69 ;chown 0.0 sdu5
mknod -m 755 sdu6 b 65 70 ;chown 0.0 sdu6
mknod -m 755 sdu7 b 65 71 ;chown 0.0 sdu7
mknod -m 755 sdu8 b 65 72 ;chown 0.0 sdu8
mknod -m 755 sdu9 b 65 73 ;chown 0.0 sdu9
mknod -m 755 sdu10 b 65 74 ;chown 0.0 sdu10
mknod -m 755 sdu11 b 65 75 ;chown 0.0 sdu11
mknod -m 755 sdu12 b 65 76 ;chown 0.0 sdu12
mknod -m 755 sdu13 b 65 77 ;chown 0.0 sdu13
mknod -m 755 sdu14 b 65 78 ;chown 0.0 sdu14
mknod -m 755 sdu15 b 65 79 ;chown 0.0 sdu15
mknod -m 755 sdv b 65 80 ; chown 0.0 sdv
mknod -m 755 sdv1 b 65 81 ;chown 0.0 sdv1
mknod -m 755 sdv2 b 65 82 ;chown 0.0 sdv2
mknod -m 755 sdv3 b 65 83 ;chown 0.0 sdv3
mknod -m 755 sdv4 b 65 84 ;chown 0.0 sdv4
mknod -m 755 sdv5 b 65 85 ;chown 0.0 sdv5
mknod -m 755 sdv6 b 65 86 ;chown 0.0 sdv6
mknod -m 755 sdv7 b 65 87 ;chown 0.0 sdv7
mknod -m 755 sdv8 b 65 88 ;chown 0.0 sdv8
mknod -m 755 sdv9 b 65 89 ;chown 0.0 sdv9
mknod -m 755 sdv10 b 65 90 ;chown 0.0 sdv10
mknod -m 755 sdv11 b 65 91 ;chown 0.0 sdv11
mknod -m 755 sdv12 b 65 92 ;chown 0.0 sdv12
mknod -m 755 sdv13 b 65 93 ;chown 0.0 sdv13
mknod -m 755 sdv14 b 65 94 ;chown 0.0 sdv14
mknod -m 755 sdv15 b 65 95 ;chown 0.0 sdv15
mknod -m 755 sdw b 65 96 ; chown 0.0 sdw
mknod -m 755 sdw1 b 65 97 ;chown 0.0 sdw1
mknod -m 755 sdw2 b 65 98 ;chown 0.0 sdw2
mknod -m 755 sdw3 b 65 99 ;chown 0.0 sdw3
mknod -m 755 sdw4 b 65 100 ;chown 0.0 sdw4
mknod -m 755 sdw5 b 65 101 ;chown 0.0 sdw5
mknod -m 755 sdw6 b 65 102 ;chown 0.0 sdw6
mknod -m 755 sdw7 b 65 103 ;chown 0.0 sdw7
mknod -m 755 sdw8 b 65 104 ;chown 0.0 sdw8
mknod -m 755 sdw9 b 65 105 ;chown 0.0 sdw9
mknod -m 755 sdw10 b 65 106 ;chown 0.0 sdw10
mknod -m 755 sdw11 b 65 107 ;chown 0.0 sdw11
mknod -m 755 sdw12 b 65 108 ;chown 0.0 sdw12
mknod -m 755 sdw13 b 65 109 ;chown 0.0 sdw13
mknod -m 755 sdw14 b 65 110 ;chown 0.0 sdw14
mknod -m 755 sdw15 b 65 111 ;chown 0.0 sdw15
mknod -m 755 sdx b 65 112 ; chown 0.0 sdx
mknod -m 755 sdx1 b 65 113 ;chown 0.0 sdx1
mknod -m 755 sdx2 b 65 114 ;chown 0.0 sdx2
mknod -m 755 sdx3 b 65 115 ;chown 0.0 sdx3
mknod -m 755 sdx4 b 65 116 ;chown 0.0 sdx4
mknod -m 755 sdx5 b 65 117 ;chown 0.0 sdx5
mknod -m 755 sdx6 b 65 118 ;chown 0.0 sdx6
mknod -m 755 sdx7 b 65 119 ;chown 0.0 sdx7
mknod -m 755 sdx8 b 65 120 ;chown 0.0 sdx8
mknod -m 755 sdx9 b 65 121 ;chown 0.0 sdx9
mknod -m 755 sdx10 b 65 122 ;chown 0.0 sdx10
mknod -m 755 sdx11 b 65 123 ;chown 0.0 sdx11
mknod -m 755 sdx12 b 65 124 ;chown 0.0 sdx12
mknod -m 755 sdx13 b 65 125 ;chown 0.0 sdx13
mknod -m 755 sdx14 b 65 126 ;chown 0.0 sdx14
mknod -m 755 sdx15 b 65 127 ;chown 0.0 sdx15
mknod -m 755 sdy b 65 128 ; chown 0.0 sdy
mknod -m 755 sdy1 b 65 129 ;chown 0.0 sdy1
mknod -m 755 sdy2 b 65 130 ;chown 0.0 sdy2
mknod -m 755 sdy3 b 65 131 ;chown 0.0 sdy3
mknod -m 755 sdy4 b 65 132 ;chown 0.0 sdy4
mknod -m 755 sdy5 b 65 133 ;chown 0.0 sdy5
mknod -m 755 sdy6 b 65 134 ;chown 0.0 sdy6
mknod -m 755 sdy7 b 65 135 ;chown 0.0 sdy7
mknod -m 755 sdy8 b 65 136 ;chown 0.0 sdy8
mknod -m 755 sdy9 b 65 137 ;chown 0.0 sdy9
mknod -m 755 sdy10 b 65 138 ;chown 0.0 sdy10
mknod -m 755 sdy11 b 65 139 ;chown 0.0 sdy11
mknod -m 755 sdy12 b 65 140 ;chown 0.0 sdy12
mknod -m 755 sdy13 b 65 141 ;chown 0.0 sdy13
mknod -m 755 sdy14 b 65 142 ;chown 0.0 sdy14
mknod -m 755 sdy15 b 65 143 ;chown 0.0 sdy15
mknod -m 755 sdz b 65 144 ; chown 0.0 sdz
mknod -m 755 sdz1 b 65 145 ;chown 0.0 sdz1
mknod -m 755 sdz2 b 65 146 ;chown 0.0 sdz2
mknod -m 755 sdz3 b 65 147 ;chown 0.0 sdz3
mknod -m 755 sdz4 b 65 148 ;chown 0.0 sdz4
mknod -m 755 sdz5 b 65 149 ;chown 0.0 sdz5
mknod -m 755 sdz6 b 65 150 ;chown 0.0 sdz6
mknod -m 755 sdz7 b 65 151 ;chown 0.0 sdz7
mknod -m 755 sdz8 b 65 152 ;chown 0.0 sdz8
mknod -m 755 sdz9 b 65 153 ;chown 0.0 sdz9
mknod -m 755 sdz10 b 65 154 ;chown 0.0 sdz10
mknod -m 755 sdz11 b 65 155 ;chown 0.0 sdz11
mknod -m 755 sdz12 b 65 156 ;chown 0.0 sdz12
mknod -m 755 sdz13 b 65 157 ;chown 0.0 sdz13
mknod -m 755 sdz14 b 65 158 ;chown 0.0 sdz14
mknod -m 755 sdz15 b 65 159 ;chown 0.0 sdz15








mkdir -m 755 pts ; chown 0.0 pts

mknod -m 660 ram0 b 1 0 ; chown 0.6 ram0
mknod -m 660 ram1 b 1 1 ; chown 0.6 ram1
mknod -m 660 ram2 b 1 2 ; chown 0.6 ram2
mknod -m 660 ram3 b 1 3 ; chown 0.6 ram3

mknod -m 640 mem c 1 1 ; chown 0.2 mem
mknod -m 640 kmem c 1 2 ; chown 0.2 kmem
mknod -m 666 null c 1 3 ; chown 0.0 null
mknod -m 666 zero c 1 5 ; chown 0.0 zero
mknod -m 644 random c 1 8 ; chown 0.0 random
mknod -m 644 urandom c 1 9 ; chown 0.0 urandom

mknod -m 666 ptyp0 c 2 0 ; chown 0.5 ptyp0
mknod -m 666 ptyp1 c 2 1 ; chown 0.5 ptyp1
mknod -m 666 ptyp2 c 2 2 ; chown 0.5 ptyp2
mknod -m 666 ptyp3 c 2 3 ; chown 0.5 ptyp3
mknod -m 666 ptyp4 c 2 4 ; chown 0.5 ptyp4
mknod -m 666 ptyp5 c 2 5 ; chown 0.5 ptyp5
mknod -m 666 ptyp6 c 2 6 ; chown 0.5 ptyp6
mknod -m 666 ptyp7 c 2 7 ; chown 0.5 ptyp7
mknod -m 666 ptyp8 c 2 8 ; chown 0.5 ptyp8
mknod -m 666 ptyp9 c 2 9 ; chown 0.5 ptyp9
mknod -m 666 ptypa c 2 10 ; chown 0.5 ptypa
mknod -m 666 ptypb c 2 11 ; chown 0.5 ptypb
mknod -m 666 ptypc c 2 12 ; chown 0.5 ptypc
mknod -m 666 ptypd c 2 13 ; chown 0.5 ptypd
mknod -m 666 ptype c 2 14 ; chown 0.5 ptype
mknod -m 666 ptypf c 2 15 ; chown 0.5 ptypf

mknod -m 666 ttyp0 c 3 0 ; chown 0.5 ttyp0
mknod -m 666 ttyp1 c 3 1 ; chown 0.5 ttyp1
mknod -m 666 ttyp2 c 3 2 ; chown 0.5 ttyp2
mknod -m 666 ttyp3 c 3 3 ; chown 0.5 ttyp3
mknod -m 666 ttyp4 c 3 4 ; chown 0.5 ttyp4
mknod -m 666 ttyp5 c 3 5 ; chown 0.5 ttyp5
mknod -m 666 ttyp6 c 3 6 ; chown 0.5 ttyp6
mknod -m 666 ttyp7 c 3 7 ; chown 0.5 ttyp7
mknod -m 666 ttyp8 c 3 8 ; chown 0.5 ttyp8
mknod -m 666 ttyp9 c 3 9 ; chown 0.5 ttyp9
mknod -m 666 ttypa c 3 10 ; chown 0.5 ttypa
mknod -m 666 ttypb c 3 11 ; chown 0.5 ttypb
mknod -m 666 ttypc c 3 12 ; chown 0.5 ttypc
mknod -m 666 ttypd c 3 13 ; chown 0.5 ttypd
mknod -m 666 ttype c 3 14 ; chown 0.5 ttype
mknod -m 666 ttypf c 3 15 ; chown 0.5 ttypf

mknod -m 600 tty0 c 4 0 ; chown 0.0 tty0
mknod -m 600 tty1 c 4 1 ; chown 0.0 tty1
mknod -m 600 tty2 c 4 2 ; chown 0.0 tty2
mknod -m 600 tty3 c 4 3 ; chown 0.0 tty3
mknod -m 600 tty4 c 4 4 ; chown 0.0 tty4
mknod -m 600 tty5 c 4 5 ; chown 0.0 tty5
mknod -m 600 tty6 c 4 6 ; chown 0.0 tty6
mknod -m 600 tty7 c 4 7 ; chown 0.0 tty7
mknod -m 600 tty8 c 4 8 ; chown 0.0 tty8
mknod -m 600 tty9 c 4 9 ; chown 0.0 tty9

mknod -m 600 ttyS0 c 4 64 ; chown 0.0 ttyS0
mknod -m 600 ttyS1 c 4 65 ; chown 0.0 ttyS1
mknod -m 600 ttyS2 c 4 66 ; chown 0.0 ttyS2
mknod -m 600 ttyS3 c 4 67 ; chown 0.0 ttyS3
mknod -m 600 ttyS4 c 4 68 ; chown 0.0 ttyS4
mknod -m 600 ttyS5 c 4 69 ; chown 0.0 ttyS5
mknod -m 600 ttyS6 c 4 70 ; chown 0.0 ttyS6
mknod -m 600 ttyS7 c 4 71 ; chown 0.0 ttyS7
mknod -m 600 ttyS8 c 4 72 ; chown 0.0 ttyS8
mknod -m 600 ttyS9 c 4 73 ; chown 0.0 ttyS9

mknod -m 666 tty c 5 0 ; chown 0.0 tty
mknod -m 622 console c 5 1 ; chown 0.0 console

mknod -m 660 cua0 c 5 64 ; chown 0.14 cua0
mknod -m 660 cua1 c 5 65 ; chown 0.14 cua1
mknod -m 660 cua2 c 5 66 ; chown 0.14 cua2
mknod -m 660 cua3 c 5 67 ; chown 0.14 cua3
mknod -m 660 cua4 c 5 68 ; chown 0.14 cua4
mknod -m 660 cua5 c 5 69 ; chown 0.14 cua5
mknod -m 660 cua6 c 5 70 ; chown 0.14 cua6
mknod -m 660 cua7 c 5 71 ; chown 0.14 cua7
mknod -m 660 cua8 c 5 72 ; chown 0.14 cua8
mknod -m 660 cua9 c 5 73 ; chown 0.14 cua9

mknod -m 644 rtc c 10 135 ; chown 0.10 rtc
mknod -m 660 secdev c 10 140 ; chown 0.10 secdev
mknod -m 660 bcopy c 10 141 ; chown 0.10 bcopy

mknod -m 444 rom0 b 31 0 ; chown 0.0 rom0
mknod -m 444 rom1 b 31 1 ; chown 0.0 rom1
mknod -m 444 rom2 b 31 2 ; chown 0.0 rom2
mknod -m 444 rom3 b 31 3 ; chown 0.0 rom3

# Compulsory links.
ln -s /proc/self/fd fd
ln -s fd/0 stdin
ln -s fd/1 stdout
ln -s fd/2 stderr

# Recommended links links.
ln -s /proc/kcore core
ln -s ram0 ramdisk

# for memory technology devices (read: FLASH)
for a in `seq 0 16` ; do
	mknod -m 660 mtd$a c 90 `expr $a + $a` ;     chown 0.6 mtd$a
	mknod -m 660 mtdr$a c 90 `expr $a + $a + 1`; chown 0.6 mtdr$a
	mknod -m 660 mtdblock$a b 131 $a ;            chown 0.6 mtdblock$a
done	


# ppp device (pppoe)
mknod ppp c 108 0 ; chmod 600 ppp ; chown 0.6 ppp

#
# Temp vpm device.
#
mknod vpm0 c 254 0 ; chown 0.0 vpm0
mknod vpm1 c 254 1 ; chown 0.0 vpm1
mknod vpm2 c 254 2 ; chown 0.0 vpm2
mknod vpm3 c 254 3 ; chown 0.0 vpm3
mknod vpm4 c 254 4 ; chown 0.0 vpm4

#
# phonedev devices.
#
mknod phone0 c 100 0 ; chown 0.0 phone0
mknod phone1 c 100 1 ; chown 0.0 phone1
mknod phone2 c 100 2 ; chown 0.0 phone2
mknod phone3 c 100 3 ; chown 0.0 phone3
mknod phone4 c 100 4 ; chown 0.0 phone4

#
# Wireless Relay Device
mknod wlan c 151 0 ; chown 0.0 wlan
# End of file MAKEDEV
