#!/bin/sh
rm -rf /var/run/cgi_changed
rm -rf /var/run/config.check
mkdir -p /var/run/config.check

for config in /etc/config/*; do
    file=${config##*/}
    uci show "${file##*/}" > /var/run/config.check/$file
done

MD5FILE=/var/run/config.md5
changed_config=""
[ -f $MD5FILE ] && {
    for c in `md5sum -c $MD5FILE 2>/dev/null| grep FAILED | cut -d: -f1`; do
        #ubus call service event "{ \"type\": \"config.change\", \"data\": { \"package\": \"$(basename $c)\" }}"
        if [ "$changed_config" = "" ]; then
            changed_config="$(basename $c) "
        else
            changed_config="${changed_config}$(basename $c) "
        fi
    done
}

md5sum /var/run/config.check/* > $MD5FILE
rm -rf /var/run/config.check
[ -n "$changed_config" ] && { sync & }
echo "${changed_config}" > /var/run/cgi_changed
echo -n "${changed_config}"
#/sbin/luci-reload ${changed_config}
