#!/bin/sh
# Add interface to bridge
# Called when event of bridge enabled was received
# Needed object: None

script_name="$0"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/fapi_wlan_wave_lib_common.sh

# Find the radio index

radio_index=`find_index_from_interface_name wlan0`

print2log $radio_index DEBUG "$script_name $*"
timestamp $radio_index "$script_name:begin"

print2log $radio_index ATTENTION "fapi_wlan_wave_factory_reset called"

# Kill all supplicant instances
pid_to_kill=`ps | grep supplicant | grep -v grep | awk '{print $1}'`
for pid in $pid_to_kill
do
	kill -9 $pid
done

# Kill all hostapd instances
pid_to_kill=`ps | grep hostapd | grep -v grep | awk '{print $1}'`
for pid in $pid_to_kill
do
	kill -9 $pid
done

# Remove all Wave related files saved on FLASH
rm -rf ${CONF_DIR}

# Create the output configuration file
cat /dev/null > ${OUT_CONF}

# Configuration is completed successfully
update_conf_out "wlan_configuration_status" "success"

print2log $radio_index DEBUG "$script_name done"
timestamp $radio_index "$script_name:done"
