#!/bin/sh

. /lib/functions.sh

WAN_IFNAME=eth1
WLAN_IFNAMES="wlan0 wlan2 wlan0.0 wlan2.0"

# $1: name
is_wlan_if()
{
	local ifname=$1
	
	[ -n "$ifname" ] && {
		if echo $ifname | grep -q wlan; then
			echo 1
			return
		fi	
	}
	echo 0
}

# $1: name
is_bridge_if()
{
	local ifname=$1
	
	[ -n "$ifname" ] && {
		if echo $ifname | grep -q br; then
			echo 1
			return
		fi	
	}
	echo 0
}

clear_ppa_wan()
{
	local ppa_wan=$(ppacmd getwan | grep 0 | awk '{print $3}')
	for i in $ppa_wan; do
#		[ -n "$i" -a "$i" != "$WAN_IFNAME" ] && ppacmd delwan -i "$i"
		[ -n "$i" ] && ppacmd delwan -i "$i"
	done
}

clear_ppa_lan()
{
	local ppa_lan=$(ppacmd getlan | grep 0 | awk '{print $3}')
	for i in $ppa_lan; do
#		[ -n "$i" -a $(is_bridge_if "$i") -eq 0 -a $(is_wlan_if "$i") -eq 0 ] && ppacmd dellan -i "$i"
		[ -n "$i" ] && ppacmd dellan -i "$i"
	done	
}

add_ppa_wan()
{
	local wan_ifname=$1
	
	for i in $wan_ifname; do
		[ -n "$i" ] && ppacmd addwan -i "$i"	
	done
}

add_ppa_lan()
{
	local lan_ifname=$1
	
	for i in $lan_ifname; do
		[ -n "$i" ] && ppacmd addlan -i "$i"	
	done
}

config_ppa(){
	local wan_ifname=`uci get network.wan.ifname`
	local lan_ifname=`uci get network.lan.ifname`
	local wan_wtype=`uci get network.wan.wan_type`
	local wan_type=`uci get network.wan.type`
	local lan_type=`uci get network.lan.type`
		
	clear_ppa_wan
	clear_ppa_lan
		
	add_ppa_lan "$lan_ifname"	
	add_ppa_lan "$WLAN_IFNAMES"
	
	# in ap mode, just add lan and return
	config_load sysmode
	config_get mode sysmode mode "router"
	[ "$mode" = "ap" ] && {
		ppacmd dellan -i eth1
		ppacmd addwan -i eth1
		return
	}
	
	add_ppa_lan "br-lan"
	add_ppa_wan "$WAN_IFNAME"
	
	[ -n "$wan_type" -a "$wan_type" = "bridge" ] && add_ppa_wan "br-wan"
	
	#[ "$wan_wtype" = "pppoe" -o "$wan_wtype" = "l2tp" -o "$wan_wtype" = "pptp" ] && {
	[ "$wan_wtype" = "pppoe" ] && {
		local internet_proto=`uci get network.internet.proto`
		[ -n "$internet_proto" ] && add_ppa_wan "${internet_proto}-internet"
	}
	
	[ "$wan_wtype" = "pppoeshare" ] && {
		add_ppa_wan "share-internet"
	}
	
	# ipv6
	local wanv6_wtype=`uci get network.wanv6.wan_type`
	[ -n "$wanv6_wtype" -a "$wanv6_wtype" = "pppoev6" ] && {
		add_ppa_wan "${wanv6_wtype}-wanv6"
	}	
	
	for i in $wan_ifname; do
		if echo "$i" | grep -q "$WAN_IFNAME" ; then
			[ "$i" != "$WAN_IFNAME" ] && add_ppa_wan "$i"	# vlan interface
		fi
	done
}

config_ppa;