#!/bin/sh
START=99

start() {
    d2 -c bstcfg[0].URL "https://netgearup-dev.s3-us-west-2.amazonaws.com/"
    /usr/bin/bst_daemon &
}

stop() {
    killall bst_daemon
    kill -17 1
    rm /tmp/bst.log
}

boot() {
    start
}

restart() {
    stop
    start
}

case $1 in
	"start" )
		start
		;;
	"stop" )
		stop
		;;
	"boot" )
		boot
		;;
	"restart" )
		restart
		;;
esac