#!/bin/sh
START=99

start() {
    /usr/bin/dalh &
}

stop() {
    killall dalh
    kill -17 1
    rm /tmp/dalh.log
}

boot() {
    start
}

restart() {
    stop
    start
}

case $1 in
	"start" )
		start
		;;
	"stop" )
		stop
		;;
	"boot" )
		boot
		;;
	"restart" )
		restart
		;;
esac