#!/bin/sh

#This script do broadcom 490x sdk config
#Writen by zhuyu@16.07.21
# Copyright (c) 2016 TP-LINK. All rights reserved.

init_brcm_sh() {
#	/etc/init.d/hndmfg.sh start
	/etc/init.d/mount-fs.sh start
	/etc/init.d/hndnvram.sh start
}

boot_hook_add preinit_main init_brcm_sh

