#!/bin/sh

#source /opt/lantiq/etc/ugw_notify_defs.sh

if [ "$ACTION" = "mount" ]; then
        /usr/bin/objcli add usbReadyshareStorageUsbInfo $DEVICE
elif [ "$ACTION" = "umount" ]; then
        /usr/bin/objcli del usbReadyshareStorageUsbInfo $MOUNTPATH
fi
