#!/bin/sh

WIRELESS_SCHEDULE_LIBDIR=/lib/wifi
. ${WIRELESS_SCHEDULE_LIBDIR}/wireless_schedule_func.sh

cmd=$1
shift

case $cmd in
    *ACTIVE)
        wireless_schedule_handle_active "$1"
    ;;

    *DORM)
        wireless_schedule_handle_dorm "$1"
    ;;

    *RESET)
        wireless_schedule_handle_reset
        ;;
esac

