#!/bin/sh

. /lib/functions.sh
. /lib/ramips.sh
. /lib/functions/uci-defaults.sh
. /lib/functions/system.sh

ramips_setup_interfaces()
{
	local board="$1"

	case $board in
	# PEGA: remove unused boards, and add "pega-ramips"
	pega-ramips)
		ucidef_set_interfaces_lan_wan "eth0" "eth1"
		ucidef_add_switch "switch0" \
			"0:lan" "1:lan" "2:lan" "3:lan" "4:wan" "6@eth0" "5@eth1"
		;;
	esac
}

board_config_update
board=$(ramips_board_name)
ramips_setup_interfaces $board
board_config_flush

exit 0
