#!/bin/sh /etc/rc.common

START=99z

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	echo 1 > /proc/ag71xx_switch/booted
        setup_switch() { return 0; }
		#. /lib/switch/switch.sh
        setup_switch

        . /lib/switch/core.sh
	setup_ports_all
	local sysmode=$(uci get sysmode.sysmode.mode)
	if [ "$1" != "hotplug" ]; then
		if [ "$sysmode" == "router" ]; then
			setup_duplex
		fi
	fi
}

restart() {
		stop
		start $1
}

shutdown() {
		echo "Shutdown switch!"
}

stop() {
		. /lib/switch/core.sh
		
	local sysmode=$(uci get sysmode.sysmode.mode)
	if [ "$sysmode" == "router" ]; then
		unsetup_duplex
	fi

        unsetup_switch() { return 0; }
		#. /lib/switch/switch.sh
		unsetup_switch
}

reload() {
        start
}
