#!/bin/sh
echo -e "\033[31m[pega-defaults] patch_db-10 running ...\033[0m" > /dev/console

#delete for blocking icmpv6 ping
uci del_list firewall.@rule[6].icmp_type=echo-request

#Change default value for VLAN function
uci set vlan.EtherWan.ports='0t 5t'
uci set vlan.EtherWan.priority='0'
uci set network.EtherWan.name='EtherWan'

vlan_enable=$(uci get vlan.@VlanCfg[0].enableVlan)
group_type=$(uci get vlan.@VlanCfg[0].groupType)
if [ "$vlan_enable" == "false" ] || [ "$vlan_enable" == "true" -a "$group_type" == "vid" ]
then
    echo "remove network default port group setting" > /dev/console
    uci set network.Bridge=''
    uci set network.lan2=''
fi
if [ "$vlan_enable" == "true" -a "$group_type" == "vid" ]
then
    echo "Apply VLAN tag group setting" > /dev/console
    uci set network.wan.ifname='eth1.'"$(uci get vlan.EtherWan.vid)"
    uci set network.EtherWan.ports='0t 5t'
    uci set network.EtherWan.priority='$(uci get vlan.EtherWan.priority)'
fi

# Invoke dnsmasq after setting VPN
uci add_list ucitrack.@openvpn[0].affects=dnsmasq

# Keep last (all commands MUST be before 'exit 0')
exit 0
