#!/bin/sh /etc/rc.common
echo "[pega-defaults] patch_db-4 running ..." > /dev/console

#add for netgear auto update default enabled
uci set netgear.fw.auto_update="true"

# Keep last (all commands MUST be before 'exit 0')
exit 0
