#!/bin/sh

echo "[pega-defaults] run_script-4 running ..." > /dev/console

#Change admin account to be the same with root
sed -i '/admin/d' /etc/passwd
echo admin:x:0:0:admin:/root:/bin/ash >> /etc/passwd

# add 'exit 0' in the end of file (all commands MUST be before 'exit 0')
exit 0
