#!/bin/sh

echo "[pega-defaults] run_script-9 running ..." > /dev/console

# PegaBU6, Matt Lin, 2022/09/06, To limit Wirelease station number
/usr/bin/datconf -f /etc/wireless/mediatek/mt7915.dbdc.b0.dat set MaxStaNum 128
/usr/bin/datconf -f /etc/wireless/mediatek/mt7915.dbdc.b1.dat set MaxStaNum 128

# PegaBU6, Matt Lin, 2022/09/08, To Enable Wi-Fi backoff  power regulation management
/usr/bin/datconf -f /etc/wireless/mediatek/mt7915.dbdc.b0.dat  set BFBACKOFFenable 1
/usr/bin/datconf -f /etc/wireless/mediatek/mt7915.dbdc.b1.dat  set BFBACKOFFenable 1


# add 'exit 0' in the end of file (all commands MUST be before 'exit 0')
exit 0
