#!/bin/sh
#
# Iface hotplug script to set default dns when br-lan up.
#
if [ "$ACTION" = "ifup" ]; then
    if [ "$DEVICE" = "br-lan" ]; then
        echo "# LAN DNS setting" > /tmp/resolv.conf.auto
        echo "nameserver 168.95.1.1" >> /tmp/resolv.conf.auto
    fi
fi
