#!/bin/sh
#
# Iface hotplug script to record uptime for ethernet ports.
#

connname="$INTERFACE"
device="$DEVICE"
#save the current timestemp for each interface in /ramdisk/var/tmp/
if [ "${connname%"${connname#?????????}"}" = "iface_eth" ]; then #Compare first 9 chars of $connname then checking it equal to "iface_eth" or not.
    if [ "$ACTION" = "ifup" ]; then
    echo "status:up" > /var/tmp/uptime_"$device"
    {  
        awk '{print "uptime: "$1}' < /proc/uptime
        ifconfig "$device" | grep "RX packets:" | awk -F ':' '{print $2}' | awk '{print "rxpkts:" $1}'
        ifconfig "$device" | grep "TX packets:" | awk -F ':' '{print $2}' | awk '{print "txpkts:" $1}'
        ifconfig "$device" | grep "RX bytes:" | awk -F ':' '{print $2}' | awk '{print "rxbytes:" $1}'
        ifconfig "$device" | grep "TX bytes:" | awk -F ':' '{print $3}' | awk '{print "txbytes:" $1}'
        ifconfig "$device" | grep "collisions:" | awk -F ':' '{print $2}' | awk '{print "collisions:" $1}'
    } >> /var/tmp/uptime_"$device"
    elif [ "$ACTION" = "ifdown" ]; then
        echo "status:down" > /var/tmp/uptime_"${connname%"${connname#??????}"}" #Get first 6 chars of $connname to be file suffix.
    fi
fi

