#!/usr/bin/lua

-- revised for C5400X, wangian, 2017-07-20
-- 1. check if unbind is needed
-- 2. upload featureInfo

local uci   = require "luci.model.uci"
local sys   = require "luci.sys"
local fs    = require "luci.fs"
local dbg   = require "luci.tools.debug"
--local network_mgmt = require "cloud_req.device_manage"
local cloud_account = require("luci.controller.admin.cloud_account")

local ERR_CODE_UNBINDED = -20507

local uci_r = uci.cursor()

local CLOUD_TMP_DIR = "/tmp/cloud"
local CLOUD_STATUS_FILE = CLOUD_TMP_DIR .. "/cloud_status_check_done"

local MAX_CHECK_TIME = 3
local MIN_CHECK_INTERVAL = 3

local CLOUD_STATUS_LOCK = "/var/run/cloud_status.lock"
local RWLocker = require("luci.model.locker").RWLocker

-- add lock
local locker = RWLocker(CLOUD_STATUS_LOCK)
locker:wlock()

-- check account status
local need_unbind = uci_r:get("cloud_config", "device_status", "need_unbind")
if tonumber(need_unbind) == 1 then
	cloud_account.cloud_unbind()	
end

-- update dst rules
local dst_rule = uci_r:get("systime", "zoneinfo", "dst_rule")
local zone_rule = uci_r:get("systime", "zoneinfo", "zone_rule")

if dst_rule == "byuser" then
	-- do nothing
elseif dst_rule == "bycloud" then
	local update_time = uci_r:get("systime", "zoneinfo", "update_time")
	if update_time then
		cur_time = os.time()
		if cur_time - update_time > 259200 then
			local times = require "luci.model.app_timesetting"
			times.ts_update_dst(tz_region)
			luci.sys.exec("/etc/init.d/time_settings reload")
		end
	end
elseif dst_rule == "no" then
	if zone_rule == "byuser" then
		zoneId = uci_r:get("systime", "zoneinfo", "zoneId")
	elseif zone_rule == "byapp" then
		zoneId = uci_r:get("systime", "zoneinfo", "tz_region")
	end
	local times = require "luci.model.app_timesetting"
	times.ts_update_dst(tz_region)
	luci.sys.exec("/etc/init.d/time_settings reload")
end

-- for featureInfo, upload just once
if fs.access(CLOUD_STATUS_FILE) then
	dbg.print("========== CLOUD: cloud status check is done before =========")				
	locker:ulock()
	return
else		
	local check_done = false
	local check_time = 0
	local check_interval = MIN_CHECK_INTERVAL
	while not check_done do
		local error_code = cloud_account.cloud_upload_feature()	
		if tonumber(error_code) == 0 then
			check_done = true
		elseif check_time < MAX_CHECK_TIME then
			sys.call("sleep %d" % check_interval)
			check_interval = check_interval * 2
			check_time = check_time + 1
		else
			-- upload failed, try next time
			locker:ulock()
			return
		end
	end
end

if not fs.isdirectory(CLOUD_TMP_DIR) then
	fs.mkdir(CLOUD_TMP_DIR, true)
end
sys.call("touch %s" % CLOUD_STATUS_FILE)

locker:ulock()
