#!/bin/sh

. /lib/bcmenet/bcmenet_c5400s.sh

# exclude additional WAN
c5400s_get_interface_group > /dev/null

local lanaswan=$addlwan
local swmdkfmt="*unit %1 port %2 "
local ps=$(c5400s_get_lan_phy_state)
local unit=1
local port=0

# C4000V2 only has two unit
# if C5400X use this script, change it to 3 to be compatible with it
local maxunit=3

# C4000V2 only has 4 port
# if C4000V1 use this script, change it to 8 be compatible with it
local maxport=8

while [ $unit -lt $maxunit ] ; do
	port=0
	local unitfmt=${swmdkfmt/%1/${unit}}
	while [ $port -lt $maxport ] ; do
		if [ $unit -eq 1 -a $port -eq $lanaswan ] ; then
			port=$((port+1))
			continue
		fi
		local portfmt=${unitfmt/%2/${port}}
		local res=${ps#${portfmt}}
		if [ ${#res} -ge 2 ] &&  [ ${res:0:2} == "up" ]; then
			return 0
		fi
		port=$((port+1))
	done
	unit=$((unit+1))
done
echo "lan not connected"
return 1