#!/bin/sh /etc/rc.common

START=19z

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	. /lib/switch/core.sh
	unsetup_ports
}

restart() {
	echo "do nothing ..."
}

shutdown() {
		echo "Shutdown switch!"
}

stop() {
	echo "do nothing ..."
}

reload() {
	start
}
