#!/bin/sh /etc/rc.common

START=13

start()
{
	echo 0 > /sys/bus/usb/drivers/usb/usb1/power/autosuspend_delay_ms
	echo 0 > /sys/bus/usb/drivers/usb/usb2/power/autosuspend_delay_ms
	echo 0 > /sys/bus/usb/drivers/usb/usb3/power/autosuspend_delay_ms
	echo 0 > /sys/bus/usb/drivers/usb/usb4/power/autosuspend_delay_ms
	/usr/bin/ledctrl &
}

stop()
{
	[ -f /var/run/ledctrl ] && {
		local pid=$(cat /var/run/ledctrl)
		kill $pid
		rm /var/run/ledctrl
        rm /var/run/ledctrl_sock*
    }
}

