#!/bin/sh
# Copyright(c) 2023 Shenzhen TP-LINK Technologies Co.Ltd.
# file     portspeed

. /lib/switch/base.sh

if [ $# -ne 4 ]; then
    exit 0
fi

local speed=$2
local duplex=$3
local autoneg=$4
local ability

case "$autoneg" in
"on")
	ability="auto"
	;;
*)
	case $speed in
	1000)
		ability="1000_"
		;;
	100)
		ability="100_"
		;;
	10)
		ability="10_"
		;;
	*)
		exit 1
		;;
	esac
	case $duplex in
	"half")
		ability=$ability"half"
		;;
	*)
		ability=$ability"full"
		;;
	esac
	;;
esac

set_common_port_neg 1 "$ability"

exit 0
