var INCLUDE_LAN_WLAN_WDS_2_4G=0
var INCLUDE_LAN_WLAN_WDS_5G=0
var INCLUDE_NEW_WEB_UI_V2=1
var INCLUDE_APP_IQOS=1
var INCLUDE_AREACODE=0
var INCLUDE_FLASH_VOICEMAIL=1
var INCLUDE_IPV6_BRIDGE=0
var INCLUDE_IPV6_AUTO=0
var WEB_INCLUDE_TEST=0
var WEB_INCLUDE_MULTI_EWAN=0
var WEB_INCLUDE_DST=1
var WEB_INCLUDE_HELP=1
var WEB_INCLUDE_MOBILE_UI=0
var WEB_INCLUDE_QS_REGION=1
var INCLUDE_MULTI_LANGUAGE=1
var INCLUDE_LANGUAGE_EN_US=1
var INCLUDE_LANGUAGE_DE_DE=1
var INCLUDE_LANGUAGE_IT_IT=1
var INCLUDE_LANGUAGE_RU_RU=1
var INCLUDE_LANGUAGE_PL_PL=1
var INCLUDE_LANGUAGE_FR_FR=1
var INCLUDE_LANGUAGE_ES_ES=1
var INCLUDE_LANGUAGE_ZH_TW=1
var INCLUDE_LANGUAGE_FA_FA=1
var INCLUDE_LANGUAGE_ES_LA=0
var INCLUDE_LANGUAGE_PT_PT=0
var INCLUDE_LANGUAGE_PT_BR=0
var INCLUDE_LANGUAGE_EL_GR=0
var INCLUDE_LANGUAGE_TH_TH=0
var INCLUDE_WLAN_DFS=0
var INCLUDE_HTTPS=0
var INCLUDE_STS_INTF=0
var INCLUDE_LANGUAGE_EN_US=1
var INCLUDE_LANGUAGE_DE_DE=1
var INCLUDE_LANGUAGE_IT_IT=1
var INCLUDE_LANGUAGE_RU_RU=1
var INCLUDE_LANGUAGE_TR_TR=0
var INCLUDE_LANGUAGE_PL_PL=1
var INCLUDE_LANGUAGE_FR_FR=1
var INCLUDE_LANGUAGE_ES_ES=1
var INCLUDE_LANGUAGE_ES_LA=0
var INCLUDE_LANGUAGE_PT_PT=0
var INCLUDE_LANGUAGE_PT_BR=0
var INCLUDE_LANGUAGE_EL_GR=0
var INCLUDE_LANGUAGE_TH_TH=0
var INCLUDE_WEB_REGION=1
var INCLUDE_DAY_MONTH_YEAR=1
var INCLUDE_FLASH_VOICEMAIL=0
var INCLUDE_MAIL=0
var INCLUDE_ONEMESH=0
var INCLUDE_LOGIN_GDPR_ENCRYPT=1
var INCLUDE_CLOUD_HTTPS=1
var INCLUDE_CHECK_WANALIVE_WITH_PING=1
var INCLUDE_USSD=1
var INCLUDE_VOLTE=1
var BETA=0
var DATACODE=0
var INCLUDE_LAN_WLAN=1
var INCLUDE_VOIP=1
var INCLUDE_DIGITMAP
var INCLUDE_DECT
var INCLUDE_FXS_NUM=1
var INCLUDE_CALLLOG
var INCLUDE_USB_VOICEMAIL=1
var INCLUDE_PSTN
var INCLUDE_PSTN_GATEWAY
var INCLUDE_PSTN_LIFELINE
var INCLUDE_BRIDGING=1
var INCLUDE_IGMP=1
var INCLUDE_ETHERNET_WAN=1
var INCLUDE_SNMP=1
var INCLUDE_RIP=1
var INCLUDE_DDNS_PH
var INCLUDE_LAN_WLAN_MSSID=1
var INCLUDE_LAN_WLAN_WDS
var INCLUDE_IPTV=1
var INCLUDE_CWMP=1
var INCLUDE_DYNDNS=1
var INCLUDE_USB=1
var INCLUDE_USB_STORAGE
var INCLUDE_USB_MEDIA_SERVER
var INCLUDE_USB_SAMBA_SERVER
var INCLUDE_USB_FTP_SERVER
var INCLUDE_USB_OVER_IP
var INCLUDE_ADSLWAN
var INCLUDE_AUTO_PVC
var INCLUDE_IPV6=1
var INCLUDE_IPV6_SLAAC=1
var INCLUDE_SPECIAL_DIAL_MODE
var INCLUDE_WAN_MODE=1
var INCLUDE_IPSEC
var INCLUDE_NOIPDNS=1
var INCLUDE_ALG_H323=1
var INCLUDE_ALG_SIP=1
var INCLUDE_ALG_RTSP=1
var INCLUDE_PON_ETH_WAN
var INCLUDE_EPON_INFO
var INCLUDE_GPON_INFO
var INCLUDE_QOS
var INCLUDE_E8_APP
var INCLUDE_TFC_PERU
var INCLUDE_USB_3G_DONGLE
var INCLUDE_LAN_WLAN_SCHEDULE=1
var INCLUDE_ROUTE_BINDING
var INCLUDE_LAN_WLAN_GUESTNETWORK=1
var INCLUDE_LAN_WLAN_DUALBAND
var INCLUDE_LAN_WLAN_AC
var INCLUDE_LAN_WLAN_WDS_DETECT
var INCLUDE_L2TP=1
var INCLUDE_PPTP=1
var INCLUDE_IPV6_MLD
var INCLUDE_ACL=1
var INCLUDE_ACL_ADVANCE
var INCLUDE_WAN_DETECT
var INCLUDE_VDSLWAN
var INCLUDE_IPPING_DIAG
var INCLUDE_TRACEROUTE_DIAG
var INCLUDE_DOWNLOAD_DIAG
var INCLUDE_UPLOAD_DIAG
var INCLUDE_UDPECHO_DIAG
var INCLUDE_IGMP_DIAG
var INCLUDE_DUAL_ACCESS
var INCLUDE_WAN_VLAN
var INCLUDE_EWAN_IPTV=1
var INCLUDE_GERMANY_SPEC
var INCLUDE_PPP_RECONN
var INCLUDE_CHGINIT_PWD=1
var INCLUDE_NEW_WEB_UI=1
var INCLUDE_VOICEAPP
var INCLUDE_TR143
var INCLUDE_DDNS_USERDEFINE=1
var INCLUDE_DDNS_USERDEFINE_DETAIL
var INCLUDE_MULTI_LANGUAGE=1
var INCLUDE_FACTORY_DEFAULT=1
var INCLUDE_TR111_PART1
var INCLUDE_TR111_PART2
var INCLUDE_DSL_DIAG
var INCLUDE_XTM_DUAL_CFG
var INCLUDE_CLOUD=1
var INCLUDE_MIC=1
var INCLUDE_WAN_BLOCK=1
var INCLUDE_WAN_BLOCK_WAN_ERROR
var INCLUDE_WAN_BLOCK_FW_UP_INFO=1
var INCLUDE_LED_BUTTON=1
var INCLUDE_HOSTNAME_EDITABLE=1
var INCLUDE_MER=1
var INCLUDE_REBOOT_SCHEDULE=1
var INCLUDE_LED_SCHEDULE=1
var INCLUDE_APP_IQOS=1
var INCLUDE_VPN=1
var INCLUDE_OPENVPN_SERVER=1
var INCLUDE_PPTPVPN_SERVER=1
var INCLUDE_HTTP_SSL=1
var INCLUDE_NEW_WEB_UI_V2=1
var INCLUDE_HOSTNAME_EDITABLE=1
var INCLUDE_STORAGE_HTTP_SERVICE
var INCLUDE_SIP_DOMAIN
var INCLUDE_DNS_PROXY=1
var INCLUDE_MAIL
var INCLUDE_FOTA
var INCLUDE_YANDEX_DNS
var INCLUDE_WISP
var INCLUDE_WISP_WAN
var INCLUDE_AP_MODE
var INCLUDE_XHCI
var INCLUDE_USB_SFTP_SERVER
var INCLUDE_CLOUD_V2=1
var INCLUDE_STS_INTF
var INCLUDE_DISABLE_LAN6
var INCLUDE_SPEEDTEST
var INCLUDE_EWAN_VLAN=1
var INCLUDE_IPV6_FORWARDING_RULE=1
var INCLUDE_BROADSOFT
var INCLUDE_IPTV_V2=1
var INCLUDE_AUTO_UPGRADE_MODE
var INCLUDE_LAN_WLAN_MACFILTER
var INCLUDE_IPV6_TUNNEL_GATEWAY
var INCLUDE_PPP_HOST_UNIQ=1
var INCLUDE_IPV6_HTTP=1
var INCLUDE_AREACODE
var INCLUDE_CZ
var INCLUDE_RU_IPTV
var INCLUDE_CLOUD_HTTPS=1
var INCLUDE_ONEMESH
var INCLUDE_TC
var INCLUDE_3G4G_BACKUP=1
var INCLUDE_LTEWAN=1
var INCLUDE_USB_3G_BACKUP
var INCLUDE_EWAN_BACKUP
var INCLUDE_DATALIMIT_SMS_ALERT=1
var INCLUDE_LTE_NET_STATISTICS=1
var INCLUDE_USSD=1
var INCLUDE_USSD_DIAGNOSIS
var INCLUDE_VOLTE=1
var INCLUDE_LTE_SEARCH_BAND=1
var IGD = "IGD"
var IGD_DEV_INFO = "IGD_DEV_INFO"
var SYSLOG_CFG = "SYSLOG_CFG"
var PROC_STATUS = "PROC_STATUS"
var MEM_STATUS = "MEM_STATUS"
var MANAGEMENT_SERVER = "MANAGEMENT_SERVER"
var MANAGEMENT_DEV = "MANAGEMENT_DEV"
var ETH_SWITCH = "ETH_SWITCH"
var SYS_CFG = "SYS_CFG"
var NET_CFG = "NET_CFG"
var NET6_CFG = "NET6_CFG"
var USER_CFG = "USER_CFG"
var CURRENT_USER = "CURRENT_USER"
var APP_CFG = "APP_CFG"
var HTTP_CFG = "HTTP_CFG"
var HTTPS_CERT_AUTH = "HTTPS_CERT_AUTH"
var PH_DDNS_CFG = "PH_DDNS_CFG"
var PH_RT_DATA = "PH_RT_DATA"
var DYN_DNS_CFG = "DYN_DNS_CFG"
var UPNP_CFG = "UPNP_CFG"
var UPNP_PORTMAPPING = "UPNP_PORTMAPPING"
var DIAG_TOOL = "DIAG_TOOL"
var CWMP_CFG = "CWMP_CFG"
var SNMP_CFG = "SNMP_CFG"
var NOIP_DNS_CFG = "NOIP_DNS_CFG"
var ACL_CFG = "ACL_CFG"
var USERDEFINE_DDNS_CFG = "USERDEFINE_DDNS_CFG"
var REBOOT_SCHEDULE_CFG = "REBOOT_SCHEDULE_CFG"
var LED_SCHEDULE_CFG = "LED_SCHEDULE_CFG"
var MAIL_CFG = "MAIL_CFG"
var DMZ_HOST_CFG = "DMZ_HOST_CFG"
var TIME = "TIME"
var HOUR = "HOUR"
var L3_FORWARDING = "L3_FORWARDING"
var L3_FORWARDING_ENTRY = "L3_FORWARDING_ENTRY"
var L3_IP6_FORWARDING = "L3_IP6_FORWARDING"
var L3_IP6_FORWARDING_ENTRY = "L3_IP6_FORWARDING_ENTRY"
var L2_BRIDGING = "L2_BRIDGING"
var L2_BRIDGING_ENTRY = "L2_BRIDGING_ENTRY"
var L2_BRIDGING_FILTER = "L2_BRIDGING_FILTER"
var L2_BRIDGING_INTF = "L2_BRIDGING_INTF"
var LAN_DEV = "LAN_DEV"
var LAN_HOST_CFG = "LAN_HOST_CFG"
var LAN_IP_INTF = "LAN_IP_INTF"
var LAN_DHCP_STATIC_ADDR = "LAN_DHCP_STATIC_ADDR"
var LAN_DHCP_COND_SRV_POOL = "LAN_DHCP_COND_SRV_POOL"
var LAN_DHCP_COND_SRV_POOL_OPT = "LAN_DHCP_COND_SRV_POOL_OPT"
var LAN_IP6_HOST_CFG = "LAN_IP6_HOST_CFG"
var LAN_IP6_INTF = "LAN_IP6_INTF"
var LAN_ETH_INTF = "LAN_ETH_INTF"
var LAN_HOSTS = "LAN_HOSTS"
var LAN_HOST_ENTRY = "LAN_HOST_ENTRY"
var LAN_IP6_NEIGH = "LAN_IP6_NEIGH"
var LAN_IP6_NEIGH_ENTRY = "LAN_IP6_NEIGH_ENTRY"
var LAN_WLAN = "LAN_WLAN"
var LAN_WLAN_WPS = "LAN_WLAN_WPS"
var LAN_WLAN_MACTABLEENTRY = "LAN_WLAN_MACTABLEENTRY"
var LAN_WLAN_ASSOC_DEV = "LAN_WLAN_ASSOC_DEV"
var LAN_WLAN_BSSDESC_ENTRY = "LAN_WLAN_BSSDESC_ENTRY"
var LAN_WLAN_WEPKEY = "LAN_WLAN_WEPKEY"
var LAN_WLAN_WDSBRIDGE = "LAN_WLAN_WDSBRIDGE"
var LAN_WLAN_MULTISSID = "LAN_WLAN_MULTISSID"
var LAN_WLAN_MSSIDENTRY = "LAN_WLAN_MSSIDENTRY"
var LAN_WLAN_MSSIDWEPKEY = "LAN_WLAN_MSSIDWEPKEY"
var LAN_WLAN_WLBRNAME = "LAN_WLAN_WLBRNAME"
var LAN_WLAN_TASK_SCHEDULE = "LAN_WLAN_TASK_SCHEDULE"
var LAN_WLAN_SCHEDULEITEM = "LAN_WLAN_SCHEDULEITEM"
var LAN_WLAN_GUESTNET = "LAN_WLAN_GUESTNET"
var LAN_WLAN_SYNC = "LAN_WLAN_SYNC"
var LAN_WLAN_SYNC_WEPKEY = "LAN_WLAN_SYNC_WEPKEY"
var LAN_IGMP_SNOOP = "LAN_IGMP_SNOOP"
var STORED_HOST_ENTRY = "STORED_HOST_ENTRY"
var WAN_DEV = "WAN_DEV"
var WAN_COMMON_INTF_CFG = "WAN_COMMON_INTF_CFG"
var WAN_DSL_INTF_CFG = "WAN_DSL_INTF_CFG"
var WAN_DSL_INTF_STATS = "WAN_DSL_INTF_STATS"
var WAN_DSL_INTF_STATS_TOTAL = "WAN_DSL_INTF_STATS_TOTAL"
var TEST_PARAMS = "TEST_PARAMS"
var WAN_ETH_INTF = "WAN_ETH_INTF"
var WAN_ETH_INTF_STATS = "WAN_ETH_INTF_STATS"
var WAN_PON = "WAN_PON"
var WAN_EPON_INTF = "WAN_EPON_INTF"
var WAN_EPON_INTF_OAM_STATS = "WAN_EPON_INTF_OAM_STATS"
var WAN_EPON_INTF_MPCP_STATS = "WAN_EPON_INTF_MPCP_STATS"
var WAN_EPON_INTF_STATS = "WAN_EPON_INTF_STATS"
var WAN_EPON_INTF_OPTICAL_STATS = "WAN_EPON_INTF_OPTICAL_STATS"
var WAN_GPON_INTF = "WAN_GPON_INTF"
var WAN_GPON_INTF_OMCI_STATS = "WAN_GPON_INTF_OMCI_STATS"
var WAN_GPON_INTF_STATS = "WAN_GPON_INTF_STATS"
var WAN_GPON_INTF_OPTICAL_STATS = "WAN_GPON_INTF_OPTICAL_STATS"
var WAN_LTE_INTF_CFG = "WAN_LTE_INTF_CFG"
var WAN_DSL_DIAG = "WAN_DSL_DIAG"
var WAN_CONN_DEVICE = "WAN_CONN_DEVICE"
var WAN_DSL_LINK_CFG = "WAN_DSL_LINK_CFG"
var WAN_PTM_LINK_CFG = "WAN_PTM_LINK_CFG"
var WAN_PTM_LINK_STATS = "WAN_PTM_LINK_STATS"
var WAN_PON_LINK_CFG = "WAN_PON_LINK_CFG"
var WAN_ETH_LINK_CFG = "WAN_ETH_LINK_CFG"
var WAN_USB_3G_LINK_CFG = "WAN_USB_3G_LINK_CFG"
var USB_MODEM_PARAM = "USB_MODEM_PARAM"
var WAN_LTE_LINK_CFG = "WAN_LTE_LINK_CFG"
var LTE_NET_STATUS = "LTE_NET_STATUS"
var LTE_SIMLOCK = "LTE_SIMLOCK"
var LTE_WAN_CFG = "LTE_WAN_CFG"
var LTE_PROF_STAT = "LTE_PROF_STAT"
var LTE_ISP_PROF = "LTE_ISP_PROF"
var LTE_USER_PROF = "LTE_USER_PROF"
var LTE_PROFILE = "LTE_PROFILE"
var LTE_TIME = "LTE_TIME"
var WAN_L2TP_CONN = "WAN_L2TP_CONN"
var WAN_L2TP_CONN_PORTMAPPING = "WAN_L2TP_CONN_PORTMAPPING"
var L2TP_CONN_PORTTRIGGERING = "L2TP_CONN_PORTTRIGGERING"
var WAN_L2TP_CONN_STATS = "WAN_L2TP_CONN_STATS"
var WAN_PPTP_CONN = "WAN_PPTP_CONN"
var WAN_PPTP_CONN_PORTMAPPING = "WAN_PPTP_CONN_PORTMAPPING"
var PPTP_CONN_PORTTRIGGERING = "PPTP_CONN_PORTTRIGGERING"
var WAN_PPTP_CONN_STATS = "WAN_PPTP_CONN_STATS"
var WAN_IP_CONN = "WAN_IP_CONN"
var WAN_IP_CONN_PORTMAPPING = "WAN_IP_CONN_PORTMAPPING"
var WAN_IP_CONN_IP6PORTMAPPING = "WAN_IP_CONN_IP6PORTMAPPING"
var IP_CONN_PORTTRIGGERING = "IP_CONN_PORTTRIGGERING"
var WAN_PPP_CONN = "WAN_PPP_CONN"
var WAN_PPP_CONN_PORTMAPPING = "WAN_PPP_CONN_PORTMAPPING"
var WAN_PPP_CONN_IP6PORTMAPPING = "WAN_PPP_CONN_IP6PORTMAPPING"
var PPP_CONN_PORTTRIGGERING = "PPP_CONN_PORTTRIGGERING"
var WAN_PPP_CONN_STATS = "WAN_PPP_CONN_STATS"
var STAT_CFG = "STAT_CFG"
var RECORD_CFG = "RECORD_CFG"
var RECORD_ENTRY = "RECORD_ENTRY"
var STAT_ENTRY = "STAT_ENTRY"
var DDOS_CFG = "DDOS_CFG"
var DOS_HOST = "DOS_HOST"
var ARP = "ARP"
var ARP_ENTRY = "ARP_ENTRY"
var ARP_BIND = "ARP_BIND"
var ARP_BIND_ENTRY = "ARP_BIND_ENTRY"
var QUEUE_MANAGEMENT = "QUEUE_MANAGEMENT"
var CLASSIFICATION = "CLASSIFICATION"
var QOS_APP = "QOS_APP"
var QOS_INTF = "QOS_INTF"
var QOS_QUEUE = "QOS_QUEUE"
var TC = "TC"
var TC_RULE = "TC_RULE"
var IQOS = "IQOS"
var IQOS_CONF = "IQOS_CONF"
var IQOS_DB = "IQOS_DB"
var IQOS_RULE = "IQOS_RULE"
var ALG_CFG = "ALG_CFG"
var IPTV = "IPTV"
var DSL_IPTV_CFG = "DSL_IPTV_CFG"
var ETH_IPTV_CFG = "ETH_IPTV_CFG"
var FIREWALL = "FIREWALL"
var INTERNAL_HOST = "INTERNAL_HOST"
var EXTERNAL_HOST = "EXTERNAL_HOST"
var TASK_SCHEDULE = "TASK_SCHEDULE"
var RULE = "RULE"
var URL_LIST = "URL_LIST"
var URL_CFG = "URL_CFG"
var IP6_FIREWALL = "IP6_FIREWALL"
var IP6_INTERNAL_HOST = "IP6_INTERNAL_HOST"
var IP6_EXTERNAL_HOST = "IP6_EXTERNAL_HOST"
var IP6_TASK_SCHEDULE = "IP6_TASK_SCHEDULE"
var IP6_RULE = "IP6_RULE"
var IP6_TUNNEL = "IP6_TUNNEL"
var DSLITE = "DSLITE"
var SIT_6RD = "SIT_6RD"
var SERVICES = "SERVICES"
var VOICE = "VOICE"
var XTP_VOICE_PROCESS_STS = "XTP_VOICE_PROCESS_STS"
var XTP_VOICE_PROCESS = "XTP_VOICE_PROCESS"
var VOICE_CAP = "VOICE_CAP"
var VOICE_CAP_SIP = "VOICE_CAP_SIP"
var VOICE_CAP_MGCP = "VOICE_CAP_MGCP"
var VOICE_CAP_CODECS = "VOICE_CAP_CODECS"
var VOICE_PROF = "VOICE_PROF"
var VOICE_PROF_CW = "VOICE_PROF_CW"
var VOICE_PROF_PROVIDER = "VOICE_PROF_PROVIDER"
var VOICE_PROF_SIP = "VOICE_PROF_SIP"
var VOICE_PROF_SIP_EVTSUBSCRIBE = "VOICE_PROF_SIP_EVTSUBSCRIBE"
var VOICE_PROF_MGCP = "VOICE_PROF_MGCP"
var VOICE_PROF_RTP = "VOICE_PROF_RTP"
var VOICE_PROF_FAXT38 = "VOICE_PROF_FAXT38"
var XTP_USB_VOICEMAIL_PUBLICCFG = "XTP_USB_VOICEMAIL_PUBLICCFG"
var XTP_MULTI_ISP = "XTP_MULTI_ISP"
var XTP_MULTIISP_CODEC = "XTP_MULTIISP_CODEC"
var XTP_MULTIISP_CODEC_LIST = "XTP_MULTIISP_CODEC_LIST"
var XTP_MULTIISP_INCOMING_CALL = "XTP_MULTIISP_INCOMING_CALL"
var XTP_MULTIISP_OUTGOING_CALL = "XTP_MULTIISP_OUTGOING_CALL"
var VOICE_PROF_LINE = "VOICE_PROF_LINE"
var VOICE_PROF_LINE_SIP = "VOICE_PROF_LINE_SIP"
var XTP_DECT_HANDSET_INFO = "XTP_DECT_HANDSET_INFO"
var XTP_VOICEAPP_INFO = "XTP_VOICEAPP_INFO"
var VOICE_PROF_LINE_XTPUSBVM = "VOICE_PROF_LINE_XTPUSBVM"
var VOICE_PROF_LINE_CALLFEAT = "VOICE_PROF_LINE_CALLFEAT"
var VOICE_PROF_LINE_PROC = "VOICE_PROF_LINE_PROC"
var VOICE_PROF_LINE_CODEC = "VOICE_PROF_LINE_CODEC"
var VOICE_PROF_LINE_CODEC_LIST = "VOICE_PROF_LINE_CODEC_LIST"
var VOICE_PROF_LINE_STATS = "VOICE_PROF_LINE_STATS"
var XTP_INCOMING_CALL = "XTP_INCOMING_CALL"
var XTP_OUTGOING_CALL = "XTP_OUTGOING_CALL"
var XTP_FEATURE_CODE = "XTP_FEATURE_CODE"
var VOICE_PHY_INTERFACE = "VOICE_PHY_INTERFACE"
var VOICE_PHYINTERFACE_TESTS = "VOICE_PHYINTERFACE_TESTS"
var XTP_VOICE_MULTI_ISPDIALPLAN = "XTP_VOICE_MULTI_ISPDIALPLAN"
var XTP_VOICE_PSTN = "XTP_VOICE_PSTN"
var XTP_DECT_BASE_STATION = "XTP_DECT_BASE_STATION"
var XTP_VOICEAPP_BASE_STATION = "XTP_VOICEAPP_BASE_STATION"
var XTP_TELE_CONTACT = "XTP_TELE_CONTACT"
var STORAGE_SERVICE = "STORAGE_SERVICE"
var CAPABLE = "CAPABLE"
var USER_ACCOUNT = "USER_ACCOUNT"
var USB_DEVICE = "USB_DEVICE"
var LOGICAL_VOLUME = "LOGICAL_VOLUME"
var FOLDER_BROWSE = "FOLDER_BROWSE"
var FOLDER_NODE = "FOLDER_NODE"
var DLNA_MEDIA_SERVER = "DLNA_MEDIA_SERVER"
var DLNA_MEDIA_SERVER_FOLDER = "DLNA_MEDIA_SERVER_FOLDER"
var SMB_SERVICE = "SMB_SERVICE"
var SMB_SERVICE_FOLDER = "SMB_SERVICE_FOLDER"
var SMB_USER_ACCESS = "SMB_USER_ACCESS"
var FTP_SERVER = "FTP_SERVER"
var FTP_SERVER_FOLDER = "FTP_SERVER_FOLDER"
var FTP_USER_ACCESS = "FTP_USER_ACCESS"
var STORAGE_HTTP = "STORAGE_HTTP"
var STORAGE_HTTP_FOLDER = "STORAGE_HTTP_FOLDER"
var XTP_PRINT_SERVICE = "XTP_PRINT_SERVICE"
var XTP_VOICE_DND = "XTP_VOICE_DND"
var XTP_CALL_FWD = "XTP_CALL_FWD"
var XTP_CALL_FWD_LIST = "XTP_CALL_FWD_LIST"
var XTP_CALL_THROUGH = "XTP_CALL_THROUGH"
var XTP_CALLTHROUGH_NUM = "XTP_CALLTHROUGH_NUM"
var XTP_IGD_CALL_FIREWALL_CFG = "XTP_IGD_CALL_FIREWALL_CFG"
var XTP_IGD_SPEED_DIAL_CFG = "XTP_IGD_SPEED_DIAL_CFG"
var XTP_IGD_AREA_CODE_CFG = "XTP_IGD_AREA_CODE_CFG"
var XTP_IGD_AREA_CODE_EXCEPTION = "XTP_IGD_AREA_CODE_EXCEPTION"
var XTP_IGD_MULTI_ISP_DIAL_PLAN = "XTP_IGD_MULTI_ISP_DIAL_PLAN"
var XTP_IGD_MULTIISPDP_LIST = "XTP_IGD_MULTIISPDP_LIST"
var XTP_CALLLOGCFG = "XTP_CALLLOGCFG"
var SYS_MODE = "SYS_MODE"
var EWAN = "EWAN"
var USER_INFO = "USER_INFO"
var GPON_USER_INFO = "GPON_USER_INFO"
var GPON_AUTH_CTC = "GPON_AUTH_CTC"
var GPON_AUTH_SN = "GPON_AUTH_SN"
var GPON_AUTH_PWD = "GPON_AUTH_PWD"
var GPON_MAC_INFO = "GPON_MAC_INFO"
var GPON_FWD_RULE = "GPON_FWD_RULE"
var GPON_LOCAL_RULE_ENTRY = "GPON_LOCAL_RULE_ENTRY"
var GPON_REMOTE_RULE_ENTRY = "GPON_REMOTE_RULE_ENTRY"
var GPON_OMCI_IOT = "GPON_OMCI_IOT"
var GPON_OMCI_IOT_ENTRY = "GPON_OMCI_IOT_ENTRY"
var GPON_OMCI_ME_ATTR = "GPON_OMCI_ME_ATTR"
var WAN_DETECT = "WAN_DETECT"
var WAN_DSL_AUTO_PVC_PAIR = "WAN_DSL_AUTO_PVC_PAIR"
var X_TP_LTE = "X_TP_LTE"
var LTE_SMS = "LTE_SMS"
var LTE_SMS_CONFIG = "LTE_SMS_CONFIG"
var LTE_SMS_SENDNEWMSG = "LTE_SMS_SENDNEWMSG"
var LTE_SMS_RECVMSGBOX = "LTE_SMS_RECVMSGBOX"
var LTE_SMS_RECVMSGENTRY = "LTE_SMS_RECVMSGENTRY"
var LTE_SMS_SENDMSGBOX = "LTE_SMS_SENDMSGBOX"
var LTE_SMS_SENDMSGENTRY = "LTE_SMS_SENDMSGENTRY"
var LTE_SMS_DRAFTMSGBOX = "LTE_SMS_DRAFTMSGBOX"
var LTE_SMS_DRAFTMSGENTRY = "LTE_SMS_DRAFTMSGENTRY"
var LTE_SMS_UNREADMSGBOX = "LTE_SMS_UNREADMSGBOX"
var LTE_SMS_UNREADMSGENTRY = "LTE_SMS_UNREADMSGENTRY"
var LTE_BANDINFO = "LTE_BANDINFO"
var LTE_USSD = "LTE_USSD"
var LTE_WRITECODE = "LTE_WRITECODE"
var CLOUD_SERVICE = "CLOUD_SERVICE"
var FW_UPGRADE_INFO = "FW_UPGRADE_INFO"
var CLOUD_USER_ACCOUNT = "CLOUD_USER_ACCOUNT"
var OWNER_INFO = "OWNER_INFO"
var CURRENT_USER_INFO = "CURRENT_USER_INFO"
var CLOUD_DDNS = "CLOUD_DDNS"
var CLOUD_DDNS_ENTRY = "CLOUD_DDNS_ENTRY"
var WAN_BLOCK = "WAN_BLOCK"
var WAN_ERROR_BLOCK = "WAN_ERROR_BLOCK"
var FW_UP_INFO_BLOCK = "FW_UP_INFO_BLOCK"
var IPPING_DIAG = "IPPING_DIAG"
var TRACEROUTE_DIAG = "TRACEROUTE_DIAG"
var ROUTE_HOPS = "ROUTE_HOPS"
var DOWNLOAD_DIAG = "DOWNLOAD_DIAG"
var UPLOAD_DIAG = "UPLOAD_DIAG"
var UDPECHO_DIAG = "UDPECHO_DIAG"
var CAP = "CAP"
var PERF_DIAG = "PERF_DIAG"
var LOCAL = "LOCAL"
var LED_BUTTON = "LED_BUTTON"
var VPN = "VPN"
var IPSEC = "IPSEC"
var IPSEC_CFG = "IPSEC_CFG"
var OPENVPN = "OPENVPN"
var OVPN_CLIENT = "OVPN_CLIENT"
var OVPN_SSL_FILES = "OVPN_SSL_FILES"
var OVPN_CERT_AUTH = "OVPN_CERT_AUTH"
var OVPN_SSL_SERVER = "OVPN_SSL_SERVER"
var OVPN_SSL_CLIENT = "OVPN_SSL_CLIENT"
var PPTPVPN = "PPTPVPN"
var PVPN_CLIENT = "PVPN_CLIENT"
var LTE_NET_SEL = "LTE_NET_SEL"
var LTE_NET_SEL_LIST = "LTE_NET_SEL_LIST"
var LTE_BAND_SEL = "LTE_BAND_SEL"
var ONEMESH = "ONEMESH"
var ONEMESH_CLIENT = "ONEMESH_CLIENT"
var ONEMESH_RT = "ONEMESH_RT"
var ONEMESH_TOPO = "ONEMESH_TOPO"
var ONEMESH_AVAIDEV = "ONEMESH_AVAIDEV"
var ONEMESH_DEVICE = "ONEMESH_DEVICE"
var ONEMESH_DETAIL = "ONEMESH_DETAIL"
var ONEMESH_RELIST = "ONEMESH_RELIST"
var ONEMESH_MAC = "ONEMESH_MAC"
var ONEMESH_REALL = "ONEMESH_REALL"
var SPEEDTEST = "SPEEDTEST"
var SPEEDTEST_LOG = "SPEEDTEST_LOG"
var SPEEDTEST_STAT = "SPEEDTEST_STAT"
var WAKE_ON_LAN = "WAKE_ON_LAN"
var CONN_DEV = "CONN_DEV"
var WAKE_DEV = "WAKE_DEV"
var HOST_NUM = "HOST_NUM"
var SKIPLIST = "SKIPLIST"
var TPLINK_LOGIN_DOMAIN = "tplinkmodem.net"
