#!/bin/sh /etc/rc.common
# Copyright (c) 2015, 2020, The Linux Foundation. All rights reserved.
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

START=40
USE_PROCD=1

skb_recycler_config() {
	local max_skbs=1024
	local max_spare_skbs=256
	local memtotal=$(grep MemTotal /proc/meminfo | awk '{print $2}')

	[ $memtotal -lt 131072 ] && max_skbs=512
	[ -e /proc/device-tree/MP_512 ] && max_skbs=512 && max_spare_skbs=128
	[ -n "$max_skbs" ] && echo "$max_skbs" > /proc/net/skb_recycler/max_skbs
	[ -n "$max_spare_skbs" ] && echo "$max_spare_skbs" > /proc/net/skb_recycler/max_spare_skbs
}

reload_service() {
	skb_recycler_config
}

start_service() {
	reload_service
}

