#!/bin/sh /etc/rc.common

START=99

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	insmod /lib/modules/*/kernel/drivers/usb/host/ehci-hcd.ko
        insmod /lib/modules/*/kernel/drivers/usb/host/ehci-platform.ko
        insmod /lib/modules/*/kernel/drivers/usb/host/ohci-hcd.ko
        insmod /lib/modules/*/kernel/drivers/usb/host/ohci-platform.ko
        insmod /lib/modules/*/kernel/drivers/usb/host/xhci-hcd.ko
        insmod /lib/modules/*/kernel/drivers/usb/host/xhci-plat-hcd.ko

}

stop() {
	rmmod bcm_usb.ko
}