#!/bin/sh /etc/rc.common

START=25
STOP=90

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

NETWORK_MOD_ID=290
LOGX_ID_NETIFD_START=200
LOGX_ID_NETIFD_STOP=201

[ -f /lib/vpn/vpn_fc.sh ] && . /lib/vpn/vpn_fc.sh

start() {
	local pid=""
	local enable
	config_load tfstats
	config_get enable "switch" enable
	
	local sysmode=`uci get sysmode.sysmode.mode`
	
	if [ "$sysmode" == "repeater" ];then
		local sta_2g=$(uci get profile.@wireless[0].wireless_sta_2g -c /etc/profile.d)
		local sta_5g=$(uci get profile.@wireless[0].wireless_sta_5g -c /etc/profile.d)
		brctl delif br-lan $sta_2g
		brctl delif br-lan $sta_5g
	fi

	# rtl8197: hw_nat only support lan mask as 255.255.255.0
	if [ "$sysmode" != "ap" -a "$sysmode" != "repeater" ]; then
		local lanmask=`uci get network.lan.netmask 2>/dev/null`
		if [ "$lanmask" != "255.255.255.0" ];then
			echo 0 > /proc/hw_nat
		else
			echo 1 > /proc/hw_nat
		fi
	fi

	# BCM4908: work around a flow cache bug
	if [ -d /proc/fcache/ ] ; then
		update_pptp_fc_gre_status
	fi

	# Intel:config ppa
	if [ -d /proc/ppa/ ] ; then
		config_ppa
	fi	
	
	stop

	[ -e /proc/sys/kernel/core_pattern ] && {
		ulimit -c unlimited
		echo '/tmp/%e.%p.%s.%t.core' > /proc/sys/kernel/core_pattern
	}

	# netifd depends on "statistics" kern module
	# we insmod statistics in boot, so no need to do it here
	# insmod statistics
	if [ "$enable" = "on" ] ; then
		ubus call tfstats on || true
	fi
	service_start /sbin/netifd

	pid=$(pidof netifd)
	if [ x"$pid" != x ]; then
		logx -p $pid $NETWORK_MOD_ID $LOGX_ID_NETIFD_START
	fi
}

restart() {
	start

	# for brcm reset wl affinity
	if [[ -f /etc/init.d/bcm_cpu_affinity ]]; then
		/etc/init.d/bcm_cpu_affinity start
	fi
}

shutdown() {
	stop
}

stop() {
	local pid=$(pidof netifd)

	ifdown -a
	if [ x"$pid" != x ]; then
		sleep 1
	fi

	service_stop /sbin/netifd
	ubus call tfstats off || true
	#rmmod statistics

	if [ x"$pid" != x ]; then
		logx -p $pid $NETWORK_MOD_ID $LOGX_ID_NETIFD_STOP
	fi
}

reload() {
	ubus call network reload

	# for brcm reset wl affinity
	if [[ -f /etc/init.d/bcm_cpu_affinity ]]; then
		/etc/init.d/bcm_cpu_affinity start
	fi
}
