#!/bin/sh /etc/rc.common

START=90

cfg_switch() 
{
	local mode="$(uci get sysmode.sysmode.mode)"
	if [ "$mode" == "ap" -o "$mode" == "repeater" ]; then
		echo 1 > /proc/rtl_dnstrap/enable
		echo 2 > /proc/hw_nat
		echo "0 0" > /proc/net/vlan/vlanEnable
		echo 1 > /proc/br_mldsnoop
		echo 1 > /proc/br_igmpsnoop
	else
		. /lib/switch/base.sh
		setup_wan_duplex
	fi

	echo 1 > /proc/br_igmpquery
	echo 1 > /proc/br_mldquery

	echo 1 > /proc/rtl865x/link
}

start() {
	cfg_switch &
}
