#!/usr/bin/env lua

local uci = require "luci.model.uci"
local uci_t = uci.cursor()
local en = uci_t:get("ledpm", "leds", "enable") or "off"

if en == "on"
then
	print(uci_t:get("ledctrl", "NIGHT", "enable") or "off")
end
