#!/bin/sh

[ "$DEVICE" == "lo" ] && exit 0

#add by wanghao
[ "$INTERFACE" == "lan " -a "$ACTION" == "ifup" ] && {
	echo "running" > /tmp/run/network_running
}
#add end

. /lib/functions.sh
. /lib/functions/network.sh
. /lib/iptv/iptv_func.sh
. /lib/iptv/iptv_core.sh

# Do the gc when 'iptv stop'.
local en=$(uci_get_state iptv core enable)
[ -z "$en" ] && exit 0
[ "$en" != "1" ] && {
	uci_revert_state iptv
	exit 0
}

config_get mode "iptv" "mode"
case "$mode" in
	Bridge)
	#Do nothing
	;;
	*)
		local prio_pair=$(uci_get_state iptv core priority)
		local ifname=
		local prio=
		for pair in $prio_pair; do
			ifname=${pair%%-*}
			prio=${pair##*-}
			set_8021q_prio $ifname 0 $prio
		done
	;;
esac

# As IPTV would change the lan interface name, we need to redo the enable gro
# to keep it work.
[ -e /etc/hotplug.d/block/60-enable_gro ] && /etc/hotplug.d/block/60-enable_gro

