#!/bin/sh /etc/rc.common
USE_PROCD=1
START=20

start_service() {
	echo -e "\033[35m Pega DIL monitor daemon start \033[0m" > /dev/console
	procd_open_instance
	procd_set_param command pudild 
	procd_set_param respawn
	procd_close_instance
}
