#!/bin/sh /etc/rc.common

/etc/preinit.d/scapi_utils.sh
USE_PROCD=1
START=80

start_service() {
        procd_open_instance
        procd_set_param command pu_attachDevd
        procd_set_param respawn
        procd_close_instance
}

