#!/bin/sh /etc/rc.common
START=65

start() {
	/opt/lantiq/usr/sbin/ppasessmgmt -i 30 -n 200 -m 2048
#	/opt/lantiq/etc/rc.d/sess_mgmt.sh --enable
#	/opt/lantiq/etc/rc.d/sess_mgmt.sh --disable
}	

stop() {
	/opt/lantiq/etc/rc.d/sess_mgmt.sh --disable
}
