#!/bin/sh
SVC="upagent"

start_service() {
  	#Enable log debug log to console and log to file for upagent
	d2 -c dallogcfg[0].UpAgentLogLevel LOG_DEBUG
	d2 -c dallogcfg[0].UpagentLogToConsole true
	d2 -c dallogcfg[0].UpagentLogToFile true

	procd_open_instance $SVC
	procd_set_param command /usr/bin/upagent
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-30} ${respawn_retry:-5}
	echo '/tmp/%e.%p.%s.%t.core' > /proc/sys/kernel/core_pattern
	procd_set_param limits core="unlimited"
	procd_close_instance
}

stop_service() {
    killall upagent
    kill -17 1
    rm /tmp/upagent.pid
}

boot() {
    start
}

restart() {
    stop
	d2 -c upstatus.addXdeviceIdDone false 
    start
}

#start_nonopenwrt used for NH ODM to start upagent module 
#Just call this procedure to start upagent module for NH SKUs
start_nonopenwrt() {
  echo "start upagent module for Non openWRT ********* "
  #<< PEGA Mark: support DAL logs
  #if [ -e /data/dal/log_dal_when_bootup ]; then
  d2 -c dallogcfg[0].UpagentConfigurationApply false
  sleep 1
  setlogLevelForDAL.sh upagent LOG_DEBUG false true
  #fi
  #PEGA >>
  /usr/bin/upagent &
}

case "$1" in
	start)
		echo -e "\033[35mStarting UPAgent...\033[0m"
		start_nonopenwrt
		exit 0
		;;

	stop)
		echo "Stopping UPAgent..."
		stop_service
		exit 0
		;;

	*)
		echo "$0: unrecognized option $1"
		exit 1
		;;

esac

