#!/bin/sh

tble() {
	while true 
	do
		rf_process=`ps -w|grep "/bin/rf_test"|grep -v "grep"|wc -l`
		if [ $rf_process = 0 ]; then
			killall bsa_server
			echo 1 > /proc/driver/hs_uart/reset_bt
			sleep 1
			/bin/bsa_server -d /dev/ttyH0 -p /etc/bluetooth/firmware.hcd -all=0 &
			sleep 3

			/bin/rf_test &
		fi
		sleep 2
	done
}

tble
