#!/bin/sh

case "$1" in
	start)
		echo -e "\033[35mStarting bst...\033[0m"
		d2 -c bstcfg[0].URL "https://netgearup-dev.s3-us-west-2.amazonaws.com/"
		/usr/bin/bst_daemon &
		#<< PEGA Mark: support DAL logs
		if [ -e /data/dal/log_dal_when_bootup ]; then
		    d2 -c dallogcfg[0].BstConfigurationApply false
		    sleep 1
		    setlogLevelForDAL.sh bst LOG_DEBUG false true
		fi
		#PEGA >>
		exit 0
		;;

	stop)
		echo "Stopping bst..."
		killall bst_daemon
		kill -17 1
		rm /tmp/bst.log
		exit 0
		;;

	*)
		echo "$0: unrecognized option $1"
		exit 1
		;;

esac

