#!/bin/sh

start() {
    #<< PEGA Mark: support DAL logs
    #<< PEGA KKHuang: Alway enable ash log >>
    #if [ -e /data/dal/log_dal_when_bootup ]; then
        d2 -c dallogcfg[0].CshConfigurationApply false
        sleep 1
        setlogLevelForDAL.sh csh LOG_DEBUG false true
    #fi
    #PEGA >>
    /usr/bin/csh &
}

stop() {
    killall csh
    kill -17 1
    rm /tmp/csh.log
}

boot() {
    start
}

restart() {
    stop
    start
}

case "$1" in
	start)
		echo -e "\033[35mStarting CSH...\033[0m"
		start
		exit 0
		;;

	stop)
		echo "Stopping CSH..."
        stop
		exit 0
		;;

    restart)
		echo "Restart CSH..."
        restart
		exit 0
        ;; 
	*)
		echo "$0: unrecognized option $1"
		exit 1
		;;

esac

