#!/bin/sh

set_if_empty() {
    SYM="$1"
    
    # read value, make sure d2d is up.
    until VAL=$(d2 -s ${SYM}); do sleep .1; done
    if [ "${VAL}empty" == "empty" ]; 
    then
        d2 -c ${SYM} -- "$2"; 
    fi
}

start() {
	mkdir -p /data/dal
	ln -s /data/dal /tmp/dal

      # Start d2

      # We may need to chmod following in future.
      mkdir -p /tmp/d2

      # TODO:
      # We should source a config file that defines where R/W
      # filesystem is mounted.
      # Hard-coded for now
      PERSISTDIR=/tmp/dal/d2d

      mkdir -p ${PERSISTDIR}
      
      #BETA_XTRA="-d /etc/d2" //will be use in future if required for qa env

      #d2d ${BETA_XTRA} ${PERSISTDIR} &

      d2d ${PERSISTDIR} &

        
        #set some default value

# This is must for all the SKU those are going to use this script. As the router boots up internet should be Unknown until ODM will detect any # network connectivity on the target machine. Do not remove the below line without any further discussion with DAL Team.

# Also the General table in DAL is persistence. So it will always have the latest value whatever it has before the reboot. So to make sure it
# always reset to default as "Unknown" after the router boots up.
        /bin/dal_update_DB.sh
        #d2 -c general.internetstatus Unknown
        #d2 -c general.devicemodel RAX30
        #d2 -c general.devicename RAX30
        #d2 -c general.fwrevision "`cat /firmware_version`"
		#d2 -c dalmoduleversion.RELEASEVersion "`cat /etc/version.txt`"
        #d2 -c general.fsn "`artmtd -r sn|head -1 |cut -d ':' -f 2-`"
        #d2 -c general.fsn "5U618BWH0000C"
# Commenting general.region as "artmtd" CLI is specific to Qualcomm based SKU so will not be applicable for other SKUs		
#        d2 -c general.region "`artmtd -r region|head -1 |cut -d 'x' -f 2-`"
        #d2 -c general.defaultmac "`ifconfig br0|head -1|awk -F ' ' '{print $5}'`"
        #d2 -c general.wan_ifname         "$(nvram get wan_ifname)"
        #d2 -c general.lan_ifname         "$(nvram get lan_ifname)"
        
      # ODMSTOP ORBI  
       /etc/init.d/d2_countryname.sh &      
}


case "$1" in
	start)
		echo -e "\033[35mStarting d2...\033[0m"
		start
		exit 0
		;;

	stop)
		echo "Stopping d2..."
        killall d2d
		exit 0
		;;

	*)
		echo "$0: unrecognized option $1"
		exit 1
		;;

esac


