#!/bin/sh /etc/rc.common

START=18

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

. /lib/bcmenet/bcmenet_c5400s.sh

config_agg () {

	# only support one LAG now
	[ $lagmask -ne 0 -a $lag1portmap -ne 0 ] && bcm_4908_config_trunk ${lag1portmap}
}

config_addl_wan () {

	[ $addlwan -ne -1 ] && bcm_4908_set_addl_wan ${addlwan}
}

load_bcmenet_driver () {

	insmod /lib/modules/*/extra/rdpa_gpl.ko  
	insmod /lib/modules/*/extra/rdpa_gpl_ext.ko  
	insmod /lib/modules/*/extra/rdpa.ko  
	insmod /lib/modules/*/extra/rdpa_mw.ko
	insmod /lib/modules/*/extra/chipinfo.ko  
	insmod /lib/modules/*/extra/pktflow.ko
	insmod /lib/modules/*/extra/nciTMSkmod.ko
	insmod /lib/modules/*/extra/wfd.ko 

	# set LAN MAC to RoboSwitch Multiport Address
	#
	# N.B.
	# if we disabled ULF, we must set LAN MAC to RoboSwitch, 
	# either multiport address or static ARL entry.
	# because RoboSwitch default disable learning address from IMP port
	# if we don't add LAN MAC manually to RoboSwitch, 
	# all traffic to CPU will be flooded. 
	#
	local bcmenet_param=""
	local mac=`getfirm MAC`
	if [ $? -eq 0 ] ; then
		bcmenet_param="tp_lanmac=$mac"
	fi
	insmod /lib/modules/*/extra/bcm_enet.ko $bcmenet_param

	insmod /lib/modules/*/extra/pktrunner.ko 

	insmod /lib/modules/*/extra/bcmvlan.ko  
	insmod /lib/modules/*/extra/pwrmngtd.ko  
	insmod /lib/modules/*/extra/bcmpdc.ko  
	insmod /lib/modules/*/extra/bcmspu.ko  
	
	insmod /lib/modules/*/extra/rdpa_cmd.ko

	# We need to down eth0 prior to starting runner's data path init
	ifconfig eth0 down &> /dev/null

	# Initialize bdmf shell
	bdmf_shell -c init | while read a b ; do echo $b ; done > /var/bdmf_sh_id
	alias bs="bdmf_shell -c `cat /var/bdmf_sh_id` -cmd "
}

start_link_poll () {

	/bin/swmdk &
}

# FIXME: using a better way to check network device
# now delete all old devices, and create some new
#
config_network_device ()
{

	while uci delete network.@device[0] > /dev/null 2>&1 ; do
		:
	done

	/sbin/network_firm $@
}

config_if () {

	# set trunk hash algorithm
	[ $lagmask -ne 0 ] && {
		local hashAlgo=$(uci get switch.lan_agg.hashmode)
		bcm_4908_set_trunk ${hashAlgo}
	}

	# disable 53134 P5 mac traffic
	# FIX low throughput bug when flow control enabled
	#
	bcm_4908_set_53134_port_traffic 5 0x3

	# enable PAUSE capability
	#
	bcm_4908_set_pause 1 255 2
	bcm_4908_set_pause 2 255 2

	# moved from /etc/init.d/boot
	config_load sysmode
	config_get mode sysmode mode
	local internetIf
	if [ $mode = "ap" ]; then
		internetIf=$int_wan
	else
		# always init to eth0 for robust, if iptv enabled, /etc/init.d/iptv will change it
		# internetIf=$(uci get network.wan.ifname)
		internetIf=$int_wan		
	fi
	config_network_device ${internetIf} ${lan_ifs}

	# FIXME: waiting mdev create dev node
	# dead loop may happen
	while [ ! -c /dev/bcmrdpa ] ; do
		echo "waiting mdev create /dev/bcmrdpa" >&2
		sleep 1
	done
}

start() {

	c5400s_get_interface_group

	# step 1: config trunk to boardparams before insmod driver
	#			must be called before load_bcmenet_driver
	config_agg

	# config addtional wan
	config_addl_wan

	# step 2: insmod bcm enet releated drivers
	load_bcmenet_driver

	# step 4: set port tm, and so on...
	config_if

	# step 3: start swmdk to do link poll of RoboSwitch and external switch 53134
	start_link_poll

	c5400s_interface_init_config

	echo "bcmenet Initialize done..." >&2

} 2> /dev/console 1>&2

restart() {
	echo "bcmenet don't support restart" >&2

}

shutdown() {
	echo "bcmenet don't support shutdown" >&2
}

stop() {
	echo "bcmenet don't support stop" >&2
}

reload() {
	echo "bcmenet don't support reload" >&2
}
