#!/bin/sh /etc/rc.common

START=22

start()
{
    echo "Starting bsa_server..." >/dev/console
    bt_enable=$(uci get bluetooth.B1.enable)
    if [[ "$bt_enable" == "on" ]]
    then
	cd /tmp
	ulimit -s 64
	
	echo 1 > /proc/driver/hs_uart/bt_rx_decode
	echo 1 > /proc/driver/hs_uart/reset_bt
		sleep 1
		/bin/bsa_server -d /dev/ttyH0 -p /etc/bluetooth/firmware.hcd -all=0 &
	fi
}

stop()
{
	echo "Stopping bsa_server..." >/dev/console
	killall bsa_server
}