#!/bin/sh /etc/rc.common

START=99
SERVICE_DAEMONIZE=1

start()
{
	local delay_time=$(uci get profile.@ifttt[0].delay_time -c "/etc/profile.d")
	[ ! -z "$delay_time" ] && { sleep $delay_time && touch /tmp/ifttt_allow_upload & }
}
