#!/bin/sh /etc/rc.common

START=99
SERVICE_DAEMONIZE=1

local NGX_LOG_PATH_PRE=/var/log
local NGX_LOG_PATH="$NGX_LOG_PATH_PRE/nginx"
local NGX_LIB_PATH_PRE=/var/lib
local NGX_LIB_PATH="$NGX_LIB_PATH_PRE/nginx"

start()
{
	# check tpfile support 
	#`uci get profile.@tpfile[0].tpfile_support -c /etc/profile.d`
	local tpfile_support
	config_load "profile"
	config_get tpfile_support tpfile_diff tpfile_support "no"

	if [ "$tpfile_support" = "yes" ]; then	
		if [ ! -d $NGX_LOG_PATH_PRE ]; then
			mkdir $NGX_LOG_PATH_PRE
		fi
		if [ ! -d $NGX_LOG_PATH ]; then
			mkdir $NGX_LOG_PATH
		fi
		if [ ! -d $NGX_LIB_PATH_PRE ]; then
			mkdir $NGX_LIB_PATH_PRE
		fi
		if [ ! -d $NGX_LIB_PATH ]; then
			mkdir $NGX_LIB_PATH
		fi

		create_cer.sh
		/usr/sbin/nginx -c /etc/nginx/nginx.conf
	fi
}

stop()
{
	nginx -s stop
}

restart()
{
	stop
	start
}
