#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=99

PC_LIBDIR=/lib/qos

pc() {
	. $PC_LIBDIR/core.sh
	fw_$1
}

start() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
	pc start
	fi
}

stop() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
	pc stop
	fi
}

restart() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
	pc restart
	fi
}

reload() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
	pc reload
	fi
}
