#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2016 TP-Link
# Author: Zhu Junjie <zhujunjie@tp-link.net>
# Date: 14Nov16

START=99

start() {
	/usr/bin/tm_shn -q
	echo "QOS config trigger start!"
}

stop(){
	echo "QOS config trigger stop!"
}
