#!/bin/sh
# smartdhcp hotplug for detect immediately when frontend connected in RE mode
# Copyright (c) 2016 Shenzhen TP-LINK Technologies Co.Ltd.
# Author  : Sharon Lin <sharon.lin@tp-link.com>
# Date    : 9 Dec 2016

. /lib/functions.sh
. /lib/functions/network.sh

SMARTDHCP_MONITOR_PID="/var/run/smartdhcp_monitor.pid"
SMARTDHCP_STATUS_FILE="/tmp/smartdhcp_current_status"

send_smartdhcp_signal() {
	kill -SIGUSR1 $(cat "$SMARTDHCP_MONITOR_PID")
}
	
if [ "$ACTION" == "frontend-up" ]; then
	send_smartdhcp_signal
elif [ "$ACTION" == "frontend-down" ]; then
	if [ -e ${SMARTDHCP_STATUS_FILE} ]; then
		local current=$(cat ${SMARTDHCP_STATUS_FILE})
		[ "$current" == "1" ] && /etc/init.d/smartdhcp restart
	fi
fi

