#!/bin/sh

[ "change" = "$ACTION" -a -n "$SUBACTION" -a -n "$BRIDGENAME" -a -n "$INTERFACE" ] && {
    case $SUBACTION in
        braddif)
            wifi vlan with_br "$BRIDGENAME" "$INTERFACE"
            ;;
        brdelif)
            ;;
    esac
}
