#!/bin/sh /etc/rc.common

START=18

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	#. /lib/gmac3/gmac3_fwd.sh
	#. /lib/gmac3/gmac3_switch.sh
	
	#gmac3_switch_adjust
	#gmac3_fwd_action
	return 0
}

restart() {
	return 0
}

stop() {
	return 0
}

reload() {
	return 0
}
