#!/bin/sh /etc/rc.common

START=95

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	#stable_higher_throughput &
	return 0
}

restart() {
	stop
	start
	return 0
}

stop() {
	killall stable_higher_throughput
	return 0
}

reload() {
	return 0
}
