#!/bin/sh /etc/rc.common

START=99

boot() {
	# enable gpio2, which will enable usb phy
	local reg_tmp=$(mem -s 0x16c00000 -ud | cut -d : -f 2-)
	reg_tmp=$(($reg_tmp|0x00000004))
	mem -s 0x16c00000 -uw $reg_tmp
}
