#!/bin/sh
#
# Copyright (c) 2016 Shenzhen TP-LINK Technologies Co.Ltd.
# Author  : Eddie Ho <eddie.ho@tp-link.com>
# Date    : 29 Mar 2016
#


IFNAME=$1
CMD=$2

is_no_any_down() {
	for dir in /var/run/wpa_supplicant-*; do
		[ -d "$dir" ] || continue
		config_load wireless
		config_get_bool vap_enable ${dir#"/var/run/wpa_supplicant-"} enable 0
		if [ "$vap_enable" = "0" ]; then
			continue
		fi
		if [ "`wpa_cli -p $dir status| grep wpa_state| cut -d = -f 2`" != "COMPLETED" ]; then
			echo 0
			return
		fi
	done
	echo 1
}

is_no_any_up() {
        for dir in /var/run/wpa_supplicant-*; do
                [ -d "$dir" ] || continue
		config_load wireless
		config_get_bool vap_enable ${dir#"/var/run/wpa_supplicant-"} enable 0
		if [ "$vap_enable" = "0" ]; then
			continue
		fi
                if [ "`wpa_cli -p $dir status| grep wpa_state| cut -d = -f 2`" == "COMPLETED" ]; then
                        echo 0
                        return
                fi
        done
        echo 1
}

count_vap() {
	local count=0
        for dir in /var/run/wpa_supplicant-*; do
		[ -d "$dir" ] && count=$((count+1))
	done
	echo $count
}

echo "[RE][LED]$IFNAME:$CMD" > /dev/console
case "$CMD" in
	CONNECTED|WPS-TIMEOUT|DISCONNECTED)
		. /sbin/wifi detect

		if [ $(is_no_any_down) -eq 1 ] && [ $(is_no_any_up) -eq 1 ]; then
			ledcli RE_OFF
		elif [ $(is_no_any_down) -eq 1 ]; then
			ledcli RE_ON
		else
			ledcli RE_INPROGRESS
		fi

		if [ "$CMD" = "CONNECTED" ]; then
			if [ $(count_vap) -eq 1 ] || [ $(is_no_any_down) -ne 1 ]; then
				env -i ACTION="frontend-up" /sbin/hotplug-call smartdhcp
			fi
		fi
		if [ "$CMD" = "DISCONNECTED" ] && [ $(is_no_any_up) -eq 1 ]; then
			env -i ACTION="frontend-down" /sbin/hotplug-call smartdhcp
		fi
		;;
esac

