#!/bin/sh

# This script runs when init it run during the boot process.
# Mounts everything in the fstab

mount -a
#mount -o remount +w /

#
# Mount the RAM filesystem to /tmp
#

mount -t ramfs -n none /tmp
mount -t ramfs -n none /var
mount -t ramfs -n none /config

#export PATH=$PATH:/etc/ath

#insmod /lib/modules/2.6.15/net/ag7100_mod.ko
#insmod /lib/modules/2.6.15/net/ag7240_mod.ko

#
# Set lo eth1 up
#
ifconfig lo 127.0.0.1 up
#ifconfig eth1 up

#
# insert netfilter/iptables modules
#

/etc/rc.d/rc.modules

#
# when disable nas, we need this to login
#
echo 'root:x:0:0:root:/root:/bin/sh' > /tmp/passwd

#
# Start Our Router Program
#
#/usr/bin/ledserver &

ifconfig eth0 up
brctl addbr br0
ifconfig br0 up
brctl setfd br0 0
vconfig add eth0 1
brctl addif br0 eth0.1
ifconfig eth0.1 up
ifconfig br0 192.168.0.254

/usr/bin/uclited
tdb -r /usr/bin/httpd 

/etc/rc.d/rc.init

echo 524288 > /proc/sys/net/ipv4/ipfrag_high_thresh
