#!/bin/sh

. /lib/functions.sh

[ "$DEVICE" = "lo" ] && exit 0

[ "$INTERFACE" = "lan" ] && {
	config_load sysmode
	config_get mode sysmode mode router
	[ $mode == "router" ] && /etc/init.d/imb restart
}
