O 3 HOST_INTERFACE
G 3 1 GLOBAL_GID1
S 3 1 1 202 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: Out of Main Loop
S 3 1 1 2938 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: Bad Interrupt
S 3 1 1 2986 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: HostInterface_ReadInitVector_BufferAddressNotAlignedToDWord
S 3 1 1 2998 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: HostInterface_ReadInitVector_BufferSizeNotAlignedToDWord
S 3 1 1 3012 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: HostInterface_PushToTailError_PD_Buffer_logger_post_dma_activate
S 3 1 1 3028 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: tx_out_no_free_hds_error
S 3 1 1 3038 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: rx_out_no_free_hds_error
S 3 1 1 3052 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: HostInterface_Mailbox_FifoOutFullError
S 3 1 1 3067 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: HostInterface_CbmFragmentation_WA_RingFullError
