#!/bin/sh /etc/rc.common

START=68
STOP=32

IS_AVIRA_SENTINEL_LITE_RESTART=0

start () {
        echo "[aviraSentinelLite]: start">/dev/console

        export LD_LIBRARY_PATH=/usr/lib/avira:$LD_LIBRARY_PATH
        export PATH=/usr/bin/avira:$PATH
        service_start /usr/bin/avira/avirasentinellite/avirasentinellite

        if [ ! -f /etc/config/avira ];then
            touch /etc/config/avira
            uci set avira.info='global'
        fi

        ## if state is paid or '' before, set config to free.
        ## if state is paid before, state has been changed.
        local changed="n"
        local state=`uci -q get avira.info.state`
        if [ "x$state" != "xfree" ];then
            changed="y"
            uci set avira.info.state='free'
            uci commit
            uci_commit_flash
        fi

	echo "[aviraSentinelLite]: start IS_AVIRA_SENTINEL_LITE_RESTART: $IS_AVIRA_SENTINEL_LITE_RESTART ">/dev/console
	echo 0 > /proc/pctl/payment
	lua /usr/sbin/report_upload_components lite $changed
	
	[ -e /etc/init.d/avira_accel_support ] && {
		/etc/init.d/avira_accel_support restart
	}	
}

stop() {
	echo "[aviraSentinelLite]: stop">/dev/console
	
	service_stop /usr/bin/avira/avirasentinellite/avirasentinellite
		
	[ -e /etc/init.d/avira_accel_support ] && {
		/etc/init.d/avira_accel_support restart
	}		
}

restart()
{
	echo "[aviraSentinelLite]: restart">/dev/console
	echo "[aviraSentinelLite]: restart IS_AVIRA_SENTINEL_LITE_RESTART: $IS_AVIRA_SENTINEL_LITE_RESTART ">/dev/console
	IS_AVIRA_SENTINEL_LITE_RESTART=1
	
	stop "$@"
	start "$@"
}
