#!/bin/sh /etc/rc.common

START=68
STOP=32

IS_AVIRA_SENTINEL_FULL_RESTART=0

start () {
	echo "[aviraSentinelFull]: start">/dev/console
	
    export LD_LIBRARY_PATH=/usr/lib/avira:$LD_LIBRARY_PATH
    export PATH=/usr/bin/avira:$PATH
    service_start /usr/bin/avira/avirasentinelfull/avirasentinelfull

    if [ ! -f /etc/config/avira ];then
        touch /etc/config/avira
        uci set avira.info='global'
    fi

    local changed="n"
    local state=`uci -q get avira.info.state`
    if [ "x$state" != "xpaid" ];then
        changed="y"
        uci set avira.info.state='paid'
        uci commit
        uci_commit_flash
    fi
        
	echo "[aviraSentinelFull]: start IS_AVIRA_SENTINEL_FULL_RESTART: $IS_AVIRA_SENTINEL_FULL_RESTART ">/dev/console
	echo 1 > /proc/pctl/payment
	lua /usr/sbin/report_upload_components full $changed
	
	[ -e /etc/init.d/avira_accel_support ] && {
		/etc/init.d/avira_accel_support restart
	}	
}

stop() {
	echo "[aviraSentinelFull]: stop">/dev/console

    service_stop /usr/bin/avira/avirasentinelfull/avirasentinelfull
	
	[ -e /etc/init.d/avira_accel_support ] && {
		/etc/init.d/avira_accel_support restart
	}	
}

restart()
{
	echo "[aviraSentinelFull]: restart">/dev/console
	echo "[aviraSentinelFull]: restart IS_AVIRA_SENTINEL_FULL_RESTART: $IS_AVIRA_SENTINEL_FULL_RESTART ">/dev/console
	IS_AVIRA_SENTINEL_FULL_RESTART=1
	
	stop "$@"
	start "$@"
}


