#!/bin/sh /etc/rc.common

START=99
STOP=1
USE_PROCD=1

start_service() {
	local EXE_NAME=unifi-anywhere
	local APP=/usr/sbin/uanywhere-launcher.sh
	local SHARE_DIR=/usr/share/$EXE_NAME
	local BLECONN_SHARE_DIR=/usr/share/bleconn
	local STOP_TIMEOUT=12

	# Don't run app on devices which are not supported by bleconnd
	$BLECONN_SHARE_DIR/bleconn-check-sys-support.sh $BLECONN_SHARE_DIR || return 0

	$SHARE_DIR/check-sys-support.sh $SHARE_DIR || return 0

	procd_open_instance
	procd_set_param command $APP $EXE_NAME $SHARE_DIR/$EXE_NAME-init "-" 60 60 5
	procd_set_param respawn
	procd_set_param term_timeout $STOP_TIMEOUT
	procd_close_instance
}
