#!/bin/sh
#
# generate a fake cal data for rtl8197+rtl8832

. /lib/wifi/rtk_wlan_extend.sh

/usr/sbin/mp.sh

set_cal_data

ifconfig wlan1 down
ifconfig wlan1 up

ifconfig wlan0 down
ifconfig wlan0 up


/usr/sbin/mp.sh

