#!/bin/sh
. /lib/switch/base.sh

local in_lan_status=""
local wan_status=""
local in_lan_speed=""
local wan_speed=""
local wan_duplex=""
local in_lan_duplex=""

local wan_unit=""
local lan_units=""

get_lan_wan_phyunit "lan_units" "wan_unit"

get_lan_status()
{
	get_common_port_list_status  "in_lan_status" "$lan_units"
}

get_lan_speed()
{	
	get_common_port_list_speed  "in_lan_speed" "$lan_units"
}

get_lan_duplex()
{
	get_common_port_list_duplex  "in_lan_duplex" "$lan_units"
}

get_wan_speed()
{
	get_common_port_speed "wan_speed" "$wan_unit"
}

get_wan_status()
{
	get_common_port_status "wan_status" "$wan_unit"
}

get_wan_duplex()
{
	get_common_port_duplex "wan_duplex" "$wan_unit"
}

case $1 in
	"lan_status")
		get_lan_status
		echo -n $in_lan_status 
		;;
	"lan_speed")
		get_lan_speed
		echo -n $in_lan_speed
		;;
	"wan_status")
		get_wan_status 
		echo -n $wan_status
		;;
	"wan_speed")
		get_wan_speed
		echo -n $wan_speed
		;;
	"lan_duplex")
		get_lan_duplex
		echo -n $in_lan_duplex
		;;
	"wan_duplex")
		get_wan_duplex
		echo -n $wan_duplex
		;;
	"speed")
		get_wan_speed
		get_lan_speed
		echo -n $wan_speed $in_lan_speed
		;;
	"duplex")
		get_wan_duplex
		get_lan_duplex
		echo -n $wan_duplex $in_lan_duplex
		;;
		*)
		echo "bad choice"
		;;
esac
