#!/bin/sh
#
# Copyright (C) 2011-2012 OpenWrt.org
#

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/ramips.sh
. /lib/uboot-envtools.sh
. /lib/functions.sh
. /lib/functions/system.sh	# for find_mtd_chardev
. /lib/functions/pega.sh	# for mtd_get_erase_size

BOOTENV_PART=Config
PDATA_PART=PDATA
PDATA_CONF="/etc/pdata.config"
board=$(ramips_board_name)

case "$board" in
	# PEGA: remove unused boards, and add pega-ramips
	pega-ramips)
		mtd="$( find_mtd_chardev $BOOTENV_PART )"
		# 'Config' only use erasesize to store data not entire partition size
		erasesize="$( mtd_get_erase_size $BOOTENV_PART )"
		ubootenv_add_uci_config "$mtd" "0x0" "$erasesize" "$erasesize"
		mtd2="$( find_mtd_chardev $PDATA_PART )"
		[ -n "$mtd2" ] && {
			# 'PDATA' only use erasesize to store data not entire partition size
			# And enable redund offset one erasesize
			erasesize2="$( mtd_get_erase_size $PDATA_PART )"
			echo "$mtd2 0x0 $erasesize2 $erasesize2" > $PDATA_CONF
			echo "$mtd2 $erasesize2 $erasesize2 $erasesize2" >> $PDATA_CONF
		}
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
