#!/bin/sh

. /lib/functions/pega.sh

baseMacAddr=$(fw_printenv -c /etc/pdata.config -n MAC 2>/dev/null)
SSID=$(fw_printenv -c /etc/pdata.config -n SSID 2>/dev/null)
passphrase=$(fw_printenv -c /etc/pdata.config -n passphrase 2>/dev/null)
region_no=$(fw_printenv -n region_no 2>/dev/null)
if [ -n "$region_no" ]
then
    nmrpSku="$(pega_get_skuName_by_nmrpRegionNo "$region_no")"
    if [ -z "$nmrpSku" ]; then
        nmrpSku="PA"
    fi
else
    nmrpSku="PA"
fi
iso3166_countryCode=$(/usr/bin/lua -lcommonFunc/wifiUtils_wifiCountryCodeMapping -e _sh_getISO3166CountryCodeByNmrpSku\(\""$nmrpSku"\"\))
wifi24g_channelRegion=$(/usr/bin/lua -lcommonFunc/wifiUtils_wifiCountryCodeMapping -e _sh_get24gSupportedChannelByNtgrWirelessRegion\(\""$iso3166_countryCode"\"\))
wifi5g_channelRegion=$(/usr/bin/lua -lcommonFunc/wifiUtils_wifiCountryCodeMapping -e _sh_get5gSupportedChannelByNtgrWirelessRegion\(\""$iso3166_countryCode"\"\))

[ -z "$baseMacAddr" -o -z "$SSID" ] && {
	echo -e "\033[41;37m[sync-pdata] There is no \033[41;30mMAC\033[41;37m or \033[41;30mSSID\033[41;37m in PDATA!!!\033[0m" > /dev/console
}

[ -n "$baseMacAddr" ] && {
	macAddrInHex=$(echo "$baseMacAddr" | awk -F ':' '{printf 0x$1$2$3$4$5$6}')
	lan_mac=$baseMacAddr
	wan_mac=$(macToString "$(printf %012X $((0x$macAddrInHex + 0x01)))")
	wifi2_mac=$baseMacAddr
	wifi5_mac=$(macToString "$(printf %012X $((0x$macAddrInHex + 0x02)))")
}

[ -n "$SSID" ] && {
	wifi2_ssid=$SSID
	wifi5_ssid=${SSID}"-5G"
}

echo "[sync-pdata] lan_mac=$lan_mac, wan_mac=$wan_mac, wifi2_mac=$wifi2_mac, wifi5_mac=$wifi5_mac, wifi2_ssid=$wifi2_ssid, wifi5_ssid=$wifi5_ssid" > /dev/console

# Read lan/wan mac form Factory
factory_lan=$(/sbin/mtk_factory_rw.sh -r lan)
factory_wan=$(/sbin/mtk_factory_rw.sh -r wan)

[ -n "$lan_mac" -a "$lan_mac" != "$factory_lan" ] && {
	# sync lan mac to Factory
	/sbin/mtk_factory_rw.sh -w lan ${lan_mac:0:2} ${lan_mac:3:2} ${lan_mac:6:2} ${lan_mac:9:2} ${lan_mac:12:2} ${lan_mac:15:2}
	ifconfig eth0 hw ether "$lan_mac"
}
[ -n "$wan_mac" -a "$wan_mac" != "$factory_wan" ] && {
	# sync wan mac to Factory
	/sbin/mtk_factory_rw.sh -w wan ${wan_mac:0:2} ${wan_mac:3:2} ${wan_mac:6:2} ${wan_mac:9:2} ${wan_mac:12:2} ${wan_mac:15:2}
	ifconfig eth1 hw ether "$wan_mac"
}
[ -n "$wifi2_mac" ] && datconf -f /etc/wireless/mediatek/mt7915.dbdc.b0.dat set MacAddress "$wifi2_mac"
[ -n "$wifi5_mac" ] && datconf -f /etc/wireless/mediatek/mt7915.dbdc.b1.dat set MacAddress "$wifi5_mac"
[ -n "$wifi2_ssid" ] && datconf -f /etc/wireless/mediatek/mt7915.dbdc.b0.dat set SSID1 "$wifi2_ssid"
[ -n "$wifi2_ssid" ] && datconf -f /etc/wireless/mediatek/mt7915.dbdc.b0.dat set SSID2 "NETGEAR-Guest"
[ -n "$wifi5_ssid" ] && datconf -f /etc/wireless/mediatek/mt7915.dbdc.b1.dat set SSID1 "$wifi5_ssid"
[ -n "$wifi5_ssid" ] && datconf -f /etc/wireless/mediatek/mt7915.dbdc.b1.dat set SSID2 "NETGEAR-5G-Guest"
[ -n "$passphrase" ] && datconf -f /etc/wireless/mediatek/mt7915.dbdc.b0.dat set WPAPSK1 "$passphrase"
[ -n "$passphrase" ] && datconf -f /etc/wireless/mediatek/mt7915.dbdc.b1.dat set WPAPSK1 "$passphrase"
[ -n "$iso3166_countryCode" ] && datconf -f /etc/wireless/mediatek/mt7915.dbdc.b0.dat set CountryCode "$iso3166_countryCode"
[ -n "$iso3166_countryCode" ] && datconf -f /etc/wireless/mediatek/mt7915.dbdc.b1.dat set CountryCode "$iso3166_countryCode"
[ "$nmrpSku" = "US" ] && datconf -f /etc/wireless/mediatek/mt7915.dbdc.b1.dat set Channel "153"
## 2022.05.26, PegaBU6, YochengLian, Default 5G channel for PA Sku also be 153. SKU_Consolidation_V0.8_5_2022050.pptx page 10. ##
## 2022.07.21, PegaBU6, YochengLian, Netgear PE urgent requirement to sync PA Sku behavior for US and CA sku and for beta user release. ##
if [ "$nmrpSku" = "PA" ] || [ "$nmrpSku" = "US" ] || [ "$nmrpSku" = "CA" ]
then
    datconf -f /etc/wireless/mediatek/mt7915.dbdc.b1.dat set Channel "153"
    ## 2022.06.09, PegaBU6, YochengLian, Still set the SKUenable and SkuTableIdx for PA Sku implementation.
    datconf -f /etc/wireless/mediatek/mt7915.dbdc.b0.dat set SKUenable "1"
    datconf -f /etc/wireless/mediatek/mt7915.dbdc.b0.dat set SkuTableIdx "1"
    datconf -f /etc/wireless/mediatek/mt7915.dbdc.b1.dat set SKUenable "1"
    datconf -f /etc/wireless/mediatek/mt7915.dbdc.b1.dat set SkuTableIdx "1"
fi
[ "$nmrpSku" = "WW" ] && datconf -f /etc/wireless/mediatek/mt7915.dbdc.b1.dat set Channel "44"
[ -n "$wifi24g_channelRegion" ] && datconf -f /etc/wireless/mediatek/mt7915.dbdc.b0.dat set CountryRegion "$wifi24g_channelRegion"
[ -n "$wifi5g_channelRegion" ] && datconf -f /etc/wireless/mediatek/mt7915.dbdc.b1.dat set CountryRegionABand "$wifi5g_channelRegion"

exit 0
