#!/bin/sh /etc/rc.common

START=99
STOP=90

start() {
	echo "...cat..." > /dev/console
	cat /usr/sbin/hostapd > /dev/null
	echo "...cat done..." > /dev/console
	return 0
}

restart() {
	return 0
}

shutdown() {
	return 0
}

stop() {
	return 0
}

reload() {
	return 0
}
