#!/bin/sh

/etc/init.d/aws default
rm -rf /data/dni/ntp/save_time
rm -rf /data/dni/armor_debug
echo "[`date '+%Y/%m/%d %T'`]factory_default, remove all files" >> /data/dni/armor_debug 
rm -rf /opt/bitdefender/*
cp /etc/wlan/nvram/default_user.nvm /data/.user_nvram.setting
rm -rf /data/dal /tmp/ntgrdata/dal
/sbin/artmtd -w nmrp 1
sync
data_exist=`mount | grep data`
traffic_exist=`ps -w | grep traffic |grep -v 'grep'`
if [ "x$data_exist" != "x" ]; then
	fuser -mk /data/
	killall dal_ash
	umount /data
fi
[ -n "$traffic_exist" ] && killall traffic_meter
sleep 2
/sbin/Nencmgr reset
config default
