#!/bin/sh

. /etc/wlan/wifi_conf

if [ $# -gt 1 ]; then
	echo setting ......
	for ifname in ${main_ifname_list}; do
		eval "echo "wl -i $ifname $@" > /dev/console"
		eval "wl -i $ifname $@ 2>/dev/null"
	done
elif [ $# -gt 0 ]; then
	echo getting ......
	for ifname in ${main_ifname_list}; do
		eval "echo "wl -i $ifname $1" > /dev/console"
		eval "wl -i $ifname $1 2>/dev/null"
		if [ $ifname = wl1 -o $ifname = wl2 ]; then
			echo "####################################################################################"
		fi
	done
else
	for ifname in ${main_ifname_list}; do
		eval "echo "wl -i $ifname status" > /dev/console"
		eval "wl -i $ifname status 2>/dev/null"
		if [ $ifname = wl1 -o $ifname = wl2 ]; then
			echo "####################################################################################"
		fi
	done
fi


