#!/bin/sh

. /lib/upgrade/common.sh

# initialize defaults
RAMFS_COPY_BIN="/bin/busybox \
		/bin/ash \
		/bin/sh \
		/bin/dash \
		/bin/mount \
		/bin/umount \
		/bin/ps \
		/bin/sleep \
		/bin/cat \
		/bin/echo \
		/bin/rm \
		/bin/config \
		/bin/sed \
		/bin/datalib \
		/sbin/reboot \
		/sbin/artmtd \
		/sbin/mtd \
		/sbin/ledcontrol \
		/sbin/led_ring \
		/sbin/ifconfig \
		/sbin/pivot_root \
		/sbin/reboot \
		/usr/bin/killall \
		/usr/bin/head \
		/usr/bin/hexdump \
		/usr/bin/jshn \
		/usr/sbin/part_dev \
		/usr/sbin/nandwrite \
		" # extra programs for temporary ramfs root

RAMFS_COPY_DATA="/usr/share/libubox/jshn.sh \
		/etc/resolv.conf \
		/usr/lib/libcrypt* \
		/lib/libgcc_s* \
		/lib/libc.so* \
		/lib/libdni* \
		/lib/libcommon_utils.so \
		/usr/lib/libuClibc* \
		/lib/ld-* \
		/usr/lib/libiconv* \
		/usr/lib/libdni* \
		/usr/lib/libcfgmtd.so \
		"      # extra data files

mkdir -p /tmp/root

run_ramfs
