#!/bin/sh

SSO_CONTROL_TIME=/tmp/sso_time
config="/bin/config"
sso_time=10
i=0

# Enable DNS Hijack mode
dns_hijack()
{
	killall -SIGUSR1 dnsmasq
	sleep 1
	killall -SIGUSR1 dnsmasq
	/usr/sbin/net-wall restart
}

# Disable DNS Hijack mode
dns_unhijack()
{
	killall -SIGUSR2 dnsmasq
	sleep 1
	killall -SIGUSR2 dnsmasq
	/usr/sbin/net-wall restart
}

if [ -f "$SSO_CONTROL_TIME" ]; then
	sso_time=`cat $SSO_CONTROL_TIME`	
fi

dns_unhijack
while [ "$i" -lt "$sso_time" ]
do
	i=$(( $i + 1 ))
	sleep 60 
done

if [ "$($config get dns_hijack)" = "1" ]; then
	dns_hijack
fi
