#!/bin/sh

/bin/config set radio_number=0x3
/bin/config set ssid_number_per_radio=0x3
module_name=$(cat /module_name)
if [ "${module_name}" = "RAX10" -o "${module_name}" = "RAX10v2" -o "${module_name}" = "R6700AXv2" -o "${module_name}" = "RAX36S" ]; then
	/bin/config set radio_number=0x3
	/bin/config set wl2g_int="wl0"
	/bin/config set wl5g1_int="wl1"
	/bin/config set wl5g2_int="wl2"
	if [ "${module_name}" = "WAX204" ]; then
		/bin/config set ssid_number_per_radio=0x7
	fi
elif [ "${module_name}" = "RAX70" -o "${module_name}" = "RAX78" ]; then
	/bin/config set radio_number=0x7
	/bin/config set wl2g_int="wl1"
	/bin/config set wl5g1_int="wl2"
	/bin/config set wl5g2_int="wl0"
fi

