#!/bin/sh /etc/rc.common

START=99

. /lib/ledpm/ledgeneral_core.sh

start()
{
     ledgeneral_start
     #insmod button-hotplug at the end of the booting,or iw will cause system halted!
     load_modules "$(ls /etc/modules.d/* | grep "button-hotplug")"
     
     #as usb may not detected when boot,do it again here!
     ledcli USB1
     ledcli USB3
     ledcli LEDGNRLED
     ledcli STATUS
}

stop()
{
     ledgeneral_stop
}

restart()
{
     ledgeneral_restart
}

reload()
{
     ledgeneral_reload
}
