#!/bin/sh
# don't change wireless smp_affinity for bcm4906

#local release=$(uname -a)
#local txworkq=$(nvram get txworkq)

#[ "x$DEVNAME" != "x" ] && exit 0

# Fix these hard code
#$(echo "$INTERFACE" | grep -Eq "^eth[6-8]$") || exit 0

#case "$ACTION" in
#	add)
#		[ -e /proc/irq/8/smp_affinity ] && echo 2 > /proc/irq/8/smp_affinity
#		[ -e /proc/irq/9/smp_affinity ] && echo 4 > /proc/irq/9/smp_affinity
#		[ -e /proc/irq/10/smp_affinity ] && echo 8 > /proc/irq/10/smp_affinity	
#	;;
#	remove)
#	;;
#	*)
#	;;
#esac