O 3 HOST_INTERFACE
G 3 1 GLOBAL_GID1
S 3 1 1 201 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: Out of Main Loop
S 3 1 1 2959 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: Genrisc Internal Abort Error
S 3 1 1 2978 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: Bad Interrupt
S 3 1 1 3026 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: HostInterface_ReadInitVector_BufferAddressNotAlignedToDWord
S 3 1 1 3038 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: HostInterface_StaIdEqual192Jira2499
S 3 1 1 3052 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: HostInterface_ReadInitVector_BufferSizeNotAlignedToDWord
S 3 1 1 3066 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: HostInterface_PushToTailError_PD_Buffer_logger_post_dma_activate
S 3 1 1 3082 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: tx_out_no_free_hds_error
S 3 1 1 3092 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: rx_out_no_free_hds_error
S 3 1 1 3106 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: HostInterface_Mailbox_FifoOutFullError
S 3 1 1 3117 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: HostInterface_HdTidError
S 3 1 1 3131 Fatal Error in file: "../Code/Source/hostInterface.c"; Fatal Print: HostInterface_CbmFragmentation_WA_RingFullError
