#!/bin/sh

[ "$DEVICE" == "lo" ] && exit 0

. /lib/functions.sh
. /lib/functions/network.sh
. /lib/iptv/iptv_func.sh
. /lib/iptv/iptv_core.sh

config_get mode "iptv" "mode"
case "$mode" in
	Bridge)
	#Do nothing
	;;
	*)
		local prio_pair=$(uci_get_state iptv core priority)
		local ifname=
		local prio=
		local vid=
		
		for pair in $prio_pair; do
			ifname=${pair%%-*}
			prio=${pair##*-}

			vid=${ifname##*.}
			# set RTL8197H TX priority

			set_8021q_prio $ifname 0 $prio
			set_8021q_prio $ifname 7 $prio
		done
	;;
esac

# As IPTV would change the lan interface name, we need to redo the enable gro
# to keep it work.
[ -e /etc/hotplug.d/block/60-enable_gro ] && /etc/hotplug.d/block/60-enable_gro

