#!/bin/sh

# Keep these, and disable all other services
KEEP_SERVICES="boot boot-ftm qca-nss-dp qca-nss-ecm qca-nss-ppe-ds qca-ssdk ubnt_bootconf ubnt_plugins ubnt_sysinit umount 01_skb_recycler sysctl"

remove_unwanted_services() {
	echo "Disabling unused startup services" > /dev/kmsg
	for service in /etc/init.d/*; do
		service_name=$(basename "$service")
		if ! echo "$KEEP_SERVICES" | grep -qE "(^| )$service_name( |$)"; then
			echo "Removing unused startup service: $service_name" > /dev/kmsg
			find /etc/rc.d/ -type l -regex ".*/[SK][0-9]*$service_name" -exec rm -f {} \;
		fi
	done
}

boot_hook_add preinit_ubnt remove_unwanted_services
