#!/bin/sh

# Copyright (C) 2009 OpenWrt.org

#echo ACTION=$ACTION, DEVPATH=$DEVPATH, SUBSYSTEM=$SUBSYSTEM, BUSNUM=$BUSNUM >/dev/console

#echo "--------------" >>/dev/console
#echo "busnum=$BUSNUM" >> /dev/console
#echo "action=$ACTION" >> /dev/console
#echo "intf=$INTERFACE" >> /dev/console
#echo "devnum=$DEVNUM" >> /dev/console
#echo "dev=$DEVICE" >> /dev/console
#echo "pdt=$PRODUCT" >> /dev/console
#echo "type=$TYPE" >> /dev/console
#echo "--------------" >>/dev/console

if [ "$DEVNUM" = "001" ]
then
    exit 0
fi

if [ "$BUSNUM" != "001" ]
then
    exit 0
fi

USB="USB1"

case "$ACTION" in
	add)
		# update LEDs
        uci set ledctrl.$USB.ledon='1'
        ledcli "$USB"_ON
		;;
	remove)
		# update LEDs
        uci set ledctrl.$USB.ledon='0'
        ledcli "$USB"_OFF
		;;
esac	
