#!/bin/sh /etc/rc.common

START=65
STOP=35

start () {
		local mode=$(uci get sysmode.sysmode.mode)
		if [ "x$mode" != "xrouter" ]; then
			return 0
		fi
	
        export LD_LIBRARY_PATH=/usr/lib/avira:$LD_LIBRARY_PATH
        export PATH=/usr/bin/avira:$PATH
        service_start /usr/bin/avira/avirawatchdog/avirawatchdog
}

stop() {
        service_stop /usr/bin/avira/avirawatchdog/avirawatchdog
}