#!/bin/sh

if [ "$(nvram get rftestflag)" == "1" ]; then
	rmmod wl
	rmmod dhd
	rmmod igs
	rmmod emf
	rmmod hnd

	# kill acsd2, it may change the channel or stop TX.
	# delete pid file of acsd2 at /tmp/dm/ first, or debug_monitor will start acsd2
	acsd_pid=`pgrep acsd2|awk -F " " '{print $1}'`
	rm -rf /tmp/dm/${acsd_pid}
	killall acsd2

	nvram set rftestflag=0
	nvram set btntestflag=0

	nvram unset wl0_vifs
	nvram unset wl1_vifs
	mv /tp_data/radio_bk /tmp/radio_bk_tmp
	wifi start
	hapdsupport -s
	hapdsupport -f
	mv /tmp/radio_bk_tmp /tp_data/radio_bk
	is_rftest_ready=`netstat -anp| grep -E '8888|8889' | grep -v grep | wc -l`
	until [ $is_rftest_ready -eq 2 ]
	do
		sleep 1
		is_rftest_ready=`netstat -anp| grep -E '8888|8889' | grep -v grep | wc -l`
	done
fi
