#!/bin/sh
# Copyright (c) 2016 Shenzhen TP-LINK Technologies Co.Ltd.
# Author		Wang Hao<wanghao@tp-link.com.cn>

cmd=$1
shift

. /lib/functions.sh

SYS_SET_TIME=$(uci_get_state systime core sync)
case $cmd in
    *ACTIVE) 
		#send lock to leds
		if [ $SYS_SET_TIME -eq 1 ]; then
			echo "on" > /tmp/led_nightMode
			ubus send leds '{"action":"4","status":"1"}'
		fi
    ;;

    *DORM)
		#send unlock to leds
		if [ $SYS_SET_TIME -eq 1 ]; then
			echo "off" > /tmp/led_nightMode
			ubus send leds '{"action":"4","status":"0"}'
		fi
    ;;
	
    *RESET) 

	;;
esac

