#!/bin/sh /etc/rc.common

START=12

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start()
{
        service_start /usr/bin/lp5523ctrl &

        #add night mode rule
        /etc/sbin/leds_night_mode &
}

stop()
{
        service_stop /usr/bin/lp5523ctrl
}

