#!/bin/sh /etc/rc.common

START=99
STOP=99

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
    #config_load sysmode
    #config_get sysmode sysmode mode "router"
    #if [ "$sysmode" = "router" ]; then
    #    service_start /usr/sbin/speedtest
    #fi

	return 0
}

stop() {
    #config_load sysmode
    #config_get sysmode sysmode mode "router"
    #if [ "$sysmode" = "router" ]; then
    #    service_stop /usr/sbin/speedtest
    #fi

	return 0
}
