#!/bin/sh /etc/rc.common

START=19

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
        # always reset wan to eth0 for robust, if iptv enabled, /etc/init.d/iptv will change it
        . /lib/iptv/iptv_network.sh
        . /lib/iptv/iptv_core.sh
        set_wan eth0 0

	#hanjiayan modified for AC2200

        . /lib/switch/core.sh

        setup_switch

        # down all ports
        link_down_all_ports
		
        setup_vlan
		
	    setup_agg
}

restart() {
		stop
        start
}

shutdown() {
		echo "Shutdown switch!"
}

stop() {
		. /lib/switch/core.sh
		unsetup_vlan

		unsetup_duplex
		
		unsetup_switch
		
	    unsetup_agg
}

reload() {
        start
}
