#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2016 TP-Link
# Author: Zhu Junjie <zhujunjie@tp-link.net>
# Date: 14Nov16

START=99

start() {
	echo "tm-shn start #######" > /dev/console
    config_load sysmode
    config_get sysmode sysmode mode "router"
	config_load network
	config_get wan_type wan wan_type "dhcp"

    if [ "$sysmode" = "router" ]; then
		if [ "$wan_type" != "v6plus" -a "$wan_type" != "dslite" ];then
        	/usr/bin/tm_shn -b start
		fi
    fi

    return 0
}

stop(){
    config_load sysmode
    config_get sysmode sysmode mode "router"
    if [ "$sysmode" = "router" ]; then
        /usr/bin/tm_shn -t stop
        /usr/bin/tm_shn -b stop
    fi
    return 0
}

reload() {
    config_load sysmode
    config_get sysmode sysmode mode "router"
    if [ "$sysmode" = "router" ]; then
        /usr/bin/tm_shn -p
        /usr/bin/tm_shn -q
    fi
    return 0
}

boot(){
	start
	echo "tm-shn boot #######" > /dev/console
	uci_revert_state "tm_qos"
	uci_set_state "tm_qos" "core" "" "state"
	uci_set_state "tm_qos" "core" "qos_real_up" "0"
}
