#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2016 TP-Link
# Author: Zhu Junjie <zhujunjie@tp-link.net>
# Date: 14Nov16

START=99

local TEMP_UCI_PATH=/tmp/tmp-device-config
local SEC_HIS_UCI_FILE=/tmp/tmp-device-config/security_history

start() {
	if [ ! -f $SEC_HIS_UCI_FILE ]; then
		if [ ! -d $TEMP_UCI_PATH ]; then
			mkdir $TEMP_UCI_PATH
		fi
		cp /etc/config/security_history $TEMP_UCI_PATH
	fi
	

	config_load network
	config_get wan_type wan wan_type "dhcp"	

	if [ "$wan_type" != "v6plus" -a "$wan_type" != "dslite" ];then
		/usr/bin/tm_shn -s
	fi	
	echo "Security config trigger start!"
}

stop(){
	echo "Security config trigger stop!"
}
