#!/bin/sh
#
# Startup script for iBurst UT wireless modem Linux driver -- network module
#   By default, the network devices are ibut0, ibut1 etc.
#
# Use: place this in the directory for startup scripts,
#       typically /etc/rc.d/init.d. For example:
#               cp ibutNet /etc/rc.d/init.d/.
#
# The following are magic configuration comments (do "man chkconfig")
# chkconfig: 2345 97 3
# description: ArrayComm iBurst UT Wireless Modem -- network connectivity

# ibutInstallDir -- where ibut files are
ibutInstallDir=/etc/pcmcia

# Source function library.
#. /etc/rc.d/init.d/functions

# Source ibut definitions and functions
. $ibutInstallDir/ibutConfig


# See how we were called.
case "$1" in
  start)
        #echo -n "Starting ibutNet: "
		ibutNetStart
		echo 92 > /var/run/monitor.fifo
        ;;
  stop)
        #echo -n "Stopping ibutNet: "
        ibutNetStop
        ;;
  status)
        ibutNetStatus
        ;;
  restart|reload)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
