#!/bin/sh /etc/rc.common                                                        

#START=90

start() {                                                                       
        echo "Starting lirc"                                                    
        mkdir -p /var/run/lirc                                                     
        /usr/sbin/lircd -d /dev/lirc1
}

stop() {                                                                        
        echo "Stopping lirc"                                                    
        /bin/kill `pidof lircd`                                                 
        return 0                                                                
}

reload() {
	/bin/kill -SIGHUP `pidof lircd`
}

restart() {
	stop
	start
}
