#!/bin/sh
# Function: Turn off 5g/5g2 DFS CAC

# 5g/5g2 DFS CAC changes status
DFS_CAC_CHANGE_TRUE=1
DFS_CAC_CHANGE_FALSE=0
dfs_cac_change_status=0

# BCM CAC time on:-1 off:0
DFS_CAC_TIME_OFF=0

# Obtain all wl interface
wl_count=$(uci show wireless | awk '/^wireless\.wl[0-9]+=wifi-device/ {count++;print count}')
# If wl interface is 5g/5g2, turn off DFS CAC time
if [ -n "$wl_count" ]; then
    for i in ${wl_count}; do
        ifname=$((i-1))
        ifname_band=$(uci get wireless.wl${ifname}.band)
        # check interface is 5g or 5g2
        if [ ${ifname_band} = "5g" ] || [ ${ifname_band} = "5g_2" ]; then
            # CMD: turn off dfs cac time
            command="wl -i wl${ifname} dfs_preism 0;nvram set wl${ifname}_dfs_preism=0"
            eval $command
            # check whether the dfs cac time has been closed
            if [ $(nvram get wl${ifname}_dfs_preism) -eq ${DFS_CAC_TIME_OFF} ]; then
                echo "Turn off ${ifname_band} DFS success!"
                dfs_cac_change_status=$DFS_CAC_CHANGE_TRUE
            else
                echo "ERROR: Turn off ${ifname_band} DFS fail!"
            fi
        fi
    done
else
    dfs_cac_change_status=$DFS_CAC_CHANGE_FALSE
fi

# If nothing to do, output relevant prompts
if [ ${dfs_cac_change_status} -eq ${DFS_CAC_CHANGE_FALSE} ]; then
    echo "ERROR: Failt to turn off 5g or 5g2 DFS CAC time!"
fi
