#!/bin/sh
# Copyright (c) 2016 Shenzhen TP-LINK Technologies Co.Ltd.
# Author  : Eddie Ho <eddie.ho@tp-link.com>
# Date    : 21 Aug 2016


FACTORY_RESET_PID="/var/run/factory_reset.pid"

[ -e ${FACTORY_RESET_PID} ] && {
        local pid=$(cat ${FACTORY_RESET_PID})
        echo "$0: Kill pid $pid." > /dev/console
        [ -n "$pid" ] && kill -9 $pid
        rm -f ${FACTORY_RESET_PID}
}
echo $$ > $FACTORY_RESET_PID
echo "$0: my pid $$." > /dev/console

sleep 5

echo "$0: reset DUT config......" > /dev/console

ledcli LAN_ON && ledcli RE_ON && ledcli WAN0_ON && ledcli WAN1_ON && ledcli WIFI2G_ON && ledcli WIFI5G_ON && ledcli STATUS_ON && ledcli WPS_ON

if nvrammanager -s | grep -q user-config2; then
        nvrammanager -e -p user-config1 >/dev/null 2>&1;
        nvrammanager -e -p user-config2 >/dev/null 2>&1;
else
        nvrammanager -e -p user-config >/dev/null 2>&1;
fi
if nvrammanager -s | grep -wq certificate; then
	echo "$0: erase certificate" > /dev/console
	nvrammanager -e -p certificate >/dev/null 2>&1;
fi
[ -f /sbin/board_factory ] && board_factory
[ -f /sbin/mcu_reset ] && mcu_reset

killall -9 ledctrl

reboot

