#!/bin/sh
# Copyright(c) Shenzhen TP-LINK Technologies Co.Ltd.
#
# Details : Internet Accessibility Detectiion script.
# Author  : Sharon Lin <sharon.lin@tp-link.com>
# Version : 1.0
# Date    : 20 Apr, 2016

(
    flock -n 9 || exit 0
    /lib/autodetect/internetdetect.sh $@ &
) 9>/var/run/internetdetect.lock
