#!/bin/sh
# Copyright (c) 2016 Shenzhen TP-LINK Technologies Co.Ltd.
# Author  : Sharon Lin <sharon.lin@tp-link.com>
# Date    : 25 Nov 2016


. /lib/functions.sh

local PPTPD_PROT="1723"

usage()
{
	echo "/usr/bin/upnp_conflict_check [type] [protocol] [port] " > /dev/console
	exit
}

check_vpn_config()
{
	echo "#### check_vpn_config $@" > /dev/console
	local ext_proto=$1
	local ext_port=$2
	local pptpd_enabled
	local openvpn_enabled
	local openvpn_port
	local openvpn_proto
	config_load pptpd
	config_get pptpd_enabled pptpd enabled
	config_load openvpn
	config_get openvpn_enabled server enabled
	config_get openvpn_port server port
	config_get openvpn_proto server proto

	# translate to upper case
	openvpn_proto=`echo $openvpn_proto | tr '[a-z]' '[A-Z]'`
	if [ "$pptpd_enabled" == "on" -a "$ext_port" == "$PPTPD_PROT" ]
	then
		echo "PPTPD"
	fi
	if [ "$openvpn_enabled" == "on" -a "$openvpn_proto" == "$ext_proto" -a "$ext_port" == "$openvpn_port" ]
	then
		echo "OPENVPN"
	fi
	return
}

check_rmgmt_config()
{

	local ext_host=$1
	local ext_port=$2
	local enable
	local port
	local ipaddr
	config_load administration
	config_get enable remote enable
	config_get port remote port
	config_get ipaddr remote ipaddr
	if [ "$enable" == "partial" ]
	then
		if [ "$ext_host" == "*" -o "$ext_host" == "$ipaddr" ] && [ "$ext_port" == "$port" ]
		then
			echo "RMGMT"
		fi
	elif [ "$enable" == "all" -a  "$ext_port" == "$port" ]
	then
		echo "RMGMT"
	fi

	return
}

check_vs_config()
{
	local cfg=$1
	local ext_proto=$2
	local ext_port=$3
	local enable
	local protocol
	local external_port
	config_get enable "$cfg" enable
	config_get protocol "$cfg" protocol
	config_get external_port "$cfg" external_port
	if [ "$enable" == "on" ]
	then
		if [ "$protocol" == "ALL" -o "$protocol" == "$ext_proto" ]
		then
			if [ "$external_port" == "$ext_port" ]
			then
				echo "VS"
			fi
		fi
	fi
	return
}


check_pt_config()
{
	local cfg=$1
	local ext_proto=$2
	local ext_port=$3
	local enable
	local protocol
	local external_port
	config_get enable "$cfg" enable
	config_get protocol "$cfg" external_protocol
	config_get external_port "$cfg" external_port
	if [ "$enable" == "on" ]
	then
		if [ "$protocol" == "ALL" -o "$protocol" == "$ext_proto" ]
		then
			if [ "$external_port" == "$ext_port" ]
			then
				echo "PT"
			fi
		fi
	fi
	return
}

check_dmz_config()
{
	local cfg=$1
	local ext_proto=$2
	local ext_port=$3
	local enable
	local protocol
	local external_port
	config_get enable "$cfg" enable
	if [ "$enable" == "on" ]
	then
		echo "DMZ"
	fi
	return
}

check_nat_config()
{
	config_load nat
	config_foreach check_vs_config rule_vs $1 $2
	config_foreach check_pt_config rule_pt $1 $2
	config_foreach check_dmz_config nat_dmz $1 $2
}

upnp_check_config()
{
	local type=$1
	case $type in
		vpn)
			check_vpn_config $2 $3
		;;

		rmgmt)
			check_rmgmt_config  $2 $3
		;;

		nat)
			check_nat_config $2 $3
		;;

		*)
		usage
		;;
	esac
	return
}

upnp_check_config $@


exit
