#!/bin/sh

mount -a
# added by yangcaiyong for sysfs
mount -t sysfs /sys /sys
# ended add

/bin/mkdir -m 0777 -p /var/lock
/bin/mkdir -m 0777 -p /var/log
/bin/mkdir -m 0777 -p /var/run
/bin/mkdir -m 0777 -p /var/tmp
/bin/mkdir -m 0777 -p /var/Wireless/RT2860AP
/bin/mkdir -m 0777 -p /var/tmp/wsc_upnp

/bin/mkdir -m 0777 -p /var/tmp/dropbear
#for the dirs of samba and ntfs-3g, zjj, 20111129
/bin/mkdir -m 0777 -p /var/usbdisk
/bin/mkdir -m 0777 -p /var/dev
/bin/mkdir -m 0777 -p /var/samba/lib
/bin/mkdir -m 0777 -p /var/samba/private
/bin/mkdir -m 0777 -p /var/samba/var/locks
cp -p /etc/passwd.bak /var/passwd
#end by zjj
/bin/mkdir -m 0777 -p /var/l2tp

echo 30 > /proc/sys/net/unix/max_dgram_qlen

echo 1 > /proc/sys/net/ipv4/ip_forward
echo 1 > /proc/sys/net/ipv6/conf/all/forwarding

#krammer add for LAN can't continuous ping to WAN when exchenging the routing mode
#bug1126
echo 3 > /proc/sys/net/netfilter/nf_conntrack_icmp_timeout

echo 0 > /proc/sys/net/ipv4/conf/default/accept_source_route
echo 0 > /proc/sys/net/ipv4/conf/all/accept_source_route

insmod /lib/modules/kmdir/kernel/drivers/scsi/scsi_mod.ko
insmod /lib/modules/kmdir/kernel/drivers/scsi/sd_mod.ko

insmod /lib/modules/kmdir/kernel/drivers/usb/core/usbcore.ko

#for 3g-dongle, add by zjj, 20120521
mount -t usbfs usbfs /proc/bus/usb/

insmod /lib/modules/kmdir/kernel/drivers/usb/host/xhci-hcd.ko
insmod /lib/modules/kmdir/kernel/drivers/usb/host/ehci-hcd.ko
insmod /lib/modules/kmdir/kernel/drivers/usb/host/ohci-hcd.ko
insmod /lib/modules/kmdir/kernel/drivers/usb/storage/usb-storage.ko

insmod /lib/modules/kmdir/kernel/drivers/scsi/scsi_wait_scan.ko
insmod /lib/modules/tfat.ko
insmod /lib/modules/tntfs.ko
insmod /lib/modules/thfsplus.ko
insmod /lib/modules/texfat.ko


#netfilter modules load
insmod /lib/modules/kmdir/kernel/net/netfilter/nf_conntrack_proto_gre.ko
insmod /lib/modules/kmdir/kernel/net/netfilter/nf_conntrack_pptp.ko
insmod /lib/modules/ipt_STAT.ko
insmod /lib/modules/tp_domain.ko

telnetd
cmmsyslogd &

# ETH Driver
#insmod /lib/modules/kmdir/kernel/drivers/net/ctf/ctf.ko
#insmod /lib/modules/kmdir/kernel/drivers/net/et/et.ko

#ifconfig eth0 up
#ifconfig lo 127.0.0.1 netmask 255.0.0.0

#create & up eth0.1 for 6318
#vconfig add eth0 1
#ifconfig eth0.1 up

echo 2097152 > /proc/sys/net/core/rmem_max
echo 133120 > /proc/sys/net/core/rmem_default
echo 2097152 > /proc/sys/net/core/wmem_max
echo 133120 > /proc/sys/net/core/wmem_default
echo 4096 65536 2097152 > /proc/sys/net/ipv4/tcp_rmem
echo 4096 65536 2097152 > /proc/sys/net/ipv4/tcp_wmem
echo 50 > /proc/sys/vm/dirty_ratio

echo 5 > /proc/sys/vm/dirty_background_ratio
echo 50 > /proc/sys/vm/dirty_writeback_centisecs
echo 80 > /proc/sys/vm/swappiness
echo 1000 > /proc/sys/vm/dirty_expire_centisecs
cos &
#rttd &
rftest -n
