#!/bin/sh /etc/rc.common

START=99

boot() {
	start
}

start() {
	mkdir -p /var/ther
	cp -f /etc/conf/ther.conf /var/ther/conf

	killall ther_control
	ther_control &
}

stop() {
	killall ther_control
}
