#!/bin/sh /etc/rc.common
#
# Copyright (c) 2022 TP-LINK Technologies Co., Ltd.
# All Rights Reserved.

START=30
STOP=90
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

wifi_sys_led_flick(){
	hz=2		#flick 2 times per second
	sleeptime=`expr 1000000 / $hz / 2`
	while true
	do
		ledcli WIFI2G_ON
		ledcli WIFI5G_ON
		usleep $sleeptime
		ledcli WIFI2G_OFF
		ledcli WIFI5G_OFF
		usleep $sleeptime
	done
}

start() {
	echo "wireless is starting..." > /dev/console

	local factory_mode

	/sbin/wifi_firm
	/sbin/wifi_check_country
	/sbin/wifi init
	/sbin/wifi reload

	factory_mode=$(uci get factory.factorymode.enable)
	
	# calibration process.
	[ "$(/sbin/is_cal)" = "false" -a "$factory_mode" = "yes" ] && {
		echo "wireless is not calibrated, starting mp.sh..." > /dev/console
		/usr/sbin/mp.sh &
		wifi_sys_led_flick &
	}
	
	touch /tmp/wireless_init_done

	if [ "$factory_mode" != "yes"  ]; then
		[ -f "/usr/bin/meshd" ] && {
			echo "=====>>>>> start meshd" > /dev/console
			killall meshd
			meshd &
		}
	fi

	return 0
}

restart() {
	/sbin/wifi reload
	return 0
}

shutdown() {
	/sbin/wifi down
	return 0
}

stop() {
	/sbin/wifi down
	return 0
}

reload() {
	/sbin/wifi reload
	return 0
}
