#!/bin/sh

local in_lan_status=""
local ou_lan_status=""
local wan_status=""
local in_lan_speed=""
local ou_lan_speed=""
local wan_speed=""
local speeds=""
local wan_duplex=""
local in_lan_duplex=""
local ou_lan_duplex=""
local duplexs=""
local wan_ifname="eth1"
local lan_ifnames=""

append_status()
{
	eval $1=\"\$$1' '$2\"
}

# usage: get_port_speed $var_name $port_speed
get_port_speed()
{
	local var_name=$1
	local port_speed=$2
	local speed
	
	if [ -n "$port_speed" ]
	then
		case $port_speed in
		"2.5G")
			speed="2500"
			;;
		"1G")
			speed="1000"
			;;
		"1000M")
			speed="1000"
			;;
		"100M")
			speed="100"
			;;
		"10M")
			speed="10"
			;;
		*)
			echo "bad port speed: $speed"
			speed="0"
			;;
		esac
		
		append_status "$var_name" "$speed"
	else
		append_status "$var_name" "0"
	fi
}

# usage: get_port_status $var_name $port_status
get_port_status()
{
	local var_name=$1
	local port_status=$2
	
	if [ $port_status -eq 1 ]; then
		append_status "$var_name" "connected"
	else
		append_status "$var_name" "unconnected"
	fi
}

# usage: get_port_duplex $var_name $port_duplex
get_port_duplex()
{
	local var_name=$1
	local port_duplex=$2
	
	if [ -n "$port_duplex" ]
	then
		if [ "$port_duplex" == "FD" ]
		then
			append_status "$var_name" "FULL"
		else
			append_status "$var_name" "HALF"
		fi
	else
		append_status "$var_name" "NONE"
	fi
}

get_lan_status()
{	
	local res=$(sed -n '1p' /proc/driver/phy/phyStatus)
	
	for port in ${res}
	do
		get_port_status "in_lan_status" "$port"
	done
}

get_lan_speed()
{
	local res=$(sed -n '2p' /proc/driver/phy/phyStatus)
	
	for port in ${res}
	do
		get_port_speed "in_lan_speed" "$port"
	done
}

get_lan_duplex()
{
	local res=$(sed -n '3p' /proc/driver/phy/phyStatus)
	
	for port in ${res}
	do
		get_port_duplex "in_lan_duplex" "$port"
	done
}

get_wan_speed()
{
	local var_name="wan_speed"
	local dev_name=$wan_ifname
	
	local speed=$(ethctl $dev_name media-type | grep -i " Up " | egrep -o "[0-9\.]+.")
	if [ -n "$speed" ]
	then
		case $speed in
		"2.5G")
			speed="2500"
			;;
		"1G")
			speed="1000"
			;;
		"1000M")
			speed="1000"
			;;
		"100M")
			speed="100"
			;;
		"10M")
			speed="10"
			;;
		*)
			echo "bad port speed: $speed"
			speed="0"
			;;
		esac
		
		append_status "$var_name" "$speed"
	else
		append_status "$var_name" "0"
	fi
}

get_wan_status()
{
	local var_name="wan_status"
	local dev_name=$wan_ifname
	
	ethctl $dev_name media-type | grep -iq " Up "
	if [ $? -eq 0 ]; then
		append_status "$var_name" "connected"
	else
		append_status "$var_name" "unconnected"
	fi
}

get_wan_duplex()
{
	local var_name="wan_duplex"
	local dev_name=$wan_ifname
	
	local duplex=$(ethctl $dev_name media-type | grep -i " Up " | egrep -io "duplex:.*"| awk '{print $2}')
	if [ -n "$duplex" ]
	then
		if [ "$duplex" == "FD" ]
		then
			append_status "$var_name" "FULL"
		else
			append_status "$var_name" "HALF"
		fi
	else
		append_status "$var_name" "NONE"
	fi
}


case $1 in
	"lan_status")
		get_lan_status
		echo -n $in_lan_status $ou_lan_status 
		;;
	"lan_speed")
		get_lan_speed
		echo -n $in_lan_speed $ou_lan_speed
		;;
	"wan_status")
		get_wan_status 
		echo -n $wan_status
		;;
	"wan_speed")
		get_wan_speed
		echo -n $wan_speed
		;;
	"lan_duplex")
		get_lan_duplex
		echo -n $in_lan_duplex $ou_lan_duplex
		;;
	"wan_duplex")
		get_wan_duplex
		echo -n $wan_duplex
		;;
	"speed")
		get_wan_speed
		get_lan_speed
		echo -n $wan_speed $in_lan_speed $ou_lan_speed
		;;
	"duplex")
		get_wan_duplex
		get_lan_duplex
		echo -n $wan_duplex $in_lan_duplex $ou_lan_duplex
		;;
		*)
		echo "bad choice"
		;;
esac



