#!/bin/sh

#df $1 | tail -n 1 | awk '{print $2" "$4}' > /dev/console
#df $1 | tail -n 1 | awk '{print $2" "$4}'

#echo pwd="$PWD" > /dev/console
#echo reading dfree of path: $1!!! > /dev/console

total=`df $PWD/$1 | tail -n 1 | awk '{print $2}'`
avail=`df $PWD/$1 | tail -n 1 | awk '{print $4}'`

if [ $total -eq 0 -a "$1" = "." ]; then
for i in `ls $PWD`
do
curr=`df $PWD/$i | tail -n 1 | awk '{print $2}'`
total=`expr $total + $curr`
curr=`df $PWD/$i | tail -n 1 | awk '{print $4}'`
avail=`expr $avail + $curr`
done
fi

#echo $total $avail > /dev/console
echo $total $avail
