#!/bin/sh
. /lib/functions.sh

STDOUT="/dev/null"
DEV_NUM="0 2"
VAP_NUM=3

# define for brcm
DEV=wlan
VAP=wl

wifi_firm_info(){
	local mac=""
	local cfgmac=""
	local wps_pin=""
	local ssid=""
	local uuid=""
	local change_flag=""
	for i in $DEV_NUM; do
		cfgmac="`uci get wireless.${DEV}$(($i)).macaddr`"
		if [ "$i" = "0" ]; then
			mac=$(network_get_firm "lan_dec1")
		else
			#5G_MAC = 2G_MAC - 1
			mac=$(network_get_firm "lan_dec2")
		fi
		mac="`echo $mac | tr '[a-f]' '[A-F]'`"
		cfgmac="`echo $cfgmac | tr '[a-f]' '[A-F]'`"
		if [ -z ${cfgmac} ]; then
			uci set wireless.${DEV}$(($i)).macaddr="$mac"
			change_flag="1"
		elif [ "${mac}" != "${cfgmac}" ]; then
			uuid="`uuidgen -t`"
			uci set wireless.${DEV}$(($i)).macaddr="$mac"
			change_flag="1"
		else
			: 
		fi

		if [ -z "$(config_get ${DEV}$(($i)) hwmode)" ]; then
			if [ "$i" = "0" ]; then
				hwmode="bgnax"
			else
				hwmode="anacax_5"
			fi
			uci set wireless.${DEV}$(($i)).hwmode="$hwmode"
			change_flag="1"
		fi

		if [ -z "$(config_get ${DEV}$(($i)) band)" ]; then
			if [ "$i" = "0" ]; then
				band="2g"
			else
				band="5g"
			fi
			uci set wireless.${DEV}$(($i)).band="$band"
			change_flag="1"
		fi

		for j in $(seq $VAP_NUM); do
			#set default pin for vap
			if [ ! -z "$(config_get ${VAP}$(($i))$(($j)) wps_label)" -a \
				-z "$(config_get ${VAP}$(($i))$(($j)) wps_pin)" ]; then
				if [ -z "$wps_pin" ]; then
					wps_pin="$(getfirm PIN)"
				fi
				if [ -z "$wps_pin" ]; then
					wps_pin="12345670"
				fi
				uci set wireless.${VAP}$(($i))$(($j)).wps_pin="${wps_pin}"
				change_flag="1"
			fi

			#set default ssid and security for home network
			local ssid_get
			if [ -z "$(config_get ${VAP}$(($i))$(($j)) guest)" -a \
				"$(config_get ${VAP}$(($i))$(($j)) mode)" = "ap" ]; then
				#if [ -z "$(config_get ${VAP}$(($i))$(($j)) ssid)" ]; then
				config_get ssid_get ${VAP}$(($i))$(($j)) ssid
				if [ -z "${ssid_get}" ]; then
					ssid="$(getfirm SSID)"
					local suffix
					#suffix=$(uci get wireless.${DEV}$(($i)).macaddr|awk -F '-' '{printf $5$6}'|tr 'a-f' 'A-F')
					suffix=$(getfirm MAC|awk -F '-' '{printf $5$6}'|tr 'a-f' 'A-F')
					[ "$band" = "5g" -a "$i" = "2" ] && suffix="${suffix}_${band//g/G}"
					uci set wireless.${VAP}$(($i))$(($j)).ssid="${ssid}_${suffix}"
					change_flag="1"
				fi

				if [ -z "$(config_get ${VAP}$(($i))$(($j)) encryption)" ]; then
					if [ -z "$wps_pin" ]; then
						wps_pin="$(getfirm PIN)"
					fi
					uci set wireless.${VAP}$(($i))$(($j)).encryption="psk"
					uci set wireless.${VAP}$(($i))$(($j)).psk_key="${wps_pin}"
					change_flag="1"
				fi
			fi

			#default security of guest network is none.
			if [ "$(config_get ${VAP}$(($i))$(($j)) guest)" = "on" ]; then
				config_get ssid_get ${VAP}$(($i))$(($j)) ssid
				#if [ -z "$(config_get ${VAP}$(($i))$(($j)) ssid)" ]; then
				if [ -z "${ssid_get}" ]; then
					ssid="$(getfirm SSID)"
					local suffix
					#suffix=$(uci get wireless.${DEV}$(($i)).macaddr|awk -F '-' '{printf $5$6}'|tr 'a-f' 'A-F')
					suffix=$(getfirm MAC|awk -F '-' '{printf $5$6}'|tr 'a-f' 'A-F')
					[ "$band" = "5g" -a "$i" = "2" ] && suffix="${suffix}_${band//g/G}"
					uci set wireless.${VAP}$(($i))$(($j)).ssid="${ssid}_Guest_${suffix}"
					change_flag="1"
				fi
				
				if [ -z "$wps_pin" ]; then
					wps_pin="$(getfirm PIN)"
				fi
				if [ -z "$(config_get ${VAP}$(($i))$(($j)) encryption)" ]; then
					uci set wireless.${VAP}$(($i))$(($j)).encryption="none"
					uci set wireless.${VAP}$(($i))$(($j)).psk_key="${wps_pin}"
					change_flag="1"
				fi
			fi
		done
	done

	if [ -z "$(config_get wps model_name)" ]; then
		local model="$(getfirm MODEL)"
		uci set wireless.wps.model_name="${model}"
		change_flag="1"
	fi

	if [ -z "$(config_get wps wps_uuid)" ]; then
		uuid="`uuidgen -t`"
	fi

	# UUID change with DUT's MAC
	if [ -n "${uuid}" ]; then
		uci set wireless.wps.wps_uuid="${uuid}"
		change_flag="1"
	fi

	if [ -z "$(config_get wps wps_manufacturer)" -o -z "$(config_get wps wps_manufacturer_url)" ]; then
		local firm="$(getfirm FIRM)"
		local website="$(getfirm WEBSITE)"
		uci set wireless.wps.wps_manufacturer="${firm}"
		uci set wireless.wps.wps_manufacturer_url="${website}"
		change_flag="1"
	fi
	if [ "$change_flag" = "1" ]; then
		wifi_commit
	fi
}

config_load wireless
echo "[   wifi_firm]debug label" >/dev/console
wifi_firm_info
