VI:onu_synce_nco_ctrl.vi
IN:"__ARG0":USR:0:PRT:"+onu_synce_nco_ctrl.vi nco_en %d"
IN:"__ARG1":USR:1:PRT:"+onu_synce_nco_ctrl.vi nco_fracn_num %d"
IN:"__ARG2":USR:2:PRT:"+onu_synce_nco_ctrl.vi nco_fracn_den %d"
IN:"__ARG3":USR:3:PRT:"+onu_synce_nco_ctrl.vi nco_comp_val %d"
IN:"__ARG4":USR:4:PRT:"+onu_synce_nco_ctrl.vi nco_sw_hold_val %d"
IN:"__ARG5":USR:5:PRT:"+onu_synce_nco_ctrl.vi nco_update_max %d"
IN:"__ARG6":USR:6:PRT:"+onu_synce_nco_ctrl.vi nco_auto_hold_sel %d"
IN:"__ARG7":USR:7:PRT:"+onu_synce_nco_ctrl.vi nco_auto_hold_inv %d"
