VI:onu_d6s_prbs_status.vi
OUT:"DP_PGC_INSYNCREG":PRN:"PRBS InSync status (PRBS pattern lock): 0x%x"
OUT:"DP_PGC_PCRDERRREG":PRN:"Number of PRBS Bit Errors: %d"
OUT:"DP_PGC_SYNCLOSSREG":PRN:"PRBS LossSync status: 0x%x"
OUT:"DP_PGC_PCRDWORDREG_47_32":PRN:"most-significant 16 bits of the 48-bit word counter: 0x%x"
OUT:"DP_PGC_PCRDWORDREG_31_16":PRN:"middle 16 bits of the 48-bit word counter: 0x%x"
OUT:"DP_PGC_PCRDWORDREG_15_0":PRN:"least-significant 16 bits of the 48-bit word counter: 0x%x"
OUT:"DP_PGC_RO_0_REG":PRN:"16 bit status register (conains InSync & LossSyn): 0x%x"
