#!/bin/sh /etc/rc.common
START=90

# Add $2 to value of symbol $1 as csv 
csv_add() {
 local SEP=""
 local VAL=$(d2 -s "${1}")
 for item in ${VAL//,/ }; do
    [ "${item}" = "${2}" ] && return 0
    SEP="," 
 done
 d2 -c "${1}" "${VAL}${SEP}${2}"
}

upgrade_cfg() {

    XAGENT_ID=$(d2 -s xagentcfg[0].x_agent_id)
    if [ "${XAGENT_ID}empty" == "empty" ]; then

        d2 -c xagentcfg[0].x_agent_id         "$(/opt/lantiq/usr/sbin/readycloud_nvram get x_agent_id)"
        d2 -c xagentcfg[0].x_agent_claim_code "$(/opt/lantiq/usr/sbin/readycloud_nvram get x_agent_claim_code)"
        d2 -c xagentcfg[0].x_agent_registered "$(/opt/lantiq/usr/sbin/readycloud_nvram get x_agent_registered)"
        d2 -c xagentcfg[0].x_agent_claimed    "$(/opt/lantiq/usr/sbin/readycloud_nvram get x_agent_claimed)"

        # Keep the old nvram settings for downgrade to non DAL FW.
        #/opt/lantiq/usr/sbin/readycloud_nvram set x_agent_id=
        #/opt/lantiq/usr/sbin/readycloud_nvram set x_agent_claim_code=
        #/opt/lantiq/usr/sbin/readycloud_nvram set x_agent_registered=
        #/opt/lantiq/usr/sbin/readycloud_nvram set x_agent_claimed=
        #/opt/lantiq/usr/sbin/readycloud_nvram commit
    fi
}

start() {
    #Set x_force_connection, So xAgent can reach xCloud
    d2 -c xagentcfg[0].x_force_connection 1

    # add status handler, if needed
    csv_add xagentcfg[0].x_handler_event_sink /usr/bin/evsinkd2

    # Modify genie soap port from 80 to 5000.
    d2 -c rgeniecfg[0].genie_soap_port 5000 #xagent must uses the "HTTP" protocol and the 5000 port can compatiable to old implement before Secutiry Enhancement plan F implemented.

    SN=`d2 -s general.FSN`
    MODEL=`d2 -s general.DeviceModel`
    /opt/xagent/xagent -w -d --ca_file /opt/xagent/certs/ca-bundle-mega.crt \
            --hardware_id ${SN} --model_id ${MODEL} --agent_keepalive 20,3,20
    
    pidof xcenvsw.sh || (cd /etc/xagent; ./xcenvsw.sh) &  
}

stop() {
    killall xagent
    d2 -c xagentstatus.connected 0
    d2 -c xagentstatus.pid 0
}

boot() {
    [ "`cat /tmp/orbi_type`" = "Satellite" ] && return
    upgrade_cfg
    start
}

restart() {
    stop
    start
}
