#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

. /lib/functions.sh
. /lib/upgrade/nand.sh
. /lib/functions/pega.sh

do_mount_root() {
	pega_preinit_restoredefault
	echo "Before mount_root"
	local rootfs_data_mtdnum=$( find_mtd_index "$DATA_PART" )
	local fixed_data_mtdnum=$( find_mtd_index "$FIXED_PART" )
	#echo "rootfs_data_mtdnum=$rootfs_data_mtdnum, fixed_data_mtdnum=$fixed_data_mtdnum"
	if [ ! "$rootfs_data_mtdnum" -a "$fixed_data_mtdnum" ]; then
		echo "fixed_data mtd partition found!"
		pega_attach_fixed_data
	fi
	echo "Start mount_root"
	mount_root
	boot_run_hook preinit_mount_root
	[ -f /sysupgrade.tgz ] && {
		echo "- config restore -"
		cd /
		tar xzf /sysupgrade.tgz
	}
}

[ "$INITRAMFS" = "1" ] || boot_hook_add preinit_main do_mount_root
