#!/bin/sh

# For Broadcom solution
ifnames="wl1.1 wl0.1"
for ifname in $ifnames; do
    if [ -n "`wl -i $ifname assoclist | grep -i $1 2>/dev/null`"  ]; then
        echo 1
        exit
    fi
done
echo 0

