#!/bin/sh
mount -a
mkdir -p /var/run
cat /etc_ro/motd
nvram_daemon&
system.sh
sleep 1
goahead&

#for telnet debugging
telnetd

#for syslogd
mkdir -p /var/log

# for vpn
mkdir /tmp/ppp
echo > /var/log/wtmp
# for ftp
echo "ip	0	IP" > /etc/protocols
echo "tcp	6	TCP" >> /etc/protocols
echo "udp	17	UDP" >> /etc/protocols
