#!/bin/sh /etc/rc.common
# Copyright (c) 2013 The Linux Foundation. All rights reserved.
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

mtd_name=`cat /proc/mtd | grep "ART" | grep -o "mtd."`

system_config() {
	local cfg="$1"

	local hostname conloglevel timezone

	# config_get hostname "$cfg" hostname 'OpenWrt'
	hostname=$(getfirm HOSTNAME_NO_BLANK) && [ -z "$hostname" ] && hostname="OpenWrt"
	echo "$hostname" > /proc/sys/kernel/hostname

	config_get conloglevel "$cfg" conloglevel
	config_get buffersize "$cfg" buffersize
	[ -z "$conloglevel" -a -z "$buffersize" ] || dmesg ${conloglevel:+-n $conloglevel} ${buffersize:+-s $buffersize}

	config_get timezone "$cfg" timezone 'UTC'
	echo "$timezone" > /tmp/TZ

	config_get zonename "$cfg" zonename
	[ -n "$zonename" ] && [ -f "/usr/share/zoneinfo/$zonename" ] && ln -s "/usr/share/zoneinfo/$zonename" /tmp/localtime

	# apply timezone to kernel
	date -k

	# Start logd
	[ -x /etc/init.d/logd ] && /etc/init.d/logd start

	if [ -x /sbin/klogd ]; then
		config_get klogconloglevel "$cfg" klogconloglevel
		args="${klogconloglevel:+-c $klogconloglevel}"
		service_start /sbin/klogd $args
	fi
}

apply_uci_config() {
	sh -c '. /lib/functions.sh; include /lib/config; uci_apply_defaults'
}

#this for decrease nvrammanger call
set_getfirm_config() {
	# MAC
	nvrammanager -r /tmp/default-mac -p default-mac >/dev/null 2>&1
	# PIN
	nvrammanager -r /tmp/pin -p pin >/dev/null 2>&1
	# MODEL && HOSTNAME_NO_BLANK && HOSTNAME_BLANK && 
	# HOSTNAME_UNDERLINE && FIRM && WEBSITE && HARDVERSION && LANGUAGE && 
	# PRODUCT_ID && SPECIAL_ID && HW_ID && REGION && OEM_ID && COUNTRY
	nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	# DEV_ID
	nvrammanager -r /tmp/deviceId -p device-id > /dev/null 2>&1
	# SOFTVERSION && FW_ID
	nvrammanager -r /tmp/softversion -p soft-version >/dev/null 2>&1
}

#this for US and RU fw co-edition. replace files.
set_coediton_fw() {
    special_id=$(getfirm SPECIAL_ID)
    echo $special_id >/dev/console
    if [ "A$special_id" == "A52550000" ];then
        mv  /lib/switch/core_ru.sh /lib/switch/core.sh
        mv  /lib/qos/core_qos_ru.sh /lib/qos/core_qos.sh
        mv  /www/webpages/pages/userrpm/iptv_ru.html  /www/webpages/pages/userrpm/iptv.html
        mv  /www/webpages/pages/frame/quick-setup_isp_pre_conf.html  /www/webpages/pages/frame/quick-setup.html
        mv  /www/webpages/pages/frame/advanced_ru.html  /www/webpages/pages/frame/advanced.html
        mv  /www/webpages/pages/frame/basic_ru.html  /www/webpages/pages/frame/basic.html
        mv  /usr/lib/lua/luci/controller/admin/iptv_ru.lua  /usr/lib/lua/luci/controller/admin/iptv.lua
    else
        rm  -rf  /lib/switch/core_ru.sh
        rm  -rf  /lib/qos/core_qos_ru.sh
        rm  -rf  /www/webpages/pages/userrpm/iptv_ru.html
        rm  -rf  /www/webpages/pages/frame/quick-setup_isp_pre_conf.html
        rm  -rf  /www/webpages/pages/frame/advanced_ru.html
        rm  -rf  /www/webpages/pages/frame/basic_ru.html
        rm  -rf  /usr/lib/lua/luci/controller/admin/iptv_ru.lua
    fi

    if [ "A$special_id" == "A52550000" -o "A$special_id" == "A42520000" ];then
        mv /lib/firmware/QCA9888/hw.2/boarddata_0_br_ru.bin /lib/firmware/QCA9888/hw.2/boarddata_0.bin
        rm -rf /lib/firmware/QCA9888/hw.2/boarddata_0_kr_hk.bin
        rm -rf /lib/firmware/QCA9888/hw.2/boarddata_0_ca.bin
    elif [ "A$special_id" == "A4B520000" ];then
        mv /lib/firmware/QCA9888/hw.2/boarddata_0_kr_hk.bin /lib/firmware/QCA9888/hw.2/boarddata_0.bin
        rm -rf /lib/firmware/QCA9888/hw.2/boarddata_0_br_ru.bin
        rm -rf /lib/firmware/QCA9888/hw.2/boarddata_0_ca.bin
    elif [ "A$special_id" == "A43410000" ];then
        mv /lib/firmware/QCA9888/hw.2/boarddata_0_ca.bin /lib/firmware/QCA9888/hw.2/boarddata_0.bin
        rm -rf /lib/firmware/QCA9888/hw.2/boarddata_0_br_ru.bin
        rm -rf /lib/firmware/QCA9888/hw.2/boarddata_0_kr_hk.bin
    else
        rm -rf /lib/firmware/QCA9888/hw.2/boarddata_0_br_ru.bin
        rm -rf /lib/firmware/QCA9888/hw.2/boarddata_0_kr_hk.bin
        rm -rf /lib/firmware/QCA9888/hw.2/boarddata_0_ca.bin
    fi

    if [ "A$special_id" == "A4B520000" ];then
		mv /www/webpages/pages/userrpm/dmz_kr.html /www/webpages/pages/userrpm/dmz.html
		mv /www/webpages/pages/userrpm/iptv_kr.html /www/webpages/pages/userrpm/iptv.html
		mv /www/webpages/domain-redirect_kr.html /www/webpages/domain-redirect.html
		mv /www/webpages/error_kr.html /www/webpages/error.html
		mv /www/webpages/themes/green/css/domain-redirect_kr.css /www/webpages/themes/green/css/domain-redirect.css
		mv /lib/nat/nat_dmz_kr.sh /lib/nat/nat_dmz.sh
		mv /lib/nat/nat_init_kr.sh /lib/nat/nat_init.sh
	else
		rm -rf /www/webpages/pages/userrpm/dmz_kr.html
		rm -rf /www/webpages/pages/userrpm/iptv_kr.html
		rm -rf /www/webpages/domain-redirect_kr.html
		rm -rf /www/webpages/error_kr.html
		rm -rf /www/webpages/themes/green/css/domain-redirect_kr.css
		rm -rf /lib/nat/nat_dmz_kr.sh
		rm -rf /lib/nat/nat_init_kr.sh
    fi
}

start() {
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	touch /var/log/wtmp
	touch /var/log/lastlog
	touch /tmp/resolv.conf.auto
	ln -sf /tmp/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && mount -t debugfs debugfs /sys/kernel/debug
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	mod_files=/etc/modules.d/*
	#skip wlan driver modules.
	load_modules `echo $mod_files|sed 's/\/etc\/modules.d\/33-qca-wifi.*-perf//'`	

	# disable ipv6
	[ -e /proc/sys/net/ipv6/conf/all/disable_ipv6 ] && echo 1 >/proc/sys/net/ipv6/conf/all/disable_ipv6
	# allow wifi modules time to settle
	# sleep 1
	[ -c /dev/dk0 ] || mknod /dev/dk0 c 63 0                   
	[ -c /dev/dk1 ] || mknod /dev/dk1 c 63 1

	#[ "$(/sbin/is_cal)" = "true" ] || {
	#	/sbin/wifi default > /tmp/wireless.tmp
	#	[ -s /tmp/wireless.tmp ] && {
	#		cat /tmp/wireless.tmp >> /etc/config/wireless
	#	}
	#	rm -f /tmp/wireless.tmp
	#}
	/sbin/sound detect > /tmp/sound.tmp
	[ -s /tmp/sound.tmp ] && {
		cat /tmp/sound.tmp >> /etc/config/sound
	}
	rm -f /tmp/sound.tmp

	## prepare tmp partition
	#MTDDEV=$(grep rootfs_data /proc/mtd | cut -d ":" -f1)
	#mkdir /tmp/mnt >/dev/console 2>&1
	#mount -t jffs2 $MTDDEV /tmp/mnt >/dev/console 2>&1
	loadprofile >/dev/console 2>&1
	loadconfig >/dev/console 2>&1
	#loadqosdatabase >/dev/console 2>&1
	[ -f /sbin/loadopenvpncert ] && loadopenvpncert >/dev/console 2>&1

	set_getfirm_config
	set_coediton_fw
	apply_uci_config
	config_load system
	config_foreach system_config system

	/sbin/network_firm

	killall -q hotplug2
        [ -x /sbin/hotplug2 ] && /sbin/hotplug2 --override --persistent \
                        --set-rules-file /etc/hotplug2.rules \
                        --set-coldplug-cmd /sbin/udevtrigger \
                        --max-children 1 >/dev/null 2>&1 &

        # create /dev/root if it doesn't exist
        [ -e /dev/root -o -h /dev/root ] || {
                rootdev=$(cat /proc/cmdline | grep -o "root=.* " | cut -d " " -f1 | cut -d "=" -f2)

                [ -n "$rootdev" ] && ln -s "$rootdev" /dev/root
        }
	
	[ -L /dev/caldata ] || ln -s /dev/${mtd_name} /dev/caldata
	if [ "$(/sbin/is_cal)" != "true" ]; then
		ifconfig eth0 up
		ifconfig eth1 up
		brctl addbr br-lan
		brctl addif br-lan eth0
		brctl addif br-lan eth1
		ifconfig br-lan 192.168.0.1 up
		/sbin/switch_link_up
		/etc/init.d/tddp start
		#factory reset button press check!
		#/etc/init.d/factory_settings_reset boot
		sleep 3
		/etc/init.d/art start
		cd /
		sleep 240
    fi  
	
}

stop() {
	service_stop /sbin/klogd
	[ -x /etc/init.d/logd ] && /etc/init.d/logd stop
}
