// In "menu_str", all words come from the left menu 
var menu_str = {
	status:"Status",
	map:"Network Map",
	internet:"Internet",
	qs:"Quick Setup",
	sysmod:"Operation Mode",
	network:"Network",
	wan:"WAN Settings",
	ewan:"EWAN",
	usb3g:"3G/4G Settings",
	group:"Interface Grouping",
    lan: "LAN",
	lan6:"IPv6 LAN Settings",
	macclone:"MAC Clone",
	alg:"ALG",
	dsl:"DSL Settings",
	autopvc:"PVC Auto-detection",
	ipsec:"IPSec VPN",
	iptv:"IPTV",
	dhcp:"DHCP Server",
	dhcpserver:"DHCP Settings",
	dhcpclient:"Clients List",
	addrresrv:"Address Reservation",
	condpool:"Conditional Pool",
	wl:"Wireless",
	wlset:"Wireless Settings",
	wl2g:"Wireless 2.4GHz",
	wlbasic:"Basic Settings",
	wps:"WPS",
	wlsec:"Wireless Security",
	wlsche:"Wireless Schedule",
	wlacl:"MAC Filtering",
	wladv:"Wireless Advanced",
	wlstat:"Wireless Status",
	wl5g:"Wireless 5GHz",
	wlbasic5g:"Basic Settings",
	wlqss5g:"WPS Settings",
	wlsec5g:"Wireless Security",
	wladv5g:"Wireless Advanced",
	wlstat5g:"Wireless Status",
	wlguest:"Guest Network",
    wlguestBasic:"Basic Settings",
	wlguestBasic2G:"Basic Settings 2.4GHz",
	wlguestStats:"Guest Network Status",
	wlguestStats2G:"Guest Status 2.4GHz",
	wlguestBasic5g:"Basic Settings 5GHz",
	wlguestStats5g:"Guest Status 5GHz",
	voip:"VoIP",
	voicetel:"Telephone Numbers",
	voicebook:"Telephone Book",
	voicedev:"Telephony Devices",
	voicelog:"Call Log",
	voicerule:"Call Rules",
    voiceblock: "DND & Call Blocking",
	voicefwd:"Call Forward",
	voiceth:"Call Through",
	voicedect:"DECT",
    voiceapp: "tpPhone",
    usbmail: "USB Voice Mail",
	usb:"USB Settings",
    disk: "Device Settings",
    fold: "Sharing Access",
	usbmanage:"USB Mass Storage",
	usbac:"User Accounts",
	featurecode:"Feature Code Setting",
	samba:"Storage Sharing",
	ftp:"FTP Server",
	dlna:"Media Server",
	printer:"Print Server",
	router:"Route Settings",
	gw:"Default Gateway",
	rt:"Static Route",
	rip:"RIP Settings",
	router6:"IPv6 Route Settings",
	gw6:"IPv6 Default Gateway",
	rt6:"IPv6 Static Route",
	fwd:"NAT Forwarding",
	vs:"Virtual Servers",
	pt:"Port Triggering",
	dmz:"DMZ",
	upnp:"UPnP",
	pc:"Parental Controls",
	fw:"Firewall",
	sec:"Security",
	acc:"Access Control",
	fwrule:"Rule",
	fwlan:"LAN Host",
	fwwan:"WAN Host",
	fwsch:"Schedule",
	ddos:"DDoS",
	ipv6:"IPv6",
	settings:"Settings",
	fw6:"IPv6 Firewall",
	fw6rule:"IPv6 Rule",
	fw6lan:"IPv6 LAN Host",
	fw6wan:"IPv6 WAN Host",
	fw6sch:"IPv6 Schedule",
	tunnel6:"IPv6 Tunnel",
	qos:"Quality of Service",
	qosbasic:"Basic Settings",
	qoslist:"SP/WRR Settings",
	tclist:"Bandwidth Control",
	tc:"Bandwidth Control",
	arp:"IP & MAC Binding",
	arpbind:"Binding Settings",
	arplist:"ARP List",
	ddns:"Dynamic DNS",
	diag:"Diagnostics",
	tools:"System Tools",
	log:"System Log",
	time:"Time Settings",
	mcl:"Manage Control",
	cwmp:"CWMP Settings",
	snmp:"SNMP Settings",
	bnr:"Backup & Restore",
	def:"Factory Defaults",
	softup:"Firmware Upgrade",
	admin:"Administration",
	restart:"Reboot",
	stat:"Statistics",
	phone:"Phone Setup",
	dectbase:"DECT Base Station",
	advroute:"Advanced Routing",
	advset:"Advanced Settings",
	sysConf:"System Parameters",  //added by jy
	vpnserver:"VPN Server",		  //added by ccy
	openvpn:"OpenVPN",
	pptpvpn:"PPTP VPN",
	vpnconn:"VPN Connections",
	language: "Language",
    dhcpclilist: "DHCP Client List",
    telephone: "Phone",
    sSett: "Sharing Settings",
    sAccount: "Sharing Account",
	folder: "Folder Sharing"
};
// In "m_str", most of the words are from the button. Some are used to display the stat or the result. 
var	m_str = {
	action:"Action",
	add: "Add",
	addnew: "Add New",
	del: "Delete",
	detecting: "Detecting",
	view: "View",
	edit: "Edit",
	done: "Done",
	set:"Set",
	scan:"Scan",
	survey:"Survey",
	save: "Save",
	apply:"Apply",
	back: "Back",
	next: "Next",
	help: "Help",
	reload: "Reload",
	refresh: "Refresh",
	reset:"Reset",
	block:"Block",
    bind: "Bind",
	start: "Start",
	end: "End",
	stop: "Stop",
	conn: "Connect",
	disconn: "Disconnect",
	renew: "Renew",
	release: "Release",
	en: "Enable",
	dis: "Disable",
	en24g: "Enable 2.4G Guest Network",
	en5g: "Enable 5G Guest Network",
	disboth: "Disable Guest Network",
	enall: "Enable All",
	disall: "Disable All",
	delall: "Delete All",
	ensel: "Enable Selected",
	dissel: "Disable Selected",
	delsel: "Delete Selected",
	allow: "Allow",
	deny: "Deny",
	finish:"Finish",
	reboot:"Reboot",
	quit: "Quit",
	bound:"Bound",
	unbound:"Unbound",
	unplugged: "Unplugged",
	enabled: "Enabled",
	disabled: "Disabled",
	loaded:"Loaded",
	unloaded:"Unloaded",
	initing: "Initializing",
	obtaining: "Obtaining",
	connected: "Connected",
	connecting: "Connecting",
	disconnected: "Disconnected",
	teleunavail:"Telephone service unavailable. Please check your account settings or register a new number.",
	auto: "Auto",
	unknown: "Unknown",
	none: "None",
	err: "Error",
	warn:"Warning",
	note:"Note",
	notes: "Notes",
	errno: "Error code",
	success: "Success",
	pass:"Pass",
	skip:"Skip",
	fail: "Fail",
	enWlsIptv:"Enable a wireless connection for IPTV",
	remove:"Remove",
	selectall:"Select All",
	unselectall:"Deselect All",
	yes:"Yes",
	no:"No",
	ok:"OK",
	cancel:"Cancel",
	config:"Config",
	bannermodel:"Model No. ",
	unplugged:"Unplugged",
	identifying:"Identifying...",
	identified:"Successfully Identified",
	unreg:"Unregister",
	wephex:"hex digits",
	wepchar:"ASCII chars",
	other:"Other",
	location:"Handset Location",
	syn:"Date and time Synchronization",
	reconfig:"Reconfig",
    retest: "Try again",
	viewserv:"View Existing Applications",
	viewservices:"View Existing Services",
	backup:"Backup",
	restore:"Restore",
	facrestore:"Factory Restore",
	exit:"Exit",
	on:"on",
	off:"off",
	curChannel:"Current Channel",
	waiting: "Waiting...",
	isnull: "--",
	from: "From:",
	to: "To:",
	confirm:"Confirm",
	generate:"Generate",
	exportStr:"Export"
};
// In "c_str", all strings are from the confirm window
var c_str = {
    chgmod: "The changes will not take effect until the router reboots. Are you sure to continue?",
	creboot: "The device will reboot. Are you sure to continue?",
    cdefaults: "All current configurations will be lost once the router is restored. Are you sure to continue?",
	del_con: "Are you sure you would like to delete this interface?",
    save_reboot: "The changes will not take effect until the router reboots. Are you sure to continue?",
    dslcfg_ask: "Clicking Yes will cause a disconnection. Are you sure to continue?",
    lancfg_ask: "Modification of LAN IP address or subnet mask will require you to re-login. Write down the changes if you want to continue. Are you sure to continue?",
	refresh: "The webpage will refresh. Would you like to continue?",
    refresh_dis: "This page will refresh and may cause disconnection. Are you sure to continue?",
    ftp_vs_conflict: "This port conflicts with an existing virtual server. Click Yes to disable the related virtual server entry and continue. Click No to use another port to avoid this conflict.",
    ftp_pt_conflict: "This port conflicts with an existing trigger port. Click Yes to disable the related trigger port entry and continue. Click No to use another port to avoid this conflict.",
    ftp_upnp_conflict: "This port conflicts with the UPnP. Click Yes to delete the related UPnP entry and continue. Click No to use another port to avoid this conflict.",
    ftp_dmz_conflict: "FTP Function conflict with the DMZ Host. Click Yes to disable the DMZ Host and continue.",
    forwarding_ftp_conflict: "The current settings conflict with the Internet access of the USB FTP Server. Please click Yes to disable Internet access of the USB FTP Server and enable the necessary port forwarding requirements.",
    qos_del_queue: "Once the queue is deleted, all the classifications related to this queue will be deleted. Are you sure to delete this queue?",
    usb3g_del_all: "Are you sure you would like to delete all USB modem configuration files?",
    voice_dialplan: "Dial Plan can only be added when there is an existing account. Would you like to add an account?",
    lan_reboot: "Modification of LAN IP address or subnet mask will take effect after rebooting. Are you sure to reboot now?",
    del_conflict_conns: "Are you sure to delete the conflicted connections?",
    del_choosed: "Are you sure to delete the selected items?",
	block_client_black:"Are you sure to add your using device to black list.",
	block_client_white:"Are you sure to delete your using device from white list.",
	block_client_parentCtrl:"Are you sure to add your using device to client list under control.",
	logout:"Are you sure to logout?",
	del_tunnels:"Are you sure to delete these tunnels?",
    voice_del_con: "Are you sure to delete this entry?",
	voice_del_allcon: "Are you sure you would like to delete all entries?",
	wlan_unencrypted: "Wireless network isn't encrypted. Are you sure you want to continue?",
    groupDSLSysMode: "Note: You cannot disable VLAN when IPTV is enabled.",
    groupETHSysMode: "Note: VLAN cannot be disabled in Wireless Router mode.",
    saveAndReconn: "Wireless settings are changed successfully. Please reconnect to the router using the new wireless settings.",
	ovpnNoCertSave: "No certficate currently, click OK to generate one and save your configuration.",
	ovpnDDNSNotEnWanConn: "Dynamic DNS is not configured. If you continue, you may need to update the file when WAN IP changes. We strongly recommend that you configure Dynamic DNS or assign a static IP for WAN port first.",
	ovpnDDNSDisconnWanConn: "Dynamic DNS is disconnected. If you continue, you may need to update the file when WAN IP changes. We strongly recommend that you connect Dynamic DNS or assign a static IP for WAN port first."    
};
// In "s_str", strings are complex. Most of them appear more than once. Some form long button. Some used by Javascript. 
var s_str = {
	l2tp: "L2TP",
 	pptp: "PPTP",
	index:"Index",
	status:"Status",
	desc:"Description",
	internet:"Internet",
    conntype: "Internet Connection Type:",
	ipmask:"IP/Mask",
	bridge:"Bridge",
	dynip:"Dynamic IP",
	staip:"Static IP",
    pppoe: "PPPoE",
    pppoa: "PPPoA",
    ipoa: "IPoA",
	macaddr:"MAC Address:",
	ipaddr:"IP Address:",
	netmask:"Subnet Mask:",
	gateway:"Gateway:",
	defgw:"Default Gateway:",
	dns:"Primary DNS:",
	secdns:"Secondary DNS:",
	dnsServers:"DNS Servers:",
	group:"Group:",
	intf:"Interface",
	port: "Port",
	proto:"Protocol:",
	operation:"Operation",
	atm:"ATM Configuration",
    encapmod: "Encapsulation Mode:",
    atmqos: "ATM QoS Type:",
	fps:" frames/s",		
	pps:"packets/second",
    optional: "(optional)",
	recom:"(Recommended)",
	service:"WAN Service Setup",
	username:"Username:",
	passwd:"Password:",
	pppusr:"Username:",
	ppppwd:"Password:",
    pppoeusr: "PPPoE Username:",
    pppoepwd: "PPPoE Password:",
    pppoausr: "PPPoA Username:",
    pppoapwd: "PPPoA Password:",
    cfmpwd: "Confirm Password:",
    unicast: "Get IP using Unicast DHCP:",
    noreq: "(It is usually not required.)",
	srvname:"Service Name:",
	acname:"Server Name:",
	midle:"Max Idle Time:",
	minutes:"minutes",
	seconds:"seconds",
	pkts:"Packets",
	bytes:"bytes.",
    mtuSize: "MTU Size(in bytes):",
    zmean: "(0 means that connection is always on.)",
	connmode:"Connection Mode:",
	typedemand:"Connect on demand",
	typeauto:"Always on",
	typemanual:"Connect manually",
	authtype:"Authentication Type:",
	cur_con: "Current Connection",		
	ennat:"NAT:",
    enfullcone: "Full-cone NAT:",
	enspi:"SPI Firewall:",
	enigmp:"IGMP Proxy:",
    mtu1480: "1480 by default",
    mtu1500: "1500 by default",
    mtu1460: "1460 by default",
    mtu1420: "1420 by default",
    nochg: "do not change unless necessary",
    nochg2: "Do not change unless necessary.",
    dnsmanual: "Use the following DNS Addresses:",
	hostname:"Host Name:",
	echo:"Echo Request Interval:",
    echoinfo: "seconds. (0-120. The default value is 30.)",
    useispaddr: "Use the IP specified by ISP:",
	ispaddr:"ISP specified IP Address:",
	option:"Option",
	resume_mac:"Restore Factory MAC",
	rebooting:"Rebooting",
	uploading:"Uploading",
	upgrading:"Upgrading",
    wait_reboot: "The device is rebooting. Please wait...",
    wait_upload: "Uploading, please wait...",
    wait_restore: "Please wait, configurations will take effect after the device reboots...",
    wait_upgrade: "The device is rebooting. Please wait...",
		generating: "Generating",
		exporting: "Exporting",
		wait_generate: "Generating certificate. It may take a few minutes, please wait.",
		wait_generate_note: "Keep the device powered on, or you need to generate the certificate again.",
	wireless:"Wireless",
	wl:"Wireless Settings",
    modeghz24: "2.4GHz",
    modeghz5_1: "5GHz-1",
    modeghz5_2: "5GHz-2",
    ghz24: "2.4GHz Wireless Network:",
    ghz5: "5GHz Wireless Network:",
	ghz5_1: "5GHz-1 Wireless Network:",
	ghz5_2: "5GHz-2 Wireless Network:",
	wl2g:"2.4GHz Wireless",
	wl5g_2:"5GHz-2 Wireless",
	wl5g_1:"5GHz-1 Wireless",
	wlradio:"Wireless Radio:",
    wlradioen: "Enable",
	wlname:"Wireless Network Name (SSID):",
    gnssid: "Guest Network SSID:",
	ssid:"(Also called SSID)",
	hidessid:"Hide SSID",
	permanent: "Permanent",
	region:"Region:",
	timezone:"Time Zone:",
	wl11b:"11b only",
	wl11bg:"11bg mixed",
	wl11g:"11g only",
	wl11n:"11n only",
	wl11bgn:"11bgn mixed",
	wl11a:"11a only",
	wl11an:"11an mixed",
	wl11ac:"11a/n/ac mixed",
	channel: "Channel:",
	mode:"Mode:",
	chnwidth:"Channel Width:",
	encryption:"Encryption:",
	security:"Security",
	wlsec:"Security:",
    wldissec: "None",
	wlsecpersonalrec:"WPA/WPA2 Personal(Recommended)",
	wlsecpersonal:"WPA/WPA2 Personal",
	wlsecenterprise:"WPA/WPA2 Enterprise",
	encrypted:"Encrypted",
	version:"Version:",
	auto:"Auto",
	wpa:"WPA-PSK",
	wpa2:"WPA2-PSK",
	wpanopsk: "WPA",
    wpa2nopsk: "WPA2",
	opensys:"Open System",
    bit64: "64-Bit",
    bit128: "128-Bit",
	sharekey:"Shared Key",
	key:"Key",
    wepkey1: "Key 1",
    wepkey2: "Key 2",
    wepkey3: "Key 3",
    wepkey4: "Key 4",
	keytype:"Key Type:",
	keyvalue:"Key Value:",
	weptype:"WEP Key Format: ",
	wepkeyindex:"Key Index:",
	hex:"Hexadecimal",
	wlpwd:"Password:",
    pskpwdwarn: "(Enter 8 to 63 ASCII characters or 8 to 64 Hexadecimal digits.)",
	qss_ok:"Device has been added successfully!",
	qss_fail:"Failed to add the device!",
	associated:"Associated",
	faccess:"Full-Access",
	ronly:"Read-Only",
	naccess:"No-Access",
	standby:"Standby",
	online:"Online",
	offline:"Offline",
	active1:"Active",
	inactive:"Inactive",
	not_vailable:"Not Available",
	newfld:"Add New Folder",
	browse:"Browse",
	hide:"Hide",
	disk:"Disk",
	activate:"Activate",
	deactivate:"Deactivate",
	label:"Label",
	volume:"Volume",
	filesys:"File System",
	capacity:"Capacity",
	freespace:"Free Space",
	both:"Both",
	active:"Active",
	passive:"Passive",
	all:"ALL",
	any_host:"Any Host",
	any_time:"Any Time",
	time:"Time",
    sun: "Sun",
    mon: "Mon",
    tues: "Tue",
    wed: "Wed",
    thur: "Thu",
    fri: "Fri",
    sat: "Sat",
	last:"Last",
	list_blank:"Current list is blank",
	max:"Max",
	min:"Min",
	reset_all:"Reset All",
	getgmt: "Getting GMT...",
	getGmt2:"Get GMT",
	getPcTime:"Get from PC",
	gmtfail: "Failed to get GMT",		
	scheduleTip:"The Effective Time is based on the time of the router. The time can be set in \"Advanced > System Tools > Time Settings\"",
/*add for led night mode*/
	nightMode:"Night Mode:",
	nightTime:"Period of Night Time:",
	nightTimeTip:"Note: The time is based on the router's time, which can be set in \"System Tools > Time Settings\"",
	enableLedNMTip:"Note: To enable or disable the night mode, please turn on the LED switch first.",
/*end add*/
	timeSet:" Time Settings",		
	wrong_domain:"Invalid Domain",
	auth_fail:"Authentication Failed",
	standard_user:"Standard User",
	advanced_user:"Advanced User",
    diag_end: "Diagnostics completed",
    diag_pause: "Diagnostics paused",
	diag_dsl:"Test xDSL Synchronization",
    diag_eth: "Please check if the LAN or WAN port is properly connected.",
	diag_wan:"Test WAN Connection",
	diag_ppp:"Test PPP Server connection",
	diag_auth:"Test authentication with ISP",
	diag_ip:"Test assigned IP address",
	diag_dhcp:"Test DHCP Server's connection",
	diag_gw:"Ping default gateway",
	diag_dns:"Ping primary Domain Name Server",
	diag_root:"Test DNS Root",
	diag_ncsi:"Network Connection Status Inspect(NCSI)",
	diag_surf:"Test Internet Browsing",
	no_internet:"Not find Internet joins in",
    no_wan: "Please configure the WAN interface.",
	emerg:"Emergency",
	alert:"Alert",
	crit:"Critical",
	notice:"Notice",
	info:"Information",
	debug:"Debug",
	enable:"Enable",
	ip4en:"Enable IPv4",
	ip6en:"Enable IPv6",
	ip6addr:"IPv6 Address:",
	plen:"Prefix Length:",
    ip6gw: "IPv6 Gateway:",
    ip6dns: "IPv6 DNS Server:",
    ip6secdns: "Secondary IPv6 DNS Server:",
    ip6defgw: "IPv6 Gateway:",
    ip6dnsmanual: "Use the following IPv6 DNS Address:",
	ip6useispaddr:"Use IPv6 specified by ISP:",
	ip6ispaddr:"ISP specified IPv6 Address:",
	ip6ispgw:"ISP specified IPv6 Gateway:",
    ip6unicast: "Get IPv6 Address using Unicast DHCP:",
	ip6addrconf:"Addressing Type:",
    enmld: "MLD Proxy:",
	staip6:"Static IPv6",
	dynip6:"Dynamic IPv6",
    wanconn: "WAN Connection:",
	useLoginAccount:"Use Web Login Account",
	en3gbackup:"Enable 3G/4G as a backup solution for Internet access",
	loc3g:"Location",
	isp3g:"Mobile ISP",
	opmod:"Operation Mode",
    muanl_3g_apn: "Set Dial Number, APN, Username and Password manually",
	dialnum3g:"Dial Number",
	disconnecting:"Disconnecting",
	secondConn:"Secondary Connection:",
	srvIpName:"VPN Server IP/Domain Name",
	addrMode:"DNS Address Mode",
	enSsidBrc:"Enable SSID Broadcast",
    host: "Host:",
	wlScheCtl:"(schedule control)",
	wlUsrCtl:"(user control)",
	enalgo:"Encryption Algorithm:",
	intealgo:"Integrity Algorithm:",
	locale:"Locale Selection:",
	telephonyprovider:"Telephony Provider:",
	prefix:"Prefix",
	number:"Number",
	phonenumber:"Phone Number:",
	voipnumber:"VoIP number:",
	voippassword:"VoIP password:",	
	intertelnumber:"Internet telephone number:",
	voipusername:"User name:",
	sipusername:"SIP user name:",
	contractpassword:"Contract password",
	dscnumber:"Number:",
	dscpassword:"Password:",
	sippassword:"SIP Password:",
	sipname:"SIP Name:",
	dusnetnumber:"DUS.net number:",
	sipline:"Auth ID:",
	registrar:"Registrar Address:",
	proxyserver:"Proxy server:",
	areacode:"Area code",
	telephoneno:"Telephone no:",
    sipid:"SIP ID:",
	telenumber:"Telephone number:",
	emailaddress:"E-mail address:",
	prof:"Profile Name",
	phone:"Phone Number/User ID",
	registraraddr:"Registrar Address:",
	registrarport:"Registrar Port:",
	auid:"Authentication ID",
	password:"Password",
	sipproxy:"SIP Proxy:",
	sipproxyport:"SIP Proxy Port:",
	outboundproxy:"Outbound Proxy:",
	outboundproxyport:"Outbound Proxy Port:",
	label1:"Register via Outbound Proxy",
	siplist:"SIP Account List",
	sipaccount:"Voice - SIP Account",
	blacklistconf:"Black List-Configuration",
    enterinfo: "Enter a number with 3 to 16 digits in length.",
	regdect:"Register New DECT Handset",
	dialplan:"Dial Plan",
	dest:"Destination",
	maxchar:"(16 character max.)",
	none:"None",
	operate:"Operate",
	phone1:"Phone 1",
	phone2:"Phone 2",
	pstn:"PSTN",
	num:"number",
	whitelist:"White List-Configuration",
	blacklist:"Blacklist",
	white:"Whitelist",
	title2:"Max of 30 entries can be configured.",
	id:"ID",
	calllog:"Call Log",
	src:"Source",
	dst:"Destination",
	type:"Type:",
	process:"Process",
	calllogconf:"Call Log Configuration",
    usbmass: "The USB storage device is disconnected.",
    noConfig: "No properly formatted files were found within the USB storage device.",
	uncond:"unconditionally",
	usbmailnote:"Please note that your previous setting of",
	usbmailend:"in phone setup page has been disabled since you have enabled USB VoiceMail triggering",
	usbmailendon:"in phone setup page has been disabled since you have enabled USB VoiceMail triggering on",
	nocondend:"no answer/unconditionally",
	callfirewall:"Call Firewall",
	emergencycall:"Emergency Call Settings(PSTN).",
	forbiddencall:"Forbidden Call",
	endwith:"End With '#'",
	forwardun:"Forward Unconditionally:",
	noanswer:"no answer",
	linenote:"in USB VoiceMail page has been disabled since you have enabled forwarding on",
	speeddial:"Speed Dial",
	usbvoicemail:"USB Voice Mail",
	voiplan:"LAN",
	voipwan:"Any_WAN",
	voiproute:"IP_Routed",
	voipbridge:"IP_Bridged",
	feature:"Feature Code",
	dslmode:"DSL Modulation Type:",
	destADSL:"VPI/VCI",
	destVDSL:"VPI/VCI or VID",
	noAvaiIntf:"No available interface",
	phonesetup:"Phone Setup",
	dectbase:"Handset Register",
	phoneedit:"Phone Edit",
	city1:"(GMT-12:00) Enewetak, Kwajalein",
	city2:"(GMT-11:00) Midway Island, Samoa",
	city3:"(GMT-10:00) Hawaii",
	city4:"(GMT-09:00) Alaska",
	city5:"(GMT-08:00) Pacific Time (US & Canada); Tijuana",
	city6:"(GMT-07:00) Mountain Time (US & Canada); Arizona",
	city7:"(GMT-06:00) Central Time (US & Canada); Central America, Mexico City",
	city8:"(GMT-05:00) Eastern Time (US & Canada); Bogota, Lima",
	city9:"(GMT-04:30) Caracas",
	city10:"(GMT-04:00) Atlantic Time (Canada); Santiago, Asuncion",
	city11:"(GMT-03:30) Newfoundland",
	city12:"(GMT-03:00) Brasilia, Buenos Aires, Georgetown, Greenland",
	city13:"(GMT-02:00) Mid-Atlantic",
	city14:"(GMT-01:00) Azores, Cape Verde Is.",
	city15:"(GMT) Greenwich Mean Time: Dublin, Edinburgh, London, Lisbon",
	city16:"(GMT+01:00) Amsterdam, Berlin, Rome, Stockholm, Paris, Prague, Bratislava",
	city17:"(GMT+02:00) Cairo, Athens, Istanbul, Minsk, Jerusalem, Kiev, Chisinau",
	city18:"(GMT+03:00) Baghdad, Kuwait, Moscow, Riyadh",
	city19:"(GMT+03:30) Tehran",
	city20:"(GMT+04:00) Abu Dhabi, Muscat, Baku, Tbilisi, Yerevan, St.Petersburg",
	city21:"(GMT+04:30) Kabul",
	city22:"(GMT+05:00) Islamabad, Karachi, Tashkent",
	city23:"(GMT+05:30) Madras, Kolkata, Mumbai, New Delhi",
	city24:"(GMT+05:45) Katmandu",
	city25:"(GMT+06:00) Almaty, Astana, Dhaka, Ekaterinburg, Bishkek",
	city26:"(GMT+06:30) Rangoon",
	city27:"(GMT+07:00) Bangkok, Jakarta, Hanoi, Novosibirsk",
	city28:"(GMT+08:00) Beijing, Chongqing, Urumchi, Hong Kong, Taipei, Kuala Lumpur, Perth",
	city29:"(GMT+09:00) Tokyo, Osaka, Sapporo, Seoul",
	city30:"(GMT+09:30) Darwin, Adelaide",
	city31:"(GMT+10:00) Brisbane, Guam, Canberra, Melbourne, Sydney, Yakutsk",
	city32:"(GMT+11:00) Magadan, Solomon Is., New Caledonia",
	city33:"(GMT+12:00) Fuji, Kamchatka Peninsula, Marshall Is., Wellington",
	city34:"(GMT+13:00) Nukualofa",
    dslSyncFail: "Please check if your phone cable is properly connected.",
    ethNoLink: "Please check if the LAN or WAN port is properly connected.",
    adslPppTimeout: "Check the DSL settings such as VPI/VCI and encapsulation mode. Contact your Internet service provider to confirm if your line is in good condition.",
    vdslPppTimeout: "Check the DSL settings such as VLAN ID. Contact your Internet service provider to confirm if your line is in good condition.",
    ethPppTimeout: "Please check the line quality with your Internet service provider.",
    pppAuthFail: "Check your Internet Username & Password. Confirm with your Internet service provider if needed.",
    pppOtherFail: "PPP connection failed. Please contact your Internet service provider to confirm if your line is in good condition. If the problem still exists, please contact TP-LINK technical support for further help.",
    dnsDiagFail: "Please configure your DNS manually.",
	diagOtherFail:"Please reconfigure your parameters. If the problem still exists, please contact your ISP.",
    usb3gUnplugged: "Please confirm that your SIM card has been inserted into the modem correctly.",
    usb3gAuthFail: "Please check APN, dial number, username and password with your Internet service provider. Enter them manually and try again.",
    usb3gOtherFail: "Check whether your USB modem is in our 3G/4G compatibility list of your region. If it is, please feel free to contact TP-LINK technical support. If it isn’t, we're sorry that your modem isn't compatible with our router.",
	connid:"Connection ID:",
	onlineno:"T-Online Number:",
	usersuf:"User Suffix:",
	reconset:"Auto disconnect and reconnect at(HH:MM)",
	qs:"Quick Setup",
	basic:"Basic",
	adv:"Advanced",
	login:"Login",
    login2: "Log in",
	logout:"Logout",
    logout2: "Logout",
	reboot:"Reboot",
	sup:"Support",
	faq:"FAQ",
	swver:"Firmware Version:",
	hwver:"Hardware Version:",
	low:"Low",
	middle:"Middle",
	high:"High",
    vpi: "VPI:",
    vci: "VCI:",
    vlan: "VLAN ID:",
    vlanrange: "VLAN ID (1-4094):",
	envlan:"Enable VLAN ID",
	intfname:"Interface Name:",
	servname:"Service Name:",
	exterport:"External Port:",
	interip:"Internal IP:",
	interport:"Internal Port:",
	close:"Close",
    choose: "Choose",
	nointf:"No interface",
	enthisentry:"Enable this Entry ",
	app:"Application: ",
	on:"On",
	off:"Off",
	multimode:"Multimode",
	clickhide:"Click to hide.",
	kbps: "kbps",
    range: "range",
    len: "length",
    phonenum: "Phone Number",
    nightModeNote:"note:To enable or disable the night mode, please turn on the led switch first",
    pcr: "PCR:",
    scr: "SCR:",
    mbs: "MBS:",
    getauto: "Get Dynamically from ISP",
    wlsecwep: "WEP",
    ascii: "ASCII",
    fSharing: "File Sharing",
    tap2g: "2.4GHz",
    tap5g: "5GHz",
    saved: "Saved.",
    loading: "Loading..."
};
// In "s_str", strings are from each WEB page. Most of them are used only once in all pages.
var n_str = {
	status:{
		c_macaddr:"MAC Address:",
		c_ipaddr:"IP Address:",
		c_netmask:"Subnet Mask:",
		c_defgw:"Default Gateway:",
		c_primdns:"Primary DNS:",
		c_secdns:"Secondary DNS:",
		c_conntype:"Connection Type:",
        c_netname: "Network SSID:",
        c_guest_netname: "Guest Network SSID:",
		c_wlradio:"Wireless Radio:",
		c_chnwidth:"Channel Width:",
		c_channel:"Channel:",
		c_mode:"Mode:",
		c_dhcp:"DHCP:",
		c_plen:"Prefix Length:",
		c_assigntype:"Assigned Type:",
		c_hidessid:"Hide SSID:",
		c_seeeach:"See each other:",
		c_wlguest:"Guest Network",
		c_wireless:"Wireless",
		c_lan:"LAN",
		c_name:"Name:",
		t_devinfo:"Device Information",
		t_swver:"Firmware Version:",
		t_hwver:"Hardware Version:",
		t_uptime:"System Up Time:",
		t_dsl:"DSL",
		t_link:"Line Status:",
		t_dslmode:"DSL Modulation Type:",
		t_annex:"Annex Type:",
		t_up:"Upstream",
		t_down:"Downstream",
		t_currate:"Current Rate(kbps)",
		t_maxrate:"Max Rate(kbps)",
		t_snr:"SNR Margin(dB)",
		t_att:"Line Attenuation(dB)",
		t_errs:"Errors(pkts)",
		t_title:"Name",
		t_tx1:"Max Tx Rate:",
		t_wlwds:"WDS Status:",
		t_wlSchedu:"Schedule:",
		t_tx2:"Max Tx Rate",
		t_ip6title:"Name",
		t_ip6addrplen:"IPv6 Address/Prefix Length",
		t_lan6cfgtype:"Autoconfiguration Type",
		t_voice:"Voice"
	},
    networkMap:{
		c_router:"Router",
		c_wlclient:"Wireless Clients",
		c_wireclient:"Wired Clients",
		c_phone:"Phone",
		c_dect:"DECT",
		c_printer:"Printer",
		c_usbdisk:"USB Disk",
		c_macaddr:"MAC Address:",
        c_netaddr: "IP Address:",
		c_conntype:"Connection Type:",
		c_gateway:"Gateway:",
		t_netstatus:"Internet Status:",
		t_telestatus:"Telephone Status:",
		c_secconn:"Secondary Connection:",
		c_ipaddr:"IP Address:",
		c_ssid:"SSID:",
		c_channel:"Channel:",
		c_mac:"MAC:",
		c_guest2g:"2.4GHz Guest Network",
		c_guest5g:"5GHz Guest Network",
		c_guest5g_1:"5GHz-1 Guest Network",
		c_guest5g_2:"5GHz-2 Guest Network",
		c_status:"Status:",
		c_name:"Name:",
		c_brand:"Brand:",
		c_total:"Total:",
		c_avil:"Available:",
        c_dns: "DNS Server:",
        t_noprint: "No Printer",
        t_nousb: "No Device",
        t_access: "Online Devices",
        t_wireless_h: "Wireless Clients (Host Network)",
        t_wireless_g: "Wireless Clients (Guest Network)",
        t_usbdev: "USB Devices"
    },
	sysMode:{
		et:"Operation Mode",
        t_mode: "Please select an operation mode:",
		t_sysmod1:"DSL Modem Router Mode",
		t_sysmod2:"3G/4G Router Mode",
		t_sysmod3:"Wireless Router Mode"
	},
	wanBasic: {
		et1:"Internet Connection Setup",
		et2:"Internet",
        xDslTipTextVDSL: "Note: The router now is working on VDSL mode. To use ADSL connection as your default Internet connection, go to Advanced > Network > DSL Settings > DSL Modulation Type to change it into ADSL mode.",
        xDslTipTextADSL: "Note: The router now is working on ADSL mode. To use VDSL connection as your default Internet connection, go to Advanced > Network > DSL Settings > DSL Modulation Type to change it into VDSL mode.",
		t_ispList:"ISP List",
		t_secondConn:"Secondary Connection:",
		t_netstatus:"Internet Status:",
		t_detecting:"Detecting"
	},
    wan: {
		et:"WAN Interface",
		et1:"Internet Connection Setup",
		et2:"MAC Clone",
		t_info:"This page shows the information of the entire DSL WAN interface.",
		t_name:"Name",
		t_type:"Type",
		t_autoPvc:"Enable PVC Auto-detection",
        t_note1: "Note: The above parameters has several connections, and it will prohibit any modifications of the following parameters.",
        t_note2: "Note: Do not change the parameters below unless necessary!",
		t_speDial:"Special Dial:",
		t_defMac:"Use Default MAC Address",
		t_computerMac:"Use Current Computer MAC Address",
		t_customMac:"Use Custom MAC Address"
	},
	ethWan:{
		et:"WAN Interface",		
		t_en:"Enable EWAN connection",
		t_addrType:"Addressing Type:",
		t_secondConn:"Secondary Connection:",
        t_dualaccess: "(For Dual Access)",
        t_pppoe: "PPPoE",
        t_dnsaddr: "DNS Address",
        t_autoauth: "Auto",
        t_pap: "PAP",
        t_chap: "CHAP",
        t_mschap: "MS-CHAP",
        t_mtu: "MTU Size:",
        t_mtu1500: "(The default is 1500. Do not change unless necessary.)",
        t_nat: "NAT",
        t_fnat: "Full-cone NAT",
        t_firewall: "SPI Firewall",
        t_igmp: "IGMP Proxy",
        t_defecho: "(0-120. The default is 30.)",
        t_notclone: "Do not Clone MAC Address",
        t_clonecus: "Use Custom MAC Address"
	},
	basic3g:{
		t_sett:"3G/4G Settings",
        t_3g_info: "Note: 3G or 4G access is unavailable in the current operation mode. Please enable 3G/4G backup or change the operation mode to 3G/4G Router mode.",
        t_3g_modem: "3G/4G USB Modem:",
		card_name_unplugged:"Unplugged",
        card_name_ing: "Detecting...",
        card_name_ok: "Detected successfully.",
		t_pin_status:"PIN Status",
        pin_status_fail: "Unable to unlock SIM card.",
		pin_status_ready:"Ready",
        pin_status_pin: "SIM Locked",
        pin_status_puk: "PIN Locked",
        pin_status_errror: "Unknown Error",
		t_connStat:"Connection Status:"
	},
	usb3g:{
		t_sett:"3G/4G Settings",
        t_3g_info: "Note: 3G or 4G access is unavailable in the current operation mode. Please enable 3G/4G backup or change the operation mode to 3G/4G Router mode.",
		t_backup_delay_time:"Backup Delay",
		t_revert_delay_time:"Revert Delay",
        t_3g_modem: "3G/4G USB Modem:",
		t_pin_status:"PIN Status",
		card_name_unplugged:"Unplugged",
        card_name_ing: "Detecting...",
        card_name_ok: "Detected successfully.",
        pin_status_fail: "Unable to unlock SIM card.",
		pin_status_ready:"Ready",
		pin_status_pin:"SIM Locked",
		pin_status_puk:"PIN Locked",
		pin_status_errror:"Unknown Error",
		t_pin_code:"PIN",
        t_auto_unlock_pin_code:"Auto-unlock PIN",
		pinUnlockBtn:"Unlock",
		t_apn:"APN:",
		t_maa:"(0 means always active.)",
        t_autoauth: "Auto Auth.",
		t_pap:"PAP",
		t_chap:"CHAP",
		t_connStat:"Connection Status:",
        t_pin_chg_en: "Enable PIN Modification",
        t_old_pin: "Old PIN",
        t_new_pin1: "New PIN",
        t_new_pin2: "Confirm New PIN",
		t_mtu:"MTU Size (in bytes)",
        t_mtu1480: "(The default is 1480, do not change unless necessary.)",
		t_follow_ip:"Use The Following IP Address",
		t_static_ip:"Static IP Address",
		t_follow_dns:"Use The Following DNS Servers",
		t_pri_dns:"Primary DNS",
		t_sec_dns:"Secondary DNS",
		modem_set_Btn:"Modem Settings"
	},
	usb3gModemList:{
		t_ums:"3G/4G USB Modem Settings",
		t_file:"File:",
        t_3g_modem: "Note: Restoring the router to the default settings will cause the loss of the .bin file. You can back up and re-upload it, or download the latest .bin file from TP-LINK official website (www.tp-link.com) and install it into your router to retrieve all its functions.",
		upload:"Upload",
		back:"Back"
	},
	group:{
		t_grouptitle:"Interface Grouping",
		t_wancon:"WAN Interface",
		t_lancon:"LAN Interface",
		t_note1:"Note: You cannot disable VLAN functionality with an IPTV or Ethernet WAN Connection enabled.",
        t_note4: "Enable VLAN:"
	},

	groupAdd:{
        t_addgrouptitle: "Add a New Group",
		t_name:"Group Name:",
		t_eniso:"Enable Group Isolation"
	},

	alg:{
		et:"Application Layer Gateway (ALG) ",
		t_vpn:"Virtual Private Network(VPN)",
		t_pptp:"PPTP Pass-through:",
		t_l2tp:"L2TP Pass-through:",
		t_ipsec:"IPSec Pass-through:",
		t_alg:"Application Layer Gateway(ALG)",
        t_ftp: "FTP ALG:",
        t_tftp: "TFTP ALG:",
        t_h323: "H323 ALG:",
        t_sip: "SIP ALG:"
	},
	dslcfg:{
		et:"DSL Settings",
		t_mode:"DSL Modulation Type:",
		t_annex:"Annex Type:",
		t_enswap:"Bit Swap:",
		t_ensra:"SRA:"
	},
	dhcp:{
		t_lanTitle:"LAN",
		t_dhcpTitle:"DHCP Server",
		t_clistTitle:"Client List",
        t_clistNum: "Total Clients:",
		t_staticTitle:"Address Reservation",
		t_condTitle:"Condition Pool",
		c_enable:"Enable this entry",

		/* dhcpEdit.htm */
		t_ipVer:"IP Version:",
		t_ipVer4:"IPv4",
		t_ipVer6:"IPv6",
        t_lan4: "LAN IP:",
		t_snoop:"IGMP Snooping:",
        t_ensnoop: "Enable",
        t_secIp: "Second IP:",
        t_ensecip: "Enable",
		t_dhcp:"DHCP:",
		t_dhcpserv:"DHCP Server",
		t_relay:"DHCP Relay",
		t_ippool:"IP Address Pool:",
		t_leasetime:"Address Lease Time:",
        t_leaseval: "minutes. (1-2880. The default value is 1440.)",
		t_defdomain:"Default Domain:",
		t_remote:"Remote Server Address:",
        t_relay_warn: "Note: To make DHCP Relay configurations effective, disable the NAT of the WAN connection.",
        t_custom: "custom",
        t_endhcp: "Enable",

		/* dhcpStaticEdit.htm*/
        t_resvip: "Reserved IP:",
        t_description:"Description:",

		/* dhcpCondEdit.htm */
		t_facility:"Facility:",
		t_vendor:"Vendor ID:",
		t_poolstart:"Start IP Address:",
		t_poolend:"End IP Address:",
		t_devtype:"Device Type:",
		t_pc:"PC",
		t_camera:"Camera",
		t_hgw:"HGW",
		t_stb:"STB",
		t_phone:"Phone",
		t_unkown:"Unknown",
		t_addopt1:"Add Option:",
		t_optval1:"Option Value:",
		t_addopt2:"Add Option:",
		t_optval2:"Option Value:",
        t_opt240: "Option 240",
        t_opt241: "Option 241",
        t_opt242: "Option 242",
        t_opt243: "Option 243",
        t_opt244: "Option 244",
        t_opt245: "Option 245",
		t_dns1:"DNS1:",
		t_dns2:"DNS2:",

		/* lan6.htm */
		t_sameSession:"Use the IPv4 connection's PPPoE session",
		t_addrtype:"Address Type:",
		t_radvd:"RADVD",
		t_rdnss:"Enable RDNSS",
		t_ula:"Enable ULA Prefix",
		t_ulapfx:"ULA Prefix:",
		t_ulaplen:"ULA Prefix Length:",
		t_dhcp6s:"DHCPv6 Server",
        t_startaddr: "Starting IPv6 Address:",
        t_endaddr: "Ending IPv6 Address:",
		t_lstime:"Leased Time:",
		t_lssec:"seconds",
		t_delegated:"Delegated",
		t_static:"Static",
		t_wan:"Prefix Delegated WAN Connection:",
		t_pfxtype:"Site Prefix Type:",
		t_pfx:"Site Prefix:",
        t_plen: "Site Prefix Length:",
        t_clientNum: "Total Clients",
        t_assignIP: "Assigned IP Address",
        t_lease: "Address Lease Time",
        t_leasevalNote: "(1-2880. The default is 1440.)",
        t_noaddress: "No Address Reservation",
        t_addaddress: "Add Address Reservation",
        t_enaddress: "Enable Reservation"
	},
    wirelessBasic: {
		et:"Settings",
		t_enmssid:"Enable Multi SSID",
        t_warn1: "Please ensure that you select the correct region to conform to local laws.",
        t_warn2: "Make sure the settings are correct.",
		t_enwl:"Enable Wireless Router Radio",
		t_enbcast:"Enable SSID Broadcast",
		t_enwds:"Enable WDS",
		t_brssid:"SSID(to be bridged):",
		t_brbssid:"BSSID(to be bridged):",
		t_eg:"e.g. 00:1D:0F:11:22:33",
		t_wepidx:"WEP Index:",
        t_nopwd: "The password is not editable here, go to Advanced > Wireless to change it.",
        t_enterprise: "The password is not editable here, go to Advanced > Wireless to change it.",
        t_wep: "The password is not editable here, go to Advanced > Wireless to change it."
	},
	wlScan_2G:{
		et:"AP List",
		t_info:"The scanned APs within the area:",
		t_aps:"APs:",
		t_signal:"Signal strength"
	},
	wlScan_5G:{
		et:"AP List",
		t_info:"The scanned APs within the area:",
		t_aps:"APs:",
		t_signal:"Signal strength"
	},
    wps:{
		et:"WPS Settings",
        t_routerpin: "Router PIN",
		t_note:"Note: The WPS function is not supported with WEP security, WPA/WPA2 - Enterprise authentication or TKIP encryption enabled.",
		t_warn1:"Wireless Router Radio is disabled, Click ",
		t_warn2:" here",
		t_warn3:" to enable it.",
        c_notePIN: "Other devices can connect to the router using the router's WPS PIN.",
		ssid_wps_1:"Wireless SSID Broadcast is disabled, Click",
		ssid_wps_2:" here",
		ssid_wps_3:" to enable it.",
        c_enablepin: "Router PIN:",
        c_curpin: "Current PIN:",
		t_defPin_2g:"Restore",
		t_genPin_2g:"Generate",
		t_defPin_5g:"Restore",
		t_genPin_5g:"Generate",
		t_addnewdev:"Add a new device:",
		addNew:"Add device",
		t_pinDisabled:"Disable Router's PIN",
		t_wizard:"WPS Settings",
		c_enablewps:"Enable WPS:",
		c_noteSetup:"Select a setup method:",
		c_pbc:"Push Button (Recommended)",
        c_notePBC: "Press the physical WPS button on the router or click the Connect button below.",
        c_pinnum: "PIN Code",
        c_clinetpin: "Enter the client's PIN:",
        c_clinetpin: "Client PIN",
        c_wpsMethod: "Setup Method",
        c_wps: "WPS",
        c_startWPS: "Press the WPS button on the router or tap the Start WPS button above.",
        c_connectClient: "A client device can be connected to the router using its WPS PIN."
	},
	wirelessSettings:{
		et:"Wireless Security Settings",		
		t_note1:"Note: WEP security and TKIP encryption are not supported in 11n only mode.",
        t_note2: "Note: The network security cannot be set to WEP, WPA/WPA2 Enterprise or TKIP when the WPS function is enabled .",
        t_note3: "Note: WEP security is not supported with Multi SSID enabled.",
        t_note4: "To protect your wireless network, it is highly recommended to enable wireless security, select WPA/WPA2 Personal as the security type and select AES as the encryption type.",
		t_selkey:"Key Selected:",
		t_wepkey:"WEP Key",
		t_mode:"Mode:",
		t_txpow:"Transmit Power:",
		t_low:"Low",
		t_middle:"Middle",
		t_high:"High",
		t_time:"Group Key Update Period:",
		t_timeval:"minimum is 30, 0 meaning no update",
		t_srvIp:"RADIUS Server IP:",
		t_srvPort:"RADIUS Server Port:",
		t_srvPwd:"RADIUS Server Password:",
		t_wlRadiusPort:"(1-65535, 0 stands for default port 1812)",
		t_radius_psw:"RADIUS Server Password:",
		t_wlSec_t19:"Group Key Update Period:",
        t_wlSec_t20: "(seconds, minimum is 30, 0 meaning no update)",
        t_tkip: "TKIP",
        t_aes: "AES"
	},
    macFilter: {
		et:"MAC Filter Settings",
		t_info:"On this page you can configure Wireless MAC Filtering to control wireless access on the network.",
        t_acl: "Enable Wireless MAC Filtering:",
		t_rule:"Filtering Rules",
        t_selrule: "Select a filtering rule:",
		t_deny:"Deny",
        t_black: "Block wireless access from the devices in the list below.",
		t_allow:"Allow",
        t_white: "Allow wireless access only from the devices in the list below.",
		t_list:"Devices List",
		t_macaddr:"MAC Address:",
		t_description:"Description:",
		t_en:"Enable this Entry",
        t_confirm: "Are you sure you would like to delete these rules?",
        t_online: "Devices Online"
	},
    wirelessAdv: {
		et:"Advanced Settings",
		t_txpow:"Transmit Power:",
		t_beacon_2g:"Beacon Interval:",
		t_beacon_5g:"Beacon Interval:",
		t_rts_2g:"RTS Threshold:",
		t_rts_5g:"RTS Threshold:",
		t_frag_2g:"Fragmentation Threshold:",
		t_frag_5g:"Fragmentation Threshold:",
		t_dtim_2g:"DTIM Interval:",
		t_dtim_5g:"DTIM Interval:",
		t_time_2g:"Group Key Update Period:",
		t_time_5g:"Group Key Update Period:",
        t_sgi_2g: "Short GI:",
        t_ensgi_2g: "Enable",
        t_sgi_5g: "Short GI:",
        t_ensgi_5g: "Enable",
        t_iso_2g: "AP Isolation:",
        t_eniso_2g: "Enable",
        t_iso_5g: "AP Isolation:",
        t_eniso_5g: "Enable",
        t_wmm_2g: "WMM:",
        t_enwmm_2g: "Enable",
        t_wmm_5g: "WMM:",
        t_enwmm_5g: "Enable",
		t_notice:"Note:	 Fragmentation is not allowed in 802.11n mode.",
		t_wds_2g:"WDS Bridging:",
		t_wds_5g:"WDS Bridging:",
		t_enwds_2g:"Enable WDS Bridging",
		t_enwds_5g:"Enable WDS Bridging",
        c_ssid_bridge: "SSID (to be bridged):",
        c_mac_bridge: "MAC (to be bridged):",
		t_mac_2g:"SSID (to be bridged):",
		t_mac_5g:"SSID (to be bridged):",
        t_confirm: "The current wireless network channel should be the same as that of the AP to be bridged. Click Yes to change the current channel; otherwise the WDS function will not take effect."
	},
	wirelessStat:{
        et: "Online Devices",
		t_info:"This page displays the basic information of all stations connected to the wireless network.",
		t_tip:"Wireless Stations Currently Connected:",
		t_curstat1:"Current Status",
		t_curstat2:"Current Status",
		t_rxpkts1:"Received Packets",
		t_rxpkts2:"Received Packets",
		t_txpkts1:"Sent Packets",
		t_txpkts2:"Sent Packets"
	},
    wlGuestDulBandBasic: {
		et:"Guest Network",
		t_wlGuest_t1:"Wireless function is disabled, Click",
		t_wlGuest_t2:" here",
		t_wlGuest_t3:" to enable it.",
		t_gnInfo:"You can configure a wireless network for guests.",
		t_gNet:"Guest Network:",
		t_ssid:"SSID:",
		t_sec:"Security:",
		t_see:"See each other:",
		t_allowsee:"Allow guests to see each other",
		t_acclocal:"Access my local network:",
		t_lAccess:"Allow guests to access my local network",
		t_usbshare:"USB Storage Sharing:",
		t_uAccess:"Allow guests to access my USB storage sharing",
		t_wIso:"Guest Network Isolation:",
		t_gNtc:"Guest Network Bandwidth Control:",
		t_gnTc_warn:"Device's Bandwidth Control Function is disabled, Click",
		t_minrate:"Min Rate",
		t_maxrate:"&nbsp;&nbsp;&nbsp;&nbsp;Max Rate",
		t_up:"Upstream:",
		t_down:"Downstream:",
		c_setpwd:"Set Password",
		t_disguest:"Disable Guest Network"
	},
    wlGuestDulBandAdv: {
		et:"Settings",
		t_wlGuest_t1:"Wireless function is disabled, Click",
		t_wlGuest_t2:" here",
		t_wlGuest_t3:" to enable it.",
		t_gnInfo:"You can configure a wireless network for guests.",
		t_gNet:"Guest Network:",
		t_ssid:"SSID:",
		t_sec:"Security:",
		t_see:"See each other:",
		t_allowsee:"Allow guests to see each other",
		t_acclocal:"Access my local network:",
		t_lAccess:"Allow guests to access my local network",
		t_usbshare:"USB Storage Sharing:",
		t_uAccess:"Allow guests to access my USB storage sharing",
		t_wIso:"Guest Network Isolation:",
		t_gNtc:"Bandwidth Control:",
		t_gnTc_warn:"Device's Bandwidth Control Function is disabled, Click",
		t_minrate:"Min Rate",
		t_maxrate:"&nbsp;&nbsp;&nbsp;&nbsp;Max Rate",
		t_up:"Upstream:",
		t_down:"Downstream:",
		c_setpwd:"Set a password",
		t_disguest:"Disable Guest Network",
		t_entc:"Enable guest network bandwidth control",
        t_tcup: "Upstream (kbps):",
        t_tcdown: "Downstream (kbps):",
        t_distc: "The router's Bandwidth Control function is disabled, please go to Advanced > Bandwidth Control to enable it."
	},
	wirelessSchedule: {
		et:"Task Schedule",
        t_tip1: "Drag the mouse over the schedule table to select the period during which you need your wireless off automatically.",
        t_tip2: "The Wireless Time Schedule is based on the time of the router. The time can be set in \"System Tools > Time Settings\" page.",
        c_en: " Wireless Schedule:",
        t_wifi: "Wi-Fi Off"
	},
	usbManage:{
        t_dSett: "USB Storage Device",
		t_sSett:"Sharing Settings",
		t_nsn:"Network/Media Server Name:",
		t_info:"Folder Sharing",
		t_esa:"Share All:",
		t_brw:"My Router",
		t_vol:"Volume Name:",
		t_folP:"Folder Path:",
		t_shareN:"Folder Name:",
		t_agna:"Allow Guest Network Access",
		t_ea:"Enable Authentication",
		t_wa:"Enable Write Access",
		t_ems:"Enable Media Sharing",
		t_ea_a:"Enable Authentication:",
		t_browse:"Browse"
	},
	printSrv:{
		t_ps:"Print Server",
		t_noprint: "None",
        t_sest: "Print Server:",
		t_pn:"Printer Name:",
        c_installStep: "Print Server Installation Steps:",
		t_step1:"Step1:",
        t_note1: "Connect a USB printer to the USB port of the router via a USB cable.",
		t_step2:"Step2:",
        t_note2: "Install the printer driver on your computer. Refer to the computer manufacturer's manuals for instructions.",
		t_step3:"Step3:",
        	t_note3: "Install the TP-LINK USB Printer Controller Utility, You can download it (for both Windows and Mac OS X) from TP-LINK's official website:",
        	t_note3_link: "www.tp-link.com"
	},
	diskSettings:{
        t_diskSett: "USB Storage Device"
	},
	folderSharing:{
		t_shareAcc:"Sharing Account",
        t_info1: "Content sharing requires a sharing account. You can use the login account or create a new one.",
		t_account:"Account:",
		t_ula:"Use Default Account",
		t_ufa:"Use New Account",
		t_salp:"(Same as Login Password)",
        t_shareSett: "Sharing Settings",
		t_nsn:"Network/Media Server Name:",
		t_sf:"Folder Sharing",
		t_esa:"Share All:",
		t_brw:"My Router",
		t_vol:"Volume Name:",
		t_folP:"Folder Path:",
		t_shareN:"Folder Name:",
		t_agna:"Allow Guest Network Access",
		t_ea:"Enable Authentication",
		t_wa:"Enable Write Access",
		t_ems:"Enable Media Sharing",
		t_ea_a:"Enable Authentication:",
        t_browse: "Browse",
        addFolder: "Add Folder",
        modFolder: "Modify Folder",
        note: "Access using the sharing account username and password.",
        noFolder: "No Shared Folders"
	},
	route:{
		et1:"Default Gateway Settings",
        et2: "Static Routing",
		et3:"IPv6 Static Route",
		t_info1:"Select a WAN interface as the system default gateway.",
        t_info2: "This WAN interface is used in another group. Please select another one.",
		c_selwan:"Select WAN Interface:",
		c_addInf:"Add Interface",
		c_status: "Status:",
		c_intf: "Interface:",
        t_info3: "Select a WAN interface as the IPv6 default gateway.",
        t_dstip: "Destination IP",
        t_dstip6: "Destination IPv6 Address",
        t_plen: "Prefix Length",
        c_enable: "Enable this entry"
	},
    virtualServer: {
		et:"Virtual Servers",
		t_iprange:"(XX-XX or XX)",
        t_port: "(XX or Blank, 1-65535)"
	},
    portTrigger: {
		et:"Port Triggering",
        c_triggerport: "Triggering Port:",
        c_triggerproto: "Triggering Protocol:",
		c_exterproto:"External Protocol: ",
		t_noavailintf:"No available interface.",
		t_exrange:"(XX)",
		t_oprange:"(XX or XX-XX or XX,XX-XX)"
	},
    dmz: {
		t_endmz:"Enable DMZ",
		t_hostip:"DMZ Host IP Address:"
	},
    upnp: {
		t_servlist:"UPnP Service List",
		t_enupnp:"UPnP:",
        t_clientnum: "Total Clients:"
		
	},
	parentCtrl:{
		et:"Parental Controls",
		t_info:"Parental Controls can be used to administer all Internet activity including limiting usage and/or access to specific websites to all clients on the network for a specified period of time.",
        t_en: "Status:",
		t_pmac:"MAC Address Of Parental PC:",
		t_curmac:"MAC Address of Current PC:",
		t_copy1:"Copy to Above",
		t_lanmac:"MAC Address in current LAN:",
		t_copy2:"Copy to",
		t_sel:"--Please Select--",
        t_mac1: "MAC Address-1",
        t_mac2: "MAC Address-2",
        t_mac3: "MAC Address-3",
        t_mac4: "MAC Address-4",
		t_setto:"Apply To:",
		t_start:"Start Time",
		t_end:"End Time",
		t_day:"Each Day",
		t_week:"Each Week",
		t_clear:"Clear Schedule",
		t_url:"Add URL:",
		t_detail:"Details",
		t_apply:"(Will not take effect until you save these changes)",
		t_devname:"Device Name: ",
		t_macaddr:"MAC Address: ",
        t_acctime: "Effective Time: ",
		t_descrip:"Description: ",
		t_enentry:"Enable",
        t_cmode: "Restriction Type:",
		t_blm:"Blacklist",
		t_wlm:"Whitelist",
        c_ak: "Add a New Keyword",
        t_ak: "Add a New Keyword",
        t_ad: "Add a New Domain Name",
        t_title1: "Parental Controls",
        t_title2: "Devices Under Parental Controls",
		t_title3:"Content Restriction",
		t_viewdev:"View Existing Devices",
        t_time: "Effective Time",
        t_restore: "Reset",
        t_noblack: "Blacklist is empty.",
        t_nowhite: "Whitelist is empty.",
        m_cmode: "Restriction Type",
        t_nodevice: "No Devices",
        t_accessdevlist: "Online Devices",
        t_adddev: "Add Device",
        t_modify: "Modify Keyword"
	},
	accessControl:{
		t_title1:"Access Control",
		t_title2:"Access Mode",
		t_title3:"Devices Online",
		t_defmode:"Default Access Mode:",
		t_devblack:"Devices in Blacklist",
		t_devwhite:"Devices in Whitelist",
		c_devname:"Device Name: ",
		c_macaddr:"MAC Address: ",
		t_en:"Access Control: ",
		t_blackListInfo:"Blacklist",
		t_whiteListInfo:"Whitelist"
	},
	ddos:{
		t_info:"DDoS Parameters can be set on this page.",
		t_dos:"DoS Protection:",
		t_note:"Note: DoS Protection will not take effect when Traffic Statistics is enabled.",
		t_icmp:"Enable ICMP-Flood Attack Filtering",
		t_icmpth:"ICMP-Flood Packets Threshold",
		t_udp:"Enable UDP-Flood Attack Filtering",
		t_udpth:"UDP-Flood Packets Threshold",
		t_sync:"Enable TCP-SYN-Flood Attack Filtering",
		t_syncth:"TCP-SYN-Flood Packets Threshold",
		t_deny:"Forbid ping packets from LAN port",
		t_list:"Blocked DoS Host List",
		t_en:"Enable DoS Protection",
		t_icmpfilter:"ICMP-FLOOD Attack Filtering:",
		t_udpfilter:"UDP-FLOOD Attack Filtering:",
		t_tcpfilter:"TCP-FLOOD Attack Filtering:",
		c_off:"Off",
		c_low:"Low",
		c_mid:"Middle",
		c_hig:"High",
		t_levelset:"Dos Protection Level Settings",
		t_icmplevel:"ICMP-FLOOD Protection Level:",
		t_udplevel:"UDP-FLOOD Protection Level:",
		t_tcplevel:"TCP-SYN-FLOOD Protection Level:",
		c_lowth:"Low Thresholds:",
		c_midth:"Middle Thresholds:",
		c_higth:"High Thresholds:",
		c_unit:"(5-3600) Packets/Secs"
	},
	ddos_host:{
		t_ip:"Host IP Address",
		t_mac:"Host MAC Address",
		t_clear:"Clear All"
	},
    ipv6Tunnel: {
        t_et: "IPv6 Tunnel",
        t_tunnel: "IPv6 Tunnel:",
		t_note:"Note: You must reconfigure the settings on this page after rebooting the device. You must also ensure the desired WAN connection is connected before you configure the tunnel.",
        t_mech: "Mechanism:",
        t_wan: "WAN Connection:",
        t_conftype: "Configuration Type:",
		t_manual:"Manual",
        t_remote: "Remote IPv6 Address:",
        t_masklen: "IPv4 Mask Length:",
        t_6rdpfx: "6RD Prefix:",
        t_6rdplen: "6RD Prefix Length:",
        t_braddr: "Border Relay IPv4 Address:",
        t_dslite: "DS-Lite",
        t_6rd: "6RD",
        t_6to4: "6to4"
	},
	trafficCtrl: {
		c_enable:"Enable this entry",
		c_to:"to",
		et:"Bandwidth Control",
		t_en:"Bandwidth Control:",
		t_type:"Line Type:",
		t_other:"Other",
		t_tup:"Total Upstream Bandwidth:",
		t_tdown:"Total Downstream Bandwidth:",
		t_enVoip:"VoIP Bandwidth Guarantee:",
		t_graiptvon:"IPTV Bandwidth Guarantee:",
		t_upgrabd:"Upstream Bandwidth Guarantee:",
		t_downgrabd:"Downstream Bandwidth Guarantee:",
        t_rule: "Controlling Rules",
		t_guest_rule:"Guest Network Bandwidth Control Rules",
		t_dslUp:"Current Upstream Rate:",
		t_dslDown:"Current Downstream Rate:",
		t_iprange:"IP Range:",
		t_portrange:"Port Range:",
		t_prio:"Priority:",
        t_prioNote: "(1 means the highest priority.)",
		t_minrate:"Min Rate",
		t_maxrate:"Max Rate",
		t_up:"Upstream:",
        t_down: "Downstream:",
        dsl: "DSL",
        noRule: "No Rules",
        addRule: "Add a New Rule"
	},
    arpBind: {
		et:"Binding Settings",
        t_info: "On this page you can configure IP-MAC Binding entries.",
		t_bind:"ARP Binding:",
		t_status:"Binding Status",
		t_title1:"Settings",
		t_title2:"ARP List",
		t_title3:"Binding List",
        t_en: "IP & MAC Binding:",
		t_macaddr:"MAC Address: ",
		t_ipaddr:"IP Address: ",
		t_enentry:"Enable"
	},
    arpBindEdit: {
		et:"Binding Settings",
		t_info:"This page allows you to set IP-MAC Binding entries.",
		t_bind:"Bind"
	},
    arpList: {
		et:"ARP List",
		importBtn: "Load Selected"
	},
	ddns:{
		et:"Dynamic DNS Settings",
		t_servprov:"Service Provider:",
		t_dns_dyndns:"Dyndns",
		t_dns_noip:"NO-IP",
		btn_go_register:"Go to register..",
		c_user:"Username:",
		c_pwd:"Password:",
		c_domain:"Domain Name:"
	},
	diagnostic:{
		et:"Diagnostic Tools",
        t_info: "Click the Start button to test the Internet connection of the router.",
        t_note: "Note:",
		t_addr:"Target IP Address/Domain Name:"
	
	},
	log:{
		et:"System Log",
		t_logfilter:"Log Filter:",
		t_logtype:"Type:",
		t_loglevel:"Level:",
		t_time:"Time",
		t_type:"Type",
		t_level:"Level",
		t_content:"Content",
		t_clear:"Clear Log",
		t_save:"Save Log",
		t_setting:"Log Settings"
	},
	logConf:{
		et:"Log Settings",
		t_local:"Save Locally",
		t_remote:"Save Remotely",
		t_minlvl1:"Minimum Level",
		t_minlvl2:"Minimum Level",
		t_ip:"Server IP",
		t_port:"Server Port",
		t_fcname:"Local Facility Name"
	},
	time:{
		et:"Time Settings",
		t_plssel:"Please Select",
		t_time:"Time:",
		c_optional:"(optional)",
        t_info: "Note: Click the \"GET GMT\" button to update the time from the Internet with the preset servers or the customized servers (enter the IP address or domain name) in the above fields.",
		t_zone:"Time Zone:",
		t_date:"Date:",
        t_dlsaving: "Daylight Saving Time",
        t_dlsaving1: "Daylight Saving Time:",
        t_endlsaving: "Enable Daylight Saving Time",
		t_npt1:"NTP Server I:",
		t_npt2:"NTP Server II:",
		GetTime:"Get GMT",
        t_dst_start: "Start:",
        t_dst_end: "End:",
        t_format: "(MM/DD/YY)",
        c_month1: "Jan",
        c_month2: "Feb",
        c_month3: "Mar",
        c_month4: "Apr",
        c_month5: "May",
        c_month6: "Jun",
        c_month7: "Jul",
        c_month8: "Aug",
        c_month9: "Sept",
        c_month10: "Oct",
        c_month11: "Nov",
        c_month12: "Dec",
        c_week1: "1st",
        c_week2: "2nd",
        c_week3: "3th",
        c_week4: "4th",
        c_week5: "Last",
        c_day1: "Mon",
        c_day2: "Tue",
        c_day3: "Wed",
        c_day4: "Thu",
        c_day5: "Fri",
        c_day6: "Sat",
        c_day7: "Sun",
        curTime: "Current Time:",
        setType: "Set Time",
        auto: "Sync via the Internet",
        manual: "Manually"
	},
	manageCtrl:{
		t_account:"Account Management",
		t_oldname:"Old User Name:",
		t_oldpwd:"Old Password:",
		t_newname:"New User Name:",
		t_newpwd:"New Password:",
		t_confirm:"Confirm New Password:",
		t_local:"Local Management",
		t_remote:"Remote Management",
		c_port:"Port:",
		c_addr:"IP/MAC Address:",
		t_enableremote:"Remote Management:",
		t_tip:"Passwords may contain 6-15 (Case-sensitive) letters and numbers.",
		t_ping_title:"ICMP Ping:",
		t_icmp:"ICMP Ping",
		t_ping_remote:"Remote",
		t_ping_local:"Local"
	},
	cwmp:{
		et:"CWMP Settings",
        t_info: "CPE WAN Management Protocol (also called TR-069) allows Auto-Configuration Server (ACS) to perform auto-configuration, provision, connection, and diagnostics to this device. You may configure this function under your ISP's instructions.",
		t_inform:"Inform:",
        t_cwmp: "Enable CWMP:",
        t_interval: "Inform Interval(seconds):",
		t_acsurl:"ACS URL:",
		t_acsusername:"ACS Username:",
		t_acspasswd:"ACS Password:",
		t_if:"Interface used by TR-069 client:",
		t_anywan:"Any WAN",
		t_lan:"LAN",
		t_display:"Display SOAP messages on serial console:",
		t_auth:"Connection Request Authentication",
		t_cr_name:"Connection Request Username:",
		t_cr_pwd:"Connection Request Password:",
		t_cr_path:"Connection Request Path:",
		t_cr_port:"Connection Request Port:",
		t_cr_url:"Connection Request URL:",
		getRPCMethods:"Get RPC Methods"
	},
	snmp:{
		et:"SNMP Settings",
		t_info:"Simple Network Management Protocol(SNMP) allows management applications to retrieve status updates and statistics from the SNMP agent within this device.",
        t_snmp: "Enable SNMP Agent:",
        t_read: "Read-only Community:",
        t_set: "Write Community:",
		t_name:"System Name:",
		t_desc:"System Description:",
		t_locale:"System Location:",
		t_concat:"System Contact:",
		t_trapip:"Trap Manager IP:"
	},
    backNRestore: {
		et:"Backup and Restore",
        t_savecopy: "Save a copy of your current settings.",
		t_file:"File:",
		t_restoreinfo:"Restore saved settings from a file.",
		t_facrestore:"Factory Default Restore",
        t_facrestoreinfo: "Revert all the settings to their default values."
	},
	defaultCfg:{
		et:"Factory Defaults",
        t_info: "Click to restore all the settings to factory defaults. It is highly recommended that you back up your current configurations before restoration.",
		t_restore:"Restore"
	},
	softup:{
            et1: "Device Information",
            et2: "Online Upgrade",
            et3: "Local Upgrade",
		et:"Firmware Upgrade",
		t_info:"New features will be available once the firmware upgrade is successful.",
		t_file:"New Firmware File:",
		t_note1:"Please select the correct firmware build corresponding to the hardware version of the device.",
        t_note2: "Do not turn off the router during the upgrade process to avoid any damage to the router.",
        t_note3: "After the upgrade process is completed, the router will reboot automatically.",
		t_upgrade:"Upgrade",
            c_upgrade: "Upgrade",
            c_latest: "Latest Version:",
            upTodate: "Your firmware is up to date",
            downLoad: "Downloading...",
            keepPowerOn: "To avoid any damage, keep the device powered on.",
            internetUnavailable: "Internet is unavailable.",
            downLoadFailed : "Download failed.",
            checkFail :"Invalid firmware. Please download the new firmware again.",
            checkForUpgrade: "Check for Upgrades",
            confirmContent:"Are you sure you want to upgrade the firmware?",
            illegalDevice: "Your device does not support TP-LINK cloud service. Please contact TP-LINK technical support if you want to continue.",
            upgradeAlert1:"The current firmware does not support TP-LINK cloud service. We strongly recommend that you download the latest firmware at www.tp-link.com and update it.",
            upgradeAlert2:"The current firmware does not support TP-LINK cloud service. We strongly recommend that you update the firmware by clicking the Update icon in the upper right corner."
	},
	restart:{
		et:"System Reboot",
        t_info: "Click Reboot to restart the router without changing any changes to your current settings."
	},
    stat: {
		et:"Traffic Statistics",
		t_entraf:"Enable Traffic Statistics: ",
		t_list:"Traffic Statistics List"
	},
    iptv: {
		t_title_itv:"IPTV Settings",
		t_title_qs:"Quick Setup - IPTV",
		t_info:"IPTV parameters can be set on this page.",
        t_wireless_tip: "If you would like to set the WLAN port for an IPTV connection, please enable the wireless radio on Advanced > Wireless > Wireless Settings page.",
		t_iptv:"IPTV:",
		t_iptv_tip_enable:"Enable IPTV",
        t_full_warn: "Note: If the WAN interface table is full, please go to Advanced > Network > Internet to delete an entry.",
        t_iptv_tip1: "Select a LAN port for the IPTV connection and connect the set-top box to this port.",
		t_iptv_tip2:"Note: When the WLAN port is set for an IPTV connection, the wireless functionality is only available for that IPTV connection.",
        t_iptv_tip3: "Please set the following parameters for the IPTV connection.",
		t_iptv_isp:"ISP:",
		t_iptv_vpi:"VPI:",
		t_iptv_vci:"VCI:",
		t_iptv_vlanTag:"VLAN Tag",
		t_iptv_vlanValue:"Tag Value:",
		t_enVid:"Enable VLAN ID",
		c_port:"LAN Port:"
	},
	ipsec:{
		et:"IPSec Settings",
		t_dpd:"Dead Peer Detection:",
		t_conname:"IPSec Connection Name:",
        t_remgwaddr: "Remote IPSec Gateway (URL):",
		t_tunlocaddr:"Tunnel access from local IP addresses:",
        c_sub: "Subnet Address",
		c_singleaddr:"Single Address",
		c_addrVPN:"IP Address for VPN:",
        c_submask: "Subnet Mask:",
		t_tunremaddr:"Tunnel access from remote IP addresses:",
		t_kexmeth:"Key Exchange Method:",
		t_auto:"Auto(IKE)",
		t_manual:"Manual",
		t_authmeth:"Authentication Method:",
        c_presharekey: "Pre-Shared Key",
        c_presharekey2: "Pre-Shared Key:",
		t_fosec:"Perfect Forward Secrecy:",
		t_enkey:"Encryption Key:",
		t_authalgo:"Authentication Algorithm:",
		t_authkey:"Authentication Key:",
		t_phase:"==Phase 1==",
		t_main:"Main",
		t_aggr:"Aggressive",
        t_myidtype: "Local Identifier Type:",
		t_locwanip:"Local Wan IP",
        t_myid: "Local Identifier:",
		t_remidtype:"Remote Identifier Type:",
		t_remwanip:"Remote Wan IP",
		t_remid:"Remote Identifier:",
		c_selectkeyex:"Diffie-Hellman Group for Key Exchange:",
        c_keylife: "Key Life Time(Seconds):",
		t_phase2:"==Phase 2=="
	},
    voice_advance: {
		t_st1:"Telephone Numbers",
        t_st2: "Advanced Settings",
        t_displayname: "Telephone Name:",
		t_stsip:"SIP Account Advanced Settings",
		t_preftime:"Preferred Receive Ptime:",
		t_priority:"Priority:",
		t_high:"1--high",
		t_low:"8--low",
        t_bound: "Bound Interface:",
		t_dscpsip:"DSCP for SIP:",
		t_dscprtp:"DSCP for RTP:",
		t_dtmf:"Dtmf Relay setting:",
        t_sipinfo: "SIP INFO",
        t_inband: "In-band",
        t_registimeout: "Registry Expiration Time:",
        t_regisinterval: "Registry Retry Interval:",
		t_name:"\"No answer\" time:",
        t_timeout: "(300-3600 seconds)",
        t_interval: "(30-300 seconds)",
        t_sec: "(5-60 seconds)",
		t_sipprotocol:"SIP Transport protocol:",
		t_end:"End With '#':",
        t_t38support: "T 38 Support:",
        t_mwi: "MWI:",
        t_noTN: "No Telephone Numbers",
        t_addTN: "Add a New Number"
	},
    voice_adddect: {
        t_et: "Register a Handset",
        t_info1: "To register a cordless handset to the router:",
        t_step1: "Step 1:",
        t_info2: "On your cordless handset, open the Operation menu to start registration.",
        t_step2: "Step 2:",
        t_info3: "Select a router (generally router 1) if required.",
        t_step3: "Step 3:",
        t_info4: "Enter the PIN (0000 by default) if required."
	},
    voice_callblocks: {
		t_et1:"DND Settings",
		t_endnd:"Enable DND:",
		t_dndlabel1:"Daily",
		t_dndlabel2:"Saturday and Sunday",
        t_dndlabel3: "Monday to Friday",
        t_dndtimefrom: "From:",
        t_dndtimeto: "To:",
		t_to:"To:",
        t_et2: "Call Blocking",
		t_et3:"Incoming Calls",
        t_incomingInfo: "Select the incoming number to be blocked:",
		t_number:"Number:",
		t_et4:"Outgoing Calls",
        t_numbertype: "Call Type:",
        t_mobile: "Mobile",
        t_telephone: "Landline",
		t_long:"Long Distance",
        t_inter: "International",
        t_other: "Calls with Specific Number Prefix",
        t_addpre: "Number Prefix:",
        t_addnumber: "Specific Number",
        t_addanonymous: "Anonymous Number"
	},
    voice_callforward: {
        t_et: "Call Forwarding",
        t_info1: "Select the incoming calls to be forwarded.",
		t_label1:"All incoming calls",
        t_label2: "Calls to the Telephone Number",
        t_label3: "Calls to the Phone",
		t_label4:"Calls from a person in the telephone book",
		t_label5:"Calls from the telephone number",
		t_label6:"All anonymous calls to the number",
        t_info2: "Set Forwarding Rules:",
		t_destnumlabel:"Destination telephone number:",
		t_fwdlabel:"Forward the calls via:",
        t_fwdtypelabel: "Call Forward Condition:",
        t_undion: "Unconditional",
		t_noanswer:"No Answer",
		t_enfwdlabel:"Enable this call forward rule",
		t_telphonenum:"telephone number"
	},
    voice_telebook: {
		t_et:"Telephone Book",
		t_name:"Last Name:",
		t_fname:"First name:",
        t_pri: "Private Phone Number:",
        t_work: "Work Phone Number:",
        t_cell: "Mobile Phone Number:",
		t_speeddial:"Speed dial number type:",
		t_select:"Please select",
        t_prinumber: "Private Phone Nnumber",
        t_worknumber: "Work Phone Number",
        t_cellnumber: "Mobile Phone Number",
		t_speednumber:"Speed dial number:",
        t_et2: "Emergency Number Settings",
        t_enwarm: "Enable Emergency Number:",
        t_warmtime: "No Operation Time:",
        t_warmnumber: "Emergency Number",
        t_warmnumber1: "Emergency Number1:",
        t_warmnumber2: "Emergency Number2:",
        t_warmnumber3: "Emergency Number3:",
        t_warmnumber4: "Emergency Number4:",
        t_warmnumber5: "Emergency Number5:",
        t_addTelBook: "Add a New Contact",
        t_noTelBook: "No Contacts"
	},
    voice_basic: {
		t_et:"Telephone Numbers"
	},
    voice_telephony: {
		t_et:"Telephony Devices",
		t_dev:"Device name:",
        t_info1: "Number for Outgoing Calls:",
        t_info2: "Number for Incoming Calls:",
		t_vadsup:"VAD Support:",
		t_vaden:"Enable VAD",
		t_speakgain:"Speaker Gain:",
		t_micgain:"Mic Gain:"
	},
    voice_calllog: {
		t_title:"Call Log",
		t_en:"Enable Call Log:"
	},
    voice_callthrough: {
		t_et:"Call through",
        t_et1: "Enable Call Through:",
        t_incoming: "Number for Incoming:",
        t_outgoing: "Number for Outgoing:",
		t_callpin:"PIN:",
        t_info: "Only Accept Calls from the Numbers below",
		t_addnum:"Add more numbers",
        t_whiteList: "If the \"Only Accept Calls from the Numbers below\" option is selected, you must add at least one phone number."
	},
    voice_dectadv: {
		t_et:"DECT Settings",
		t_endect:"Enable Dect:",
		t_dectreg:"Registration",
        t_info: "To make VoIP calls, register your cordless handsets to the router using the default PIN \"0000\" or your own defined PIN below.",
		t_dectpin:"PIN:",
        t_et2: "Radio Field Strength:",
		t_radio:"Reduce DECT field strength",
        t_eco: "Eco DECT",
        t_sec: "Security:",
        t_encrypt: "Enable Encryption (recommended)"
	},
    voice_electionRule: {
		t_et:"Call Rules",
        t_pre: "Call Type or Prefix:",
        t_modile: "Mobile",
        t_tel: "Landline",
		t_dis:"Long Distance",
        t_inter: "International",
        t_other: "Calls with Specific Number Prefix",
        t_addpre: "Number Prefix:",
        t_viainfo: "Number for Outgoing Calls:"
	},
    voice_usbmail: {
        t_et: "USB Voice Mail Settings",
        t_note: "Note: Please wait a few seconds after clicking the Play icon.",
        t_noUSB: "USB storage device Disconnected.",
        t_noConfig: "No proper files found in the USB storage device.",
        t_notEnough: "Not enough space available on the Voice Mailbox.",
		t_usbmail:"USB Voice Mail:",
        t_name: "\"No answer\" time:",
        t_sec: "(5-60 seconds)",
        t_notify: "Greeting for Voice Mail:",
		t_def:"default",
		t_custom:"custom",
		t_rPIN:"Remote Access PIN:",
        t_duration: "Voice Mail Duration:",
        t_usbCapText: "Voice Mailbox Capacity:",
        usbCap: "(0-0M):",
        t_et1: "Voice Mail List",
        t_pinInfo: "<span style='color: red; vertical-align:baseline'>Note: </span>Pick up the phone (analog phone or DECT handset) and dial *30 to record a personalized greeting for your voice mail.",
        t_pinInfo1: "<span style='color: red; vertical-align:baseline'>Note: </span>To access your voice mail remotely, dial the number for incoming calls. When your personal greeting starts, press *. Enter your Remote Access PIN when prompted."
	},
    voice_usbmailBasic: {
        t_et: "USB Voice Mail Settings",
        t_note: "Note: Please wait a few seconds after clicking the Play icon.",
        t_noUSB: "USB storage device disconnected.",
        t_noConfig: "No proper files found in the USB storage device.",
        t_notEnough: "Not enough space available on the Voice MailBox.",
		t_usbmail:"USB Voice Mail:",
        t_notify: "Greeting for Voice Mail:",
		t_def:"default",
		t_custom:"custom",
		t_rPIN:"Remote Access PIN:",
        t_duration: "Voice Mail Duration:",
        t_usbCapText: "Voice MailBox Capacity",
        usbCap: "(0-0M):",
        t_et1: "Voice Mail List",
        t_pinInfo: "<span style='color: red; vertical-align:baseline'>Notice: </span>Pick up the phone (analog phone or DECT handset) and dial *30 to record a personalized greeting for your voice mail.",
        t_pinInfo1: "<span style='color: red; vertical-align:baseline'>Notice: </span>To access your voice mail remotely, dial the number for incoming calls. When your personal greeting starts, press *. Enter your Remote Access PIN when prompted."
	},
    voice_regProcess: {
        t_et: "Register a Handset",
        t_note1: "Registering your handset…",
        t_note2: "Registration successful.",
        t_note3: "Unable to register to the router.",
        t_note4: "If the cordless (DECT) handset rings, it is registered successfully.",
		t_note5:"Is the telephone ringing?"
	},
    voice_phone: {
        t_dectinfo: "Phone Information",
		t_dectname:"Phone Name",
		t_decttype:"Phone Type",
		t_innernum:"Internal Number",
        t_outnum: "Number for Outgoing Calls",
		t_op:"Operation"
	},
	quicksetup: {
        t_sysModeNote: "The Quick Setup function is only available when this device is working in DSL Modem Router mode. You can switch to DSL Modem Router mode at  Advanced > Operation Mode, or configure the router on the Advanced page.",
		t_newUserTip:"Set up a new username and password",
		t_newUsrName:"New Username:",
		t_newPwd:"New Password:",
		t_cfmPwd:"Confirm New Password:",
		t_noteRegion:"Please select a region",
		t_noteTimezone:"Please select a time zone",
        t_noteUserName: "The new username is required",
        t_noteEmptyPwd: "The password is required",
        t_noteCfmPwd: "Passwords do not match.",
		t_noteNotAsciiUserName:"The new username must be ASCII characters excluding spaces.",
		t_noteNotAsciiPwd:"The password must be ASCII characters excluding spaces.",
        t_ispList: "ISP List:",
		t_l2IntfType:"L2 Interface Type:",
		t_vlan:"VLAN:",
		t_enVid:"Enable VLAN ID",
		t_tag:"VLAN ID(1-4094):",
		t_noteWlAuth:"Warning: This will change auth mode to WPA/WPA2.",
		t_fail_note:"Internet Diagnostic Failed:",
        t_succ_note: "Internet diagnosis succeeded.",
        t_setupStatus: "Congratulations! Internet connected. Enjoy the Internet!",
		t_connStatus:"Connection Status:",
		t_selIsp:"Select Internet Service Provider (ISP)",
		t_setRegion:"Time Zone",
		t_selectWanType:"Internet Connection Type",
		t_setWanType:"",
		t_inetSetup:"Internet Setup",
		t_wlSet:"Wireless Settings",
        t_connTest: "Connection Test",
		t_testInternet:"Test Internet Connection",
		t_summary:"Summary",
        t_sorry: "Sorry!",
		t_noteRejoin:"Wireless settings have been changed successfully. Please use the following wireless network names and passwords for your wireless connection.",
		t_noteConfig: "Please use the following SSID and password for wireless connection:",
		t_noteSure: "Make sure you have connected to the new wireless network.",
		t_not_reconnected: "Sorry!We detect that you have not reconnected your wireless device to the new wireless network.",
		t_permit_wireless:"I have successfully reconnected to the router using the new wireless settings.",
        t_permit_wired: "I am using a wired connection.",
        t_pppAuthFail: "Username or password is incorrect. Click Reconfig to confirm your username and password. If the problem still exists, please contact your Internet service provider.",
        t_diagLoadingText: "Testing the Internet connection. It may take one to two minutes. Please wait...",
        t_dslSettingNote: "Enter the Internet connection information needed or contact your service provider for assistance.",
        t_wlSettingNote: "You can change the wireless network name and password.",
		c_qsPPPoE:"PPPoE",
		c_qsPPPoA:"PPPoA",
		c_qsDynIp:"Dynamic IP",
		c_qsStaIp:"Static IP",
		c_qsIPoA:"IPoA",		
		c_pppUserName:"User Name:",
		c_pppPwd:"Password:",
		c_pppCfmPwd:"Confirm Password:",
		c_ipaddr:"IP Address:",
		c_mask:"Subnet Mask:",
		c_gw:"Gateway:",
		c_priDns:"DNS Server:",
		c_secDns:"Secondary DNS Server:",
		c_wl24g:"Wireless Network (2.4GHz):",
		c_wl5g:"Wireless Network (5GHz-1):",
		c_wl5g_2:"Wireless Network (5GHz-2):",
		c_enWl:"Enable",
		c_ssid:"Wireless Network Name (SSID):",
		c_wlPwd:"Password:",		
		c_dnsSrvs:"DNS Servers:",		
		c_internetFailed:"Internet not connected.",
        c_failed: "Failed.",
        c_internetConnFailed: "Internet Connection Failed.",
        c_regionTZ: "Region and Time Zone",
        c_connType: "Connection Type",
        c_useAutoDect: "If you are not sure about which Internet Connection Type you have, use Auto-Detect or contact your Internet Service Provider (ISP) for assistance.",
        c_autoDetect: "Auto-Detect",
        c_notCloneTips: "If your ISP only allows Internet access to a specific MAC Address, you need to clone the MAC Address of the primary computer. If you are not sure, select Do not Clone MAC Address.",
        c_cloneTips: "If you select Clone MAC Address, you need to clone the original computer's MAC address that is registered with your ISP.",
        c_staticTips: "Please enter your IP information.",
        c_pppoeTips: "Please enter your PPPoE username and password.",
        c_reconnTips: "Upon saving your wireless settings, you will be disconnected from your wireless network. Please reconnect using the new SSID.",
        c_failTips: "Your wireless device is not connected to the new wireless network. Please try again and tap OK.",
        c_congra: "Congratulations!",
        c_completeTips: "You have completed the Quick Setup process. Tap Test Internet Connection below, then tap Finish.",
        c_testInternet: "Test Internet Connection",
        c_vdsl: "VDSL",
        c_adsl: "ADSL",
        c_connSuccess: "Success! Tap Finish to end the Quick Setup process.",
        	t_success: "Congratulations!",
		t_sorry: "Sorry",
		t_qs_completed: "You have completed the Quick Setup process.",
		t_qs_end:"Click Test Internet Connection below, then click Finish.",
		t_qs_testInternet: ">Test Internet Connection",
		t_qs_restart: "Configuration error, please restart the Quick Setup.",
		t_test_success: "Success!",
		t_test_fail: "Failed.",
		t_qs_success_info: "Click Finish to complete the Quick Setup process.",
		t_qs_failed_info1: "Please verify that all Quick Setup parameters are correct and try again. If the problem still exists, reboot your modem, wait 2 minutes, and click Test Internet Connection again. If you are not using a modem, you may need to contact your Internet Service Provider (ISP) for assistance.",
		t_selectWanType: "Internet Connection Type",
		t_setWanType:"",
		c_qsL2TP:"L2TP",
		c_qsPPTP:"PPTP",
		t_note_title: "Note: ",
		t_typeNote:"If you are not sure which Internet Connection Type you have, use Auto Detect or contact your Internet Service Provider (ISP) for assistance.",
		t_qsPppoe_title:"Please enter your PPPoE username and password.",
		t_qsDhcp_title:"If your ISP only allows Internet access from a specific MAC address, you need to Clone that MAC Address to provide Internet access for other devices. If you are not sure, select <strong>Do NOT clone MAC Address</strong>.",
		t_qsDhcp_note: "If you select Clone Current Computer MAC Address, please make sure the MAC Address of this computer is registered with your ISP before clicking Next.",
		t_qsStatic_title:"Please enter your IP information.",
		t_qsL2tp_title:"Please enter the L2TP username and password.",
		t_qsPptp_title:"Please enter the PPTP username and password.",
		t_notMacClone:"Do NOT clone MAC Address",
		t_doMacClone:"Clone Current Computer MAC Address",
		c_vpnServer: "VPN Server IP/Domain Name:",
		t_ethUnplugged: "The cable is unplugged."
	},
	ipv6:{
		/* IPv6 Wan */
		t_et: "IPv6 Internet",
		t_pppoe: "PPPoE",
		t_6to4tunnel: "6to4 Tunnel",
		t_ip4Addr: "IPv4 Address:",
		t_ip4Mask: "IPv4 Subnet Mask:",
		t_ip4gw: "IPv4 Gateway:",

		/*IPv6 Lan*/
		t_et_lan: "IPv6 LAN",
		t_addrtype:"Addressing Type:",
		t_radvd:"RADVD",
		t_rdnss:"Enable RDNSS",
		t_ula:"Enable ULA Prefix",
		t_ulapfx:"ULA Prefix:",
		t_ulaplen:"ULA Prefix Length:",
		t_dhcp6s:"DHCPv6 Server",
		t_startaddr:"Start IPv6 Address:",
		t_endaddr:"End IPv6 Address:",
		t_lstime:"Leased Time:",
		t_lssec:"seconds",
		t_delegated:"Delegated",
		t_static:"Static",
		t_wan:"Prefix Delegated WAN Connection:",
		t_cur_wan: "Prefix Delegated WAN Connection:",
		t_pfxtype:"Site Prefix Type:",
		t_pfx:"Site Prefix:",
		t_plen:"Site Prefix Length:"
	},
	sysconf: {
		t_txpow:"Transmit Power:",
		t_beacon_2g:"Beacon Interval:",
		t_beacon_5g:"Beacon Interval:",
		t_rts_2g:"RTS Threshold:",
		t_rts_5g:"RTS Threshold:",
		t_frag_2g:"Fragmentation Threshold:",
		t_frag_5g:"Fragmentation Threshold:",
		t_dtim_2g:"DTIM Interval:",
		t_dtim_5g:"DTIM Interval:",
		t_time_2g:"Group Key Update Period:",
		t_time_5g:"Group Key Update Period:",
		t_sgi_2g:"Short GI Feature:",
		t_ensgi_2g:"Enable Short GI",
		t_sgi_5g:"Short GI Feature:",
		t_ensgi_5g:"Enable Short GI",
		t_iso_2g:"AP Isolation Feature:",
		t_eniso_2g:"Enable AP Isolation",
		t_iso_5g:"AP Isolation Feature:",
		t_eniso_5g:"Enable AP Isolation",
		t_wmm_2g:"WMM Feature:",
		t_enwmm_2g:"Enable WMM",
		t_wmm_5g:"WMM Feature:",
		t_enwmm_5g:"Enable WMM",
		t_notice:"Note:	 Fragmentation is not allowed in 802.11n mode.",
		t_wds_2g:"WDS Bridging:",
		t_wds_5g:"WDS Bridging:",
		t_enwds_2g:"Enable WDS Bridging",
		t_enwds_5g:"Enable WDS Bridging",
		t_mac_2g:"MAC Address (to be bridged):",
		t_mac_5g:"MAC Address (to be bridged):",
		t_confirm:"Current AP channel is $, which is different from the configured AP channel. Do you want to continue and change the channel?",
		et_2g_adv: "Wireless 2.4GHz",
		et_5g_adv: "Wireless 5GHz",
		et_nat: "NAT",
		et_ddos:  "DoS Protection Settings",
		t_nat: "NAT:",
		t_hw_nat: "NAT Boost:",
		t_ennat: "Enable NAT",
		t_en_hw_nat: "Enable NAT Boost"
	},
	openvpnServer: {
		t_openvpn: "OpenVPN",
		t_noCertNote: "Note:",
		t_noCertNote1: "No certificate currently, please",
		t_noCertNote2: "Generate",
		t_noCertNote3: "one before enabling VPN Server.",
		t_enOvpn: "Enable VPN Server",
		t_serType: "Service Type:",
		t_udp: "UDP",
		t_tcp: "TCP",
		t_serPort: "Service Port:",
		t_ovpnSubnetAndMask: "VPN Subnet/Netmask:",
		t_cliAccess: "Client Access:",
		t_home: "Home Network Only",
		t_internetHome: "Internet and Home Network",
		t_genCert: "Certificate",
		t_genText: "Generate the certificate.",
		t_configFile: "Configuration File",
		t_exportConfig: "Export the configuration.",
		t_vpnGuide: "VPN Client Installtion Guide",
		t_guidePara1: "To enable and connect your client devices to the OpenVPN server:",
		t_guidePara2: "Before you configure the OpenVPN server, please configure Dynamic DNS Service (recommended) or assign a static IP address for WAN port. Please make sure your external port of NAT settings is not the service port, and your System Time is synchronized with Internet.",
		t_note1: "Select Enable VPN Server.",
		t_note2: "Configure the OpenVPN server parameters (Service Type, Service Port and Client Access) and click Save.",
		t_note3: "Click Export to save the configuration file.",
		t_note4_1: "On your client devices, download and install the OpenVPN client utility from",
		t_note4_2: "The official supported platforms include Windows, Mac OSX, Linux.",
		t_note5: "Launch the OpenVPN client utility and add a new VPN connection using the saved configuration file to connect your client device to the VPN server.",
		t_note6: "To learn more about OpenVPN clients, visit"
	},
	pptpvpnServer: {
		t_pptpvpn: "PPTP VPN",
		t_enPvpn: "Enable VPN Server",
		t_cliIp: "Client IP Address:",
		t_cliNum: "(up to 10 clients)",
		t_username: "Username:",
		t_password: "Password:",
		t_vpnGuide: "VPN Client Installtion Guide",
		t_guidePara1: "To enable and connect your client devices to the PPTP VPN server:",
		t_guidePara2: "Before you configure the PPTP VPN server, please configure Dynamic DNS Service (recommended) or assign a static IP address for WAN port. Please make sure your external port of NAT settings is not 1723 and your System Time is synchronized with Internet.",
		t_note1: "Select Enable VPN Server.",
		t_note2: "Configure the PPTP VPN server parameters and click Save.",
		t_note3: "On your client devices, create a PPTP VPN connection. The official supported platforms include Windows, Mac OSX, Linux, iOS, and Android.",
		t_note4: "Launch the PPTP VPN program, add a new connection and enter the domain name of the registered DDNS service or the static IP address that assigned to the WAN port, to connect your client device to the PPTP VPN server."
	},
	vpnServerStatus: {
		t_vpnConn: "VPN Connections",
		t_ovpnConn: "OpenVPN Connection",
		t_pvpnConn: "PPTP VPN Connection"
	}

};
       
var table_str = { 
	id:"ID", 
	idx:"Index",
	time:"Time",
	type:"Type",
	lvl:"Level",
	name:"Name", 
	wanInfName:"WAN Interface Name",
	enable:"Enable", 
	modify:"Modify", 
	bound:"Bound",
	description:"Description", 
	ip:"IP Address",
	mac:"MAC Address", 
	conntype:"Connection Type", 
	sec:"Security", 
	revpkg:"Received Packets", 
	sendpkg:"Sent Packets", 
	transrate: "Transmit Rate",
	wl2g:"2.4GHz", 
	wl5g:"5GHz-1", 
	wl5g_1:"5GHz-1", 
	wl5g_2:"5GHz-2", 
    wlguest2g: "Guest 2.4GHz",
    wlguest5g: "Guest 5GHz-1",
    wlguest5g_2: "Guest 5GHz-2",
	bssid:"BSSID", 
	ssid:"SSID", 
	signal:"Signal strength", 
	channel:"Channel", 
	encryption:"Encryption", 
	connect:"Connect",
	logcont:"Log Content",
	devname:"Device Name",
    accesstime: "Internet Access Time",
	effectivetime: "Effective Time",
	operation:"Operation",
	status:"Status",
	bindstatus:"Binding Status",
	del:"Delete",
	group:"Group",
	destNtw:"Destination IP",
	destNtw6:"Destination IPv6 Address/Prefix Length",
	subMask:"Subnet Mask",
	dftGw:"Gateway",
	dhcpPool:"DHCP Pool",
	clientName:"Client Name",
    assip: "Assigned IP",
    leaseTime: "Leased Time",
    resip: "Reserved IP",
	vid:"Vendor ID",
    ipRange: "Starting IP Address/Ending IP Address",
	facility:"Facility",
	lanif:"LAN Interface",
	wanif:"WAN Interface",
	avlanif:"Available LAN",
	avwanif:"Available WAN",
	descpt:"Description",
	priority:"Priority",
	upbw:"Up(min/max)",
	downbw:"Down(min/max)",
    volume: "Volume Name",
	active:"Active",
	capacity:"Capacity",
	freeSpace:"Free Space",
	shareName:"Folder Name",
	folderPath:"Folder Path",
	mediaSharing:"Media Sharing",
	netNeig:"Network Neighborhood",
	mediaServer:"Media Server",
	ftp:"FTP",
	ftpSign:"ftp://",
	ftpInternet:"FTP(via Internet)",
	dlnaAcMethod:"Media Server",
	acMethod:"Access Method",
    link: "Access",
	port:"Port",
	vendor:"Vendor",
	model:"Model",
	safelyRemove:"Safely Remove",
	selectopt:"Select a folder",
	profilename:"Profile Name",
    phonename: "Device Name",
	voicenumber:"Number",
	provider:"Provider",
    innum: "Number for Incoming Calls",
	internum:"Internal number",
	outnum:"Number of outgoing",
    numbertype: "Number",
    prefixtype: "Call Type or Prefix",
	call:"Calls",
	fwd:"Forward via",
	dstnum:"Destination number",
	fwdtype:"Forward type",
	logdate:"Date/Time",
	logtype:"Type",
	logdur:"Duration (hh:mm)",
	lognum:"Number/Contacts",
	logdev:"Device Number",
	logtel:"Telephony device",
	via:"Number for Outgoing",
	telnumber:"Telephone Number",
	speednumber:"Speed dial number",
	usbinnum:"Incoming Number",
	sett:"Setting",
	na:"--",
    phone1: "Phone 1",
    phone2: "Phone 2",
	voicemail:"Voice Mail",
	auto:"Auto",
	servname:"Service Type",
	exterport:"External Port",
	interip:"Internal IP",
	interport:"Internal Port",
	protocol:"Protocol",
	application:"Application",
	triggerport:"Triggering Port",
	triggerproto:"Triggering Protocol",
	exterproto:"External Protocol",
	appname:"Application Name",
	servdesc:"Service Description",
	interipaddr:"Internal IP Address",
	ipmacaddr:"IP Address/MAC Address",
	ttpackets:"Total Packets",
	ttbytes:"Total Bytes",
	crpackets:"Current Packets",
	crbytes:"Current Bytes",
	cricmptx:"Current ICMP Tx",
	crudptx:"Current UDP Tx",
	crsynyx:"Current SYN Tx",
	connname:"Connection Name",
	remgateway:"Remote Gateway",
	locaddr:"Local Address",
	remaddr:"Remote Address",
	wired:"Wired",
	wireless:"Wireless",
    encrypted: "Encrypted",
    wldissec: "None",
    on:"On",
    off:"Off",
    nightModeNote:"Note:To enable or disable the night mode, please turn on the led switch first",
    routeDestNtw:"Destination Network",
    Intf:"Interface",
	remoteIp: "Remote IP",
	assignedIp: "Assigned IP"    
};

var if_str =
{
	NULL:"",
	LAN:"LAN & WLAN",
	Internet:"Internet Connection",
	Public:"Public Connection",
	OpenVPN: "OpenVPN Connection",
	PPTPVPN: "PPTPVPN Connection"	
};