#!/bin/sh

installevent_ntp_sync ()
{
    blank_state="$(uci -q get netgear.system.blank_state)"
    if [ "$blank_state" == "1" ]; then
        ubus call ntgr_ra_iot.installEvent send '{"eventType":"ntp synced"}'
    fi
}

. /lib/functions/procd.sh

TIMEVALIDFILE="/tmp/ntp_sync"

[ "$ACTION" = stratum ] || exit 0

logger -t [MustDisplay] "[Time synchronized with NTP server]"

[ -f "$TIMEVALIDFILE" ] || {
        echo "[NTPD] Time is synchronized" >$TIMEVALIDFILE
        # check wifi schedule
        /usr/sbin/wifischedule.sh &
        # APP feature: check guest wifi schedule
        /usr/sbin/wifi_guest_schedule_2g.sh &
        /usr/sbin/wifi_guest_schedule_5g.sh &
        #send installEvent for ntp-syn
        installevent_ntp_sync
}

POT_NTPSYNC=`pot -n | grep ReadFromNTPSYNCFlash | awk -F ' ' '{print $2}'`
if [ "fail" = "$POT_NTPSYNC" ]; then
    pot -N `date +%s`
fi
