#!/bin/sh
. /lib/functions.sh
. /lib/wifi/qcawifi.sh

STDOUT="/dev/null"
DEV_NUM=2

#define special id for country code
UN_sid=00000000
US_sid=55530000
EU_sid=45550000

#define country for country code
US_country="US "
EU_country="GB BZ DE "

#define default for each country code
US_default_country="US"
EU_default_country="GB"

dec_mac(){
	echo $1 | awk 'BEGIN{FS="-";dec=1}{for(i=6;i>0;i--){j="0x"$i;\
	if(i>3){if(j-dec<0){j=j-dec+256;dec=1;}else{j=j-dec;dec=0;}}printf("%02x",j);printf "-"}}' \
	| awk 'BEGIN{FS="-"}{for(i=6;i>0;i--){printf $i;if(i>1){printf "-"}}}'
}

wifi_firm_info(){
	local mac=""
	local cfgMac=""
	local change_flag=""
	local wps_pin=""
	local ssid=""
	
	local idx=0
	cd /sys/class/net/
	[ -d wifi0 ] || load_qcawifi
	for dev in $(ls -d wifi* 2>$STDOUT); do
		case "$(cat ${dev}/hwcaps)" in
			*11bgn) mode_11=bgn;band="2g";;
			*11abgn) mode_11=bgn;band="2g";;
			*11an) mode_11=an_5;band="5g";;
			*11an/ac) mode_11=anac_5;band="5g";;
			*11a/ac) mode_11=ac_5;band="5g";;
			*11abgn/ac) mode_11=anac_5;band="5g";;
		esac
		if [ -z "$(config_get wifi${idx} hwmode)" ]; then
			uci set wireless.wifi${idx}.hwmode=${mode_11}
			change_flag="1"
		fi
		if [ -z "$(config_get wifi${idx} band)" -o "$(config_get wifi${idx} band)" != ${band} ]; then
			uci set wireless.wifi${idx}.band=${band}
			change_flag="1"
		fi

		cfgMac="$(config_get wifi${idx} macaddr)"
		mac="$(getfirm MAC)"
		case $band in
			2g) ;;
			5g) mac=$(dec_mac $mac) ;;
		esac
		mac="$(echo $mac | tr 'a-f' 'A-F')"
		if [ -z "${cfgMac}" -o "${mac}" != "${cfgMac}" ]; then
			uci set wireless.wifi${idx}.macaddr=${mac}
			change_flag="1"
		else
			:
		fi

		if [ -z "$wps_pin" ]; then
			wps_pin="$(getfirm PIN)"
			[ -z "$wps_pin" ] && wps_pin="12345670"
		fi
		if [ -z "$ssid" ]; then
			ssid="$(getfirm SSID)"
		fi
		local suffix
		suffix=$(getfirm MAC | awk -F '-' '{printf $5$6}'|tr 'a-f' 'A-F')
		[ "$band" = "5g" ] && suffix="${suffix}_${band//g/G}"

		local ssid_get
		if [ "$(config_get ath${idx} device)" = "wifi${idx}" ]; then
			if [ -z "$(config_get ath${idx} wps_pin)" ]; then
				uci set wireless.ath${idx}.wps_pin=${wps_pin}
				uci set wireless.ath${idx}.wps_state=2
				change_flag="1"
			fi
			config_get ssid_get ath${idx} ssid
			if [ -z "${ssid_get}" ]; then
				uci set wireless.ath${idx}.ssid="${ssid}_${suffix}"
				change_flag="1"
			fi
			if [ -z "$(config_get ath${idx} encryption)" ]; then
				uci set wireless.ath${idx}.encryption="psk"
				uci set wireless.ath${idx}.psk_key=${wps_pin}
				change_flag="1"
			fi
		fi
		if [ "$(config_get ath${idx}1 device)" = "wifi${idx}" ]; then
			config_get ssid_get ath${idx}1 ssid
			if [ -z "${ssid_get}" ]; then
				uci set wireless.ath${idx}1.ssid="${ssid}_Guest_${suffix}"
				change_flag="1"
			fi
			if [ "$(config_get ath${idx}1 passwd_cycle)" != "never" ]; then
					uci set wireless.ath${idx}1.encryption="psk"
					change_flag="1"
			else
				if [ -z "$(config_get ath${idx}1 encryption)" ]; then
					uci set wireless.ath${idx}1.encryption="none"
					change_flag="1"
				fi
			fi
			local psk_key_get
			config_get psk_key_get ath${idx}1 psk_key
			if [ -z "${psk_key_get}" ]; then
				uci set wireless.ath${idx}1.psk_key=${wps_pin}
				change_flag="1"
			fi
		fi

		# country must be matched with SID (special ID)
		local country="$(config_get wifi${idx} country)"
		local SID="$(getfirm SPECIAL_ID)"
		local countryCode=""
		local match="yes"
		if [ $SID = $US_sid ]; then
			countryCode="US"
		elif [ $SID = $EU_sid ]; then
			countryCode="EU"
		else
			countryCode="UN"
		fi
		if [ $countryCode != "UN" ]; then
			eval echo \$${countryCode}_country | grep -wq $country && match="yes" || match="no"
		fi
		if [ $match == "no" ]; then
			eval country=\$${countryCode}_default_country
			uci set wireless.wifi${idx}.country=$country
			change_flag="1"
		fi

		idx=$(($idx+1))
	done
	if [ -z "$(config_get wps model_name)" ]; then
		local model="$(getfirm MODEL)"
		uci set wireless.wps.model_name=${model}
		change_flag="1"
	fi
	if [ -z "$(config_get wps wps_manufacturer)" -o -z "$(config_get wps wps_manufacturer_url)" ]; then
		local firm="$(getfirm FIRM)"
		local website="$(getfirm WEBSITE)"
		uci set wireless.wps.wps_manufacturer=${firm}
		uci set wireless.wps.wps_manufacturer_url=${website}
		change_flag="1"
	fi
	if [ "$change_flag" = "1" ]; then
		wifi_commit
	fi
}

config_load wireless
wifi_firm_info
