#!/bin/sh

case "$ACTION" in 
	USB3_RESET) 
	echo "================USB3_RESET==========ACTION :  $ACTION========" >> /dev/console
	linux_ver=`grep -o "Linux version [0-9A-Za-z_.-]*" /proc/version | grep -o "[0-9A-Za-z_.-]*$"`
	rmmod /lib/modules/$linux_ver/kernel/drivers/usb/host/xhci-plat-hcd.ko 
	rmmod xhci-hcd
	sleep 1s 
	insmod xhci-hcd
	insmod /lib/modules/$linux_ver/kernel/drivers/usb/host/xhci-plat-hcd.ko 
	;; 
esac
