#!/bin/sh

#This script is used to handle the command from DAL Auto test tool.
#It converts the "control-firmware" commands to "pucfu" commands.
#"control-firmware CHECK_AUTO false" converts to "pucfu -a -d -l".
#"control-firmware CHECK_ON_DEMAND_UPAPP false" converts to "pucfu -u -d -l".
#"control-firmware CHECK_ON_DEMAND_GUI false" converts to "pucfu -g -d -l".
echo "called $0 $1 $2" > /dev/console

if [ "$1" = "CHECK_AUTO" ] && [ "$2" = "false" ]; then
	pucfu -a -d -l
fi

if [ "$1" = "CHECK_ON_DEMAND_UPAPP" ] && [ "$2" = "false" ]; then
	pucfu -u -d -l
fi

if [ "$1" = "CHECK_ON_DEMAND_GUI" ] && [ "$2" = "false" ]; then
	pucfu -g -d -l
fi

