#!/bin/sh
#
# Copyright (c) 2022 Shenzhen TP-LINK Technologies Co.Ltd.
#
# dongao@tp-link.com.hk
# 2022-11-21
# Content:
#	Save patation information of radio

CAL_FLAG_SIZE=1
XCAP_SIZE_5G=3
TSSI_SIZE_5G=28
GAIN_DIFF_SIZE_5G=28
CW_DIFF_SIZE_5G=28
RX_GAIN_SIZE=3
THERMAL_SIZE=2
CCK_SIZE=28
HT40_1S_SIZE=28
TSSICCK_SIZE=28
TSSIHT40_SIZE=28


cal_data_list="cal_flag:${CAL_FLAG_SIZE},0 \
			xcap:${XCAP_SIZE_5G},5g \
			5G_bw40_1s_tssi_A:${TSSI_SIZE_5G},5g \
			5G_bw40_1s_tssi_B:${TSSI_SIZE_5G},5g \
			5G_GAIN_DIFF_A:${GAIN_DIFF_SIZE_5G},5g \
			5G_GAIN_DIFF_B:${GAIN_DIFF_SIZE_5G},5g \
			5G_CW_DIFF_A:${CW_DIFF_SIZE_5G},5g \
			5G_CW_DIFF_B:${CW_DIFF_SIZE_5G},5g \
			5G_rx_gain_low:${RX_GAIN_SIZE},5g \
			5G_rx_gain_mid:${RX_GAIN_SIZE},5g \
			5G_rx_gain_high:${RX_GAIN_SIZE},5g \
			thermalA:${THERMAL_SIZE},5g \
			thermalB:${THERMAL_SIZE},5g \
			pwrlevelCCK_A:${CCK_SIZE},2g \
			pwrlevelCCK_B:${CCK_SIZE},2g \
			pwrlevelHT40_1S_A:${HT40_1S_SIZE},2g \
			pwrlevelHT40_1S_B:${HT40_1S_SIZE},2g \
			pwrlevel_TSSICCK_A:${TSSICCK_SIZE},2g \
			pwrlevel_TSSICCK_B:${TSSICCK_SIZE},2g \
			pwrlevel_TSSIHT40_1S_A:${TSSIHT40_SIZE},2g \
			pwrlevel_TSSIHT40_1S_B:${TSSIHT40_SIZE},2g \
			ther:${THERMAL_SIZE},2g \
			thermal1:${THERMAL_SIZE},2g \
			thermal2:${THERMAL_SIZE},2g \
			cal_flag_new:${CAL_FLAG_SIZE},0"
