#!/bin/sh
# start wps pbc

if [ "$(uci get factory.factorymode.enable)" = "yes" -o "$(/sbin/is_cal)" != "true" ]; then
	if [ ! -e /tmp/btn_check ]; then
		echo 0 > /tmp/btn_check
	fi
	ret=$(cat /tmp/btn_check)
	ret=$(($ret | 0x8))
	echo $ret > /tmp/btn_check

elif [ "$(uci get meshd.meshd.enable)" == "on" -a "$(uci get meshd.meshd.role)" == "agent" ]; then
    FRONT_IFACES=$(uci get profile.@wireless[0].wireless_mesh_sta_2g -c /etc/profile.d)" "$(uci get profile.@wireless[0].wireless_mesh_sta_5g -c /etc/profile.d)
    for vif in $FRONT_IFACES; do
        wifi wps $vif pbc
    done
    
    if [ "$(ps | grep meshd | grep -v grep | wc -l)" != "0" ]; then
        killall tp_wps_led
    fi
    /usr/bin/tp_wps_led &

else
    lua -e "require 'luci.controller.admin.wireless'.wireless_wps_connect({option = 'connect'})"
fi
