#!/bin/sh
# Copyright(c) 2008-2014 Shenzhen TP-LINK Technologies Co.Ltd.
#
# Details : Test internet connectivity.
# Author  : Ye Qianchuan <yeqianchuan@tp-link.net>
# Version : 1.0
# Date    : 11 Apr, 2014

. /lib/functions/network.sh

usage() {
    cat <<EOF
online-test [url [timeout]]
EOF
    exit 0
}

CHECK_URL=tp-link.com
TIMEOUT=2

[ "$1" = "-h" ] && usage

[ -n "$1" ] && CHECK_URL="$1"
[ -n "$2" ] && TIMEOUT="$2"

IFC=wan
ubus list | grep -q network.interface.internet && IFC=internet

network_get_dnsserver DNS_SERVERS "$IFC"
# We only need the primary one.
# DNS_SERVER=${DNS_SERVER%% *}

for server in $DNS_SERVERS; do
	# If DNS servers contain local IP, don't check the internet status.
	check_internet=1
	if [ -n "$server" ]; then
    # FIXME: Ugly and unreliable.
        # FIX that when use ppp to dial, P-t-P addr(ppp server ip) may be the same as the dns server
        ifconfig | grep -wq "inet6* addr: *$server"  || \
            check_internet=0
	fi

	# Check the internet status.
	[ $check_internet -eq 0 ] && \
    	dnslookup -t $TIMEOUT "$CHECK_URL" $server>/dev/null && return 0
done
return 1
