#!/bin/sh
. /lib/functions.sh

# Template for wps status.
# Use board specific script replaces this script.

# This is a example of board47094 (c5300):

wps_status=""
SPLIT=";"
EFMT="PBC Status: .+PIN Status: .+Last WPS result: .+"
#IFACES="wl01 wl11 wl21"
IFACES="ath0 ath1"
#get_ifaces ()
#{
#echo $(lua -e "for _,vip in pairs(require 'luci.model.wireless'.Apcfg().section[2*3*31]) do print(vip) end")
#}

config_load wireless

for vif in ${IFACES}
do
	config_get device "$vif" device
	config_get_bool enable "$vif" enable
	config_get_bool disabled "$device" disabled
	if [ "$disabled" = "0" -a "$enable" = "1" ] ; then
		local status="$(wifi wps $vif status)"
		status=$(echo "$status" | sed -e "/^[[:space:]]*$/d" -e "/wps_shell_over/d")
		if echo $status | grep -qE "$EFMT" ;
		then
			wps_status="$status$SPLIT$wps_status"
		fi
	fi
done

echo "$wps_status"
