#!/bin/sh /etc/rc.common

START=99

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

. /lib/switch/core_phy.sh

start() {
	bcm_set_cpu_lan_mac
	
	bcm_set_iq

	apmode_setup_fc

	setup_all_pause
	
	setup_wan_duplex

	setup_wan_ports

	setup_phy_eee
	
	setup_phy_wirespeed

	# set Standard Max. Frame Size for 6756 eth PHY
	# read cmd: dw 80420028    result:  0x80420028 : 000007d0   (2000 as default)
	# refer to the page 946 of the 6756-PR100.pdf register guide, change it to 1526
	sw 80420028 0x000005f6

	power_up_all_ports

	echo "bcm tm init done" > /dev/console
}
