#!/bin/sh

opmode="$(uci get network.@opmode[0].mode)"
if [ "$opmode" = "router" ]; then
    if [ "$INTERFACE" = "wan" ] || [ "$INTERFACE" = "pptp" ] || [ "$INTERFACE" = "l2tp" ]; then
             /usr/bin/dal_update_wan.sh
    elif [ "$INTERFACE" = "lan" ]; then
             /usr/bin/dal_update_lan.sh
    fi
else
    if [ "$INTERFACE" = "lan" ]; then
        #sleep for waiting 'inet_check.sh' update 'network.inet.check'
        (sleep 5s;/usr/bin/dal_update_wan.sh;/usr/bin/dal_update_lan.sh;) &
    fi
fi