#!/bin/sh

opmode="$(uci -q get network.@opmode[0].mode)"
wan_mode="$(uci get network.inet_global.wan_mode)"

# router mode
if [ $opmode == "router" ]; then
    # wan connection mode is PPTP, only need handle the hotplug event from 'pptp' interface
    if [ $wan_mode == "PPTP" -a  "$INTERFACE" != "pptp" ]; then
        return
    # wan connection mode is L2TP, only need handle the hotplug event from 'l2tp' interface
    elif [ $wan_mode == "L2TP" -a  "$INTERFACE" != "l2tp" ]; then
        return
    # other wan connection modes, only need handle the hotplug event from 'wan' interface
    elif [ $wan_mode != "PPTP" -a $wan_mode != "L2TP" -a "$INTERFACE" != "wan" ]; then
        return
    fi
fi

# ap mode, only need handle the hotplug event from 'lan' interface
if [ $opmode == "ap" -a "$INTERFACE" != "lan" ]; then
	return
fi

# bridge mode, not support Dynamic DNS, ignore all interface hotplug event
if [ $opmode == "bridge" ]; then
	return
fi

config_load ddns

local ddnsProvider
config_get ddnsProvider myddns_ipv4 service_name

if [ $ddnsProvider == "netgear" ]; then
    local ddnsEnable
    local ddnsPid=""
    config_get ddnsEnable myddns_ipv4 enabled

    case "$ACTION" in                                                                        
    ifup)
        if [ "$ddnsEnable" == "1" ]; then
            `killall ntgrddnsd`
            /sbin/ntgrddnsd -m 0 &
        fi
    ;;
    ifdown)
        `killall ntgrddnsd`
    ;;
    esac
else
    case "$ACTION" in
    ifup)
        /etc/init.d/ddns enabled && /usr/lib/ddns/dynamic_dns_updater.sh -n "$INTERFACE" -- start
        ;;
    ifdown)
        /usr/lib/ddns/dynamic_dns_updater.sh -n "$INTERFACE" -- stop
        ;;
    esac
fi
