#!/bin/sh /etc/rc.common

START=99zzzz
STOP=90


boot() {

	##set gpio1 to enable usb power	
	echo 1 > /proc/tplink/power_usb
	echo "enable power usb" > /dev/console

	## set phy_auto_up flag to make phy up automatically when restart network
	echo 1 > /proc/mt7621/phy_auto_up
	touch /tmp/dut_bootdone
	###insmod modules here
    #insmod /lib/modules/$(uname -r)/ehci-hcd.ko
	while [ `cat /proc/tplink/power_usb` -eq 0 ]
	do
		echo 1 > /proc/tplink/power_usb
		echo "try to enable power usb" > /dev/console
		sleep 1
	done &
	
	echo 3 > /proc/sys/vm/drop_caches
	echo "drop caches" > /dev/console
}

start() {
    return 0
}

stop() {
    return 0
}
