#!/bin/sh /etc/rc.common

START=12

start()
{
		uci set ledctrl.GENERAL.enable="on"
		uci set ledctrl.NIGHT.enable="off"
		uci commit ledctrl
        service_start /usr/bin/ledcenter &
}

stop()
{
        service_stop /usr/bin/ledcenter
}