#!/bin/sh /etc/rc.common

START=99

. /lib/ledpm/ledgeneral_core.sh

start()
{
     ledgeneral_start
}

stop()
{
     ledgeneral_stop
}

restart()
{
     ledgeneral_restart
}

reload()
{
     ledgeneral_reload
}
