#!/bin/sh /etc/rc.common

START=99z

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {

        . /lib/switch/core.sh

        apmode_setup_fc
        
		setup_duplex
		
		setup_ports
}

restart() {
		stop
        start
}

shutdown() {
		echo "Shutdown switch!"
}

stop() {
		. /lib/switch/core.sh
		unsetup_ports
}

reload() {
        start
}
