#!/bin/sh

local res

local phy_2g5_support=$(uci get profile.@phyport[0].phyport_2g5_support -c /etc/profile.d)
if [ x"$phy_2g5_support" == x"yes" ]; then
	# "up" is also in "duplex" when wan isn't in auto mode
	res=$(ethctl eth0 media-type | grep -i " Up ");
else
	res=$(ethctl eth0 media-type | grep up);
fi

if [ -n "$res" ]; then
	return 0;
else
	return 1;
fi
