#!/bin/ash
# /usr/etc/profile
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/bin/scripts
export LD_LIBRARY_PATH=/ram/lib:/lib:/lib/iptables

alias d='ls'
alias dir='ls -al'

[ -e /etc/profile ] && sh /etc/profile

