#!/bin/sh
export PATH=$PATH:/usr/bin/scripts
export LD_LIBRARY_PATH=/ram/lib:/lib:/lib/iptables

mount -t usbfs none /proc/bus/usb
mount -t sysfs none /sys

while [ ! -f /tmp/csman/pre4.dat ]
do
	cp -a /usr/mv2ram/* /ram	
done	

#hostname
cp /etc/hostname /proc/sys/kernel/hostname

cat /proc/net/dev

switch reg w 168 17

ifconfig eth2 up
ifconfig lo up
vconfig add eth2 1
vconfig add eth2 2

# insert usb module
#modprobe ehci-hcd
#modprobe ohci-hcd
echo > /proc/sys/kernel/hotplug
gpio l 18 4000 0 1 0 4000 # Cut off 3G Module Power

# insert modules for iptables
insmod /lib/xt_time.ko

# for 3G modem
mkdir -p /var/dev
mkdir -p /var/lock
mkdir -p /var/config

syslogd
klogd -f
getpsec -f 0x3FE000 /tmp/csman/pre1.dat

if [ ! -f /usr/www/index.htm ]; then
	echo "Mount D Section."
	mount -t squashfs /dev/mtdblock4 /usr/www
fi

commander

