#!/bin/sh

# echo ACTION=$ACTION, DEVPATH=$DEVPATH, SUBSYSTEM=$SUBSYSTEM, BUSNUM=$BUSNUM >/dev/console

#echo "--------------" >>/dev/console
#echo "busnum=$BUSNUM" >> /dev/console
#echo "action=$ACTION" >> /dev/console
#echo "intf=$INTERFACE" >> /dev/console
#echo "devnum=$DEVNUM" >> /dev/console
#echo "dev=$DEVICE" >> /dev/console
#echo "pdt=$PRODUCT" >> /dev/console
#echo "type=$TYPE" >> /dev/console
#echo "--------------" >>/dev/console

[ "$BUSNUM" != "" ] && echo ${BUSNUM//0/} > /tmp/printer
INTERFACE_ID=`echo $INTERFACE | cut -d "/" -f 1`

if [ ! "$INTERFACE_ID" = "7" ]
then
	exit 0
fi
		
case "$ACTION" in
        add|remove)
            . /lib/print_server/printer_discovery.sh
            scan_printers
			[ "$ACTION" = "add" ] && {
				usb=$(cat /tmp/printer)
				case "$usb" in
					1|2)
						usb="USB1"
						;;
					3|4)
						usb="USB3"
						;;
					*)
						exit 0
						;;
				esac
				uci set ledctrl.$usb.ledon=1
				ledcli $usb
			}
            ;;
esac