#!/bin/sh

start() {
    /usr/bin/dalh &
    #<< PEGA Mark: support DAL logs
    if [ -e /data/dal/log_dal_when_bootup ]; then
	d2 -c dallogcfg[0].DalhConfigurationApply false
	sleep 1
	setlogLevelForDAL.sh dalh LOG_DEBUG false true
    fi
    #PEGA >>
}

stop() {
    killall dalh
    kill -17 1
    rm /tmp/dalh.log
}



case "$1" in
	start)
		echo -e "\033[35mStarting DALH...\033[0m"
		start
		exit 0
		;;

	stop)
		echo "Stopping DALH..."
		stop
		exit 0
		;;

	*)
		echo "$0: unrecognized option $1"
		exit 1
		;;

esac

