#!/bin/sh

start() {
    /usr/bin/dal_ra &
}

stop() {
    killall dal_ra
    kill -17 1
    rm /tmp/dal_ra.log 
}

boot() {
    start
}

restart() {
    stop
    start
}


case "$1" in
	start)
		echo -e "\033[35mStarting RA...\033[0m"
		boot
		exit 0
		;;

	stop)
		echo "Stopping RA..."
		stop
		exit 0
		;;

	*)
		echo "$0: unrecognized option $1"
		exit 1
		;;

esac

