#!/bin/sh
NTGR_ROUTERLOGIN_COM="75.2.84.193"
NTGR_ROUTERLOGIN_NET="99.83.191.32"
opmode=`/sbin/uci get network.@opmode[0].mode`

if [ "$opmode" == "router" ]
then
  lan_ip=`/sbin/uci get network.lan.ipaddr`
  netmask=`/sbin/uci get network.lan.netmask`
  iptables -t nat -D routerlogin -i br-lan -s $lan_ip/$netmask -d $NTGR_ROUTERLOGIN_COM/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination $lan_ip
  iptables -t nat -D routerlogin -i br-lan -s $lan_ip/$netmask -d $NTGR_ROUTERLOGIN_COM/32 -p tcp -m tcp --dport 443 -j DNAT --to-destination $lan_ip
  iptables -t nat -D routerlogin -i br-lan -s $lan_ip/$netmask -d $NTGR_ROUTERLOGIN_NET/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination $lan_ip
  iptables -t nat -D routerlogin -i br-lan -s $lan_ip/$netmask -d $NTGR_ROUTERLOGIN_NET/32 -p tcp -m tcp --dport 443 -j DNAT --to-destination $lan_ip
  iptables -t nat -A routerlogin -i br-lan -s $lan_ip/$netmask -d $NTGR_ROUTERLOGIN_COM/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination $lan_ip
  iptables -t nat -A routerlogin -i br-lan -s $lan_ip/$netmask -d $NTGR_ROUTERLOGIN_COM/32 -p tcp -m tcp --dport 443 -j DNAT --to-destination $lan_ip
  iptables -t nat -A routerlogin -i br-lan -s $lan_ip/$netmask -d $NTGR_ROUTERLOGIN_NET/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination $lan_ip
  iptables -t nat -A routerlogin -i br-lan -s $lan_ip/$netmask -d $NTGR_ROUTERLOGIN_NET/32 -p tcp -m tcp --dport 443 -j DNAT --to-destination $lan_ip
fi

if [ "$opmode" == "ap" ]
then
  BR_LAN_IP=`ifconfig br-lan 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'`
  BR_MASK=`ifconfig br-lan 2>/dev/null|awk '/inet addr:/ {print $4}'|sed 's/Mask://'`
  iptables -t nat -D routerlogin -i br-lan -s $BR_LAN_IP/$BR_MASK -d $NTGR_ROUTERLOGIN_COM/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination $BR_LAN_IP
  iptables -t nat -D routerlogin -i br-lan -s $BR_LAN_IP/$BR_MASK -d $NTGR_ROUTERLOGIN_COM/32 -p tcp -m tcp --dport 443 -j DNAT --to-destination $BR_LAN_IP
  iptables -t nat -D routerlogin -i br-lan -s $BR_LAN_IP/$BR_MASK -d $NTGR_ROUTERLOGIN_NET/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination $BR_LAN_IP
  iptables -t nat -D routerlogin -i br-lan -s $BR_LAN_IP/$BR_MASK -d $NTGR_ROUTERLOGIN_NET/32 -p tcp -m tcp --dport 443 -j DNAT --to-destination $BR_LAN_IP
  iptables -t nat -A routerlogin -i br-lan -s $BR_LAN_IP/$BR_MASK -d $NTGR_ROUTERLOGIN_COM/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination $BR_LAN_IP
  iptables -t nat -A routerlogin -i br-lan -s $BR_LAN_IP/$BR_MASK -d $NTGR_ROUTERLOGIN_COM/32 -p tcp -m tcp --dport 443 -j DNAT --to-destination $BR_LAN_IP
  iptables -t nat -A routerlogin -i br-lan -s $BR_LAN_IP/$BR_MASK -d $NTGR_ROUTERLOGIN_NET/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination $BR_LAN_IP
  iptables -t nat -A routerlogin -i br-lan -s $BR_LAN_IP/$BR_MASK -d $NTGR_ROUTERLOGIN_NET/32 -p tcp -m tcp --dport 443 -j DNAT --to-destination $BR_LAN_IP
fi
