#!/bin/sh
opmode=$(uci get network.@opmode[0].mode)
[ "$opmode" = "router" ] || return

cone_type=""
filter_type=$(uci -q get firewall.nat_cone.filter_type)

[ "$filter_type" = "secured" ] && cone_type="--coneType restricted"

# NAT CONE only handles UDP packets from WAN
[ -z "$(iptables -t nat -L zone_wan_prerouting | grep CONE)" ] && iptables -t nat -A zone_wan_prerouting -p udp -j CONE $cone_type -m comment --comment NAT_CONE

