#!/bin/sh
iptables -t nat -A routerlogin -p udp --dport 53 -m string --hex-string "|0b|routerlogin|03|net" --algo bm -j REDIRECT --to-ports 53
iptables -t nat -A routerlogin -p tcp --dport 53 -m string --hex-string "|0b|routerlogin|03|net" --algo bm -j REDIRECT --to-ports 53
iptables -t nat -A routerlogin -p udp --dport 53 -m string --hex-string "|0b|routerlogin|03|com" --algo bm -j REDIRECT --to-ports 53
iptables -t nat -A routerlogin -p tcp --dport 53 -m string --hex-string "|0b|routerlogin|03|com" --algo bm -j REDIRECT --to-ports 53
ip6tables -t nat -A routerlogin -p udp --dport 53 -m string --hex-string "|0b|routerlogin|03|net" --algo bm -j REDIRECT --to-ports 53
ip6tables -t nat -A routerlogin -p tcp --dport 53 -m string --hex-string "|0b|routerlogin|03|net" --algo bm -j REDIRECT --to-ports 53
ip6tables -t nat -A routerlogin -p udp --dport 53 -m string --hex-string "|0b|routerlogin|03|com" --algo bm -j REDIRECT --to-ports 53
ip6tables -t nat -A routerlogin -p tcp --dport 53 -m string --hex-string "|0b|routerlogin|03|com" --algo bm -j REDIRECT --to-ports 53

