#!/bin/sh

allow_trust_ip=`/sbin/uci get firewall.@BlockSite[0].allow_TrustIp`
trust_ip_addr=`/sbin/uci get firewall.@BlockSite[0].trust_IpAddr`
blocking_type=`/sbin/uci get blocksite.@UrlFilterCfg[0].blocking_type`

if [ "$blocking_type" == "never" ]; then
  iptables -w -F urlfilter  > /dev/null 2>&1
  ip6tables -w -F urlfilter  > /dev/null 2>&1
else
  iptables -w -A urlfilter -p tcp --dport 80 -j NFQUEUE --queue-num 80 --queue-bypass 2> /var/tmpDebug
  if [ "$allow_trust_ip" == "true" ]; then
    iptables -w -I urlfilter -p tcp -s $trust_ip_addr -j RETURN 2> /var/tmpDebug
  fi
  ip6tables -w -A urlfilter -p tcp --dport 80 -j NFQUEUE --queue-num 80 --queue-bypass 2> /var/tmpDebug
fi
