#! /bin/sh
#AC10v4 gpio配置脚本

SAVE_PATH=$(pwd)

cd /sys/devices/virtual/misc/ugw_gpio/gpio_base/

#sys led
echo 0 > gpio_index
cd sys_led
echo 1 > gpio_id
echo 50 > freq
echo 1 > pattern
echo 1 > start
cd ..

#lan led
echo 5 > gpio_index
cd lan_led
echo 0 > gpio_id
echo 20 > freq
echo 2 > pattern
echo 1 > start
cd .. 

#wan led
#echo 6 > gpio_index
#cd wan_led
#echo 24 > gpio_id
#echo 20 > freq
#echo 2 > pattern
#echo 1 > start
#cd .. 

#wps led
echo 1 > gpio_index
cd wps_led
echo 12 > gpio_id
#echo 1 > pattern
echo 0 > start
cd ..

#2.4G led
echo 2 > gpio_index
cd 2.4G_led
echo 12 > gpio_id
#echo 1 > pattern
echo 1 > start
cd ..

#复位按键
echo 32 > gpio_index
cd reset_btn
echo 27 > gpio_id
#echo 16 > signal
echo 80 > act_time
echo 80 > inact_time
echo 1 > start
#echo xxx > pid
cd ..

#WPS按键
echo 33 > gpio_index
cd wps_btn
echo 27 > gpio_id
#echo 10 > signal
echo 3 > act_time
echo 30 > inact_time
echo 1 > effect_time
echo 1 > start
cd ..

cd $SAVE_PATH
