#!/bin/sh
# stop switch
local LANPHY1=$(uci get switchport_map.switchport_map.lan1)
local LANPHY2=$(uci get switchport_map.switchport_map.lan2)
local LANPHY3=$(uci get switchport_map.switchport_map.lan3)
local LANPHY4=$(uci get switchport_map.switchport_map.lan4)

for lan_phy in $LANPHY1 $LANPHY2 $LANPHY3 $LANPHY4
do
let "lan_phy-=1"
ssdk_sh debug phy set $lan_phy 0 0x800
done