#!/bin/sh
ssdk_sh fdb entry flush 1

lan_mac=$(network_firm lan)
ssdk_sh fdb entry add "${lan_mac//:/-}" 1 forward forward 6 yes no no no no no no no

wan_mac=$(network_firm wan)
ssdk_sh fdb entry add "${wan_mac//:/-}" 5 forward forward 0 yes no no no no no no no
