#!/bin/sh

#This script do broadcom 490x sdk config
#Writen by zhuyu@16.07.21
# Copyright (c) 2016 TP-LINK. All rights reserved.

init_ltqpreinit_sh() {
	. /etc/ltqpreinit/preinit
}

boot_hook_add preinit_main init_ltqpreinit_sh

