#!/bin/sh

have_module () {
	grep "^$1" /proc/modules
	return $?
}

check_module () {
	module="$1"; shift; params="$*"

	grep "^$module" /proc/modules
	[ $? -ne 0 ] && {
		insmod /lib/modules/3.10.104/"$module" "$params"
	}
	# sleep 1
	return $?
}

init_modules () {
	echo "============================== close eth1 phy power ========================="
	switch_cli dev=1 nPortId=15 GSW_PORT_LINK_CFG_SET bLinkForce=1 eLink=1
	echo "============================== close eth1 phy power ends ===================="

	check_module ppa_api.ko
	check_module ppa_api_sw_accel_mod.ko
	check_module macvlan.ko
	check_module ltq_eth_drv_xrx500.ko
	check_module ltq_pae_hal.ko
	check_module ltq_tmu_hal_drv.ko
	check_module ltq_directpath_datapath.ko
	check_module ppa_api.ko
	check_module ppa_api_proc.ko
	check_module ltq_mpe_hal_drv.ko
	check_module ppa_api_tmplbuf.ko
	check_module directconnect_datapath.ko  multiport=2
	check_module dc_mode0-xrx500.ko 
	check_module ppa_api.ko 
	check_module ppa_api_proc.ko 
	check_module swa_stack_al.ko 
	check_module ppa_api_sw_accel_mod.ko 
	check_module ltqmips_dtlk.ko 
	check_module dlrx_fw.ko 
	check_module ppa_api_tmplbuf.ko
	check_module l2nat.ko
	check_module gpio-button-hotplug.ko	
}


init_for_test () {

	ppacmd init
	
	ifconfig lo up
	ifconfig eth0_1 up
	ifconfig eth0_2 up
	ifconfig eth0_3 up
	ifconfig eth0_4 up
	ifconfig eth1 up	

	brctl addbr br-lan
	ip link set br-lan up
	brctl addif br-lan eth0_1
	brctl addif br-lan eth0_2
	brctl addif br-lan eth0_3
	brctl addif br-lan eth0_4
	
	sleep 1
	
	ifconfig br-lan 192.168.0.1 netmask 255.255.255.0

	ppacmd addlan -i br-lan
	ppacmd addlan -i eth0_1
	ppacmd addlan -i eth0_2
	ppacmd addlan -i eth0_3
	ppacmd addlan -i eth0_4
	ppacmd addwan -i eth1
}

init_network()
{
	# Init PPA, default threshold is 3
	echo "tcp-threshold 3" > /etc/ppa.conf
	echo "udp-threshold 3" >> /etc/ppa.conf
	ppacmd init -f /etc/ppa.conf
	
	ifconfig lo up
	ifconfig eth0_1 up
	ifconfig eth0_2 up
	ifconfig eth0_3 up
	ifconfig eth0_4 up

	ifconfig eth1 up	
	echo "============================== close eth1 phy power ========================="
	switch_cli dev=1 nPortId=15 GSW_PORT_LINK_CFG_SET bLinkForce=1 eLink=1
	echo "============================== close eth1 phy power ends ===================="


	brctl addbr br-lan
	ip link set br-lan up
	brctl addif br-lan eth0_1
	brctl addif br-lan eth0_2
	brctl addif br-lan eth0_3
	brctl addif br-lan eth0_4
	
	ppacmd addlan -i br-lan
	ppacmd addlan -i eth0_1
	ppacmd addlan -i eth0_2
	ppacmd addlan -i eth0_3
	ppacmd addlan -i eth0_4
	ppacmd addwan -i eth1	
}

boot_hook_add preinit_main init_modules
boot_hook_add preinit_main init_network