#!/usr/bin/lua 

local params = {...} --The first parameter is the specific purpose
if #params > 0 then
  local dns = require "commonFunc.dnsUtils"
  print( dns.getDNS(params[1]) or "")
else
  print("0.0.0.0")
end

