#!/bin/sh /etc/rc.common
START=96

start() {
    tar -zxvf /usr/bin/ash.tar.gz -C /usr/bin/
    for retry_num in `seq 1 5`
    do
        if [ "$(pidof bdbrokerd)" != "" ]; then
            echo "bdbrokerd is up, call ash start" > /dev/console
        else
            echo "bdbrokerd is not up, delay 2s" > /dev/console
            sleep 2
        fi
    done
    d2 -c armorcfg[0].action none

    /usr/bin/dal_ash 2>/dev/null &
}

stop() {
    killall dal_ash
    kill -17 1
    rm /tmp/dal_ash.log
}

boot() {
    start
}

restart() {
    stop
    start
}
