#!/bin/sh /etc/rc.common

START=22

TRIGGER_DIR=/tmp/router-analytics/trigger_data

start()
{
	#create files and set d2 value for RAE trigger event
	mkdir -p $TRIGGER_DIR/raw_data/backup
	mkdir -p $TRIGGER_DIR/publish_data
	d2 -c DalRaFolderPath[0].dalRaMemoryPath  /tmp/router-analytics/trigger_data/raw_data
	if [ "x`d2 -s DalRaFolderPath[0].dalRaNtpGetResult`" = "x" ];then
		d2 -c DalRaFolderPath[0].dalRaNtpGetResult No
	fi

	/etc/init.d/aws boot &
}
