#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=96
start() {
	echo "control-firmware will be Running when Internet status is UP !!!" > /dev/console
		/usr/sbin/boot-notification > /dev/console &
		echo "CFU will auto check during 00:00~24:00 local time zone (a random number of sec between 0 to of 86400)" > /dev/console
		/usr/sbin/cfu-auto-check > /dev/console &
}
