#!/bin/sh /etc/rc.common
START=20

start() {
	# Start detcable

	if [ "$(/bin/config get factory_mode)" != "1" ]; then
		/usr/bin/detcable 2 $(cat /module_name)
	else
		/usr/bin/detcable 2 $(cat /module_name) 2>/dev/null
	fi
}

stop() {
	killall detcable
}

restart() {
	stop
	start
}
