#!/bin/sh /etc/rc.common
# Copyright (C) 2013-2014 OpenWrt.org

START=00

boot() {
	mount -a
	need_overlay=`mount |grep squashfs`

	[ "$need_overlay" = "" ] && return
	.  /lib/functions/preinit.sh
	[ ! -d /tmp ] && [ -d /var ] && mkdir /var/tmp
	ramoverlay
}

start()
{
	boot
}
