#!/bin/sh /etc/rc.common
# Copyright (C) 2020-2021 Delta Networks Inc.


START=50

CONFIG=/bin/config
CONFIG_FILE="/tmp/net-cgi.conf"

HOST_NAME=$(cat /hardware_version)
UPG_MOD=$($CONFIG get dgc_upg_mod)
HW_ID=$($CONFIG get dgc_hw_id)
if [ "x$HOST_NAME" == "xRAX36S" ]
then
	AN_MODE_4="2401"
	ROUTER_TYPE="AX3000 4-Stream WiFi6 Router "
else
	AN_MODE_4=""
	ROUTER_TYPE=""
fi
MERGE_AU_NZ=1
MAPE_SUPPORT_REGION=AP
SUPPORT_RA_OPT_IN_OPT_OUT=1
SUPPORT_PCCW_IGMP=1
OPTIMIZE_WW_APS_REGION=1
UNIFIED_WIRELESS_REGION=1
DEVICE_NAME_LENGTH=63
SUPPORT_MULTI_LANG_NAMEING=1
SUPPORT_CONTROL_BRIDGE_MODE=1

config() {
	printf "### GENERATED AUTOMATICALLY, PLEASE DON'T EDIT MANUALLY\n"

	printf "%s\n" \
		"nc_upg_mod \"${UPG_MOD}\"" \
		"nc_hw_id \"${HW_ID}\"" \
		"nc_an_mode_4 \"${AN_MODE_4}\"" \
		"nc_router_type \"${ROUTER_TYPE}\"" \
		"nc_merge_au_nz \"${MERGE_AU_NZ}\"" \
		"nc_mape_support_region \"${MAPE_SUPPORT_REGION}\"" \
		"nc_support_ra_opt_in_opt_out \"${SUPPORT_RA_OPT_IN_OPT_OUT}\"" \
		"nc_support_pccw_igmp \"${SUPPORT_PCCW_IGMP}\"" \
		"nc_optimize_ww_ap_region \"${OPTIMIZE_WW_APS_REGION}\"" \
		"nc_unified_wireless_region \"${UNIFIED_WIRELESS_REGION}\"" \
		"nc_device_name_length \"${DEVICE_NAME_LENGTH}\"" \
		"nc_support_multi_lang_naming \"${SUPPORT_MULTI_LANG_NAMEING}\"" \
		"nc_support_control_bridge_mode \"${SUPPORT_CONTROL_BRIDGE_MODE}\"" \
		""
}
update_lang() {
	lower_host_name=$(echo $HOST_NAME | tr '[A-Z]' '[a-z]')
	ls /www/languages-*.js | while read line; do
		sed -i "s/RAX10/$HOST_NAME/g" $line;
		sed -i "s/rax10/$lower_host_name/g" $line;
	done;
}
start() {
	echo "net-cgi is managed by lighttpd!!!"
	config > $CONFIG_FILE
	#update_lang
}

stop() {
	echo "net-cgi is managed by lighttpd!!!"
}

restart() {
	echo "net-cgi is managed by lighttpd!!!"
	start
}

boot() {
	start
}
