#!/bin/sh /etc/rc.common

START=11

boot()
{
	if ! ubinfo /dev/ubi2 -N ntgrcryptD; then
		ubimkvol /dev/ubi2 -s 5MiB -N ntgrcryptD
	fi
	if ! ubinfo /dev/ubi2 -N ntgrcryptK; then
		ubimkvol /dev/ubi2 -s 512KiB -N ntgrcryptK
	fi
	Nencmgr init
}

