#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=14
start() {
	[ -f /etc/sysctl.conf ] && sysctl -p -e >&-
	[ -d /etc/sysctl.d ] && \
		for i in /etc/sysctl.d/*.conf; do
			sysctl -e -p $i >&-
		done

	exit 0
}
