#!/bin/sh

case "$1" in
	boot)
		wlan updateconf
		sleep 1
		wlan down
		sleep 1
		wlan up
		exit 0
		;;

	restart)
		wlan updateconf
		sleep 1
		wlan down
		sleep 1
		wlan up
		exit 0
		;;

	start)
		wlan updateconf
		sleep 1
		wlan down
		sleep 1
		wlan up
		exit 0
		;;

	stop)
		wlan down
		sleep 1
		exit 0
		;;

	*)
		echo "$0: unrecognized option $1"
		exit 1
		;;

esac

