#!/bin/sh /etc/rc.common
START=80

start(){
	[ "$(cat /tmp/openvpn/cert_file_status)" = "1" ] && [ "x`$CONFIG get factory_mode`" != "x1" ] && {
		rm -rf /tmp/md5vpn > /dev/null
		/etc/init.d/openvpn regenerate_cert_file
		/etc/init.d/openvpn start
	}
}
