#!/bin/sh /etc/rc.common

/etc/preinit.d/scapi_utils.sh
USE_PROCD=1
START=11

start_service() {
        file="/tmp/lighttpd5.conf"
        if [ -f "$file" ]
        then
            echo "$file exist."
        else
            cp /opt/vendor/www2/lighttpd5.conf "$file"
        fi
		## add white host to avoid dns rebind
        file_host="/tmp/vendorwhitehost.conf"
        if [ -f "$file_host" ]
        then
            echo "$file_host exist."
        else
            cp /opt/vendor/www2/vendorwhitehost.conf "$file_host"
        fi
        procd_open_instance
        procd_set_param command lighttpd-angel -D -f "$file"
        procd_set_param respawn
        procd_close_instance
}