#!/bin/sh /etc/rc.common

START=70

start() {
	echo -e "\033[33mbootcheck \033[0m" > /dev/console
	if [ -f /etc/shutdown ]; then
		rm /etc/shutdown
		echo -e "\033[33mLast shutdown is normal!! Check /etc/rebootReason \033[0m" > /dev/console
	else
		rm /etc/rebootReason
		echo -e "\033[33mLast shutdown is unknown or kernel crash!! \033[0m" > /dev/console
	fi

}

