#!/bin/ash
# This file should not be modified -- make local changes to
# /etc/ppp/ip-up.local instead

GATEWAY=$5
route del default 
route add default gw $GATEWAY
echo $1 > /var/run/3g_ifname
echo 90 > /var/run/monitor.fifo
echo  1 > /var/run/3g_link_status
