#!/bin/sh

local model=`getfirm MODEL`

if [ "$model" == "Archer AX11000" ] ; then
	uci set locale.sysinfo.model="AX11000 MU-MIMO Tri-Band Gaming Router"
	echo locale.sysinfo.model="AX11000 MU-MIMO Tri-Band Gaming Router" > /dev/console
elif [ "$model" == "Archer AX10000" ] ; then
	uci set locale.sysinfo.model="AX10000 Tri-Band Wi-Fi 6 Gaming Router"
	echo locale.sysinfo.model="AX10000 Tri-Band Wi-Fi 6 Gaming Router" > /dev/console
fi

uci commit
