#!/bin/sh
switch_cli GSW_QOS_PORT_REMARKING_CFG_SET nPortId=5 dev=1 eDSCP_IngressRemarkingEnable=0 bDSCP_EgressRemarkingEnable=0 bPCP_IngressRemarkingEnable=1 bPCP_EgressRemarkingEnable=0 bSTAG_PCP_IngressRemarkingEnable=0 bSTAG_DEI_IngressRemarkingEnable=0 bSTAG_PCP_DEI_EgressRemarkingEnable=0
switch_cli GSW_QOS_SVLAN_CLASS_PCP_PORT_SET dev=1 nPortId=15 nTrafficClass=7 nCPCP=7 nSPCP=7
switch_cli GSW_QOS_SVLAN_CLASS_PCP_PORT_SET dev=1 nPortId=15 nTrafficClass=6 nCPCP=6 nSPCP=6
switch_cli GSW_QOS_SVLAN_CLASS_PCP_PORT_SET dev=1 nPortId=15 nTrafficClass=5 nCPCP=5 nSPCP=5
switch_cli GSW_QOS_SVLAN_CLASS_PCP_PORT_SET dev=1 nPortId=15 nTrafficClass=4 nCPCP=4 nSPCP=4
switch_cli GSW_QOS_SVLAN_CLASS_PCP_PORT_SET dev=1 nPortId=15 nTrafficClass=3 nCPCP=3 nSPCP=3
switch_cli GSW_QOS_SVLAN_CLASS_PCP_PORT_SET dev=1 nPortId=15 nTrafficClass=2 nCPCP=2 nSPCP=2
switch_cli GSW_QOS_SVLAN_CLASS_PCP_PORT_SET dev=1 nPortId=15 nTrafficClass=1 nCPCP=1 nSPCP=1
switch_cli GSW_QOS_SVLAN_CLASS_PCP_PORT_SET dev=1 nPortId=15 nTrafficClass=0 nCPCP=0 nSPCP=0
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=128 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=0 action.eTrafficClassAction=2 action.nTrafficClassAlternate=0 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=129 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=1 action.eTrafficClassAction=2 action.nTrafficClassAlternate=0 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=130 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=2 action.eTrafficClassAction=2 action.nTrafficClassAlternate=0 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=131 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=3 action.eTrafficClassAction=2 action.nTrafficClassAlternate=0 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=132 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=4 action.eTrafficClassAction=2 action.nTrafficClassAlternate=0 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=133 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=5 action.eTrafficClassAction=2 action.nTrafficClassAlternate=0 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=134 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=6 action.eTrafficClassAction=2 action.nTrafficClassAlternate=0 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=135 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=7 action.eTrafficClassAction=2 action.nTrafficClassAlternate=0 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1

switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=136 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=8 action.eTrafficClassAction=2 action.nTrafficClassAlternate=1 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=137 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=9 action.eTrafficClassAction=2 action.nTrafficClassAlternate=1 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=138 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=10 action.eTrafficClassAction=2 action.nTrafficClassAlternate=1 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=139 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=11 action.eTrafficClassAction=2 action.nTrafficClassAlternate=1 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=140 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=12 action.eTrafficClassAction=2 action.nTrafficClassAlternate=1 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=141 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=13 action.eTrafficClassAction=2 action.nTrafficClassAlternate=1 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=142 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=14 action.eTrafficClassAction=2 action.nTrafficClassAlternate=1 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=143 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=15 action.eTrafficClassAction=2 action.nTrafficClassAlternate=1 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1

switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=144 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=16 action.eTrafficClassAction=2 action.nTrafficClassAlternate=2 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=145 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=17 action.eTrafficClassAction=2 action.nTrafficClassAlternate=2 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=146 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=18 action.eTrafficClassAction=2 action.nTrafficClassAlternate=2 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=147 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=19 action.eTrafficClassAction=2 action.nTrafficClassAlternate=2 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=148 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=20 action.eTrafficClassAction=2 action.nTrafficClassAlternate=2 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=149 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=21 action.eTrafficClassAction=2 action.nTrafficClassAlternate=2 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=150 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=22 action.eTrafficClassAction=2 action.nTrafficClassAlternate=2 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=151 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=23 action.eTrafficClassAction=2 action.nTrafficClassAlternate=2 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1

switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=152 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=24 action.eTrafficClassAction=2 action.nTrafficClassAlternate=3 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=153 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=25 action.eTrafficClassAction=2 action.nTrafficClassAlternate=3 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=154 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=26 action.eTrafficClassAction=2 action.nTrafficClassAlternate=3 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=155 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=27 action.eTrafficClassAction=2 action.nTrafficClassAlternate=3 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=156 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=28 action.eTrafficClassAction=2 action.nTrafficClassAlternate=3 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=157 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=29 action.eTrafficClassAction=2 action.nTrafficClassAlternate=3 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=158 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=30 action.eTrafficClassAction=2 action.nTrafficClassAlternate=3 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=159 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=31 action.eTrafficClassAction=2 action.nTrafficClassAlternate=3 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1

switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=160 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=32 action.eTrafficClassAction=2 action.nTrafficClassAlternate=4 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=161 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=33 action.eTrafficClassAction=2 action.nTrafficClassAlternate=4 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=162 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=34 action.eTrafficClassAction=2 action.nTrafficClassAlternate=4 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=163 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=35 action.eTrafficClassAction=2 action.nTrafficClassAlternate=4 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=164 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=36 action.eTrafficClassAction=2 action.nTrafficClassAlternate=4 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=165 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=37 action.eTrafficClassAction=2 action.nTrafficClassAlternate=4 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=166 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=38 action.eTrafficClassAction=2 action.nTrafficClassAlternate=4 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=167 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=39 action.eTrafficClassAction=2 action.nTrafficClassAlternate=4 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1

switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=168 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=40 action.eTrafficClassAction=2 action.nTrafficClassAlternate=5 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=169 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=41 action.eTrafficClassAction=2 action.nTrafficClassAlternate=5 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=170 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=42 action.eTrafficClassAction=2 action.nTrafficClassAlternate=5 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=171 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=43 action.eTrafficClassAction=2 action.nTrafficClassAlternate=5 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=172 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=44 action.eTrafficClassAction=2 action.nTrafficClassAlternate=5 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=173 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=45 action.eTrafficClassAction=2 action.nTrafficClassAlternate=5 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=174 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=46 action.eTrafficClassAction=2 action.nTrafficClassAlternate=5 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=175 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=47 action.eTrafficClassAction=2 action.nTrafficClassAlternate=5 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1

switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=176 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=48 action.eTrafficClassAction=2 action.nTrafficClassAlternate=6 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=177 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=49 action.eTrafficClassAction=2 action.nTrafficClassAlternate=6 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=178 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=50 action.eTrafficClassAction=2 action.nTrafficClassAlternate=6 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=179 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=51 action.eTrafficClassAction=2 action.nTrafficClassAlternate=6 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=180 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=52 action.eTrafficClassAction=2 action.nTrafficClassAlternate=6 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=181 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=53 action.eTrafficClassAction=2 action.nTrafficClassAlternate=6 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=182 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=54 action.eTrafficClassAction=2 action.nTrafficClassAlternate=6 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=183 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=55 action.eTrafficClassAction=2 action.nTrafficClassAlternate=6 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1

switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=184 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=56 action.eTrafficClassAction=2 action.nTrafficClassAlternate=7 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=185 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=57 action.eTrafficClassAction=2 action.nTrafficClassAlternate=7 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=186 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=58 action.eTrafficClassAction=2 action.nTrafficClassAlternate=7 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=187 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=59 action.eTrafficClassAction=2 action.nTrafficClassAlternate=7 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=188 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=60 action.eTrafficClassAction=2 action.nTrafficClassAlternate=7 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=189 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=61 action.eTrafficClassAction=2 action.nTrafficClassAlternate=7 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=190 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=62 action.eTrafficClassAction=2 action.nTrafficClassAlternate=7 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1
switch_cli GSW_PCE_RULE_WRITE dev=1 pattern.nIndex=191 pattern.bEnable=1 pattern.bPortIdEnable=1 pattern.nPortId=5 pattern.bDSCP_Enable=1 pattern.nDSCP=63 action.eTrafficClassAction=2 action.nTrafficClassAlternate=7 action.bRemarkPCP=1 action.bRemarkSTAG_PCP=1