#!/bin/sh
#
# Copyright (c) 2015 The Linux Foundation. All rights reserved.
# Copyright (C) 2011 OpenWrt.org

do_load_caldata() {
	. /lib/ipq806x.sh

	local board=$(ipq806x_board_name)
	local mtdblock=$(find_mtd_part ART)
	BS=512
	FILEBLOCKS=$((131072 / BS))
	SKIP0=$((4096 / BS))
	SKIP1=$((157696 / BS))
	SKIP2=$((311296 / BS))

	echo "do_load_caldata(): board = $board, mtd = $mtdblock" > /dev/kmsg

	case "$board" in
		*ap-mp03.1-*)
			dd if=${mtdblock} of=/lib/firmware/IPQ5018/caldata.bin count=$FILEBLOCKS skip=$SKIP0   # IPQ5018 2.4G
			dd if=${mtdblock} of=/lib/firmware/qcn9000/caldata_1.bin count=$FILEBLOCKS skip=$SKIP1 # QCN9000 5G
		;;
		# U6-Enterprise uses ap-mp03.3 on SPF11.3~SPF11.4, and ap-mp03.4-c1 on SPF12.0
		*ap-mp03.1 | *ap-mp03.3* | *ap-mp03.4*)
			dd if=${mtdblock} of=/lib/firmware/IPQ5018/caldata.bin count=$FILEBLOCKS skip=$SKIP0   # IPQ5018 2.4G
			dd if=${mtdblock} of=/lib/firmware/qcn9000/caldata_1.bin count=$FILEBLOCKS skip=$SKIP1 # QCN9000 5G
			dd if=${mtdblock} of=/lib/firmware/qcn9000/caldata_2.bin count=$FILEBLOCKS skip=$SKIP2 # QCN9000 6G
		;;
		*ap-dk0*)
			dd if=${mtdblock} of=/tmp/wifi0.caldata bs=32 count=377 skip=128
			dd if=${mtdblock} of=/tmp/wifi1.caldata bs=32 count=377 skip=640
		;;
	esac
}

boot_hook_add preinit_ubnt do_load_caldata
