#!/bin/sh
#

# QCA QSDK framework adds some sysctl overrides that cause issues
remove_default_sysctl() {
	if [ -d /etc/sysctl.d ]; then
			rm -f /etc/sysctl.d/*
	fi
}

boot_hook_add preinit_ubnt remove_default_sysctl
