#!/bin/sh

. /lib/functions.sh

config_load sysmode
config_get mode sysmode mode

if [ $mode = "ap" ] ; then
	echo 0x0f0f01 0x0f0f01 > /tmp/phypower_control
else
	echo 0x0f0f00 0x0f0f00 > /tmp/phypower_control
fi