#!/bin/sh

DEBUG=true
if $DEBUG; then
	CONSOLE=/dev/console
else
	CONSOLE=/dev/null
fi

EMMC_DEVICE=mmcblk0
DEVICE_PATH=/dev/$EMMC_DEVICE
DEVICE_PARTITION=/dev/${EMMC_DEVICE}p1
CHECK_PART=false

echo "Start Format EMMC device..." > $CONSOLE

# check /dev/mmcblk mount ?
if mount | grep "${DEVICE_PATH}" 1>/dev/null 2>&1; then
	echo "EMMC ${DEVICE_PATH} already be mounted, don't do anything..." > $CONSOLE;
	return 0;
fi

# check /dev/mmcblk exist
if ls /dev | grep "${EMMC_DEVICE}" 1>/dev/null 2>&1; then
	echo "EMMC ${DEVICE_PATH} device found!" > $CONSOLE;
else
	echo "EMMC ${DEVICE_PATH} device not found!" > $CONSOLE;
	return 0;
fi

# check /dev/mmcblk whether a valid mountable partition
if [ "${CHECK_PART}" == "true" ]; then
	blkid -s UUID -o value ${DEVICE_PATH} 1>/dev/null 2>&1
	if [ $? -eq 0 ]; then
		echo "EMMC ${DEVICE_PATH} already have a valid mountable partition!" > $CONSOLE;
		return 0;
	fi

	# check create partition
	if fdisk -l ${DEVICE_PATH} | grep $DEVICE_PARTITION 1>/dev/null 2>&1; then
		echo "EMMC:found partition, no need to create partition" > $CONSOLE;
		return 0;
	else
		echo "EMMC:no found partition, create it" > $CONSOLE;
		echo -e "n\np\n1\n\n\nwq\n" | fdisk $DEVICE_PATH 1>/dev/null 2>&1;
	fi
fi

# format mmcblk0 with filesystem ntfs
mkntfs $DEVICE_PATH 1>/dev/null 2>&1;

return 0;
