#!/bin/sh

DEBUG=true
if $DEBUG; then
	CONSOLE=/dev/console
else
	CONSOLE=/dev/null
fi

EMMC_DEVICE=mmcblk0
DEVICE_PATH=/dev/$EMMC_DEVICE
DEVICE_PARTITION=/dev/${EMMC_DEVICE}p1

mount_ftp() {
	# check /dev/mmcblk mount ?
	if mount | grep "${DEVICE_PATH}" 1>/dev/null 2>&1; then
		echo "EMMC ${DEVICE_PATH} already be mounted" > $CONSOLE;
	else
		# try mount
		[ -d /mnt/mmcblk0 ] || (mkdir -p /mnt/mmcblk0)
		mount -t tntfs -o umask=0000,rw $DEVICE_PATH /mnt/mmcblk0 1>/dev/null 2>&1
		if [ $? -ne 0 ]; then
			echo "EMMC: mount /mnt/mmcblk0 failed!" > $CONSOLE;
			return 0;
		fi
	fi

	# bind /tmp/ftp/emmc
	[ -d /tmp/ftp/emmc ] || (mkdir -p /tmp/ftp/emmc)
	cp -f /etc/proftpd/proftpd.conf.emmc /etc/proftpd/proftpd.conf
	mount -B /mnt/mmcblk0 /tmp/ftp/emmc 1>/dev/null 2>&1
	if [ -f /var/proftpd.pid ]; then 
        # case stop function didn't kill process
        TMP_PID=$(cat /var/proftpd.pid)
        kill -9 $TMP_PID 1>/dev/null 2>&1
        rm -f $PID_F
    fi

    /usr/sbin/proftpd
    return 0;
}

mount_smb() {
	# check /dev/mmcblk mount ?
	if mount | grep "${DEVICE_PATH}" 1>/dev/null 2>&1; then
		echo "EMMC ${DEVICE_PATH} already be mounted" > $CONSOLE;
	else
		# try mount
		[ -d /mnt/mmcblk0 ] || (mkdir -p /mnt/mmcblk0)
		mount -t tntfs -o umask=0000,rw $DEVICE_PATH /mnt/mmcblk0 1>/dev/null 2>&1
		if [ $? -ne 0 ]; then
			echo "EMMC: mount /mnt/mmcblk0 failed!" > $CONSOLE;
			return 0;
		fi
	fi

	# bind /tmp/smb/emmc
	[ -d /tmp/smb/emmc ] || (mkdir -p /tmp/smb/emmc)
	killall smbd 1>/dev/null 2>&1
	cp -f /etc/samba/smb.conf.template.emmc /etc/samba/smb.conf
	mount -B /mnt/mmcblk0 /tmp/smb/emmc 1>/dev/null 2>&1
	/usr/sbin/smbd -D
	/usr/sbin/nmbd -D
	return 0;
}

echo "Start mount EMMC device for test ..." > $CONSOLE
echo "Mount EMMC device ftp..." > $CONSOLE
mount_ftp
echo "Mount EMMC device smb..." > $CONSOLE
mount_smb
echo "Mount EMMC device for test end, enjoy it..." > $CONSOLE

return 0;
