#!/bin/sh
# Copyright (c) 2016 Shenzhen TP-LINK Technologies Co.Ltd.
# Author		Wang Hao<wanghao@tp-link.com.cn>

cmd=$1
shift

LEDPM_SET_TIME="/tmp/ledpm_enable"
case $cmd in
    *ACTIVE) 
		#send lock to leds
		if [ -f "$LEDPM_SET_TIME" ]; then
			echo "on" > /tmp/led_nightMode
			ubus send leds '{"action":"4","status":"1"}'
		fi
    ;;

    *DORM)
		#do nothing
    ;;
	
    *RESET) 

	;;
esac

