#!/bin/sh /etc/rc.common
START=96
USE_PROCD=1

start() {
    /usr/bin/dal_ash &
}

stop() {
    killall dal_ash
    #Pega, comment out to avoid reboot issue
    #kill -17 1
    rm /tmp/dal_ash.log
}

boot() {
    #++ Pega added
    setlogLevelForDAL.sh dal_ash LOG_DEBUG false true
    #--
    start
}

restart() {
    stop
    start
}

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/dal_ash
    procd_set_param respawn 2 5 99999
    procd_close_instance
}

stop_service() {
    rm /tmp/dal_ash.log
}

