#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

USE_PROCD=1
SERVICE_USE_PID=1
START=70
SERVICE_DEBUG=1
SERVICE_QUIET=0

PROG="/usr/bin/urlfilterd Exclude"
URL_LIST="/var/url_list"
URL_LIST_SCH="/var/url_list_sch"
BLKSITE_ON="/var/blocksite_on.sh"
BLKSITE_OFF="/var/blocksite_off.sh"

config_mode=''
run_stage=''
schedule_file() {
    local allow_trust_ip
    config_get allow_trust_ip $1 allow_TrustIp
    local trust_ip_addr
    config_get trust_ip_addr $1 trust_IpAddr

    echo "iptables -w -A urlfilter -p tcp --dport 80 -j NFQUEUE --queue-num 80 --queue-bypass 2> /var/tmpDebug" >> $BLKSITE_ON
    if [ "$allow_trust_ip" == "true" ]; then
      echo "iptables -w -I urlfilter -p tcp -s $trust_ip_addr -j RETURN 2> /var/tmpDebug" >> $BLKSITE_ON
    fi
    echo "ip6tables -w -A urlfilter -p tcp --dport 80 -j NFQUEUE --queue-num 80 --queue-bypass 2> /var/tmpDebug" >> $BLKSITE_ON

    echo "cp -f /var/url_list_sch /var/url_list > /dev/null 2>&1" >> $BLKSITE_ON
    echo "if [ \"\$1\" != \"noStart\" ]; then" >> $BLKSITE_ON
    echo "   /etc/init.d/blocksite start &" >> $BLKSITE_ON
    echo "fi" >> $BLKSITE_ON

    echo "iptables -w -F urlfilter  > /dev/null 2>&1" >> $BLKSITE_OFF
    echo "iptables -w -D urlfilter -p tcp -s $trust_ip_addr -j RETURN 2> /var/tmpDebug" >> $BLKSITE_OFF
    echo "ip6tables -w -F urlfilter  > /dev/null 2>&1" >> $BLKSITE_OFF
    echo "/etc/init.d/blocksite stop &" >> $BLKSITE_OFF
    echo "rm -fr /var/url_list > /dev/null 2>&1" >> $BLKSITE_OFF
}

site_block() {
    local site
    config_get site $1 url
    echo "$site" >> $URL_LIST
    echo "$site" >> $URL_LIST_SCH
}

block_type() {
    config_get config_mode $1 blocking_type

    if [ "$config_mode" == "never" ]; then
        rm -f $URL_LIST $URL_LIST_SCH 2>/dev/null
        rm -f $BLKSITE_ON $BLKSITE_OFF 2>/dev/null
        iptables -w -F urlfilter  > /dev/null 2>&1
        ip6tables -w -F urlfilter  > /dev/null 2>&1
    elif [ "$config_mode" == "schedule" ]; then
        rm -f $BLKSITE_ON $BLKSITE_OFF 2>/dev/null
        config_load firewall
        config_foreach schedule_file BlockSite
        #schedule_file
        chmod 755 $BLKSITE_ON
        chmod 755 $BLKSITE_OFF
    elif [ "$config_mode" == "always" ]; then
        rm -f $BLKSITE_ON $BLKSITE_OFF 2>/dev/null
        rm -f $URL_LIST_SCH 2>/dev/null
        /etc/firewall.d/urlfilter
    fi
}

run() {
    procd_open_instance
    procd_set_param command /usr/bin/urlfilterd Exclude
    procd_set_param respawn
    procd_close_instance
}

start_service() {
    rm -r $URL_LIST $URL_LIST_SCH 2>/dev/null
    config_load blocksite
    config_foreach site_block site
    config_foreach block_type UrlFilterCfg

    if [ "$config_mode" == "always" ]; then
        run
    elif [ "$config_mode" == "schedule" ]; then
        #For boot case, the init script only generate the related blocksite_on.sh/blocksite_off.sh
        if [ "$run_stage" == "reload" ]; then
            #For configuration change
            /etc/init.d/blocksch restart &
        elif [ "$run_stage" == "" ]; then
            #For schedule on
            run
        fi
    fi
}

stop_service() {
    rm -r $URL_LIST $URL_LIST_SCH 2>/dev/null
    #killall -9 urlfilterd
    service_stop /usr/bin/urlfilterd
}

restart() {
    run_stage="reload"
    stop
    start
}

reload_service() {
    run_stage="reload"
    stop
    start
}

boot() {
    run_stage="boot"
    start
}
