#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50

USE_PROCD=1
PROG=/usr/sbin/crond

validate_cron_section() {
	uci_validate_section system system "${1}" \
		'cronloglevel:uinteger'
}

start_service () {
	mkdir -p /var/spool/cron/crontabs

	procd_open_instance
	procd_set_param command "$PROG" -f -c /var/spool/cron/crontabs
	procd_close_instance
}

service_triggers()
{
	procd_add_validation validate_cron_section
}
