#!/bin/sh /etc/rc.common
START=91

start() {
    /usr/bin/csh &
}

stop() {
    killall csh
    #Pega, comment out to avoid reboot issue
    #kill -17 1
    rm /tmp/csh.log
}

boot() {
    #++ Pega added
    setlogLevelForDAL.sh csh LOG_DEBUG false true
    #--
    start
}

restart() {
    stop
    start
}
