#!/bin/sh /etc/rc.common
#START=17
START=22

set_if_empty() {
    SYM="$1"
    
    # read value, make sure d2d is up.
    until VAL=$(d2 -s ${SYM}); do sleep .1; done
    if [ "${VAL}empty" == "empty" ]; 
    then
        d2 -c ${SYM} -- "$2"; 
    fi
}

start() {
      # Start d2

      # We may need to chmod following in future.
      mkdir -p /tmp/d2

      # TODO:
      # We should source a config file that defines where R/W
      # filesystem is mounted.
      # Hard-coded for now
      
      #Pega ported
      PERSISTDIR=/etc/dal/d2d

      mkdir -p ${PERSISTDIR}
      
      #Pega: dynamic point to qa or prod server
      if [ -f "/etc/reserve-data/dal_qaserver" ]; then
          #BETA_XTRA="-d /etc/d2" //will be use in future if required for qa env
          BETA_XTRA="-d /etc/d2"
          d2d ${BETA_XTRA} ${PERSISTDIR} &
      else
          d2d ${PERSISTDIR} &
      fi
        
        #set some default value

# This is must for all the SKU those are going to use this script. As the router boots up internet should be Unknown until ODM will detect any # network connectivity on the target machine. Do not remove the below line without any further discussion with DAL Team.

# Also the General table in DAL is persistence. So it will always have the latest value whatever it has before the reboot. So to make sure it
# always reset to default as "Unknown" after the router boots up.
#        /usr/bin/dal_update_DB.sh
#        d2 -c general.internetstatus Unknown
#        d2 -c general.devicemodel RBR50
#        d2 -c general.fwrevision "`cat /firmware_version`"
        d2 -c dalmoduleversion.RELEASEVersion "`cat /etc/version.txt`"
#        d2 -c general.fsn "`artmtd -r sn|head -1 |cut -d ':' -f 2-`"
# Commenting general.region as "artmtd" CLI is specific to Qualcomm based SKU so will not be applicable for other SKUs		
#        d2 -c general.region "`artmtd -r region|head -1 |cut -d 'x' -f 2-`"
#        d2 -c general.defaultmac "`ifconfig br0|head -1|awk -F ' ' '{print $5}'`"
#        d2 -c general.wan_ifname         "$(nvram get wan_ifname)"
#        d2 -c general.lan_ifname         "$(nvram get lan_ifname)"
        
      # ODMSTOP ORBI  
       /etc/init.d/d2_countryname.sh &
      #Since d2_countryname.sh  wait for general.RegionName updating to set Region code, should init general table after it.
       /usr/bin/dal_update_DB.sh

}

stop() {
        killall d2d
}

boot() {
    # ODMSTART ORBI
    [ "`cat /tmp/orbi_type`" = "Satellite" ] && return
    # ODMSTOP ORBI        
    start
}

restart() {
        stop
        start
}

