#!/bin/sh /etc/rc.common
#START=99
#Pega: more early init, but still keep dal init order
START=94

start() {
    /usr/bin/dalh &
}

stop() {
    killall dalh
    #Pega, comment out to avoid reboot issue
    #kill -17 1
    rm /tmp/dalh.log
}

boot() {
    #++ Pega added
    setlogLevelForDAL.sh dalh LOG_DEBUG false true
    #--
    start
}

restart() {
    stop
    start
}
