#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

SERVICE_USE_PID=1
START=70
CRON_EMAIL="/var/spool/cron/crontabs/email"
CRON_UPDATE="/var/spool/cron/crontabs/cron.update"
MAILSEND_LOG="/usr/sbin/email_log.sh"

schedule_email() {
    local email_enable
    local email_freq
    local email_day
    local email_hour

    config_get email_enable $1 email_enable
    config_get email_freq $1 email_freq
    config_get email_day $1 email_day
    config_get email_hour $1 email_hour

    if [ "$email_enable" == "1" ]; then
        if [ "$email_freq" == "Hourly" ]; then
            echo "0 */1 * * * $MAILSEND_LOG" > $CRON_EMAIL
    	elif [ "$email_freq" == "Daily" ]; then
	    echo "0 $email_hour * * * $MAILSEND_LOG" > $CRON_EMAIL
    	elif [ "$email_freq" == "Weekly" ]; then
	    echo "0 $email_hour * * $email_day $MAILSEND_LOG" > $CRON_EMAIL
	fi
    else
	echo "" > $CRON_EMAIL
    fi

    echo "email" >> $CRON_UPDATE
}

start() {
    touch "$CRON_UPDATE"
    config_load email
    config_foreach schedule_email email
}

stop() {
    echo 'do nothing' > /dev/null
}

restart() {
    stop
    start
}

