#!/bin/sh /etc/rc.common

START=20
USE_PROCD=1

start_service() {
        procd_open_instance
        procd_set_param command /sbin/lan-monitor
        procd_set_param respawn
        procd_close_instance

        procd_open_instance
        procd_set_param command /sbin/hostname-monitor
        procd_set_param respawn
        procd_close_instance
}
