#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

SERVICE_USE_PID=1

START=50

USE_PROCD=1

checkhttpskey_expire(){
	echo " check https key expire  " > /dev/console
	if [ -f /var/lighttpd/lighttpd.pem ]; then
		if openssl x509 -checkend 864000 -noout -in /var/lighttpd/lighttpd.pem
		then
			echo 'certificate is good for another day !' > /dev/consol
		else
			echo 'certificate has expired or will do so within 10 days' > /dev/consol
			key=`head -200 /dev/urandom | md5sum | cut -f1 -d "-"`
			openssl req -x509 -config /etc/ssl.conf -sha256 -newkey rsa:2048 -passin pass:$key -keyout /var/key.pem -out /var/cert.pem -days 3650 -nodes -passout pass:$key
			if [ -f /var/key.pem ] && [ -f /var/cert.pem ]; then
				cat /var/key.pem /var/cert.pem > /tmp/lighttpd.pem
				rm -f /etc/reserve-data/interleaved-lighttpd.pem
				interleave /tmp/lighttpd.pem  /etc/reserve-data/interleaved-lighttpd.pem
				rm -f /var/lighttpd/lighttpd.pem
				mv /tmp/lighttpd.pem /var/lighttpd/lighttpd.pem
				rm -f /var/key.pem
				rm -f /var/cert.pem
			else
				deinterleave /etc/lighttpd/interleaved-lighttpd-default.pem /var/lighttpd/lighttpd.pem
			fi
		fi
	fi
}

certificateCheck() {
	echo "lighttpd boot .. certificateCheck() ............" > /dev/console
	[ ! -d "/etc/reserve-data" ] && mkdir /etc/reserve-data
	
	[ ! -d "/var/lighttpd" ] && mkdir /var/lighttpd
    
	if [ -e "/etc/reserve-data/facotryResetCertificateCheck" ]; then
		rm -f /etc/reserve-data/facotryResetCertificateCheck
	fi
    
	if [ -e "/etc/reserve-data/interleaved-lighttpd.pem" ]; then
		if [ -s "/etc/reserve-data/interleaved-lighttpd.pem" ]; then
			[ -f /usr/bin/deinterleave ] && {
				deinterleave /etc/reserve-data/interleaved-lighttpd.pem /var/lighttpd/lighttpd.pem
				checkhttpskey_expire
			}
		else
			[ -f /usr/bin/deinterleave ] && {
				deinterleave /etc/lighttpd/interleaved-lighttpd-default.pem /var/lighttpd/lighttpd.pem
				checkhttpskey_expire
			}
		fi
	else
		[ -f /usr/bin/deinterleave ] && {
			echo "certificateCheck interleaved-lighttpd.pem not exist ......" > /dev/console
			key=`head -200 /dev/urandom | md5sum | cut -f1 -d "-"`
			openssl req -x509 -config /etc/ssl.conf -sha256 -newkey rsa:2048 -passin pass:$key -keyout /var/key.pem -out /var/cert.pem -days 3650 -nodes -passout pass:$key
			if [ -f /var/key.pem ] && [ -f /var/cert.pem ]; then
				cat /var/key.pem /var/cert.pem > /tmp/lighttpd.pem
				interleave /tmp/lighttpd.pem  /etc/reserve-data/interleaved-lighttpd.pem
				cp -a /etc/reserve-data/interleaved-lighttpd.pem /etc/lighttpd/interleaved-lighttpd-default.pem
				mv /tmp/lighttpd.pem /var/lighttpd/lighttpd.pem
				rm -f /var/key.pem
				rm -f /var/cert.pem
			else
				deinterleave /etc/lighttpd/interleaved-lighttpd-default.pem /var/lighttpd/lighttpd.pem
			fi
        }
    fi

}

wsmhttpsonlan(){
    wsmEnable=$(uci_get "WebServiceManagement.config.enable_wsm")
    
    [ "$wsmEnable" == "1" ] && {
        cp -f /etc/lighttpd/https_on_lan.conf /var/lighttpd/https_on_lan.inc
        sync
    } || {
        [ -f /var/lighttpd/https_on_lan.inc ] && rm /var/lighttpd/https_on_lan.inc
        touch /var/lighttpd/https_on_lan.inc
        sync
    }
}

start_service() {
    user_exists admin || user_add admin
    [ -d /var/log/lighttpd ] || {
        mkdir -m 0775 -p /var/log/lighttpd
        chgrp www-data /var/log/lighttpd
    }
    
    [ -d /var/lighttpd ] || {
        mkdir -m 0775 -p /var/lighttpd
    }

    blank_state="$(uci_get "netgear.system.blank_state")"
    recoveryCheck="$(uci_get "loginpwd.config.enable_reset")"
    [ "$blank_state" == "1" ] && {
        CONFIG=/etc/lighttpd/lighttpd_blankState.conf
    } || {
        [ "$recoveryCheck" == "1" ] && {
            CONFIG=/etc/lighttpd/lighttpd.conf
        } || {
            CONFIG=/etc/lighttpd/lighttpd_noPwdReset.conf
        }
    }

    /etc/lighttpd/gen_htpasswd.sh
    #certificateCheck
    wsmhttpsonlan
    # start lighttpd
    procd_open_instance
    procd_set_param command /usr/sbin/lighttpd -D -f $CONFIG
    procd_set_param respawn
    procd_close_instance
    #installEvent for soap up/down
    [ "$blank_state" == "1" ] && {
        ubus call ntgr_ra_iot.installEvent send '{"eventType":"soap server up"}'
    }
}

stop_service() {
    service_stop /usr/sbin/lighttpd
    #killall -SIGINT lighttpd
    #[ -f /var/run/lighttpd2.pid ] && {
    #    kill -SIGINT `cat /var/run/lighttpd2.pid`
    #}

    #installEvent for soap up/down
    blank_state="$(uci_get "netgear.system.blank_state")"
    [ "$blank_state" == "1" ] && {
        ubus call ntgr_ra_iot.installEvent send '{"eventType":"soap server down"}'
    }
}

reload_service() {
    stop
    start
}

restart(){
    stop
    start
}

boot() {
	echo "/etc/init.d/lighttpd certificateCheck in boot()" > /dev/console
	certificateCheck
	start
}


