#!/bin/sh /etc/rc.common

START=35
STOP=85
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/odhcpd
	procd_set_param respawn
	procd_close_instance
}

lan_downup() {
	sleep 10
	/usr/sbin/lan_linkdownup.sh "force"
}

reload_service() {
	procd_send_signal odhcpd
	#PeguBU6, YochengLian, 2022.08.05, Fix RAX5-IR006 and move and centralize this operation to luci-reload + lan_linkdownup.sh.
	#[ -f "/var/state/ipv6changed" ] && {
	#	# lan link down up
	#	lan_downup &
	#	rm "/var/state/ipv6changed"
	#}
}

service_triggers()
{
	procd_add_reload_trigger "dhcp"
}

