#!/bin/sh /etc/rc.common

START=90
STOP=10

config_load openvpn

start() {
    local tun_enabled tap_enabled
    config_get tun_enabled openvpn_tun enabled
    config_get tap_enabled openvpn_tap enabled

    echo -e "\033[1;31m ########## ovpncfg.sh start ########## \033[0m" > /dev/console
    if [ $tap_enabled == '1' -a $tun_enabled == '1' ]; then
        echo -e "\033[1;31m ########## ovpncfg.sh start  openvpn enabled ########## \033[0m" > /dev/console
        /etc/openvpncfg/ovpncfg.sh
        /sbin/vpn-monitor &
    else
        echo -e "\033[1;31m ########## ovpncfg.sh start  openvpn disabled ########## \033[0m" > /dev/console
    fi
}

stop() {
    echo -e "\033[1;31m ########## ovpncfg.sh stop ########## \033[0m" > /dev/console
    local wanName
    config_get wanName global wan_name
    /etc/openvpncfg/ovpncfg-stop.sh $wanName
    killall -9 vpn-monitor
}

boot() {
    echo -e "\033[1;31m ########## openvpn boot ########## \033[0m" > /dev/console
    if [ -f "/etc/reserve-data/.cert/genkey-done" ]; then
        CHK_KEY_DONE=`cat /etc/reserve-data/.cert/genkey-done | head -n 1`
        CHK_KEY=`tail -n 2 /etc/reserve-data/.cert/keys/server/ta.key | head -n 1`

        echo "Check Openvpn Key ...."
        echo "CHK_KEY_DONE : "${CHK_KEY_DONE}
        echo "CHK_KEY      : "${CHK_KEY}

        if [ ! "${CHK_KEY_DONE}" == "${CHK_KEY}" ]; then
            echo "Check Openvpn Key error, Regenkey again."
            rm -rf /etc/reserve-data/.cert
        fi
    else
        rm -rf /etc/reserve-data/.cert
    fi

    if [ ! -d "/etc/reserve-data/.cert" ]; then
        echo -e "\033[1;31m ########## cert files NOT exist, generate CA files and key file ########## \033[0m" > /dev/console
        /usr/sbin/genkey.sh &
    fi

    start
}

<<comment
reload() {
    echo -e "\033[1;31m ########## ovpncfg.sh reload ########## \033[0m" > /dev/console
    stop
    start
}
comment
