#!/bin/sh /etc/rc.common
START=60

boot() {
    echo "PEGA pre initial..."
    if [ ! -f "/etc/rabin/ra_nvram" ]; then
        echo "generate default ra nvram"
        /usr/bin/ra_nvram restore
    fi
    if [ ! -f "/tmp/ra_nvram_run" ]; then
        echo "generate ra_nvram_run"
        /usr/bin/ra_nvram init
    fi

    # enable RA debug log by default
    touch /etc/rabin/enable_ra_log

}
