#!/bin/sh /etc/rc.common

START=91
STOP=60

SERVICE=pot

start() {
    if [ -f /usr/sbin/$SERVICE ]; then
	echo "run pot service......"
	# skipped due to using MTD direct access mechanism
	if false; then
	    MTD_DEV=`mount | grep '/mnt/pot' | awk -F ' ' '{print $1}'`
	    if [ "$MTD_DEV" == "" ]; then
	        echo "mount pot partition..."
	        mkdir -p /mnt/pot && mount -t jffs2 /dev/mtdblock11 /mnt/pot
	    fi
	fi

	$SERVICE &

    fi
}

stop() {
    if [ -f /usr/sbin/$SERVICE ]; then
	service_stop /usr/sbin/$SERVICE
    fi
}
