#!/bin/sh /etc/rc.common

START=50

start() {
    config_load qos
    config_get enabled wan enabled
    config_get method wan method

    if [ "$method" == "speedtest" ]; then
        config_get upload wan upload
        config_get download wan download
    else
        config_get upload wan manual_upload
        config_get download wan manual_download
    fi

    if [ "$enabled" == "true" ]; then
        #echo "speedtest upload $upload Kbit" > /dev/console
        #echo "speedtest download $download Kbit" > /dev/console
        # download
        switch ingress-rate on 0 $download
        switch egress-rate on 5 $download
        # upload
        switch egress-rate on 0 $upload
        switch ingress-rate on 5 $upload
    else
        # clear
        # download
        switch ingress-rate off 0
        switch egress-rate off 5
        # upload
        switch egress-rate off 0
        switch ingress-rate off 5
    fi
}

stop() {
    echo "do nothing" > /dev/null
}

restart() {
    stop
    start
}

