#!/bin/sh /etc/rc.common
START=92

start() {
    /usr/bin/dal_ra &
}

stop() {
    killall dal_ra
    #Pega, comment out to avoid reboot issue
    #kill -17 1
    rm /tmp/dal_ra.log 
}

boot() {
    start
}

restart() {
    stop
    start
}
