#!/bin/sh /etc/rc.common
# Copyright (C) 2013-2014 OpenWrt.org

START=00
STOP=90

RTC_DEV=/dev/rtc0
HWCLOCK=/sbin/hwclock

boot() {
	start && exit 0

	local maxtime="$(maxtime)"
	local curtime="$(date +%s)"
	local fwbuildtime="$(cat /etc/openwrt_release | grep BUILD_TIME | cut -d "=" -f2)"
	fwbuildtime="$(echo "${fwbuildtime}" | sed -r 's/\//-/g')"
	local fwbuildtimestamp=$(date -d "${fwbuildtime}:00" +"%s")
	local isDefault="$(uci get netgear.system.blank_state)"

	[ ! -z $isDefault ] && {
		if [[ "$isDefault" -eq "1" ]]; then
			[ ! -z $fwbuildtimestamp ] && {
				if [[ "$fwbuildtimestamp" -eq 0 ]]; then
					[ $curtime -lt $maxtime ] && date -s @$maxtime
				else
					date -s @$fwbuildtimestamp
				fi
			} || {
				[ $curtime -lt $maxtime ] && date -s @$maxtime
			}
		else
			[ $curtime -lt $maxtime ] && date -s @$maxtime
		fi
	} || {
		[ $curtime -lt $maxtime ] && date -s @$maxtime
	}

	#[ $curtime -lt $maxtime ] && date -s @$maxtime
}

start() {
	[ -e "$RTC_DEV" ] && [ -e "$HWCLOCK" ] && $HWCLOCK -s -u -f $RTC_DEV
}

stop() {
	[ -e "$RTC_DEV" ] && [ -e "$HWCLOCK" ] && $HWCLOCK -w -u -f $RTC_DEV && \
		logger -t sysfixtime "saved '$(date)' to $RTC_DEV"
}

maxtime() {
	local file newest

	for file in $( find /etc -type f ) ; do
		[ -z "$newest" -o "$newest" -ot "$file" ] && newest=$file
	done
	[ "$newest" ] && date -r "$newest" +%s
}
