#!/bin/sh /etc/rc.common

START=91
STOP=60

SERVICE=ntgr_trafficmeter

start() {
    if [ -f /usr/sbin/$SERVICE ]; then
	echo "run Netgear traffic meter daemon......"

	$SERVICE &

    fi
}

stop() {
    if [ -f /usr/sbin/$SERVICE ]; then
	service_stop /usr/sbin/$SERVICE
    fi
}

reload() {
## Traffic Meter firewall rules by 'tm.tm_control.warterMarkStstus' value!

markStatus=`/sbin/uci get tm.tm_control.warterMarkStatus`

case $markStatus in
    0|2)
	iptables -w -t nat -F FW_NAT_PREROUTING_TM
    ;;
    1)
	iptables -w -t nat -F FW_NAT_PREROUTING_TM
	iptables -w -t nat -A FW_NAT_PREROUTING_TM -p tcp -m multiport --dports 80 -j REDIRECT --to-ports 27081
	iptables -w -t nat -A FW_NAT_PREROUTING_TM -p tcp -m multiport --dports 443 -j REDIRECT --to-ports 27443
    ;;
    3|4)
	iptables -w -t nat -F FW_NAT_PREROUTING_TM
	iptables -w -t nat -A FW_NAT_PREROUTING_TM -i br-lan -p udp -m multiport --dports 53 -j REDIRECT --to-ports 38053
	iptables -w -t nat -A FW_NAT_PREROUTING_TM -p tcp -m multiport --dports 80 -j REDIRECT --to-ports 26081
	iptables -w -t nat -A FW_NAT_PREROUTING_TM -p tcp -m multiport --dports 443 -j REDIRECT --to-ports 26443
    ;;
    5)
	block_on=`/sbin/uci get tm.tm_control.block_on`
	lanIp=`/sbin/uci get network.lan.ipaddr`

	if [ "$block_on" == "true" ]; then
	    iptables -w -t nat -F FW_NAT_PREROUTING_TM
	    iptables -w -t nat -A FW_NAT_PREROUTING_TM -i br-lan -p udp -m multiport --dports 53 -j REDIRECT --to-ports 38053
	    iptables -w -t nat -A FW_NAT_PREROUTING_TM -p tcp -s $lanIp -j ACCEPT
	    iptables -w -t nat -A FW_NAT_PREROUTING_TM -p tcp -d $lanIp -j ACCEPT
	    iptables -w -t nat -A FW_NAT_PREROUTING_TM -p tcp -m multiport --dports 80 -j REDIRECT --to-ports 26081
	    iptables -w -t nat -A FW_NAT_PREROUTING_TM -p tcp -m multiport --dports 443 -j REDIRECT --to-ports 26443
	else
	    iptables -w -t nat -F FW_NAT_PREROUTING_TM
	fi
    ;;
    *) echo "unknown status"
    ;;
esac


}
