#!/bin/sh /etc/rc.common

START=25
STOP=86

shutdown() {
	/sbin/wifi down
}

start() {
	/usr/lib/lua/commonFunc/ucitrack_applyWiFiSetting.lua
	# check wifi schedule
	/usr/sbin/wifischedule.sh &
	# APP feature: check guest wifi schedule
	/usr/sbin/wifi_guest_schedule_2g.sh &
	/usr/sbin/wifi_guest_schedule_5g.sh &
	uci -c /var/state set hotplug_wifi.bridge.status=disable
	uci -c /var/state commit hotplug_wifi
	killall -WINCH led_control
	/usr/bin/lua -lcommonFunc/wifiUtils_convertWifiSettings -e "local M = require \"commonFunc.wifiUtils_convertWifiSettings\";"
	/usr/sbin/installEvent_wifi_status.sh "on" &
}

stop() {
	/sbin/wifi down
	/usr/sbin/installEvent_wifi_status.sh "off" &
}

boot() {
	/usr/bin/lua -lcommonFunc/wifiUtils_convertWifiSettings -e "local M = require \"commonFunc.wifiUtils_convertWifiSettings\";"
	start
}

restart() {
	stop
	start
}

