#!/bin/sh
KVER=2.6.35
export MODULE_PATH=/lib/modules/$KVER/net
/sbin/insmod $MODULE_PATH/adf.ko
/sbin/insmod $MODULE_PATH/asf.ko
/sbin/insmod $MODULE_PATH/ath_hal.ko
/sbin/insmod $MODULE_PATH/ath_rate_atheros.ko
/sbin/insmod $MODULE_PATH/ath_dfs.ko
/sbin/insmod $MODULE_PATH/ath_dev.ko
/sbin/insmod $MODULE_PATH/umac.ko

wlanconfig ath create wlandev wifi0 wlanmode ap
wlanconfig ath create wlandev wifi1 wlanmode ap

ifconfig wifi0 txqueuelen 1000
ifconfig wifi1 txqueuelen 1000

ifconfig ath0 txqueuelen 1000
iwpriv ath0 disablecoext 1
iwpriv ath0 mode 11NGHT40PLUS
iwconfig ath0 essid test_11ng mode master
iwconfig ath0 channel 6

ifconfig ath1 txqueuelen 1000
iwpriv ath1 mode 11NAHT40PLUS
iwconfig ath1 essid test_11na mode master
iwconfig ath1 channel 36

brctl addbr br0
brctl addif br0 eth0
brctl addif br0 ath0
brctl addif br0 ath1
brctl setfd br0 0

#ifconfig eth0 0.0.0.0
ifconfig br0 192.168.0.10
ifconfig ath0 up
ifconfig ath1 up
