#!/bin/sh
# Copyright(c) 2008-2014 Shenzhen TP-LINK Technologies Co.Ltd.
#
# Details : Test internet connectivity.
# Author  : Ye Qianchuan <yeqianchuan@tp-link.net>
# Version : 1.0
# Date    : 11 Apr, 2014

. /lib/functions/network.sh

usage() {
    cat <<EOF
online-test [url [timeout]]
EOF
    exit 0
}

# randomly pick two urls
LIST="google.com amazon.com yahoo.com ebay.com wikipedia.org reddit.com netflix.com live.com bing.com linkedin.com"
CHECK_URL=$(echo $LIST | awk 'BEGIN{srand();} {while(n<2){num=int(rand()*NF+1);if(!(num in a)){printf $num" ";a[num]=1;n++}}}')

TIMEOUT=2

[ "$1" = "-h" ] && usage

[ -n "$1" ] && CHECK_URL="$1"
[ -n "$2" ] && TIMEOUT="$2"

IFC=wan
ubus list | grep -q network.interface.internet && IFC=internet

network_get_dnsserver DNS_SERVERS "$IFC"

for d in $DNS_SERVERS; do
	for url in $CHECK_URL; do
		# If DNS servers contain local IP, don't check the internet status.
		check_internet=1
		if [ -n "$d" ]; then
		    # FIXME: Ugly and unreliable.
		    ifconfig | grep "inet6* addr" | grep -wq "$d" || \
		        check_internet=0
		fi

		# Check the internet status.
		[ $check_internet -eq 0 ] && \
		    dnslookup -t $TIMEOUT "$url" $d >/dev/null && exit 0
		# second try reduce to 1s
		TIMEOUT=1
	done
done
exit 1
