#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=45

# For intel C2700
set_local_session_learning_for_lro()
{
        # -m comment --comment "local session learning for TCP litepath and LRO"

        local iRule="INPUT -p tcp -m state --state ESTABLISHED -j EXTMARK --set-mark 0x80000000/0x80000000"
        iptables -t mangle -C $iRule 2>/dev/null || {
                iptables -t mangle -I $iRule
        }
}

FW_LIBDIR=/lib/firewall

fw() {
	. $FW_LIBDIR/core.sh
	fw_$1
}

start() {
	fw start
	
	set_local_session_learning_for_lro
}

stop() {
	fw stop
}

restart() {
	fw restart
	
	set_local_session_learning_for_lro
}

reload() {
	fw reload
	
	set_local_session_learning_for_lro
}
