#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=46

IPTV_LIBDIR=/lib/iptv

iptv() {
	. ${IPTV_LIBDIR}/iptv_core.sh
	iptv_$1
}

start() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
		iptv start
	fi
}

stop() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
		iptv stop
	fi
}

restart() {
	iptv restart
	[ -e /tmp/tm-shn/intel_SAE_QoS_conf.sh ] && {
		. /tmp/tm-shn/intel_SAE_QoS_conf.sh ifb1 disable
		. /tmp/tm-shn/intel_SAE_QoS_conf.sh ifb1 enable
	}
	
	[ -e /lib/qos/intel_SAE_QoS_conf.sh ] && {
		. /lib/qos/intel_SAE_QoS_conf.sh
		
		local enable
		config_load qos_v2
		config_get enable settings enable
	
		[ "$enable" = "on" ] && {
			disable_redirect_netifs
			enable_redirect_netifs
		}
	}
}
