#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2016 TP-Link
# Author: Zhu Junjie <zhujunjie@tp-link.net>
# Date: 14Nov16

START=99

local TEMP_UCI_PATH=/tmp/tmp-device-config
local INSIGHTS_UCI_FILE=/tmp/tmp-device-config/pc_insights
local DEV_INFO_UCI_FILE=/tmp/tmp-device-config/shn_dev_info
local DEV_STATS_UCI_FILE=/tmp/tmp-device-config/shn_dev_stats

start() {
	if [ ! -f $INSIGHTS_UCI_FILE ]; then
		if [ ! -d $TEMP_UCI_PATH ]; then
			mkdir $TEMP_UCI_PATH
		fi
		cp /etc/config/pc_insights $TEMP_UCI_PATH
	fi

	if [ ! -f $DEV_INFO_UCI_FILE ]; then
		if [ ! -d $TEMP_UCI_PATH ]; then
			mkdir $TEMP_UCI_PATH
		fi
		touch $DEV_INFO_UCI_FILE
	fi
	
	if [ ! -f $DEV_STATS_UCI_FILE ]; then
		if [ ! -d $TEMP_UCI_PATH ]; then
			mkdir $TEMP_UCI_PATH
		fi
		cp /etc/config/shn_dev_stats $TEMP_UCI_PATH
	fi
	
	/usr/bin/tm_shn -p
	echo "Parent Control config trigger start!"
}

stop(){
	echo "Parent Control config trigger stop!"
}
