#!/bin/sh /etc/rc.common

START=30
STOP=90

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
    /sbin/wifi_firm
    /sbin/wifi_check_country
    /sbin/wifi init
	return 0
}

restart() {
	/sbin/wifi reload
	return 0
}

stop() {
	/sbin/wifi down
	return 0
}

reload() {
	/sbin/wifi reload
	return 0
}
