#!/bin/sh /etc/rc.common

START=99

start () {
    config_load sysmode
    config_get mode "sysmode" "mode"
    config_load network
    config_get ipaddr "wan" "ipaddr"

    if [ $mode == 'ap' ]; then
	
		# For INTEL_GRX350
		ppacmd setppefp -f 1
		config_ppa
		
		switch_cli dev=1 GSW_PCE_RULE_WRITE pattern.nIndex=60 pattern.bEnable=1 pattern.bProtocolEnable=1 pattern.nProtocol=0x11 pattern.bAppDataLSB_Enable=1 pattern.nAppDataLSB=0x35 action.ePortMapAction=4 action.nForwardPortMap=1
		
		/etc/init.d/smartip restart
    fi
    return 0
}
