#!/bin/sh
chk_mul_wifi_domain=1

ifconfig lo 127.0.0.1

CINIT=1

hostname rlx-linux

mount -t proc proc /proc
mount -t ramfs ramfs /var

mkdir /var/tmp
mkdir /var/web
mkdir /var/log
mkdir /var/run
mkdir /var/lock
mkdir /var/system
mkdir /var/dnrd
mkdir /var/lib
mkdir /var/lib/misc

###For Oprofile
mkdir /var/root

###for tr069
mkdir /var/cwmp_default
mkdir /var/cwmp_config

if [ ! -f /var/cwmp_default/DefaultCwmpNotify.txt ]; then
	cp -p /etc/DefaultCwmpNotify.txt /var/cwmp_default/DefaultCwmpNotify.txt 2>/dev/null
fi

##For miniigd
mkdir /var/linuxigd
cp /etc/tmp/pics* /var/linuxigd 2>/dev/null

##For pptp
mkdir /var/ppp
mkdir /var/ppp/peers

#smbd
mkdir /var/config
mkdir /var/private
mkdir /var/tmp/usb

#snmpd
mkdir /var/net-snmp

cp /bin/pppoe.sh /var/ppp/true
echo "#!/bin/sh" > /var/ppp/true
#echo "PASS"     >> /var/ppp/true

#for console login
cp /etc/shadow.sample /var/shadow

#extact web pages
cd /web
#flash extr /web
cd /
 
mkdir -p /var/udhcpc
mkdir -p /var/udhcpd
cp /bin/init.sh /var/udhcpc/eth0.deconfig
echo " " > /var/udhcpc/eth0.deconfig
cp /bin/init.sh /var/udhcpc/eth1.deconfig
echo " " > /var/udhcpc/eth1.deconfig
cp /bin/init.sh /var/udhcpc/br0.deconfig
echo " " > /var/udhcpc/br0.deconfig
cp /bin/init.sh /var/udhcpc/wlan0.deconfig
echo " " > /var/udhcpc/wlan0.deconfig

if [ "$chk_mul_wifi_domain" == "1" ]; then
	wifi_domain_key=`flash get HW_WLAN0_REG_DOMAIN | sed "s/HW_WLAN0_REG_DOMAIN=//"`
	tome_zone_key=`flash get DEF_NTP_TIMEZONE | sed "s/DEF_NTP_TIMEZONE=//" | sed "s/\"//" | sed "s/\"//"`
	def_custom_passthru_key=`flash get DEF_CUSTOM_PASSTHRU_ENABLED | sed "s/DEF_CUSTOM_PASSTHRU_ENABLED=//"`
	def_ipv6_dns_auto_key=`flash get DEF_IPV6_DNS_AUTO | sed "s/DEF_IPV6_DNS_AUTO=//"`
	def_ipv6_dhcp_mode_key=`flash get DEF_IPV6_DHCP_MODE | sed "s/DEF_IPV6_DHCP_MODE=//"`
	def_ipv6_dhcp_pd_key=`flash get DEF_IPV6_DHCP_PD_ENABLE | sed "s/DEF_IPV6_DHCP_PD_ENABLE=//"`
	def_ipv6_dhcp_rapid_commit_key=`flash get DEF_IPV6_DHCP_RAPID_COMMIT_ENABLE | sed "s/DEF_IPV6_DHCP_RAPID_COMMIT_ENABLE=//"`
	def_super_name_key=`flash get DEF_SUPER_NAME | sed "s/DEF_SUPER_NAME=//" | sed "s/\"//" | sed "s/\"//"`
	def_super_password_key=`flash get DEF_SUPER_PASSWORD | sed "s/DEF_SUPER_PASSWORD=//" | sed "s/\"//" | sed "s/\"//"`
	def_user_name_key=`flash get DEF_USER_NAME | sed "s/DEF_USER_NAME=//" | sed "s/\"//" | sed "s/\"//"`
	def_user_password_key=`flash get DEF_USER_PASSWORD | sed "s/DEF_USER_PASSWORD=//" | sed "s/\"//" | sed "s/\"//"`
	user_name_key=`flash get USER_NAME | sed "s/USER_NAME=//" | sed "s/\"//" | sed "s/\"//"`
	user_password_key=`flash get USER_PASSWORD | sed "s/USER_PASSWORD=//" | sed "s/\"//" | sed "s/\"//"`
	if [ "$def_super_name_key" == "" ]; then
		echo "======change default super user======"
		flash set DEF_SUPER_NAME $def_user_name_key
		sleep 1
		flash set DEF_SUPER_PASSWORD $def_user_password_key
		sleep 1
		flash set DEF_USER_NAME user
		sleep 1
		flash set DEF_USER_PASSWORD user
		sleep 1
		flash set SUPER_NAME $user_name_key
		sleep 1
		flash set SUPER_PASSWORD $user_password_key
		sleep 1
		flash set USER_NAME user
		sleep 1
		flash set USER_PASSWORD user
		sleep 1
	fi
	if [ "$tome_zone_key" != "3\ 2" ]; then
		echo "======change default time zone======"
		flash set DEF_NTP_TIMEZONE 3\ 2
		sleep 1
	fi
	if [ "$def_custom_passthru_key" != "0" ]; then
		flash set DEF_CUSTOM_PASSTHRU_ENABLED 0
		sleep 1
	fi
	if [ "$def_ipv6_dns_auto_key" != "1" ]; then
		flash set DEF_IPV6_DNS_AUTO 1
		sleep 1
	fi
	if [ "$def_ipv6_dhcp_mode_key" != "1" ]; then
		flash set DEF_IPV6_DHCP_MODE 1
		sleep 1
	fi
	if [ "$def_ipv6_dhcp_pd_key" != "1" ]; then
		flash set DEF_IPV6_DHCP_PD_ENABLE 1
		sleep 1
	fi
	if [ "$def_ipv6_dhcp_rapid_commit_key" != "1" ]; then
		flash set DEF_IPV6_DHCP_RAPID_COMMIT_ENABLE 1
		sleep 1
	fi
	if [ "$wifi_domain_key" != "3" ]; then
		echo "======$wifi_domain_key======"
		flash set HW_WLAN0_REG_DOMAIN 3
	fi
fi

if [ "$CINIT" = 1 ]; then
startup.sh
fi

# for wapi certs related
mkdir /var/myca
# wapi cert(must done before init.sh)
cp -rf /usr/local/ssl/* /var/myca/ 2>/dev/null
# loadWapiFiles >/dev/null 2>&1
 
# for wireless client mode 802.1x
mkdir /var/1x
cp -rf /usr/1x/* /var/1x/ 2>/dev/null
 
# Start system script
init.sh gw all
 
# modify dst-cache setting
echo "8192" > /proc/sys/net/ipv4/route/max_size
echo "180" > /proc/sys/net/ipv4/route/gc_thresh
echo 20 > /proc/sys/net/ipv4/route/gc_elasticity
# echo 35 > /proc/sys/net/ipv4/route/gc_interval
echo 60 > /proc/sys/net/ipv4/route/secret_interval
# echo 10 > /proc/sys/net/ipv4/route/gc_timeout
 
# echo "4096" > /proc/sys/net/nf_conntrack_max
echo "4096" > /proc/sys/net/netfilter/nf_conntrack_max
echo "600" > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_established
echo "20" > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_time_wait
echo "20" > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_close
echo "90" > /proc/sys/net/ipv4/netfilter/ip_conntrack_udp_timeout
echo "120" > /proc/sys/net/ipv4/netfilter/ip_conntrack_udp_timeout_stream
echo "90" > /proc/sys/net/ipv4/netfilter/ip_conntrack_generic_timeout
echo "1048576" > /proc/sys/net/ipv4/rt_cache_rebuild_count
echo "32" > /proc/sys/net/netfilter/nf_conntrack_expect_max

#echo 1 > /proc/sys/net/ipv4/ip_forward #don't enable ip_forward before set MASQUERADE
#echo 2048 > /proc/sys/net/core/hot_list_length

# start web server
boa


