#!/bin/sh
START=92

start() {
    /usr/bin/dal_ra &
}

stop() {
    killall dal_ra
    kill -17 1
    rm /tmp/dal_ra.log 
}

boot() {
    start
}

restart() {
    stop
    start
}

case $1 in
	"start" )
		start
		;;
	"stop" )
		stop
		;;
	"boot" )
		boot
		;;
	"restart" )
		restart
		;;
esac