#!/bin/sh

source /opt/lantiq/etc/ugw_notify_defs.sh

if [ "$ACTION" = "mount" ]; then
	ls /mnt/usb/*/ 2>/dev/null && {
####PegaBU6, 20190815, No calling this ubus call to avoid ubus message hang. Our implementation does not need Intel USB DB(data).
####        ubus call servd notify '{ "id": '$NOTIFY_USB_DEVICE_MOUNTED', "type": false}'
    echo "No execute ubus call usb device mounted!!!" >/dev/console
	}
elif [ "$ACTION" = "umount" ]; then
####PegaBU6, 20190815, No calling this ubus call to avoid ubus message hang. Our implementation does not need Intel USB DB(data).
####        ubus call servd notify '{ "id": '$NOTIFY_USB_DEVICE_MOUNTED', "type": false }'
    echo "No execute ubus call usb device umounted!!!" >/dev/console
fi

