#!/bin/sh /etc/rc.common

# To avoid bugs, both start and restart force restart.
# By Zoey Hsiao, 14Oct15

START=99

. /lib/auto_reboot.sh

start()
{
	 autoreboot_start &
}

stop()
{
     autoreboot_stop
}

restart()
{
     start
}
