#!/bin/sh /etc/rc.common
# Copyright (c) 2016 Shenzhen TP-LINK Technologies Co.Ltd.
# Author  : Sharon Lin <sharon.lin@tp-link.com>
# Date    : 3 Mar 2016

START=99
STOP=1

. /lib/diehard/diehard_core.sh

start()
{
        diehard_start
}

stop()
{
        diehard_stop
}
