#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=29
boot() {
	# load extern modules
	load_modules "$(ls /etc/modules.d/* | grep -e button-poll)"

	[ -d /tmp/root ] && {
		lock /tmp/.switch2jffs
		firstboot switch2jffs
		lock -u /tmp/.switch2jffs
	}

	load_modules "/etc/modules.d/30-gpio-button-hotplug"

	# process user commands
	[ -f /etc/rc.local ] && {
		sh /etc/rc.local
	}

	# set leds to normal state
	. /etc/diag.sh
	set_state done

	insmod panic_probe
}
