#!/bin/sh /etc/rc.common
# Copyright(c) 2008-2014 Shenzhen TP-LINK Technologies Co.Ltd.
#
# Details : The init script for logd.
# Author  : Ye Qianchuan <yeqianchuan@tp-link.net>
# Version : 1.0
# Date    : 17 Jul, 2014

START=11
SERVICE_DAEMONIZE=1

get_log_size() {
    config_get log_size $1 log_size 128
}

start() {
    local args log_size log_debug

    config_load system
    config_foreach get_log_size system

    config_load syslog
    config_get log_debug mode debug_mode off

    args="-C ${log_size}"
    [ "$log_debug" = "on" ] && args="$args -a"
    service_start /usr/sbin/logd $args
}

stop() {
    service_stop /usr/sbin/logd
}
