#!/bin/sh /etc/rc.common
# Copyright(c) 2008-2016 Shenzhen TP-LINK Technologies Co.Ltd.
#
# Details : The init script for operation mode switch (Router, AP, Range Extender).
# Author  : Liu ChiaYu <edgar.liu@tp-link.net>
# Version : 1.0
# Date    : 26 Feb, 2016

START=12

read_sysmode() {
	#
	# add for muli-mode (AP,RT,RE mode switch)
	#
	config_load sysmode
	config_get mode sysmode mode router
}

disable_module() {
	local disable_module="/etc/disable_module"
	local cmd=""
	
	disable_module="${disable_module}_${mode}"
	echo "operatin_module : disable_module = ${disable_module}" > /dev/console
	if [ ! -e ${disable_module} ] 
	then
		echo "operatin_module :${disable_module} doesn't exist!" > /dev/console
		return
	fi
	
	while read line;do
		[ -n ${line} -a -d /sys/module/${line} ] && 
		{	
			echo "operatin_module execute : /sbin/rmmod ${line}" > /dev/console
			/sbin/rmmod ${line}
		}			
	done < ${disable_module}
}

. /lib/functions.sh

start() {
    mode="router"
    read_sysmode
    disable_module
}
