#!/bin/sh /etc/rc.common
# Copyright(c) 2008-2016 Shenzhen TP-LINK Technologies Co.Ltd.
#
# Details : The init script for operation mode switch (Router, AP, Range Extender).
# Author  : Liu ChiaYu <edgar.liu@tp-link.net>
# Version : 1.0
# Date    : 26 Feb, 2016

START=10

read_sysmode() {
	#
	# add for muli-mode (AP,RT,RE mode switch)
	#
	config_load sysmode
	config_get mode sysmode mode router
}

disable_service() {
	local disable_list="/etc/disable_list"
	local cmd=""
	
	disable_list="${disable_list}_${mode}"
	echo "operatin_mode : disable_list = ${disable_list}" > /dev/console
	if [ ! -e ${disable_list} ] 
	then
		echo "operatin_mode :${disable_list} doesn't exist!" > /dev/console
		return
	fi
	
	while read line;do
	   cmd="/etc/init.d/${line}"
	   echo "operatin_mode execute : ${cmd} disable" > /dev/console
	   [ -x ${cmd} ] && ${cmd} disable 
	done < ${disable_list}
}

. /lib/functions.sh

start() {
    mode="router"
    read_sysmode
    disable_service
}
