#!/bin/sh /etc/rc.common
# Copyright (c) 2017 Shenzhen TP-LINK Technologies Co.Ltd.
# Author  : HQL <huangqinglou@tp-link.com.cn>
# Date    : 2017/11/06

START=99

. /lib/wifi/repeater_core.sh

start()
{
		echo "===========repeater_monitor_start===============" >/dev/console
        repeater_monitor_start
}

stop()
{
        repeater_monitor_stop
}

