#!/bin/sh /etc/rc.common
# Copyright (c) 2016 Shenzhen TP-LINK Technologies Co.Ltd.
# Author  : Sharon Lin <sharon.lin@tp-link.com>
# Date    : 3 Mar 2016

START=25

. /lib/smartdhcp/smartdhcp_core.sh

start()
{
        smartdhcp_start
}

stop()
{
        smartdhcp_stop
}

