#!/bin/sh

[ "$INTERFACE" == "lan" ] || {
	[ "$INTERFACE" == "wan" -o "$INTERFACE" == "mobile" ] || exit 0
}

case "$ACTION" in
	ifup)
		/etc/init.d/qos restart
	;;
	ifdown)
		/etc/init.d/qos restart
	;;
	*)
	;;
esac
