#!/bin/sh

radio_bk_name="radio_bk"
radio_sec_bk_name="radio_sec_bk"

# copy the radio and radio_bk block to the temp files
nvrammanager -r /tmp/radio_bk -p "$radio_bk_name"
# get the file size of /tmp/radio
size=$(ls -l /tmp/radio_bk | awk '{print $5}')
# create the empty content file, the size is the same with the radio block 
dd if=/dev/zero of=/tmp/zero bs=1 count=$size
# erase the radio_bk block
nvrammanager -w /tmp/zero -p "$radio_bk_name"
# erase the radio_sec_bk block
nvrammanager -w /tmp/zero -p "$radio_sec_bk_name"