#!/bin/sh /etc/rc.common

START=99

start() {
	local rftestflag=$( nvram get rftestflag )
	if [ "$rftestflag" != "1" ]; then
		echo "rftestflag != 1,return from wifi_check" >/dev/console
		return 0
	fi
	sleep 15
	echo "will come in wifi_check" >/dev/console
	/sbin/wifi check
	return 0
}