#!/bin/sh
#

qca_wifi_modules() {
	# move ip/eb-tables back to modules.d - Gen3 nss accelerator requires iptables to
	# be loaded at all times
	if [ -d /etc/modules.d.sysinit/ ]; then
			(cd /etc/modules.d.sysinit/ && mv * /etc/modules.d 2>&1) >/dev/null
	fi
	# qca-wifi is not started on boot, only by ubntconf rc
	(cd /etc/modules.d/ && rm -f *qca-wifi* 2>&1) >/dev/null
}

boot_hook_add preinit_ubnt qca_wifi_modules
