#!/bin/sh

productionFile="/tmp/productionResetSwitch"
ttyPathNum=$(echo $(ls /dev/pts))

if [ -f "$productionFile" ]; then
    if [ "$ACTION" = "pressed" ]; then
        echo -n -e \\n$BUTTON pressed > /dev/console
        echo -n -e \\n$BUTTON pressed > /dev/pts/$ttyPathNum
        exit 0
    elif [ "$ACTION" = "released" ]; then
        echo -n -e \\n$BUTTON released > /dev/console
        echo -n -e \\n$BUTTON released > /dev/pts/$ttyPathNum
        exit 0
    fi
fi

if [ "${ACTION}" = "pressed" ]; then
. /lib/functions.sh
    echo "$BUTTON pressed, light on power red LED." > /dev/console
    echo 1 > /sys/class/gpio/gpio10/value
    exec /usr/sbin/resetLedBlink.sh 30 5 &
fi

[ "${ACTION}" = "released" ] || exit 0

. /lib/functions.sh
pidOfresetLEDBlink=$(pidof resetLedBlink.sh)

logger "$BUTTON pressed for $SEEN seconds"
echo "$BUTTON pressed for $SEEN seconds" > /dev/console

if [ "$SEEN" -lt 1 ]
then
	echo "$BUTTON pressed for $SEEN seconds..Treating it as spurrious input" > /dev/console
        echo 0 > /sys/class/gpio/gpio10/value
        if [  -n $pidOfresetLEDBlink ]; then
        kill -9 $pidOfresetLEDBlink
        fi
#	sync
#	reboot
else
	if [ "$SEEN" -lt 5 ]
	then
		echo "$BUTTON pressed for $SEEN seconds..Initiating reboot sequence" > /dev/console
                if [  -n $pidOfresetLEDBlink ]; then
                kill -9 $pidOfresetLEDBlink
                echo 1 > /sys/class/gpio/gpio10/value
                fi
                sleep $((10-$SEEN)) && echo 0 > /sys/class/gpio/gpio10/value & #Total light on Power LED 10 seconds. If reboot procedure failed, it will change back to green.
		sync
		sleep 2
		ntgrcli -r 2;
		echo "rebooting ...." > /dev/console
		reboot
	else
		echo "$BUTTON pressed for $SEEN seconds..Initiating FACTORY RESET" > /dev/console
#                echo 0 > /sys/class/gpio/gpio10/value
                if [ -z $pidOfresetLEDBlink ]; then
                . /usr/sbin/resetLedBlink.sh 30 &
                fi
#		jffs2reset -y && reboot &
#		./usr/sbin/factorycfg.sh
		ntgrcli -r 3;
    ./usr/sbin/ntgr_factorycfg.sh
	fi
fi

return 0
