#! /bin/sh

usage()
{
	echo "getfirm <info>"
	echo "        MAC"
	echo "        SSID"
	echo "        PIN"	
	echo "        MODEL"
	echo "        FIRM"
	echo "        WEBSITE"
	echo "        HARDVERSION"
	echo "        SOFTVERSION"
	echo "        LANGUAGE"
	echo "        PRODUCT_ID"
	echo "        SPECIAL_ID"
	echo "        DEV_ID"
	echo "        HW_ID"
	echo "        FW_ID"
	echo "        OEM_ID"
	echo "        COUNTRY"	
}

option="$1"
factoryLanMac="00-0A-EB-AC-25-00"
factoryPIN="12345670"

## Only read from tmp files for info below here, don't exec nvrammanager.
## nvrammanager has been moved to /etc/init.d/boot for initialization.

case $option in
	MAC)
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/default-mac" ]; then
		nvrammanager -r /tmp/default-mac -p default-mac >/dev/null 2>&1
	fi

	if [ -s "/tmp/default-mac" ];then
		echo $(grep 'MAC'  /tmp/default-mac | cut -d : -f 2-)
	else
		echo  $factoryLanMac
	fi
	;;

	SSID)
	echo  "TP-Link"
	;;

	PIN)
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/pin" ];then
		nvrammanager -r /tmp/pin -p pin >/dev/null 2>&1
	fi

	if [ -s "/tmp/pin" ];then
		echo $(cat /tmp/pin)
	else
		echo $factoryPIN
	fi
	;;

	MODEL)
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/productinfo" ];then
		nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	fi

	echo $(grep 'product_name' /tmp/productinfo | cut -d : -f 2-)
	;;

	HOSTNAME_NO_BLANK)    # show hostname like ArcherA6v2
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/productinfo" ];then
		nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	fi

	hostname=$(grep 'product_name' /tmp/productinfo | cut -d : -f 2- | sed "s/ //g")
	version=$(grep 'product_ver' /tmp/productinfo | cut -d : -f 2-)
	version=${version%%.*}
	echo "${hostname}v${version}"
	;;

	HOSTNAME_BLANK)    # show hostname like Archer A6 v2
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/productinfo" ];then
		nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	fi

	hostname=$(grep 'product_name' /tmp/productinfo | cut -d : -f 2-)
	version=$(grep 'product_ver' /tmp/productinfo | cut -d : -f 2-)
	version=${version%%.*}
	echo "${hostname} v${version}"
	;;

	HOSTNAME_UNDERLINE)  #  show hostname like Archer_A6
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/productinfo" ];then
		nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	fi

	hostname=$(grep 'product_name' /tmp/productinfo | cut -d : -f 2- | sed "s/ /_/g")
	echo "${hostname}"
	;;

	FIRM)
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/productinfo" ];then
		nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	fi

	echo $(grep 'vendor_name' /tmp/productinfo | cut -d : -f 2-)
	;;

	WEBSITE)
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/productinfo" ];then
		nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	fi

	echo $(grep 'vendor_url' /tmp/productinfo | cut -d : -f 2-)
	;;

	HARDVERSION)
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/productinfo" ];then
		nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	fi

	echo $(grep 'product_ver' /tmp/productinfo | cut -d : -f 2-)
	;;

	LANGUAGE)
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/productinfo" ];then
		nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	fi

	echo $(grep 'language' /tmp/productinfo | cut -d : -f 2-)
	;;

	PRODUCT_ID)
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/productinfo" ];then
		nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	fi

	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/productinfo" ];then
		nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	fi

	echo $(grep 'product_id' /tmp/productinfo | cut -d : -f 2-)
	;;

	SPECIAL_ID)
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/productinfo" ];then
		nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	fi

	echo $(grep 'special_id' /tmp/productinfo | cut -d : -f 2-)
	;;

	DEV_ID)
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/deviceId" ];then
		nvrammanager -r /tmp/deviceId -p device-id > /dev/null 2>&1
	fi

	echo $(grep 'dev_id' /tmp/deviceId | cut -d : -f 2-)
	;;

	HW_ID)
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/productinfo" ];then
		nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	fi

	echo $(grep 'hw_id' /tmp/productinfo | cut -d : -f 2-)
	;;

	REGION)
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/productinfo" ];then
		nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	fi

	echo $(grep 'region' /tmp/productinfo | cut -d : -f 2-)
	;;

	SOFTVERSION)
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/softversion" ];then
		nvrammanager -r /tmp/softversion -p soft-version >/dev/null 2>&1
	fi

	echo $(grep 'soft_ver' /tmp/softversion | cut -d : -f 2-)
	;;

	FW_ID)
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/softversion" ];then
		nvrammanager -r /tmp/softversion -p soft-version >/dev/null 2>&1
	fi

	echo $(grep 'fw_id' /tmp/softversion | cut -d : -f 2-)
	;;

	OEM_ID)
	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/productinfo" ];then
		nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	fi

	echo $(grep 'oem_id' /tmp/productinfo | cut -d : -f 2-)
	;;

 	COUNTRY)
 	## 文件内容为空或者文件不存在时，尝试重新读出；小概率事件，不加文件锁。
	if [ ! -s "/tmp/productinfo" ];then
		nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	fi

	echo $(grep 'country' /tmp/productinfo | cut -d : -f 2-)
	;;

	*)
	usage
	;;
esac
