#!/bin/sh

set_br_netfilter() {
    if [ $1 == "1" -o $1 == "0" ]; then
        echo $1 > /sys/class/net/br-lan/bridge/nf_call_iptables
        echo $1 > /sys/class/net/br-lan/bridge/nf_call_ip6tables

        echo $1 > /proc/sys/net/bridge/bridge-nf-call-iptables
        echo $1 > /proc/sys/net/bridge/bridge-nf-call-ip6tables
    else
        echo "bad value $1 for set_br_netfilter."> /dev/console
    fi
}

#iptv_en=`uci get iptv.iptv.enable`
qos_en=`uci get qos.settings.enable 2> /dev/null`
#guest_network_en=`uci get wireless.ath01.enable`

#if [ "$iptv_en" == "off" -a "$qos_en" == "off" -a "$guest_network_en" == "off" ];then
if [ "$qos_en" == "on" ];then
    new_value="1"
else
    new_value="0"
fi

v1=`cat /sys/class/net/br-lan/bridge/nf_call_iptables`
v2=`cat /sys/class/net/br-lan/bridge/nf_call_ip6tables`
v3=`cat /proc/sys/net/bridge/bridge-nf-call-iptables`
v4=`cat /proc/sys/net/bridge/bridge-nf-call-ip6tables`

old_value=$(($v1 & $v2 & $v3 & $v4))

if [ "$old_value" != "$new_value" ]; then
    echo "set_br_netfilter new_value=$new_value" > /dev/console
    set_br_netfilter $new_value    
fi
