#!/bin/sh

[ "$1" != "create" ] && exit 1

phyname="$(cat /sys/class/net/wifi0/phy80211/name)"
iw dev db2 del > /dev/null 2>&1
wlanconfig db2 create wlandev wifi0 wlanmode ap -cfg80211
iw phy $phyname interface add db2 type __ap
ifconfig db2 up

phyname="$(cat /sys/class/net/wifi1/phy80211/name)"
iw dev db5 del > /dev/null 2>&1
wlanconfig db5 create wlandev wifi1 wlanmode ap -cfg80211
iw phy $phyname interface add db5 type __ap
ifconfig db6 up

phyname="$(cat /sys/class/net/wifi2/phy80211/name)"
iw dev db6 del > /dev/null 2>&1
wlanconfig db6 create wlandev wifi2 wlanmode ap -cfg80211
iw phy $phyname interface add db6 type __ap
ifconfig db6 up
