#!/bin/sh

[ -z "$2" ] && exit 1

scan_wifi=$1
scan_vap=$2

# Enable passive scanning so probes are not sent
iwpriv ${scan_wifi} pasv_scan 1  # passive scan

# Create new device which varies based on platform generation
grep -q Miami /proc/ubnthal/system.info && {
        phyname="$(cat /sys/class/net/${scan_wifi}/phy80211/name)"
	iw dev ${scan_vap} del > /dev/null 2>&1
        wlanconfig ${scan_vap} create wlandev ${scan_wifi} wlanmode specialvap -cfg80211 > /dev/null 2>&1
        iw phy ${phyname} interface add ${scan_vap} type __ap
	cfg80211tool ${scan_vap} ssid "yorkscan"
} || {
	wlanconfig ${scan_vap} destroy > /dev/null 2>&1
	wlanconfig ${scan_vap} create wlandev ${scan_wifi} wlanmode sta nosbeacon > /dev/null 2>&1
}

ifconfig ${scan_vap} up

echo ${scan_vap} > /var/run/${scan_wifi}_devnames
echo ${scan_vap} > /var/run/scan_devname
