var	ERR_NO_ERROR											=0
var ERR_FS_FILE_OPEN_FAILED									=10

var	ERR_PPPOE_FIXED_IP										=1000
var	ERR_PPPOE_TIMING_SET									=1001
var	ERR_PPPOE_STRING_TOO_LONG								=1002
var	ERR_PPPOE_USERNAME_TOO_LONG								=1003
var	ERR_PPPOE_PWD_TOO_LONG									=1004
var	ERR_PPPOE_AUTO_OFF_WAITE_TIME							=1005
var	ERR_PPPOE_LCP_MRU										=1006
var	ERR_PPPOE_ECHO_REQ_INTERVAL								=1007

var	ERR_DHCP_SERVER_ADDR_POOL_ERROR							=2000
var	ERR_DHCP_SERVER_GATEWAY_ERROR							=2001
var	ERR_DHCP_SERVER_DNS_ERROR								=2002
var	ERR_DHCP_SERVER_BAK_DNS_ERROR							=2003
var	ERR_DHCP_SERVER_LEASE									=2004
var	ERR_DHCP_SERVER_START_IP_ADDR							=2005
var	ERR_DHCP_SERVER_END_IP_ADDR								=2006
var	ERR_DHCP_SERVER_START_BIGGER_END						=2007
var	ERR_DHCP_SERVER_ADD_RANGE								=2008

var	ERR_FIX_MAP_MAC_ADDR_ERROR								=3000
var	ERR_FIX_MAP_IP_ADDR_ERROR								=3001
var	ERR_FIX_MAP_REC_EXIST									=3002
var	ERR_FIX_MAP_PAGE_NUM_ERROR								=3003
var	ERR_FIX_MAP_RECORD_ALREADY_FULL							=3004
var	ERR_FIX_MAP_RECORD_MAC_ALREADY_EXIST					=3005
var	ERR_FIX_MAP_RECORD_IP_ALREADY_EXIST						=3006
var ERR_FIX_MAP_IP_EQUAL_LANIP								=3007

var	ERR_STATIC_ROUTR_ENABLE									=4000
var	ERR_STATIC_ROUTR_DESTINATION_IP							=4001
var	ERR_STATIC_ROUTR_SUBNETMASK_IP							=4002
var	ERR_STATIC_ROUTR_GATEWAY_IP								=4003
var	ERR_STATIC_ROUTR_NOEMPTY								=4004
var	ERR_STATIC_ROUTR_DUPLICATION							=4005
var	ERR_STATIC_ROUTR_DEFAULT_GATEWAY						=4006
var	ERR_STATIC_ROUTR_NOT_SAME_NETWORK						=4007
var	ERR_STATIC_ROUTR_CONFLICT_LAN_WAN						=4008
var	ERR_STATIC_DEST_CONFLICT_LAN_WAN						=4009
var	ERR_STATIC_ROUTR_ALREADY_FULL							=4010
var	ERR_STATIC_ROUTR_SAVE									=4011
var	ERR_STATIC_ROUTR_OTHER									=4012
var	ERR_WAN_DOWN_BANDWIDTH									=4013
var	ERR_WAN_UP_BANDWIDTH									=4014

var	ERR_NETWORK_MTU											=5000
var	ERR_LAN_IP_ERROR										=5001
var	ERR_LAN_MASK_ERROR										=5002
var	ERR_WAN_IP_ERROR										=5003
var	ERR_WAN_MASK_ERROR										=5004
var	ERR_WAN_DNS_ERROR										=5005
var	ERR_WAN_BACKDNS_ERROR									=5006
var	ERR_WAN_GATE_ERROR										=5007
var	ERR_WAN_LAN_CONFLICT									=5008
var	ERR_WAN_TYPE											=5009
var	ERR_LAN_IP_SET											=5010
var	ERR_LAN_MASK_SET										=5011
var	ERR_WAN_IP_SERVER										=5012
var	ERR_WAN_IP_SET											=5013
var	ERR_WAN_MASK_SET										=5014
var	ERR_WAN_DNS_SET											=5015
var	ERR_WAN_GATE_SET										=5016
var	ERR_WAN_MAC_ADDR										=5017
var	ERR_WAN_MAC_DUPLICATE									=5018
var	ERR_WAN_MAC_EQ_LAN_MAC									=5019
var	ERR_SNTP_MONTH											=5020
var	ERR_SNTP_DAY											=5021
var	ERR_SNTP_YEAR											=5022
var	ERR_SNTP_HOUR											=5023
var	ERR_SNTP_MINUTE											=5024
var	ERR_SNTP_SECOND											=5025
var	ERR_SNTP_TIME_SET										=5026
var	ERR_SNTP_TIMEZONE										=5027
var	ERR_SNTP_GET_GMT_FAILED									=5028
var ERR_SAME_WAN_IP										    =5029
var ERR_SNTP_SERVER_A                                       =5030
var ERR_SNTP_SERVER_B                                       =5031 
var ERR_SERVER_IP_ERROR	                                    =5032

var	ERR_MORNITOR_PORT_ACTIVE_PORT							=6000
var	ERR_MORNITOR_PORT_PASSIVE_PORT							=6001
var	ERR_MORNITOR_PORT_EQUAL_PORT							=6002
var	ERR_MORNITOR_NONE_PORT									=6003

var	ERR_TFTP_OVER_FILE_LEN									=7000
var	ERR_TFTP_IP_ERROR										=7001

var	ERR_FIREWALL_START_TIME_FORMAT_ERROR					=8000
var	ERR_FIREWALL_END_TIME_FORMAT_ERROR						=8001
var	ERR_FIREWALL_TIME_START_BIGGER_END						=8002
var	ERR_FIREWALL_LAN_IP_FORMAT_ERROR						=8003
var	ERR_FIREWALL_LAN_PORT_FORMAT_ERROR						=8004
var	ERR_FIREWALL_WAN_IP_FORMAT_ERROR						=8005
var	ERR_FIREWALL_WAN_PORT_FORMAT_ERROR						=8006
var	ERR_FIREWALL_PROTOCOL_TYPE_ERROR						=8007
var	ERR_FIREWALL_RECORD_ALREADY_EXIST						=8008
var	ERR_FIREWALL_IP_RECORD_ALREADY_FULL						=8009

var	ERR_FIREWALL_DOMAIN_NAME_LEN_OVER						=9000
var	ERR_FIREWALL_DOMAIN_NAME_ERROR							=9001
var	ERR_FIREWALL_DOMAIN_IS_SUBSET							=9002
var	ERR_FIREWALL_DOMAIN_RECORD_ALREADY_FULL					=9003

var	ERR_FIREWALL_TIME_NOT_FULL								=10000
var	ERR_FIREWALL_TIME_FORMAT_ERROR							=10001
var	ERR_FIREWALL_WZD_TIME_ALREADY_EXIST						=10002
var	ERR_FIREWALL_WZD_TIME_IS_SUBSET							=10003
var	ERR_FIREWALL_WZD_IP_FORMAT_ERROR						=10004
var	ERR_FIREWALL_WZD_ADDR_ALREADY_EXIST						=10005
var	ERR_FIREWALL_WZD_PORT_FORMAT_ERROR						=10006
var	ERR_FIREWALL_WZD_PORT_IS_SUBSET							=10007

var	ERR_MAC_FILTER_PAGE_NUM_ERROR							=11000
var	ERR_MAC_FILTER_RECORD_ALREADY_EXIST						=11001
var	ERR_MAC_FILTER_RECORD_ALREADY_FULL						=11002
var	ERR_MAC_FILTER_FORMAT_ERROR								=11003

var	ERR_REMOTE_MANAGE_IP_FORMAT_ERROR						=12000
var	ERR_REMOTE_MANAGE_PORT_FORMAT_ERROR						=12001
var	ERR_REMOTE_MANAGE_PORT_OUT_OF_RANGE						=12002

var	ERR_DMZ_HOST_IP_ADDR									=13000

var	ERR_VS_PAGE_NUM_ERROR									=14000
var	ERR_VS_PORT_OUT_RANGE									=14001
var	ERR_VS_PORT_FORMAT_ERROR								=14002
var	ERR_VS_IP_ADDRESS										=14003
var	ERR_VS_RECORD_ALREADY_EXIST								=14004
var	ERR_VS_PROTOCOL_TYPE_ERROR								=14005
var	ERR_VS_RECORD_ALREADY_FULL								=14006

var	ERR_SPECIAL_APP_PUBLIC_PORT								=15000
var	ERR_SPECIAL_APP_DUPLICATE_PUBLIC_PORT					=15001
var	ERR_SPECIAL_APP_DUPLICATE_TAG_PORT						=15002
var	ERR_SPECIAL_APP_RECORD_ALREADY_FULL						=15003

var	ERR_DDNS_USER_NAME_EMPTY								=16000
var	ERR_DDNS_PWD_EMPTY										=16001
var	ERR_DDNS_USER_HAS_SPACE									=16002
var	ERR_DDNS_PWD_HAS_SPACE									=16003
var	ERR_DDNS_LIST_FULL										=16004
var	ERR_DDNS_LIST_INDEX_OUT_RANGE							=16005
var	ERR_DDNS_ENTRY_BE_DELETE								=16006

var	ERR_USER_NAME_LENGTH									=17000
var	ERR_USER_PWD_LENGTH										=17001
var	ERR_USER_NAME_ERROR										=17002
var	ERR_USER_PWD_ERROR										=17003
var	ERR_USER_PWD_INVALID_CHAR								=17004

var	ERR_SYS_TFTP_FAIL										=18000
var	ERR_SYS_TFTP_FILE_LENGTH								=18001
var	ERR_SYS_TFTP_SERVNOTFOUND								=18002
var	ERR_SYS_ERR_SOCKET										=18003
var	ERR_SYS_FAIL											=18004
var	ERR_SYS_FILE_VER										=18005

var	ERR_SESSION_LIMIT_TBL_FULL								=19000
var	ERR_SESSION_LIMIT_RECORD_ALREADY_FULL					=19001
var	ERR_SESSION_LIMIT_RECORD_ALREADY_EXIST					=19002

var	ERR_ARP_REC_IP_EXIST									=20000
var	ERR_ARP_FIXMAP_FULL										=20001
var	ERR_ARP_REC_IP_EXIST_ADD_SUCC							=20002
var	ERR_ARP_REC_IP_EXIST_ADD_FAIL							=20003
var	ERR_ARP_IP_EXIST_AND_FIXMAP_FULL						=20004
var	ERR_ARP_FIXMAP_FULL_IGNORE_OTHER_ENTRYS					=20005
var ERR_ARP_FIXMAP_MAC_ERR									=20006
var ERR_ARP_IP_SAME_AS_LANIP                                =20007

var	ERR_SYS_LOG_SYS_STATUS									=21000
var	ERR_SYS_LOG_SRV_ID										=21001
var	ERR_SYS_LOG_SRV_STATUS									=21002
var	ERR_SYS_LOG_SRV_ADDRESS									=21003
var	ERR_SYS_LOG_SRV_ADDR_EXIST								=21004
var	ERR_SYS_LOG_SRV_PORT									=21005
var	ERR_SYS_LOG_SETTING_EMERGENCY							=21006
var	ERR_SYS_LOG_SETTING_ALERT								=21007
var	ERR_SYS_LOG_SETTING_CRITICAL							=21008
var	ERR_SYS_LOG_SETTING_ERROR								=21009
var	ERR_SYS_LOG_SETTING_WARNING								=21010
var	ERR_SYS_LOG_SETTING_NOTICE								=21011
var	ERR_SYS_LOG_SETTING_INFORMATIONAL						=21012
var	ERR_SYS_LOG_SETTING_DEBUG								=21013
var	ERR_SYS_LOG_SETTING_EMPTY								=21014

var	ERR_FIREWALL_SYSLOG_SERVER_INVALID_ID					=22000
var	ERR_FIREWALL_SYSLOG_SERVER_NOT_DEFINED					=22001
var	ERR_FIREWALL_SCREEN_UNKNOWN_DEFENCE						=22002
var	ERR_FIREWALL_SCREEN_SCAN_THRESHOLD						=22003
var	ERR_FIREWALL_SCREEN_DOS_THRESHOLD						=22004

var	ERR_TDDP_UPLOAD_FILE_TOO_LONG							=23000
var	ERR_TDDP_UPLOAD_FILE_FORMAT_ERR							=23001
//added by ZQQ,08.05.19 the upload file is too big
var ERR_TDDP_UPLOAD_FILE_NAME_ERR                           =23002

var	ERR_COMMON_ERROR										=25000
var	ERR_TDDP_DOWNLOAD_FILE_TOO_LONG							=25001
var ERR_VS_RECORD_CONFLICT_REMOTE_WEB_PORT                  =25002

var	ERR_DST_HOUR											=26000
var	ERR_DST_DAY												=26001
var	ERR_DST_MONTH											=26002
var	ERR_DST_BEGIN_END										=26003

var	ERR_WLAN_CONFIG_BASE									=26100
var	ERR_WLAN_CONFIG_SECURITY								=26101
var	ERR_WLAN_CONFIG_KEY										=26102
var	ERR_WLAN_MAC_FILTER_PAGE_NUM_ERROR						=26103
var	ERR_WLAN_MAC_FILTER_RECORD_ALREADY_EXIST				=26104
var	ERR_WLAN_MAC_FILTER_RECORD_ALREADY_FULL					=26105
//ºÏ²¢³ÂÑÒÎÞÏß²¿·Ö
var ERR_IP_NOT_IN_THE_SAME_SUBNET                           =26106
var ERR_WLAN_SSID_LEN                                       =26107
var ERR_WLAN_REGION                                         =26108
var ERR_WLAN_CHANNEL_WIDTH                                  =26109
var ERR_WLAN_STATIC_RATE                                    =26110
var ERR_WLAN_MODE                                           =26111      
var ERR_WLAN_BROADCAST                                      =26112
var ERR_WLAN_MAC_ADDR_INVALID                               =26113  
var ERR_WLAN_RADIUS_IP_INVALID                              =26114

//qos

var ERR_QOS_TOTAL_EGRESS_100M								= 27000	/* ZJin 090903: make the err msg more detailedly */
var ERR_QOS_TOTAL_INGRESS_100M								= 27001
var ERR_QOS_TOTAL_EGRESS_1000M								= 27002
var ERR_QOS_TOTAL_INGRESS_1000M								= 27003
var ERR_QOS_NOBUF											= 27004/* ÒÑ¾­Ã»ÓÐ¿Õ¼ä*/
var ERR_QOS_NOENT											= 27005/* ²»´æÔÚÔÚÐÅÏ¢*/
var ERR_QOS_EXIST											= 27006/* ¸ÃÐÅÏ¢ÒÑ¾­´æÔÚ*/
var ERR_QOS_USEDBW											= 27007/* ÐÂµÄQoS ´ø¿íÐ¡ÓÚÒÑÊ¹ÓÃµÄ´ø¿í*/
var ERR_QOS_NOBW											= 27008/* ÏµÍ³²»ÄÜÂú×ãËùÒªÇóµÄ´ø¿í*/
var ERR_QOS_BADRULE											= 27009/* ¹æÔòÓÐ½»¼¯*/
var ERR_QOS_TYPE											= 27010/* ´íÎóµÄÀàÐÍ*/
var ERR_QOS_MAX												= 27011/*the max error code */
var ERR_QOS_INGRESS_BANDWIDTH								= 27012/*ÏÂÐÐ´ø¿í×ÜËã´óÓÚÏµÍ³Ìá¹©×ÜÊý*/
var ERR_QOS_EGRESS_BANDWIDTH								= 27013/*ÉÏÐÐ´ø¿í×ÜÊý´óÓÚÏµÍ³Ìá¹©×ÜËã*/

//¼Ò³¤¿ØÖÆ
var ERR_PARENT_CTRL_FULL									=28000
var ERR_PARENT_CTRL_URLDESC									=28001
var ERR_PARENT_CTRL_SAME_MAC_WITH_PARENT					=28002
//¹ýÂË
var ERR_ACC_CTRL_HOST_FULL									=29000
var ERR_ACC_CTRL_TARGET_FULL								=29001
var ERR_ACC_CTRL_SCHEDULE_FULL								=29002
var ERR_ACC_CTRL_RULE_FULL									=29003
var ERR_ACC_CTRL_SAME_NAME									=29004
var ERR_ACC_CTRL_REFERED									=29005
var ERR_ACC_CTRL_RULE_CONFLICT								=29006
var ERR_ACC_PARTIAL_DEL										=29007
var ERR_ACC_DEL_NONE										=29008
var ERR_FILTER_MAC											=29009
var ERR_ACC_CTRL_HOST_IPSTART								=29010
var ERR_ACC_CTRL_HOST_IPEND									=29011
var ERR_ACC_CTRL_TARGET_IPSTART								=29012
var ERR_ACC_CTRL_TARGET_IPEND								=29013
var ERR_ACC_CTRL_HOST_IPSTART_NOT_IN_THE_SAME_SUBNET		=29014
var ERR_ACC_CTRL_HOST_IPEND_NOT_IN_THE_SAME_SUBNET			=29015
                                       
var str_err = new Array();
str_err[ERR_NO_ERROR]					=	"Ocorreu um erro. Tente novamente."
str_err[ERR_PPPOE_FIXED_IP]				=	"Endereço IP especificado incorreto!"
str_err[ERR_PPPOE_TIMING_SET]			=	"Configuração da Conexão baseada em horário está incorreta."
str_err[ERR_PPPOE_STRING_TOO_LONG]		=	"Ocorreu um erro. Tente novamente."
str_err[ERR_PPPOE_USERNAME_TOO_LONG]	=	"Nome do usuário excede o tamanho máximo (119). Entre com outro nome."
str_err[ERR_PPPOE_PWD_TOO_LONG]			=	"Senha excede o tamanho máximo (119). Entre com outra senha."
str_err[ERR_PPPOE_AUTO_OFF_WAITE_TIME]	=	"Tempo máximo inativo está fora do intervalo (10 a 99). Entre com outro valor."
str_err[ERR_PPPOE_LCP_MRU]				=	"MTU está fora do intervalo (576 a 1500). Entre com outro valor."
str_err[ERR_PPPOE_ECHO_REQ_INTERVAL]	=	"Ocorreu um erro. Tente novamente."
str_err[ERR_DHCP_SERVER_ADDR_POOL_ERROR]=	"Valores dos endereços IP's estão incorretos!"
str_err[ERR_DHCP_SERVER_GATEWAY_ERROR]	=	"Gateway incorreto. Entre com outro endereço IP."
str_err[ERR_DHCP_SERVER_DNS_ERROR]		=	"Endereço IP do servidor DNS primário incorreto. Entre com outro endereço IP."
str_err[ERR_DHCP_SERVER_BAK_DNS_ERROR]	=	"Endereço IP do servidor DNS secundário incorreto. Entre com outro endereço IP."
str_err[ERR_DHCP_SERVER_LEASE]			=	"Tempo de Expiração dos endereços está fora do intervalo (1 a 2880). Entre com outro valor."
str_err[ERR_DHCP_SERVER_START_IP_ADDR]	=	"Endereços IP's estão incorretos (inicial ou final). Entre com outro valor."
str_err[ERR_DHCP_SERVER_END_IP_ADDR]	=	"Endereços IP's estão incorretos (inicial ou final). Entre com outro valor."
str_err[ERR_DHCP_SERVER_START_BIGGER_END]=	"Endereço IP inicial é maior que o endereço IP final."
str_err[ERR_DHCP_SERVER_ADD_RANGE]		=	"Endereços IP's estão fora do intervalo de 256. Entre com outro valor."
str_err[ERR_FIX_MAP_MAC_ADDR_ERROR]		=	"Endereço MAC incorreto. Entre com outro valor."
str_err[ERR_FIX_MAP_IP_ADDR_ERROR]		=	"Endereço IP incorreto. Entre com outro valor."
str_err[ERR_FIX_MAP_REC_EXIST]			=	"Esta entrada já existe. Entre com outro valor."
str_err[ERR_FIX_MAP_PAGE_NUM_ERROR]		=	"Página do endereço IP estático incorreta. Tente novamente."
str_err[ERR_FIX_MAP_RECORD_ALREADY_FULL]=	"Número máximo de endereços IP's reservados excedido."
str_err[ERR_FIX_MAP_RECORD_MAC_ALREADY_EXIST]=	"Endereço MAC já existe."
str_err[ERR_FIX_MAP_RECORD_IP_ALREADY_EXIST]=	"Endereço IP já existe."
str_err[ERR_FIX_MAP_IP_EQUAL_LANIP]				=	"Endereço IP é diferente da faixa de IP da LAN.";
str_err[ERR_STATIC_ROUTR_ENABLE]		=	"Valor está incorreto."
str_err[ERR_STATIC_ROUTR_DESTINATION_IP]=	"Endereço IP de destino incorreto. Entre com outro endereço."
str_err[ERR_STATIC_ROUTR_SUBNETMASK_IP]	=	"Máscara de sub-rede incorreta. Entre com um valor correto. <br> Por exemplo 255.255.255.0."
str_err[ERR_STATIC_ROUTR_GATEWAY_IP]	=	"Gateway incorreto. Entre com outro endereço IP."
str_err[ERR_STATIC_ROUTR_NOEMPTY]	=	"Tabela de entrada de rota estática não está vazia."
str_err[ERR_STATIC_ROUTR_DUPLICATION]	=	"Esta entrada para roteamento estático já existe. Entre com outro valor."
str_err[ERR_STATIC_ROUTR_DEFAULT_GATEWAY]=	"Esta entrada é a do Gateway Padrão. Insira-a dentro do menu Rede."
str_err[ERR_STATIC_ROUTR_NOT_SAME_NETWORK]=	"Valor do gateway precisa estar dentro da mesma subrede do endereço IP  WAN ou LAN."
str_err[ERR_STATIC_ROUTR_CONFLICT_LAN_WAN]=	"Parâmetros IP da LAN ou WAN conflitam com o roteamento estático. Entre com outro valor."
str_err[ERR_STATIC_DEST_CONFLICT_LAN_WAN]=	"Endereço IP de destino não pode ser definido na mesma sub-rede do Endereço IP WAN ou LAN. Entre com outro valor."
str_err[ERR_STATIC_ROUTR_ALREADY_FULL]	=	"Ocorreu um erro. Tente novamente."
str_err[ERR_STATIC_ROUTR_SAVE]			=	"Ocorreu um erro. Tente novamente."
str_err[ERR_STATIC_ROUTR_OTHER]			=	"Ocorreu um erro. Tente novamente."
str_err[ERR_WAN_DOWN_BANDWIDTH]			=	"Largura de banda de download está fora do intervalo. Entre com outro valor (0-10000)"
str_err[ERR_WAN_UP_BANDWIDTH]			=	"Largura de banda de upload está fora do intervalo. Entre com outro valor (0-100000)"
//qos
str_err[ERR_QOS_NOBW]							=	"Largura de banda requerida inválida. Entre com outro valor.";
str_err[ERR_QOS_TOTAL_EGRESS_100M]				=	"Largura de banda de upload está fora do intervalo (1-100000). Entre com outro valor.";
str_err[ERR_QOS_TOTAL_INGRESS_100M]				=	"Largura de banda de download está fora do intervalo (1-100000). Entre com outro valor.";
str_err[ERR_QOS_TOTAL_EGRESS_1000M]				=	"Largura de banda de upload está fora do intervalo (1-1000000). Entre com outro valor.";
str_err[ERR_QOS_TOTAL_INGRESS_1000M]			=	"Largura de banda de download está fora do intervalo (1-1000000). Entre com outro valor.";
str_err[ERR_QOS_BADRULE]						=   "Esta regra já existe. Tente novamente.";
str_err[ERR_NETWORK_MTU]						=	"Valor incorreto da MTU. Entre com outro valor (576 a 1500).";
str_err[ERR_LAN_IP_ERROR]						=	"Endereço IP da LAN incorreto. Entre com outro valor.";
str_err[ERR_LAN_MASK_ERROR]						=	"Máscara de sub-rede incorreta para os IP's da LAN. Entre com outro valor.";
str_err[ERR_WAN_IP_ERROR]				=	"Endereço IP WAN inválido. Entre com outro valor!"
str_err[ERR_WAN_MASK_ERROR]				=	"Máscara de Sub-rede incorreta para os IP's da LAN. Entre outro valor."
str_err[ERR_WAN_DNS_ERROR]				=	"Endereço IP do DNS incorreto. Entre com outro IP. <br> Por exemplo: 200.184.26.3"
str_err[ERR_WAN_BACKDNS_ERROR]			=	"Endereço IP do DNS secundário incorreto. Entre com outro IP. <br> Por exemplo: 200.184.26.4"
str_err[ERR_WAN_GATE_ERROR]				=	"Gateway incorreto para o IP da WAN. Entre com outro endereço IP."
str_err[ERR_WAN_LAN_CONFLICT]			=	"Endereço IP da WAN e Endereço IP da LAN não podem estar na mesma sub-rede. Entre com outro valor"
str_err[ERR_WAN_TYPE]					=	"Tipo de conexão à internet incorreto. Selecione o tipo apropriado de conexão à Internet"
str_err[ERR_LAN_IP_SET]			=	"Endereço IP da LAN incorreto."
str_err[ERR_LAN_MASK_SET]		=	"Máscara de sub-rede da LAN incorreta."
str_err[ERR_WAN_IP_SERVER]		=	"Endereço IP do servidor inválido."
str_err[ERR_WAN_IP_SET]			=	"Endereço IP da WAN incorreto."
str_err[ERR_WAN_MASK_SET]		=	"Máscara de sub-rede inválida."
str_err[ERR_WAN_DNS_SET]		=	"DNS incorreto."
str_err[ERR_WAN_GATE_SET]		=	"Gateway WAN incorreto."
str_err[ERR_WAN_MAC_ADDR]				=	"Endereço MAC incorreto. Entre com outro valor."
str_err[ERR_WAN_MAC_DUPLICATE]		=	"Duas ou mais interfaces WAN têm o mesmo endereço MAC."
str_err[ERR_WAN_MAC_EQ_LAN_MAC]			=	"Endereço MAC WAN é o mesmo endereço MAC LAN."
str_err[ERR_SNTP_MONTH]							=	"Formato incorreto do mês. Entre com um valor entre (1 a 12)!";
str_err[ERR_SNTP_DAY]							=	"Formato errado do dia. Entre com um valor entre (1 a 31)!";
str_err[ERR_SNTP_YEAR]							=	"Formato incorreto do ano. Entre com um valor entre (1970 a 2037)!";
str_err[ERR_SNTP_HOUR]							=	"Formato incorreto da hora. Entre com um valor entre (0 a 23)!";
str_err[ERR_SNTP_MINUTE]						=	"Formato incorreto dos minutos. Entre com um valor entre (0 a 59)!";
str_err[ERR_SNTP_SECOND]						=	"Formato incorreto dos segundos. Entre com um valor entre (0 a 59)!";
str_err[ERR_SNTP_TIME_SET]				=	"Definição de Data/Hora sem sucesso. Tente novamente."
str_err[ERR_SNTP_TIMEZONE]				=	"Fuso Horário incorreto. Escolha o fuso horário correto para sua região."
str_err[ERR_SNTP_GET_GMT_FAILED]		=	"Atualização GMT sem sucesso. Tenha certeza que sua conexão à Internet está ativa."
str_err[ERR_SNTP_SERVER_A]						=	"Primeiro endereço IP do servidor NTP é inválido. Entre com outro valor.";
str_err[ERR_SNTP_SERVER_B]						=	"Segundo endereço IP do servidor NTP é inválido. Entre com outro valor.";
str_err[ERR_SERVER_IP_ERROR]                    =   "Endereço IP do servidor incorreto. Entre com outro valor.";
str_err[ERR_MORNITOR_PORT_ACTIVE_PORT]	=	"Espelhamento ativo esta em branco. Entre com outro valor."
str_err[ERR_MORNITOR_PORT_PASSIVE_PORT]	=	"Espelhamento passivo esta em branco. Entre com outro valor."
str_err[ERR_MORNITOR_PORT_EQUAL_PORT]	=	"Espelhamento ativo não pode ser igual ao espelhamento passivo. Selecione o outro."
str_err[ERR_MORNITOR_NONE_PORT]	=	"Espelhamento inicial está fora da faixa. Entre com outro valor."
str_err[ERR_TFTP_OVER_FILE_LEN]			=	"Tamanho do nome do arquivo está incorreto. Entre com um nome com menos de 20 caracteres."
str_err[ERR_TFTP_IP_ERROR]				=	"Endereço IP do servidor TFTP está incorreto."
str_err[ERR_FIREWALL_START_TIME_FORMAT_ERROR]=	"Horário Inicial incorreta. Entre com outro valor no formato 24 horas (hhmm)"
str_err[ERR_FIREWALL_END_TIME_FORMAT_ERROR]=	"Horário final incorreto. Entre com outro valor no formato 24 horas (hhmm)"
str_err[ERR_FIREWALL_TIME_START_BIGGER_END]=	"Horário inicial não pode ser posterior ao horário final. Entre com outro valor"
str_err[ERR_FIREWALL_LAN_IP_FORMAT_ERROR]=	"Endereço IP da LAN incorreto. Insira outro valor como: 192.168.1.2"
str_err[ERR_FIREWALL_LAN_PORT_FORMAT_ERROR]=	"Porta da LAN fora do intervalo (1 a 65534). Entre com outra porta, por exemplo 8080"
str_err[ERR_FIREWALL_WAN_IP_FORMAT_ERROR]=	"Endereço IP da WAN incorreto. Insira outro valor como: 61.145.238.5"
str_err[ERR_FIREWALL_WAN_PORT_FORMAT_ERROR]=	"Porta da WAN fora do intervalo (1 a 65534). Entre com outra porta, por exemplo 8080"
str_err[ERR_FIREWALL_PROTOCOL_TYPE_ERROR]=	"Protocolo incorreto. Selecione o protocolo correto."
str_err[ERR_FIREWALL_RECORD_ALREADY_EXIST]=	"Esta entrada já existe."
str_err[ERR_FIREWALL_IP_RECORD_ALREADY_FULL]=	"Máxima entradas na lista de filtro de IP: 8"
str_err[ERR_FIREWALL_DOMAIN_NAME_LEN_OVER]=	"Nome de domínio excede tamanho máximo (30). Entre com outro nome."
str_err[ERR_FIREWALL_DOMAIN_NAME_ERROR]	=	"Nome de domínio inválido. Entre com outro nome."
str_err[ERR_FIREWALL_DOMAIN_IS_SUBSET]	=	"Nome de domínio duplicado. Verifique e insira corretamente."
str_err[ERR_FIREWALL_DOMAIN_RECORD_ALREADY_FULL]=	"Máxima entradas na lista de filtragem de domínio: 8"
str_err[ERR_FIREWALL_TIME_NOT_FULL]		=	"Se desejar configurar o horário, você precisa entrar com o horário inicial e o horário final."
str_err[ERR_FIREWALL_TIME_FORMAT_ERROR]	=	"Formato de hora incorreto. Entre com outro valor no formato 24 horas (hhmm)"
str_err[ERR_FIREWALL_WZD_TIME_ALREADY_EXIST]=	"Intervalo de horário inserida conflita com outra entrada. "
str_err[ERR_FIREWALL_WZD_TIME_IS_SUBSET]=	"Intervalo de horário inserido em outra entrada. "
str_err[ERR_FIREWALL_WZD_IP_FORMAT_ERROR]=	"Endereço IP inválido. Entre com outro endereço IP, intervalo de endereços ou nome de domínio. <br> Se você inserir uma intervalo de endereços IP, tenha certeza que o Endereço IP inicial e o final estão dentro da mesma sub-rede e disponíveis."
str_err[ERR_FIREWALL_WZD_ADDR_ALREADY_EXIST]=	"Endereço IP ou nome de domínio estão em conflito."
str_err[ERR_FIREWALL_WZD_PORT_FORMAT_ERROR]=	"Porta Incorreta.<br>Entre com outra porta (1 a 65534), intervalo de portas ou 2 vírgulas (,,) para definir várias portas.<br>Antes de inserir a porta, tenha certeza que a mesma está disponível, como 8080 ou 2300-9600.<br>"
str_err[ERR_FIREWALL_WZD_PORT_IS_SUBSET]=	"Porta informada não é permitida ou é igual à outra porta inserida."
str_err[ERR_MAC_FILTER_PAGE_NUM_ERROR]	=	"Página de filtragem de endereço MAC está errada. Tente novamente."
str_err[ERR_MAC_FILTER_RECORD_ALREADY_EXIST]=	"Esta entrada já existe. Insira outro valor."
str_err[ERR_MAC_FILTER_RECORD_ALREADY_FULL]=	"Máxima entrada de filtragem de endereços MAC: 16"
str_err[ERR_REMOTE_MANAGE_IP_FORMAT_ERROR]=		"Endereço IP incorreto. Insira outro endereço."
str_err[ERR_REMOTE_MANAGE_PORT_FORMAT_ERROR]=	"Porta incorreta. Insira outra porta."
str_err[ERR_REMOTE_MANAGE_PORT_OUT_OF_RANGE]=	"Porta está fora do intervalo (1 a 65534). Entre com outro valor."
str_err[ERR_DMZ_HOST_IP_ADDR]			=	"Host DMZ inválido. Entre com outro host."
str_err[ERR_VS_PAGE_NUM_ERROR]			=	"Página de servidor virtual incorreta. Tente novamente!"
str_err[ERR_VS_PORT_OUT_RANGE]			=	"Intervalo de porta incorreto (1 a 65534). Entre com outro valor."
str_err[ERR_VS_PORT_FORMAT_ERROR]		=	"Insira uma porta ou intervalo de portas como: 1024-2048. Entre com outra porta ou intervalo de portas."
str_err[ERR_VS_IP_ADDRESS]				=	"Endereço IP está incorreto. Entre com outro endereço."
str_err[ERR_VS_RECORD_ALREADY_EXIST]	=	"Esta entrada já existe ou a porta está contida em outra entrada. Insira outro valor para a entrada."
str_err[ERR_VS_PROTOCOL_TYPE_ERROR]		=	"Protocolo incorreto. Selecione o protocolo novamente."
str_err[ERR_VS_RECORD_ALREADY_FULL]		=	"Máximas entradas de servidor Virtual: 16"
str_err[ERR_SPECIAL_APP_PUBLIC_PORT]	=	"Formato da porta de entrada incorreto. Entre com outro valor."
str_err[ERR_SPECIAL_APP_DUPLICATE_PUBLIC_PORT]=	"Esta entrada de porta conflita com outra entrada anterior.<br> As entradas não podem conter ou serem iguais a outras entradas, pois isso resultaria um erro."
str_err[ERR_SPECIAL_APP_DUPLICATE_TAG_PORT]=	"Esta entrada para condição de associação de portas (Porta de associação e Protocolo de associação) conflita com outra entrada de associação anterior. Entre com outra condição.<br>2 entradas de protocolo de associação não podem ser colocadas juntas quando elas possuem a mesma porta de associação."
str_err[ERR_SPECIAL_APP_RECORD_ALREADY_FULL]=	"Máxima entradas de associação de portas: 16"
str_err[ERR_DDNS_USER_NAME_EMPTY]		=	"Usuário está vazio. Entre com um usuário."
str_err[ERR_DDNS_PWD_EMPTY]				=	"Senha está vazia. Entre com uma senha."
str_err[ERR_DDNS_USER_HAS_SPACE]		=	"Usuário possui espaços no nome. Entre com um usuário sem espaços."
str_err[ERR_DDNS_PWD_HAS_SPACE]			=	"Senha está vazia. Entre com uma senha."
str_err[ERR_DDNS_LIST_FULL]				=	"Tabela de DNS Dinâmico está cheia."
str_err[ERR_DDNS_LIST_INDEX_OUT_RANGE]	=	"Índice fora do intervalo."
str_err[ERR_DDNS_ENTRY_BE_DELETE]		=	"Entrada foi excluída."
str_err[ERR_USER_NAME_LENGTH]			=	"Nome do usuário excede 15 caracteres. Insira outro usuário."
str_err[ERR_USER_PWD_LENGTH]			=	"Senha excede 15 caracteres. Insira outra senha."
str_err[ERR_USER_NAME_ERROR]			=	"Usuário antigo incorreto. Insira o usuário correto"
str_err[ERR_USER_PWD_ERROR]				=	"Senha antiga incorreta. Insira a senha correta."
str_err[ERR_USER_PWD_INVALID_CHAR]		=	"Usuário ou senha contém caracteres inválidos. Entre com outro usuário/senha."
str_err[ERR_SYS_TFTP_FAIL]				=	"Ocorreu um erro. Tente novamente."
str_err[ERR_SYS_TFTP_FILE_LENGTH]		=	"Atualização não foi completada porque o tamanho do arquivo de atualização está incorreto. Por favor, verifique se o arquivo está correto."
str_err[ERR_SYS_TFTP_SERVNOTFOUND]		=	"Atualização sem êxito, assegure-se que você informou um servidor de TFTP correto."
str_err[ERR_SYS_ERR_SOCKET]				=	"Atualização não foi completada. Verifique se o servidor TFTP foi inicializado e o arquivo de atualização está no diretório correto."
str_err[ERR_SYS_FAIL]					=	"Transmissão de arquivo com falha. Verifique o nome do arquivo escolhido."
str_err[ERR_SYS_FILE_VER]				=	"Atualização não foi completada porque a versão do arquivo de atualização está incorreta. Por favor, verifique se o arquivo está correto."
//ºÏ²¢ zqq,07.10.29
str_err[ERR_SESSION_LIMIT_TBL_FULL]		=	"Ocorreu um erro. Tente novamente."
str_err[ERR_SESSION_LIMIT_RECORD_ALREADY_FULL]	=	"Limite de sessões de endereço IP excedido."
str_err[ERR_SESSION_LIMIT_RECORD_ALREADY_EXIST]	=	"Limite de entrada de sessão já existe."
str_err[ERR_ARP_REC_IP_EXIST]			=	"Esta entrada já existe."
str_err[ERR_ARP_FIXMAP_FULL]			=	"Ocorreu um erro. Tente novamente."
str_err[ERR_ARP_REC_IP_EXIST_ADD_SUCC]	=	"Ignore a(s) entrada(s) conflitante(s) com a(s) existente(s), adicionando somente a(s) entrada(s) válida(s)."
str_err[ERR_ARP_REC_IP_EXIST_ADD_FAIL]	=	"Entrada(s) adicionada(s) conflita(m) com a(s) entrada(s) existente(s)."
str_err[ERR_ARP_IP_EXIST_AND_FIXMAP_FULL]=	"Lista de associação ARP excedida."
str_err[ERR_ARP_FIXMAP_FULL_IGNORE_OTHER_ENTRYS]=	"Lista de associação ARP excedida."
str_err[ERR_ARP_IP_SAME_AS_LANIP]               =   "Proibido associar o endereço IP da LAN com outros endereços MAC."
str_err[ERR_SYS_LOG_SYS_STATUS]			=	"Status do log do sistema inválido."
str_err[ERR_SYS_LOG_SRV_ID]				=	"ID do log de sistema inválido."
str_err[ERR_SYS_LOG_SRV_STATUS]			=	"Status do log de sistema inválido."
str_err[ERR_SYS_LOG_SRV_ADDRESS]		=	"Endereço do servidor de log de sistema inválido."
str_err[ERR_SYS_LOG_SRV_ADDR_EXIST]		=	"Endereço do servidor de log de sistema já existe."
str_err[ERR_SYS_LOG_SRV_PORT]					=	"Porta do servidor de log de sistema inválido."
str_err[ERR_SYS_LOG_SETTING_EMERGENCY]			=	"Configuração de emergência do log de sistema inválida."
str_err[ERR_SYS_LOG_SETTING_ALERT]				=	"Configurações de alertas do log de sistema inválido."
str_err[ERR_SYS_LOG_SETTING_CRITICAL]			=	"Configurações críticas do log de sistema inválido."
str_err[ERR_SYS_LOG_SETTING_ERROR]				=	"Configurações de log de sistema inválido."
str_err[ERR_SYS_LOG_SETTING_WARNING]			=	"Configurações de aviso so log de sistema inválido."
str_err[ERR_SYS_LOG_SETTING_NOTICE]				=	"Configurações de notícias do log de sistema inválida."
str_err[ERR_SYS_LOG_SETTING_INFORMATIONAL]		=	"Configurações de Informações do log de sistema inválido."
str_err[ERR_SYS_LOG_SETTING_DEBUG]				=	"Configurações de erros do log de sistema inválido."
str_err[ERR_SYS_LOG_SETTING_EMPTY]				=	"Configurações do log de sistema vazias."
str_err[ERR_FIREWALL_SYSLOG_SERVER_INVALID_ID]	=	"Firewall do log de sistema inválido."
str_err[ERR_FIREWALL_SYSLOG_SERVER_NOT_DEFINED]	=	"Firewall do log de sistema indefinido."	
str_err[ERR_FIREWALL_SCREEN_UNKNOWN_DEFENCE]	=	"Firewall desconhecido."
str_err[ERR_FIREWALL_SCREEN_SCAN_THRESHOLD]		=	"Intervalo de firewall inválido."
str_err[ERR_FIREWALL_SCREEN_DOS_THRESHOLD]		=	"Intervalo de firewall DoS inválido."
str_err[ERR_TDDP_UPLOAD_FILE_TOO_LONG]	=	"Arquivo excede o tamanho máximo! "
str_err[ERR_TDDP_UPLOAD_FILE_FORMAT_ERR]=	"Formato incorreto de arquivo!"
str_err[ERR_TDDP_UPLOAD_FILE_NAME_ERR]          =   "Formato incorreto do nome do arquivo!";
str_err[ERR_COMMON_ERROR]				=	"Ocorreu um erro. Tente novamente."
str_err[ERR_DST_HOUR]					=	"Horário de verão incorreto. Insira no formato correto."
str_err[ERR_DST_DAY]					=	"Horário de verão incorreto. Insira no formato correto."
str_err[ERR_DST_MONTH]					=	"Horário de verão incorreto. Insira no formato correto."
str_err[ERR_DST_BEGIN_END]				=	"Data de início do horário de verão não pode ser igual ou posterior à data final."
str_err[ERR_TDDP_DOWNLOAD_FILE_TOO_LONG]=	"Arquivo excede o tamanho máximo!"
str_err[ERR_VS_RECORD_CONFLICT_REMOTE_WEB_PORT] =   "Porta do gerenciamento remoto conflita com a porta do servidor virtual.";
str_err[ERR_WLAN_CONFIG_BASE]			=	"Configuração Wireless inválida!"
str_err[ERR_WLAN_CONFIG_SECURITY]		=	"Configuração(ões) de segurança Wireless inválida(o)!"
str_err[ERR_WLAN_CONFIG_KEY]			=	"Chave(s) Wireless WEP inválida!"
str_err[ERR_WLAN_MAC_FILTER_PAGE_NUM_ERROR]=	"Número da página inválida. Tente novamente."
str_err[ERR_WLAN_MAC_FILTER_RECORD_ALREADY_EXIST]=	"Entrada ACL Wireless existente. Entre com outro valor."
str_err[ERR_WLAN_MAC_FILTER_RECORD_ALREADY_FULL]=	"Número máximo de entradas Wireless ACL já excedida: 64"
// add by lsz 071103
str_err[ERR_IP_NOT_IN_THE_SAME_SUBNET] 			=   "Endereço IP não está na mesma sub-rede da rede local!";
str_err[ERR_WLAN_SSID_LEN]                      =   "Tamanho do SSID é incorreto. Entre com outro valor.";
str_err[ERR_WLAN_REGION]                        =   "Região incorreta!";
str_err[ERR_WLAN_CHANNEL_WIDTH]                 =   "Frequência do canal incorreta.";
str_err[ERR_WLAN_STATIC_RATE]                   =   "Taxa estática incorreta.";
str_err[ERR_WLAN_MODE]                          =   "Modo de configuração incorreto.";
str_err[ERR_WLAN_BROADCAST]                     =   "Configuração de broadcast de SSID incorreta.";
str_err[ERR_WLAN_MAC_ADDR_INVALID]              =   "Endereço MAC incorreto. Entre com outro valor.";
str_err[ERR_WLAN_RADIUS_IP_INVALID]				=	"Endereço IP do servidor radius incorreto. Entre com outro valor.";
//parental control
str_err[ERR_PARENT_CTRL_FULL]					=	"Lista de controle parental excedida. "
str_err[ERR_PARENT_CTRL_URLDESC]				=	"Endereço já esta sendo utilizado. "
str_err[ERR_PARENT_CTRL_SAME_MAC_WITH_PARENT]	=	"Endereço MAC do PC para as crianças deve ser diferente do PC com controle parental."
//rule filter
str_err[ERR_ACC_CTRL_HOST_FULL]					=	"Lista de host excedida. "
str_err[ERR_ACC_CTRL_TARGET_FULL]				=	"Lista de IP/Porta excedida. "
str_err[ERR_ACC_CTRL_SCHEDULE_FULL]				=	"Lista de agendamento excedida. "
str_err[ERR_ACC_CTRL_RULE_FULL]					=	"Lista de controle de acesso excedida. "
str_err[ERR_ACC_CTRL_SAME_NAME]					=	"Nome já esta sendo utilizado. "
str_err[ERR_ACC_CTRL_REFERED]					=	"Item está sendo usado e não pode ser excluído. "
str_err[ERR_ACC_CTRL_RULE_CONFLICT]				=	"Esta regra já existe."
str_err[ERR_ACC_PARTIAL_DEL]					=	"Algumas entradas não podem ser apagados porque estão sendo utilizados, somente as outras entradas podem ser excluídas. "
str_err[ERR_ACC_DEL_NONE]						=	"Todos os itens estão sendo usados e não pode ser excluído."
str_err[ERR_FILTER_MAC]							=	"Endereço MAC inválido. "
str_err[ERR_ACC_CTRL_HOST_IPSTART]				=	"Endereço IP inicial inválido."
str_err[ERR_ACC_CTRL_HOST_IPEND]				=	"Endereço IP final inválido."
str_err[ERR_ACC_CTRL_TARGET_IPSTART]			=	"Endereço IP inicial inválido."
str_err[ERR_ACC_CTRL_TARGET_IPEND]				=	"Endereço IP final inválido."
str_err[ERR_ACC_CTRL_HOST_IPSTART_NOT_IN_THE_SAME_SUBNET] = "Endereço IP inicial deve estar na mesma sub-rede do endereço IP da LAN.";
str_err[ERR_ACC_CTRL_HOST_IPEND_NOT_IN_THE_SAME_SUBNET] = "Endereço IP final deve estar na mesma sub-rede do endereço IP da LAN.";

